Repository equinor/ert, pull requests merged in 2019-04, with the labels that each got.

#299 Remove c ert
  CMakeLists.txt
  libert/CMakeLists.txt
  libert/applications/ert_tui/CMake/config/ert_build_config_file.h.in
  libert/applications/ert_tui/CMakeLists.txt
  libert/applications/ert_tui/ERT.hpp
  libert/applications/ert_tui/enkf_tui_QC.hpp
  libert/applications/ert_tui/enkf_tui_analysis.cpp
  libert/applications/ert_tui/enkf_tui_analysis.hpp
  libert/applications/ert_tui/enkf_tui_export.cpp
  libert/applications/ert_tui/enkf_tui_export.hpp
  libert/applications/ert_tui/enkf_tui_fs.cpp
  libert/applications/ert_tui/enkf_tui_fs.hpp
  libert/applications/ert_tui/enkf_tui_help.cpp
  libert/applications/ert_tui/enkf_tui_help.hpp
  libert/applications/ert_tui/enkf_tui_init.cpp
  libert/applications/ert_tui/enkf_tui_init.hpp
  libert/applications/ert_tui/enkf_tui_main.cpp
  libert/applications/ert_tui/enkf_tui_main.hpp
  libert/applications/ert_tui/enkf_tui_misc.cpp
  libert/applications/ert_tui/enkf_tui_misc.hpp
  libert/applications/ert_tui/enkf_tui_ranking.cpp
  libert/applications/ert_tui/enkf_tui_ranking.hpp
  libert/applications/ert_tui/enkf_tui_run.cpp
  libert/applications/ert_tui/enkf_tui_run.hpp
  libert/applications/ert_tui/enkf_tui_simple.cpp
  libert/applications/ert_tui/enkf_tui_simple.hpp
  libert/applications/ert_tui/enkf_tui_table.cpp
  libert/applications/ert_tui/enkf_tui_table.hpp
  libert/applications/ert_tui/enkf_tui_util.cpp
  libert/applications/ert_tui/enkf_tui_util.hpp
  libert/applications/ert_tui/enkf_tui_workflow.cpp
  libert/applications/ert_tui/enkf_tui_workflow.hpp
  libert/applications/ert_tui/ert_tui_const.hpp
  libert/applications/ert_tui/main.cpp
  libert/applications/ert_tui/menu.cpp
  libert/applications/ert_tui/menu.hpp
  libert/applications/ert_tui/upgrade_fs104.cpp
  libert/include/ert/ert/ert_version.hpp
  libert/src/ert_version.cpp
Labels: in progress, review

#325 Fix status update on run finished
  python/python/ert_gui/simulation/run_dialog.py
Labels: in progress, review

#324 Fix default plot style with one data-point
  python/python/ert_gui/plottery/plot_config.py
  python/python/ert_gui/plottery/plots/ensemble.py
Labels: review

#327 Set libres version to 2.5.rc1
  .libres_version
Labels: in progress, review

#336 Fix status update on run finished
  python/python/ert_gui/simulation/run_dialog.py
Labels: in progress, review

#344 Prevent run dialog from closing on simulation failure
  ert_gui/simulation/run_dialog.py
Labels: in progress, review

#345 Adjust size after adding toolbar
  ert_gui/gert_main.py
Labels: in progress, review

#349 Revert argument 'algorithm' -> 'mode'
  bin/ert.in
Labels: in progress, review

#343 Added IES variables to IES submenu
  ert_gui/ertwidgets/analysismodulevariablespanel.py
  ert_gui/ertwidgets/models/analysismodulevariablesmodel.py
Labels: in progress

#354 Organize progress-bar in left-to-right fashion
  ert_gui/simulation/models/simulations_tracker.py
Labels: ready for review, review

#355 Organize progress-bar in left-to-right fashion
  python/python/ert_gui/simulation/models/simulations_tracker.py
Labels: ready for review, review

#362 Edit readme to use pip install instead of cmake
  README.md
Labels: in progress, review

#360 Include queue status in detailed FM monitor
  ert_gui/simulation/detailed_progress.py
  ert_gui/simulation/models/base_run_model.py
  ert_gui/simulation/models/ensemble_experiment.py
  ert_gui/simulation/models/ensemble_smoother.py
  ert_gui/simulation/models/iterated_ensemble_smoother.py
  ert_gui/simulation/models/multiple_data_assimilation.py
  ert_gui/simulation/run_dialog.py
Labels: in progress, review

#363 2.5 patch status update
  python/python/ert_gui/simulation/detailed_progress.py
  python/python/ert_gui/simulation/models/base_run_model.py
  python/python/ert_gui/simulation/models/ensemble_experiment.py
  python/python/ert_gui/simulation/models/ensemble_smoother.py
  python/python/ert_gui/simulation/models/iterated_ensemble_smoother.py
  python/python/ert_gui/simulation/models/multiple_data_assimilation.py
  python/python/ert_gui/simulation/run_dialog.py
Labels: in progress, review

#350 Add release notes for version 2.5
  docs/rst/manual/changes/index.rst
Labels: ready for review, review

#364 Add border color indication in description of FM monitoring
  docs/rst/manual/changes/index.rst
Labels: in progress, review

#365 2.5 patch release notes
  docs/rst/manual/changes/index.rst
Labels: in progress, review
