Repository equinor/ert, pull requests merged in 2019-01, with the labels that each got.

#216 Always show advanced settings
  python/python/ert_gui/main_window.py
  python/python/ert_gui/tools/load_results/load_results_tool.py
  python/python/ert_gui/tools/run_analysis/run_analysis_tool.py
Labels: in progress, review

#219 New Travis token
  travis/build_total.py
Labels: in progress, review

#220 Yet another new github token
  travis/build_total.py
Labels: in progress, review

#224 Always display advanced option in all panels
  python/python/ert_gui/simulation/ensemble_experiment_panel.py
  python/python/ert_gui/simulation/ensemble_smoother_panel.py
  python/python/ert_gui/simulation/iterated_ensemble_smoother_panel.py
  python/python/ert_gui/simulation/multiple_data_assimilation_panel.py
  python/python/ert_gui/simulation/simulation_panel.py
  python/python/ert_gui/simulation/single_test_run_panel.py
Labels: in progress, review

#229 Fix variable name
  python/python/ert_gui/simulation/models/iterated_ensemble_smoother.py
Labels: in progress

#230 Change example.ert to handle new args list style
  test-data/local/example_case/example.ert
Labels: in progress, review

#233 Remove unused prefix argument
  python/tests/gui/ertshell/ert_shell_test_context.py
Labels: in progress

#241 Add triangular dist documentation
  docs/rst/manual/data_types/index.rst
Labels: ready for review, review

#243 Change default style of plot to emphesize descrete data
  python/python/ert_gui/plottery/plot_config.py
Labels: in progress, review
