Repository equinor/ert, pull requests merged in 2019-03, with the labels that each got.

#260 Change snake_oil.ert to use ECLBASE instead of JOB_NAME
  test-data/local/snake_oil/snake_oil.ert
Labels: in progress, review

#277 Fixed typo in link to travis
  README.md
Labels: in progress, review

#265 Removed extra __init__() argument
  python/python/ert_gui/simulation/models/iterated_ensemble_smoother.py
Labels: in progress

#279 Removed extra __init__() argument
  python/python/ert_gui/simulation/models/iterated_ensemble_smoother.py
Labels: in progress, review

#283 Change initial type to iterable in BaseRunModel
  python/python/ert_gui/simulation/models/base_run_model.py
Labels: ready for review, review

#262 Inform user about failing wf jobs
  python/python/ert_gui/tools/workflows/run_workflow_widget.py
Labels: ready for review, review

#281 Rename algorithm to mode
  bin/ert.in
  python/python/bin/ert_cli
  python/tests/global/test_cli.py
Labels: ready for review, review

#282 Validate target file system at startup
  bin/ert.in
Labels: ready for review, review

#285 Fix condition for is_forward_model_finished
  python/python/ert_gui/simulation/models/base_run_model.py
Labels: in progress, review

#286 Version 2.4 detailed patch
  python/python/ert_gui/simulation/models/base_run_model.py
Labels: ready for review, review

#290 Add func for opening stderr/stdout-files in fm monitor
  .libres_version
  python/python/ert_gui/simulation/detailed_progress.py
Labels: in progress, review

#293 Set res version to 2.4.0
  .libres_version
Labels: in progress, review

#295 ERT 2.4 release notes
  docs/rst/manual/changes/index.rst
Labels: in progress, review

#297 Set ERT version
  CMakeLists.txt
Labels: in progress, review

#301 Rename fm monitor widget class
  python/python/ert_gui/simulation/__init__.py
  python/python/ert_gui/simulation/detailed_progress.py
  python/python/ert_gui/simulation/run_dialog.py
Labels: in progress, review

#289 Add fm docs
  docs/rst/manual/forward_model/index.rst
Labels: in progress, review

#304 Doc backport 2.4
  docs/rst/manual/forward_model/index.rst
Labels: in progress, review

#305 Fix setPixel warning
  python/python/ert_gui/simulation/detailed_progress.py
Labels: in progress, review

#306 Raise micro to 2
  CMakeLists.txt
Labels: in progress, review
