Repository equinor/ert, pull requests merged in 2021-12, with the labels that each got.

#2598 Cleanup analysis update
  libres/lib/analysis/update.cpp
Labels: payback, maintenance, analysis

#2595 Delete unused arg_pack.h
  libres/lib/include/ert/res_util/arg_pack.h
  libres/lib/include/ert/res_util/arg_pack.hpp
Labels: maintenance

#2593 Remove unused regression-code
  libres/lib/CMakeLists.txt
  libres/lib/include/ert/res_util/regression.hpp
  libres/lib/res_util/regression.cpp
Labels: maintenance

#2590 Replace util_mkdir_fopen with standard C++
  libres/lib/CMakeLists.txt
  libres/lib/enkf/cases_config.cpp
  libres/lib/enkf/enkf_fs.cpp
  libres/lib/enkf/ext_param.cpp
  libres/lib/enkf/field.cpp
  libres/lib/enkf/ranking_table.cpp
  libres/lib/enkf/runpath_list.cpp
  libres/lib/enkf/state_map.cpp
  libres/lib/enkf/summary_key_set.cpp
  libres/lib/enkf/time_map.cpp
  libres/lib/include/ert/res_util/file_utils.hpp
  libres/lib/job_queue/ext_job.cpp
  libres/lib/job_queue/torque_driver.cpp
  libres/lib/res_util/file_utils.cpp
  libres/lib/res_util/subst_list.cpp
  libres/lib/res_util/template.cpp
  libres/lib/rms/rms_file.cpp
  libres/old_tests/enkf/test_enkf_analysis_config.cpp
  libres/old_tests/enkf/test_enkf_workflow_job.cpp
Labels: maintenance

#2599 Use namespace for analysis update
  libres/lib/analysis/update.cpp
  libres/lib/enkf/enkf_main.cpp
  libres/lib/include/ert/analysis/update.hpp
Labels: payback, maintenance, analysis

#2600 Fix speeling of therefore
  libres/lib/analysis/update.cpp
  libres/lib/enkf/enkf_node.cpp
  libres/lib/enkf/gen_data.cpp
  libres/lib/enkf/time_map.cpp
  libres/lib/include/ert/enkf/enkf_defaults.hpp
  libres/lib/job_queue/job_node.cpp
  libres/lib/job_queue/job_queue.cpp
  libres/lib/job_queue/local_driver.cpp
  libres/lib/res_util/block_fs.cpp
  libres/lib/res_util/thread_pool.cpp
  res/enkf/ert_run_context.py
  res/job_queue/__init__.py
  res/util/path_format.py
  tests/libres_tests/res/enkf/test_res_config.py
Labels: payback

#2597 Handle connection closed errors in EvaluatorTracker
  ert_shared/status/tracker/evaluator.py
Labels: payback

#2611 Refactor: analysis/update cleanup
  libres/lib/analysis/update.cpp
Labels: payback, maintenance, analysis

#2623 Only comment coverage after all reports are sent
  codecov.yml
Labels: ci-pipeline

#2618 Remove uncompiled migrate_bfs script
  libres/lib/enkf/migrate_bfs.cpp
Labels: payback

#2610 Mute PEP-585 warnings from BearType in Py39
  ert/data/record/_record.py
Labels: maintenance

#2620 Remove QUEUE_DEBUG flag
  libres/lib/job_queue/job_list.cpp
Labels: payback

#2633 Fix compatibility wity beartype==0.9.1
  ert/data/record/_record.py
  setup.py
  types-requirements.txt
Labels: maintenance

#2636 Remove storage that was added by mistake
  storage/snake_oil/ensemble/default_0/files/case_config
  storage/snake_oil/ensemble/default_0/files/state-map
  storage/snake_oil/ensemble/default_0/files/summary-key-set
Labels: maintenance
