Repository equinor/ert, pull requests merged in 2022-06, with the labels that each got.

#3473 Refactor creating data for running analysis
  libres/lib/analysis/update.cpp
  libres/lib/include/ert/analysis/update.hpp
  res/enkf/es_update.py
Labels: release-notes:breaking-change

#3450 Release GIL before waiting for (async) futures in C++
  libres/lib/enkf/enkf_main.cpp
  libres/lib/include/ert/enkf/enkf_main.hpp
  res/enkf/enkf_main.py
Labels: release-notes:bug-fix

#3479 Solve some infrequent pylint issues
  .github/workflows/style.yml
  ert_gui/tools/plot/plot_api.py
  ert_shared/dark_storage/enkf.py
  ert_shared/port_handler.py
  ert_shared/services/_webviz_ert_main.py
  res/analysis/configuration.py
  res/enkf/analysis_config.py
  res/enkf/enkf_main.py
  res/enkf/enkf_simulation_runner.py
  res/job_queue/job.py
  res/job_queue/queue.py
  res/job_queue/workflow_joblist.py
  res/test/synthesizer/oil_simulator.py
  tests/ert_tests/all/docs/test_ert_documentation.py
  tests/ert_tests/dark_storage/conftest.py
  tests/ert_tests/data/test_loader.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/prefect/conftest.py
  tests/ert_tests/ensemble_evaluator/prefect/test_run_dialog_ert3.py
  tests/ert_tests/ert3/engine/integration/test_engine.py
  tests/ert_tests/gui/simulation/test_run_dialog.py
  tests/ert_tests/services/test_base_service.py
  tests/ert_tests/shared/test_libres_facade.py
  tests/ert_tests/status/test_tracking_integration.py
  tests/ert_tests/storage/test_extraction.py
  tests/libres_tests/res/analysis/test_update_configuration.py
  tests/libres_tests/res/enkf/test_enkf_runpath.py
  tests/libres_tests/res/enkf/test_hook_manager.py
  tests/libres_tests/res/enkf/test_res_config.py
  tests/libres_tests/res/job_queue/test_equinor_jobmanager.py
  tests/libres_tests/res/run/test_run.py
  tests/libres_tests/res/simulator/test_batch_sim.py
Labels: release-notes:maintenance

#3467 Move create runpath and sample parameter logic from C to Python
  libres/lib/enkf/enkf_main.cpp
  libres/lib/enkf/enkf_main_manage_fs.cpp
  libres/lib/enkf/enkf_state.cpp
  libres/lib/enkf/ensemble_config.cpp
  libres/lib/include/ert/enkf/enkf_main.hpp
  libres/lib/include/ert/enkf/enkf_state.hpp
  libres/lib/python/enkf_fs_manager.cpp
  libres/old_tests/enkf/CMakeLists.txt
  libres/old_tests/enkf/test_enkf_export_inactive_cells.cpp
  libres/old_tests/enkf/test_enkf_forward_init_FIELD.cpp
  libres/old_tests/enkf/test_enkf_forward_init_GEN_KW.cpp
  libres/old_tests/enkf/test_enkf_forward_init_GEN_PARAM.cpp
  libres/old_tests/enkf/test_enkf_forward_init_SURFACE.cpp
  libres/old_tests/enkf/test_enkf_forward_init_transform.cpp
  libres/old_tests/enkf/test_enkf_plot_gen_kw_fs.cpp
  libres/old_tests/enkf/test_enkf_umask_config.cpp
  res/enkf/enkf_fs_manager.py
  res/enkf/enkf_main.py
  res/enkf/enkf_simulation_runner.py
  res/enkf/ert_run_context.py
  tests/libres_tests/integration/test_parameter_sample_types.py
Labels: release-notes:maintenance

#3492 Remove doc referring to tagged keywords
  libres/lib/enkf/enkf_main.cpp
Labels: maintenance

#3504 Remove unused function gen_kw_ecl_write_template
  libres/lib/enkf/gen_kw.cpp
  libres/lib/include/ert/enkf/gen_kw.hpp
  res/enkf/data/gen_kw.py
Labels: maintenance

#3503 Update github issue template for bugs
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: release-notes:maintenance

#3507 Remove unused param arg
  libres/lib/enkf/enkf_fs.cpp
  libres/lib/enkf/enkf_main_manage_fs.cpp
  libres/lib/include/ert/enkf/enkf_fs.hpp
  libres/old_tests/enkf/test_enkf_fs.cpp
  libres/old_tests/enkf/test_enkf_gen_data_config.cpp
  libres/old_tests/enkf/test_enkf_main.cpp
  libres/old_tests/enkf/test_enkf_run_arg.cpp
  libres/tests/analysis/test_copy_parameters.cpp
  libres/tests/analysis/test_save_parameters.cpp
  res/enkf/enkf_fs.py
Labels: release-notes:maintenance

#3510 Remove unecessary fs version checks
  libres/lib/enkf/enkf_fs.cpp
  libres/lib/enkf/enkf_main_manage_fs.cpp
  libres/lib/include/ert/enkf/enkf_fs.hpp
Labels: release-notes:maintenance

#3484 Use async context manager for ens_evaluator client
  ert/ensemble_evaluator/builder/_ensemble.py
  ert_shared/ensemble_evaluator/client.py
Labels: release-notes:maintenance

#3513 Remove unused function get_observation_count
  libres/lib/enkf/enkf_main.cpp
  libres/lib/include/ert/enkf/enkf_main.hpp
  res/enkf/enkf_main.py
Labels: release-notes:maintenance

#3477 Removal of INIT_MISFIT_TABLE workflow.
  docs/rst/manual/reference/workflows/built_in.rst
  ert_shared/share/ert/gui/help/config/keywords/keywords.txt
  ert_shared/share/ert/workflows/jobs/internal/config/INIT_MISFIT_TABLE
  libres/lib/CMakeLists.txt
  libres/lib/enkf/enkf_main_jobs.cpp
  libres/lib/enkf/misfit_ranking.cpp
  libres/lib/include/ert/enkf/misfit_ranking.hpp
  libres/lib/job_queue/workflow_job.cpp
  libres/old_tests/enkf/test_enkf_workflow_job.cpp
Labels: maintenance, improvement

#3522 Expose priors in dark-storage endpoint
  ert_shared/dark_storage/endpoints/experiments.py
  ert_shared/storage/extraction.py
Labels: visualization, release-notes:new-feature, release-notes:maintenance

#3520 Remove unused function run_path_list_load
  libres/lib/enkf/runpath_list.cpp
  libres/lib/include/ert/enkf/runpath_list.hpp
  res/enkf/runpath_list.py
  tests/libres_tests/res/enkf/test_runpath_list.py
Labels: maintenance

#3525 Remove unneeded extern C
  libres/lib/include/ert/enkf/enkf_state.hpp
Labels: release-notes:maintenance

#3530 Inline `time_map_summary_update__`
  libres/lib/enkf/time_map.cpp
Labels: release-notes:maintenance

#3526 Push runpath_list into hook_manager
  ert_shared/exporter.py
  libres/lib/CMakeLists.txt
  libres/lib/enkf/enkf_main.cpp
  libres/lib/enkf/enkf_main_jobs.cpp
  libres/lib/enkf/hook_manager.cpp
  libres/lib/enkf/runpath_list.cpp
  libres/lib/enkf/subst_config.cpp
  libres/lib/include/ert/enkf/enkf_main.hpp
  libres/lib/include/ert/enkf/hook_manager.hpp
  libres/lib/include/ert/enkf/runpath_list.hpp
  libres/old_tests/enkf/CMakeLists.txt
  libres/old_tests/enkf/test_enkf_export_inactive_cells.cpp
  libres/old_tests/enkf/test_enkf_runpath_list.cpp
  libres/old_tests/enkf/test_enkf_umask_config.cpp
  res/enkf/__init__.py
  res/enkf/enkf_main.py
  res/enkf/hook_manager.py
  res/enkf/runpath_list.py
  tests/libres_tests/res/enkf/test_res_config.py
  tests/libres_tests/res/enkf/test_runpath_list.py
  tests/libres_tests/res/enkf/test_runpath_list_ert.py
Labels: maintenance, release-notes:maintenance

#3539 Type and simplify measured.py
  .github/workflows/typing.yml
  .mypy.ini
  ert_data/measured.py
Labels: release-notes:maintenance

#3540 Select pytest asyncio_mode=auto
  pyproject.toml
Labels: release-notes:maintenance

#3461 Set file dialog to reasonable width and height - simplified approach
  ert_gui/tools/file/file_dialog.py
  tests/ert_tests/gui/tools/file/filedialog.py
  tests/ert_tests/gui/tools/file/stdout-just-right
  tests/ert_tests/gui/tools/file/stdout-long
  tests/ert_tests/gui/tools/file/stdout-long-and-extra-wide
  tests/ert_tests/gui/tools/file/stdout-short
Labels: improvement

#3554 Remove UPDATE_RUNPATH_LIST workflow
  ert_shared/share/ert/workflows/jobs/internal-gui/config/UPDATE_RUNPATH_LIST
  ert_shared/share/ert/workflows/jobs/internal-gui/scripts/update_runpath_list.py
Labels: release-notes:breaking-change

#3532 Remove graphql related code
  ert_shared/dark_storage/app.py
  ert_shared/dark_storage/common.py
  ert_shared/dark_storage/graphql/__init__.py
  ert_shared/dark_storage/graphql/ensembles.py
  ert_shared/dark_storage/graphql/experiments.py
  ert_shared/dark_storage/graphql/parameters.py
  ert_shared/dark_storage/graphql/responses.py
  ert_shared/dark_storage/graphql/unique_responses.py
  ert_shared/dark_storage/graphql/updates.py
  setup.py
  tests/ert_tests/dark_storage/test_api_compatibility.py
  tests/ert_tests/dark_storage/test_graphql_queries.py
  tests/ert_tests/dark_storage/test_http_endpoints.py
Labels: payback

#3545 Update MIN_SUPPORTED_FS_VERSION
  libres/lib/enkf/fs_driver.cpp
  libres/lib/include/ert/enkf/fs_driver.hpp
Labels: release-notes:maintenance

#3562 Remove fixing of nodes
  libres/lib/res_util/block_fs.cpp
Labels: maintenance

#3570 Make dependency on file location in Block explicit
  libres/lib/res_util/block_fs.cpp
Labels: maintenance

#3490 Drop support for Python 3.6 and Python 3.7
  .github/workflows/build.yml
  .github/workflows/run_ert2_test_data_setups.yml
  .github/workflows/run_examples_polynomial.yml
  .github/workflows/run_examples_snake_oil.yml
  .github/workflows/run_examples_spe1.yml
  README.md
  ci/github/build_linux_wheel.sh
  ci/jenkins/test_libres_jenkins.sh
  dev-requirements.txt
  ert3/config/_ensemble_config.py
  ert3/config/_experiment_config.py
  ert3/config/_parameters_config.py
  ert_shared/ensemble_evaluator/evaluator.py
  ert_shared/ensemble_evaluator/narratives/narrative.py
  ert_shared/models/types.py
  setup.py
  tests/ert_tests/shared/test_exporter.py
  tests/ert_tests/shared/test_main_entry.py
  tests/libres_tests/share/test_synthesizer.py
Labels: blocked, release-notes:breaking-change, release-notes:maintenance

#3576 Improve documentation of GEN_KW
  CONTRIBUTING.md
  docs/rst/manual/reference/configuration/data_types.rst
  docs/rst/manual/reference/configuration/keywords.rst
Labels: release-notes:maintenance

#3584 Solve pylint warnings on dangerous-default-value
  .github/workflows/style.yml
  docs/rst/manual/advanced/Oscillator.py
  docs/rst/manual/advanced/Polynomial.py
  ert_shared/storage/extraction.py
  tests/ert_tests/status/test_evaluator_tracker.py
Labels: release-notes:maintenance

#3574 Move save/load parameters to EnkfFs
  res/enkf/enkf_fs.py
  res/enkf/es_update.py
Labels: release-notes:maintenance

#3587 Add webviz-ert as dependency in setup.py
  setup.py
Labels: release-notes:dependency
