Repository equinor/ert, pull requests merged in 2022-02, with the labels that each got.

#2830 Free internal resources in ies::data_free()
  libres/lib/analysis/ies/ies_data.cpp
Labels: bug, analysis

#2845 Fix typo ensamble
  ert_data/measured.py
  tests/ert_tests/data/test_measured_data.py
  tests/ert_tests/gui/test_gui_load.py
Labels: maintenance

#2832 Increase worker memory requirements on PBS
  ert_shared/ensemble_evaluator/ensemble/prefect.py
Labels: ert3

#2851 Update config path to basename when changing working directory
  ert_gui/gert_main.py
Labels: bug

#2703 Snake ert3
  .github/workflows/run_examples_snake_oil.yml
  ert3_examples/snake_oil/README
  ert3_examples/snake_oil/designmatrixtxt2json.py
  ert3_examples/snake_oil/experiments/doe/ensemble.yml
  ert3_examples/snake_oil/experiments/doe/experiment.yml
  ert3_examples/snake_oil/experiments/evaluation/ensemble.yml
  ert3_examples/snake_oil/experiments/evaluation/experiment.yml
  ert3_examples/snake_oil/experiments/sensitivity/ensemble.yml
  ert3_examples/snake_oil/experiments/sensitivity/experiment.yml
  ert3_examples/snake_oil/parameters.yml
  ert3_examples/snake_oil/render.py
  ert3_examples/snake_oil/resources/designmatrix.xlsx
  ert3_examples/snake_oil/resources/seedtxt
  ert3_examples/snake_oil/resources/snake_oil_txt_tmpl
  ert3_examples/snake_oil/run_demo
  ert3_examples/snake_oil/snake_oil_simulator.py
  ert3_examples/snake_oil/stages.yml
  ert_shared/storage/extraction.py
Labels: Configuration, ert3

#2853 Cleanup redundant parameters
  libres/lib/analysis/update.cpp
  libres/lib/enkf/enkf_main.cpp
  libres/lib/enkf/ert_test_context.cpp
  libres/lib/include/ert/enkf/enkf_main.hpp
  libres/old_tests/enkf/test_enkf_forward_init_FIELD.cpp
  libres/old_tests/enkf/test_enkf_forward_init_GEN_KW.cpp
  libres/old_tests/enkf/test_enkf_forward_init_GEN_PARAM.cpp
  libres/old_tests/enkf/test_enkf_forward_init_SURFACE.cpp
  libres/old_tests/enkf/test_enkf_forward_init_transform.cpp
  libres/old_tests/enkf/test_enkf_main.cpp
  libres/old_tests/enkf/test_enkf_main_fs.cpp
  libres/old_tests/enkf/test_enkf_main_fs_current_file.cpp
  libres/old_tests/enkf/test_enkf_plot_data_fs.cpp
  libres/old_tests/enkf/test_enkf_state_manual_load.cpp
  libres/old_tests/enkf/test_enkf_state_report_step_compatible.cpp
  libres/old_tests/enkf/test_enkf_state_skip_summary_load.cpp
  res/enkf/enkf_main.py
Labels: enhancement, maintenance

#2874 Add release notes for 2.32
  docs/rst/manual/about/release_notes.rst
Labels: documentation

#2784 Remove changing mode of files by ext_job
  libres/lib/job_queue/ext_job.cpp
  libres/old_tests/data/job_queue/jobs/util/REPLACE
  libres/old_tests/data/job_queue/jobs/util/STORE_FILE
  libres/tests/CMakeLists.txt
  libres/tests/job_queue/test_ext_job_executable.cpp
  test-data/local/batch_sim/jobs/square_params.py
  tests/ert_tests/ensemble_evaluator/conftest.py
  tests/ert_tests/storage/test_extraction.py
  tests/libres_tests/res/job_queue/test_ext_job.py
  tests/libres_tests/res/job_queue/test_forward_model_formatted_print.py
Labels: breaking-change

#2889 Remove deprecated parameter 'loop' in Queues
  ert_shared/ensemble_evaluator/ensemble/legacy.py
  ert_shared/ensemble_evaluator/evaluator.py
Labels: maintenance, ensemble-evaluator

#2883 Remove usage of thread_pool in job_queue
  libres/lib/include/ert/job_queue/job_node.hpp
  libres/lib/job_queue/job_node.cpp
  libres/lib/job_queue/job_queue.cpp
Labels: enhancement, payback

#2884 Remove thread_pool in loading/saving parameters
  libres/lib/analysis/update.cpp
Labels: payback

#2890 Remove redundant parameter
  res/enkf/enkf_main.py
Labels: bug

#2891 Add better error handling when trying to rerun an experiment
  ert/exceptions/__init__.py
  ert/exceptions/_exceptions.py
  ert3/console/__init__.py
  ert3/console/_console.py
  ert3/console/_errors.py
  ert3/engine/_run.py
  tests/ert_tests/ert3/engine/integration/test_engine.py
Labels: enhancement, ert3

#2744 Catch 2 test for Assert update viability
  libres/lib/analysis/update.cpp
  libres/lib/enkf/analysis_config.cpp
  libres/lib/include/ert/enkf/analysis_config.hpp
  libres/tests/CMakeLists.txt
  libres/tests/analysis/test_update_is_valid.cpp
Labels: testing

#2938 Replace first iteration of convert from cwrap
  libres/lib/CMakeLists.txt
  libres/lib/include/ert/python.hpp
  libres/lib/python/enkf_fs_general_data.cpp
  libres/lib/python/enkf_fs_keyword_data.cpp
  libres/lib/python/enkf_fs_manager.cpp
  libres/lib/python/enkf_fs_summary_data.cpp
  libres/lib/python/ensemble_config.cpp
  libres/lib/python/init.cpp
  libres/lib/python/py_conversion.cpp
Labels: maintenance

#2919 Remove dead code from test_analysis_module
  tests/libres_tests/res/analysis/test_analysis_module.py
Labels: maintenance

#2947 Reference correct equation in implementation of ies
  libres/lib/analysis/ies/ies.cpp
Labels: documentation

#2954 Fix row scaling local configuration job
  test-data/local/row_scaling/workflows/scripts/row_scaling_job1.py
Labels: bug

#2988 Remove unused fprint functions
  libres/lib/enkf/active_list.cpp
  libres/lib/enkf/local_ministep.cpp
  libres/lib/enkf/local_obsdata.cpp
  libres/lib/include/ert/enkf/active_list.hpp
  libres/lib/include/ert/enkf/local_ministep.hpp
  libres/lib/include/ert/enkf/local_obsdata.hpp
Labels: maintenance

#2980 Remove dependency on semeio
  .github/workflows/run_examples_snake_oil.yml
  dev-requirements.txt
  setup.py
Labels: payback, maintenance
