Repository equinor/ert, pull requests merged in 2022-11, with the labels that each got.

#4169 Warn when expanding keywords with no refcase available
  docs/reference/configuration/keywords.rst
  src/clib/lib/enkf/ensemble_config.cpp
Labels: release-notes:maintenance

#4001 Make sure that processing reporter.event_queue does not yield ConnectionError
  src/_ert_job_runner/client.py
  src/_ert_job_runner/reporting/event.py
  tests/unit_tests/c_wrappers/job_runner/test_event_reporter.py
Labels: release-notes:misc

#4177 Remove print statements and comments
  tests/test_config_parsing/test_ensemble_config.py
Labels: release-notes:maintenance

#4183 Make `<DATE>` magic string substitution available for ert config file
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:improvement

#4198 Add no-action implementations of free to classes inheriting from BaseCClass
  src/ert/_c_wrappers/enkf/hook_workflow.py
  src/ert/_c_wrappers/enkf/observations/block_data_config.py
  src/ert/_c_wrappers/enkf/plot_data/ensemble_plot_gen_data_vector.py
Labels: release-notes:bug-fix

#4187 Fix bug where wrong function name was used
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  tests/unit_tests/gui/tools/test_case_tool.py
Labels: release-notes:bug-fix

#4207 Remove spurious print messages
  src/ert/simulator/simulation_context.py
Labels: release-notes:bug-fix

#4211 Refactor summary load
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/enkf_node.cpp
  src/clib/lib/enkf/enkf_plot_tvector.cpp
  src/clib/lib/enkf/summary.cpp
  src/clib/lib/include/ert/enkf/enkf_macros.hpp
  src/clib/lib/include/ert/enkf/enkf_node.hpp
  src/clib/lib/include/ert/enkf/enkf_plot_tvector.hpp
  src/clib/lib/include/ert/enkf/summary.hpp
  src/clib/lib/python/enkf_fs_summary_data.cpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_plot_tvector.cpp
Labels: release-notes:maintenance

#4204 Back port: Fix bug where non existing function was used
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  tests/unit_tests/gui/tools/test_case_tool.py
Labels: release-notes:bug-fix

#4205 Remove unused parameter in model_config_init
  src/clib/lib/enkf/model_config.cpp
  src/clib/lib/include/ert/enkf/model_config.hpp
Labels: payback

#4074 Add pip packages to PATH for macos-latest CI job
  .github/workflows/build.yml
Labels: release-notes:maintenance

#4226 Add release notes for version 4.0
  docs/about/release_notes.rst
Labels: release-notes:maintenance

#4227 Extend config_content_as_dict
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  src/ert/_c_wrappers/enkf/res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_config_content_as_dict.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: bug

#4228 Improve error msg when unable to acquire lock
  src/ert/cli/main.py
  src/ert/gui/gert_main.py
Labels: release-notes:maintenance

#4232 Remove unused es_testdata.cpp
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/res_util/es_testdata.hpp
  src/clib/lib/res_util/es_testdata.cpp
  src/clib/old_tests/res_util/CMakeLists.txt
  src/clib/old_tests/res_util/test_es_testdata.cpp
Labels: release-notes:maintenance

#4225 Remove unused functions
  src/clib/lib/enkf/state_map.cpp
  src/clib/lib/include/ert/enkf/state_map.hpp
  src/clib/old_tests/enkf/test_enkf_state_map.cpp
Labels: release-notes:maintenance

#4234 Solve style issues found by annotate action
  src/clib/lib/enkf/gen_data.cpp
  src/clib/lib/enkf/model_config.cpp
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/gui/ertwidgets/customdialog.py
  src/ert/gui/tools/plot/data_type_keys_list_model.py
  src/ert/gui/tools/plot/style_chooser.py
Labels: release-notes:maintenance

#4223 Always print blob for failing hypothesis tests
  tests/test_config_parsing/conftest.py
Labels: release-notes:misc

#4233 Remove unused functions on field.cpp
  src/clib/lib/enkf/field.cpp
  src/clib/lib/include/ert/enkf/field.hpp
Labels: release-notes:maintenance

#4249 Fix an issue with arglist with simulation job
  src/clib/lib/include/ert/job_queue/ext_job.hpp
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: bug

#4262 Up the timeout limit when testing the job runner startup overhead
  tests/performance_tests/test_forward_model_script_overhead.py
Labels: testing, flaky-test, release-notes:maintenance

#4266 Removed Free method in ResConfig (src/ert/_c_wrappers/enkf/res_config.py)
  src/ert/_c_wrappers/enkf/res_config.py
Labels: release-notes:maintenance

#4261 Fix job queue log message
  src/ert/_c_wrappers/job_queue/forward_model.py
  tests/unit_tests/c_wrappers/res/job_queue/test_forward_model_formatted_print.py
Labels: bug

#4256 Ensure bin in path for pytest
  tests/unit_tests/conftest.py
Labels: release-notes:misc

#4270 Fix implicit typing of optional in substituter
  src/ert/_c_wrappers/enkf/substituter.py
Labels: payback

#4200 Add hypothesis testing for and string methods to model config
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/ext_joblist.py
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/test_model_config.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:maintenance

#4171 Let torque driver pick up error codes from jobs
  src/clib/lib/job_queue/qstat_proxy.sh
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/data/job_queue/qsub_emulators/qdel
  src/clib/old_tests/data/job_queue/qsub_emulators/qsub
  tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py
  tests/unit_tests/c_wrappers/res/job_queue/test_job_queue_manager_torque.py
  tests/unit_tests/c_wrappers/res/job_queue/test_torque_driver.py
Labels: release-notes:bug-fix

#4273 Refactor enkf_fs summary data loading and gen data loading to use
  src/clib/lib/enkf/enkf_fs.cpp
  src/clib/lib/enkf/enkf_node.cpp
  src/clib/lib/enkf/enkf_state.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/run_arg.cpp
  src/clib/lib/enkf/state_map.cpp
  src/clib/lib/enkf/summary.cpp
  src/clib/lib/enkf/summary_key_matcher.cpp
  src/clib/lib/include/ert/enkf/enkf_state.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/summary_key_matcher.hpp
  src/clib/lib/include/ert/python.hpp
  src/clib/lib/python/model_callbacks.cpp
  src/ert/_c_wrappers/enkf/data/enkf_node.py
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/enkf_state.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_run_context.py
  src/ert/_c_wrappers/enkf/observations/obs_vector.py
  src/ert/_c_wrappers/enkf/run_arg.py
  src/ert/_c_wrappers/enkf/time_map.py
  src/ert/analysis/_es_update.py
  src/ert/data/loader.py
  src/ert/ensemble_evaluator/_builder/_ensemble_builder.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/ensemble_evaluator/_builder/_step.py
  src/ert/ensemble_evaluator/callbacks.py
  src/ert/gui/ertwidgets/models/ertmodel.py
  src/ert/libres_facade.py
  src/ert/shared/hook_implementations/workflows/export_misfit_data.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  src/ert/simulator/batch_simulator_context.py
  tests/unit_tests/all/plugins/snapshots/test_export_misfit/test_export_misfit/csv_data.csv
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/c_wrappers/res/enkf/data/test_gen_data.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_run_context.py
  tests/unit_tests/c_wrappers/res/enkf/test_load_forward_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_simulation_batch.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/models/test_base_run_model.py
  tests/unit_tests/status/test_tracking_integration.py
  tests/unit_tests/test_libres_facade.py
Labels: release-notes:breaking-change, release-notes:improvement

#4279 Update readthedocs config
  .readthedocs.yaml
Labels: release-notes:maintenance

#4276 Remove Narratives for testing and accompanying tests
  docs/_ext/ert_narratives.py
  docs/conf.py
  docs/developer_documentation/communication_protocol.rst
  docs/developer_documentation/index.rst
  pyproject.toml
  src/ert/ensemble_evaluator/narratives/__init__.py
  src/ert/ensemble_evaluator/narratives/dispatch_failing_job.py
  src/ert/ensemble_evaluator/narratives/monitor_failing_ensemble.py
  src/ert/ensemble_evaluator/narratives/monitor_failing_evaluation.py
  src/ert/ensemble_evaluator/narratives/monitor_successful_ensemble.py
  src/ert/ensemble_evaluator/narratives/narrative.py
  src/ert/ensemble_evaluator/narratives/proxy.py
  tests/unit_tests/ensemble_evaluator/test_contracts.py
  tests/unit_tests/ensemble_evaluator/test_dispatchers.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/ensemble_evaluator/test_monitor.py
Labels: release-notes:misc

#4257 Remove ext_joblist
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/include/ert/enkf/enkf_state.hpp
  src/clib/lib/include/ert/job_queue/ext_job.hpp
  src/clib/lib/include/ert/job_queue/ext_joblist.hpp
  src/clib/lib/job_queue/ext_joblist.cpp
  src/clib/old_tests/job_queue/CMakeLists.txt
  src/clib/old_tests/job_queue/test_ext_joblist.cpp
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/enkf/site_config.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/_c_wrappers/job_queue/ext_joblist.py
  src/ert/_c_wrappers/job_queue/forward_model.py
  tests/test_config_parsing/config_dict_generator.py
  tests/unit_tests/c_wrappers/job_runner/test_jobmanager.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_site_config.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_joblist.py
  tests/unit_tests/c_wrappers/res/job_queue/test_forward_model_formatted_print.py
  tests/unit_tests/shared/share/test_shell.py
Labels: payback

#4285 Remove unused C after enkf_fs summary and gen_data refactor
  src/clib/lib/CMakeLists.txt
  src/clib/lib/analysis/update.cpp
  src/clib/lib/enkf/enkf_analysis.cpp
  src/clib/lib/enkf/enkf_fs.cpp
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/enkf_state.cpp
  src/clib/lib/enkf/gen_obs.cpp
  src/clib/lib/enkf/meas_data.cpp
  src/clib/lib/enkf/misfit_ensemble.cpp
  src/clib/lib/enkf/misfit_member.cpp
  src/clib/lib/enkf/misfit_ts.cpp
  src/clib/lib/enkf/obs_data.cpp
  src/clib/lib/enkf/obs_vector.cpp
  src/clib/lib/enkf/summary_obs.cpp
  src/clib/lib/include/ert/analysis/update.hpp
  src/clib/lib/include/ert/enkf/enkf_analysis.hpp
  src/clib/lib/include/ert/enkf/enkf_fs.hpp
  src/clib/lib/include/ert/enkf/enkf_macros.hpp
  src/clib/lib/include/ert/enkf/enkf_obs.hpp
  src/clib/lib/include/ert/enkf/gen_obs.hpp
  src/clib/lib/include/ert/enkf/meas_data.hpp
  src/clib/lib/include/ert/enkf/misfit_ensemble.hpp
  src/clib/lib/include/ert/enkf/misfit_ensemble_typedef.hpp
  src/clib/lib/include/ert/enkf/misfit_member.hpp
  src/clib/lib/include/ert/enkf/misfit_ts.hpp
  src/clib/lib/include/ert/enkf/obs_data.hpp
  src/clib/lib/include/ert/enkf/obs_vector.hpp
  src/clib/lib/include/ert/enkf/summary_obs.hpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_meas_data.cpp
  src/clib/old_tests/enkf/test_measured.cpp
  src/clib/old_tests/enkf/test_obs_mask_deactivate.cpp
  src/clib/tests/CMakeLists.txt
  src/clib/tests/enkf/test_enkf_fs.cpp
  src/clib/tests/enkf/test_meas_data.cpp
  src/clib/tests/enkf/test_obs_data.cpp
  src/ert/_c_wrappers/enkf/observations/obs_vector.py
Labels: release-notes:maintenance

#4287 Remove install of gui test dependencies in build step
  .github/workflows/build-wheels.yml
Labels: ci-pipeline

#4309 Bump doc timelimit
  .github/workflows/build.yml
Labels: ci-pipeline

#4307 Update versions of actions and python in ci
  .github/workflows/annotate_cpp.yml
  .github/workflows/annotate_python.yml
  .github/workflows/build-wheels.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/doctest.yml
  .github/workflows/run_ert_test_data_setups.yml
  .github/workflows/style.yml
  .github/workflows/test_ert.yml
  .github/workflows/test_semeio.yml
  .github/workflows/typing.yml
Labels: ci-pipeline

#4282 Cleanup ensemble_config simplification
  src/ert/_c_wrappers/enkf/ensemble_config.py
  test-data/configuration_tests/ensemble_config.ert
  tests/unit_tests/c_wrappers/res/config/test_config_parser.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
Labels: release-notes:maintenance

#4319 Fix pytest coverage not uploading correctly
  .github/workflows/coverage.yml
Labels: ci-pipeline

#4320 Delete unused ui_return
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/res_util/ui_return.hpp
  src/clib/lib/res_util/ui_return.cpp
  src/ert/_c_wrappers/util/__init__.py
  src/ert/_c_wrappers/util/enums/__init__.py
  src/ert/_c_wrappers/util/enums/ui_return_status_enum.py
  src/ert/_c_wrappers/util/ui_return.py
  tests/unit_tests/c_wrappers/res/util/test_ui_return.py
Labels: improvement

#4323 Delete unused llsq_result_enum and message_level_enum
  src/ert/_c_wrappers/util/__init__.py
  src/ert/_c_wrappers/util/enums/__init__.py
  src/ert/_c_wrappers/util/enums/llsq_result_enum.py
  src/ert/_c_wrappers/util/enums/message_level_enum.py
  tests/test_config_parsing/config_dict_generator.py
Labels: improvement

#4330 Fix incorrect printing of enum in case info
  src/ert/gui/tools/manage_cases/case_init_configuration.py
Labels: release-notes:bug-fix

#4215 Remove TEST_CONFIG_FILE_KEY testing keyword
  src/ert/_c_wrappers/enkf/res_config.py
  tests/conftest.py
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/test_analysis_config.py
  tests/test_config_parsing/test_ensemble_config.py
  tests/test_config_parsing/test_queue_config.py
  tests/test_config_parsing/test_site_config.py
  tests/test_config_parsing/test_substitution_list.py
  tests/test_config_parsing/test_workflow_list.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_subst_config.py
Labels: release-notes:maintenance

#4315 Use caching of github actions
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-macos.yml
  .github/workflows/build.yml
  .github/workflows/doctest.yml
  .github/workflows/test_ert.yml
Labels: ci-pipeline

#4325 Ignore expected exception from file-parsing in c++ in torque driver
  src/clib/lib/job_queue/torque_driver.cpp
Labels: bug, release-notes:misc

#4340 Update ensemble_evaluator log configuration
  src/ert/logging/logger.conf
Labels: release-notes:bug-fix

#4312 Add actionlint to lint the workflow files
  .github/workflows/actionlint.yml
  .github/workflows/annotate_cpp.yml
  .github/workflows/annotate_python.yml
  .github/workflows/build.yml
Labels: ci-pipeline, release-notes:misc

#4348 Fix ensemble_evaluator log configuration
  src/ert/logging/logger.conf
Labels: release-notes:bug-fix

#4350 Revert "Add memory threshold change to yield Running event"
  src/_ert_job_runner/cli.py
  src/_ert_job_runner/job.py
  src/_ert_job_runner/reporting/message.py
  src/_ert_job_runner/runner.py
  tests/unit_tests/c_wrappers/job_runner/test_job.py
Labels: release-notes:misc

#4354 Remove deprecated config keyword PORTABLE_EXE
  src/clib/lib/job_queue/ext_job.cpp
Labels: release-notes:breaking-change, release-notes:maintenance

#4378 Resolve pylint issue with subst_list import
  src/ert/_c_wrappers/config/config_content.py
Labels: payback

#4355 Refactor enkf_config_node
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/enkf_fs.cpp
  src/clib/lib/enkf/enkf_node.cpp
  src/clib/lib/enkf/enkf_state.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/obs_vector.cpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
Labels: release-notes:maintenance

#4393 Update FORWARD_MODEL documentation
  docs/reference/configuration/keywords.rst
Labels: release-notes:maintenance

#4347 Simplify model config by removing unused code and moving C code to python
  docs/reference/configuration/keywords.rst
  src/clib/lib/CMakeLists.txt
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/enkf/enkf_fs.cpp
  src/clib/lib/enkf/enkf_state.cpp
  src/clib/lib/enkf/model_config.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/clib/lib/include/ert/enkf/enkf_defaults.hpp
  src/clib/lib/include/ert/enkf/enkf_state.hpp
  src/clib/lib/include/ert/enkf/model_config.hpp
  src/clib/lib/include/ert/enkf/obs_vector.hpp
  src/clib/lib/python/enkf_defaults.cpp
  src/clib/lib/python/model_callbacks.cpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_model_config.cpp
  src/ert/__main__.py
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/enkf/time_map.py
  src/ert/cli/main.py
  src/ert/ensemble_evaluator/callbacks.py
  src/ert/gui/gert_main.py
  src/ert/gui/simulation/single_test_run_panel.py
  src/ert/libres_facade.py
  src/ert/shared/models/base_run_model.py
  src/ert/simulator/simulation_context.py
  test-data/configuration_tests/model_config.ert
  test-data/configuration_tests/sched_file_as_history_source.ert
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/test_model_config.py
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_config_content_as_dict.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_programmatic_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:maintenance

#4384 Make extjob python only and made `STDIN null` behave the same as `STDOUT null`
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/job_queue/ext_job.hpp
  src/clib/lib/include/ert/res_util/subst_list.hpp
  src/clib/lib/job_queue/ext_job.cpp
  src/clib/lib/job_queue/job_kw_definitions.cpp
  src/clib/tests/CMakeLists.txt
  src/clib/tests/job_queue/test_ext_job_executable.cpp
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/_c_wrappers/util/substitution_list.py
  src/ert/shared/models/base_run_model.py
  tests/unit_tests/c_wrappers/job_runner/test_jobmanager.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_programmatic_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
  tests/unit_tests/c_wrappers/res/job_queue/test_forward_model_formatted_print.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/shared/share/test_shell.py
Labels: release-notes:breaking-change, release-notes:maintenance

#4390 Simplify EnsembleConfig
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
Labels: release-notes:maintenance

#4338 Add version check to file system
  src/ert/_c_wrappers/enkf/enkf_fs_manager.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_fs_manager.py
Labels: release-notes:improvement

#4403 Fix typo in model config
  src/ert/_c_wrappers/enkf/model_config.py
Labels: release-notes:maintenance
