Repository equinor/ert, pull requests merged in 2022-10, with the labels that each got.

#3967 Log experiment type and size when a run model is instatiated
  src/ert/shared/cli/model_factory.py
Labels: release-notes:maintenance

#3968 Relax protobuf pin to "<4"
  setup.py
Labels: release-notes:dependency

#3963 Give empty representation in case of non initialized objects
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/_c_wrappers/enkf/ecl_config.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/hook_manager.py
  src/ert/_c_wrappers/enkf/queue_config.py
  src/ert/_c_wrappers/enkf/site_config.py
  src/ert/_c_wrappers/enkf/subst_config.py
Labels: enhancement

#3860 Improve test coverage of ok callback
  tests/libres_tests/integration/test_parameter_sample_types.py
Labels: release-notes:improvement

#3867 Remove the GEN_PARAM keyword
  docs/reference/configuration/data_types.rst
  docs/reference/configuration/keywords.rst
  docs/reference/configuration/observations.rst
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/gen_data_config.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/gen_data_config.hpp
  src/clib/old_tests/data/enkf/ensemble/GEN_PARAM
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_enkf_config_node_gen_data.cpp
  src/clib/old_tests/enkf/test_enkf_ensemble_GEN_PARAM.cpp
  src/clib/old_tests/enkf/test_enkf_gen_data_config.cpp
  src/clib/old_tests/enkf/test_enkf_gen_data_config_parse.cpp
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  test-data/local/configuration_tests/ensemble_config.ert
  tests/libres_tests/integration/test_parameter_sample_types.py
  tests/libres_tests/res/enkf/test_ensemble_config.py
Labels: release-notes:breaking-change

#3984 Raise exception if size of gen_kw in storage differs with gen_kw_config
  src/clib/lib/enkf/gen_kw.cpp
  tests/libres_tests/res/enkf/test_priors.py
Labels: release-notes:improvement

#3994 Upgrade pybind11 requirement
  pyproject.toml
Labels: release-notes:maintenance

#3992 Remove out of date comment
  src/ert/_c_wrappers/enkf/enkf_main.py
Labels: release-notes:maintenance

#3981 Mute external DEBUG messages
  src/ert/logging/logger.conf
Labels: improvement

#3982 Make default ensemble path consistent
  src/clib/lib/enkf/model_config.cpp
  tests/test_config_parsing/test_model_config.py
Labels: release-notes:bug-fix

#3989 Remove unused function weakref from EnkfFs
  src/ert/_c_wrappers/enkf/enkf_fs.py
Labels: release-notes:maintenance

#3990 Inline function to create mount point
  src/ert/_c_wrappers/enkf/enkf_main.py
Labels: release-notes:maintenance

#3980 Resolve some pylint reported observations
  docs/conf.py
  src/ert/_c_wrappers/config/config_parser.py
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/fm/shell/shell.py
  src/ert/_c_wrappers/job_queue/environment_varlist.py
  src/ert/_c_wrappers/job_queue/ext_joblist.py
  src/ert/_c_wrappers/job_queue/workflow_runner.py
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
  src/ert/gui/ertwidgets/checklist.py
  src/ert/gui/ertwidgets/models/all_cases_model.py
  src/ert/gui/ertwidgets/searchbox.py
  src/ert/gui/simulation/view/realization.py
  src/ert/gui/tools/plot/customize/limits_customization_view.py
  src/ert/gui/tools/plot/data_type_keys_list_model.py
  src/ert/gui/tools/plot/data_type_keys_widget.py
  src/ert/gui/tools/plot/filter_popup.py
  src/ert/gui/tools/plot/plot_case_model.py
  src/ert/shared/ensemble_evaluator/client.py
  src/ert/shared/plugins/plugin_response.py
  test-data/mini_ert/jobs/aggregator.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/prefect/scripts/evaluate_coeffs.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/ert_tests/ensemble_evaluator/test_monitor.py
  tests/ert_tests/gui/simulation/view/test_realization.py
  tests/ert_tests/services/test_base_service.py
  tests/libres_tests/res/enkf/test_enkf_main.py
  tests/libres_tests/res/util/test_subprocess.py
Labels: release-notes:improvement

#3988 Change num cpu interface / usage and default value
  docs/reference/configuration/keywords.rst
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/ensemble_evaluator/builder/_ensemble_builder.py
  src/ert/shared/models/base_run_model.py
  src/ert/simulator/simulation_context.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/libres_tests/res/enkf/test_res_config.py
  tests/test_config_parsing/test_num_cpu.py
  tests/test_config_parsing/test_queue_config.py
Labels: enhancement, Configuration, release-notes:maintenance

#4003 Simplify site config
  src/clib/lib/enkf/enkf_main.cpp
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/site_config.py
Labels: payback

#4008 Remove unused hook_manager_run_workflow
  src/clib/lib/enkf/hook_manager.cpp
  src/clib/lib/include/ert/enkf/hook_manager.hpp
Labels: payback

#3880 Update torque driver to handle finished jobs
  docs/reference/configuration/keywords.rst
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
  src/clib/lib/job_queue/qstat_proxy.sh
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/job_queue/test_job_queue_driver.cpp
  src/clib/old_tests/job_queue/test_job_torque.cpp
  tests/libres_tests/res/job_queue/test_ert_qstat_proxy.py
Labels: release-notes:bug-fix

#4013 Fix bug where PRE_FIRST_UPDATE cannot be selected
  src/clib/lib/config/config_keywords.cpp
  tests/libres_tests/res/enkf/test_res_config.py
Labels: bug

#3943 Move init and storing of GEN_KW form C to python
  src/clib/lib/enkf/block_fs_driver.cpp
  src/clib/lib/enkf/enkf_fs.cpp
  src/clib/lib/enkf/enkf_node.cpp
  src/clib/lib/enkf/enkf_util.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/gen_kw.cpp
  src/clib/lib/include/ert/enkf/block_fs_driver.hpp
  src/clib/lib/include/ert/enkf/gen_kw.hpp
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/res_config.py
  test-data/externally_sampled_params/FORWARD_MODEL
  test-data/externally_sampled_params/README.md
  test-data/externally_sampled_params/coeff.tmpl
  test-data/externally_sampled_params/coeff_priors
  test-data/externally_sampled_params/config.ert
  test-data/externally_sampled_params/forward_model.py
  test-data/externally_sampled_params/obs_data.txt
  test-data/externally_sampled_params/observations
  test-data/externally_sampled_params/time_map
  tests/ert_tests/analysis/test_es_update.py
  tests/libres_tests/integration/test_parameter_sample_types.py
Labels: release-notes:breaking-change, release-notes:maintenance

#4012 Remove hook manager
  src/clib/lib/CMakeLists.txt
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/enkf/ert_workflow_list.cpp
  src/clib/lib/enkf/hook_manager.cpp
  src/clib/lib/enkf/model_config.cpp
  src/clib/lib/enkf/subst_config.cpp
  src/clib/lib/include/ert/enkf/ert_workflow_list.hpp
  src/clib/lib/include/ert/enkf/hook_manager.hpp
  src/clib/lib/include/ert/enkf/hook_workflow.hpp
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ert_workflow_list.py
  src/ert/_c_wrappers/enkf/hook_manager.py
  src/ert/_c_wrappers/enkf/res_config.py
  tests/libres_tests/res/enkf/test_hook_manager.py
  tests/libres_tests/res/enkf/test_programmatic_res_config.py
  tests/libres_tests/res/enkf/test_res_config.py
  tests/libres_tests/res/enkf/test_site_config.py
Labels: payback

#4023 Fix test_config_parsing generation and site config
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/conftest.py
  tests/test_config_parsing/test_queue_config.py
Labels: testing, ci-pipeline

#4019 Change default runpath
  src/clib/lib/include/ert/enkf/enkf_defaults.hpp
  tests/ert_tests/status/test_tracking_integration.py
  tests/ert_tests/storage/test_extraction.py
  tests/libres_tests/integration/test_parameter_sample_types.py
  tests/libres_tests/res/enkf/config/test_gen_kw_config.py
  tests/libres_tests/res/enkf/test_enkf_main.py
  tests/libres_tests/res/enkf/test_enkf_transfer_env.py
  tests/libres_tests/res/enkf/test_runpaths.py
  tests/libres_tests/test_integration_config.py
Labels: release-notes:breaking-change

#4027 Remove collectors and keymanager
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/export/__init__.py
  src/ert/_c_wrappers/enkf/export/arg_loader.py
  src/ert/_c_wrappers/enkf/export/design_matrix_reader.py
  src/ert/_c_wrappers/enkf/export/gen_data_collector.py
  src/ert/_c_wrappers/enkf/export/gen_data_observation_collector.py
  src/ert/_c_wrappers/enkf/export/gen_kw_collector.py
  src/ert/_c_wrappers/enkf/export/misfit_collector.py
  src/ert/_c_wrappers/enkf/export/summary_collector.py
  src/ert/_c_wrappers/enkf/export/summary_observation_collector.py
  src/ert/_c_wrappers/enkf/key_manager.py
  src/ert/_c_wrappers/enkf/observations/gen_observation.py
  src/ert/_c_wrappers/enkf/plot_data/ensemble_plot_gen_data.py
  src/ert/libres_facade.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  tests/ert_tests/analysis/test_es_update.py
  tests/ert_tests/data/test_integration_data.py
  tests/ert_tests/test_libres_facade.py
  tests/libres_tests/res/enkf/export/__init__.py
  tests/libres_tests/res/enkf/export/test_arg_loader.py
  tests/libres_tests/res/enkf/export/test_design_matrix.py
  tests/libres_tests/res/enkf/export/test_export_join.py
  tests/libres_tests/res/enkf/export/test_gen_data_collector.py
  tests/libres_tests/res/enkf/export/test_gen_data_observation_collector.py
  tests/libres_tests/res/enkf/export/test_gen_kw_collector.py
  tests/libres_tests/res/enkf/export/test_misfit_collector.py
  tests/libres_tests/res/enkf/export/test_summary_collector.py
  tests/libres_tests/res/enkf/export/test_summary_observation_collector.py
  tests/libres_tests/res/enkf/test_key_manager.py
Labels: payback

#4046 Remove comment with todo
  src/ert/shared/cli/main.py
Labels: release-notes:maintenance

#4049 Fix bug where extra case is created when running ies
  src/ert/shared/models/iterated_ensemble_smoother.py
Labels: release-notes:bug-fix

#4047 Move config logging from main to res_config
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/logging/logger.conf
  src/ert/shared/main.py
  tests/ert_tests/shared/test_main_entry.py
  tests/libres_tests/res/enkf/test_res_config.py
Labels: release-notes:maintenance

#4053 Make sure loading gui produces just one storage folder
  src/clib/lib/enkf/model_config.cpp
  src/ert/gui/gert_main.py
  tests/ert_tests/gui/test_gui_load.py
Labels: release-notes:bug-fix

#3997 Remove outdated GEN_DATA docs
  docs/reference/configuration/data_types.rst
  docs/reference/configuration/keywords.rst
Labels: release-notes:maintenance

#4063 Add grid and grid_file properties back to libres_facade
  src/ert/libres_facade.py
Labels: release-notes:bug-fix

#4065 Extend description of libres facade
  src/ert/libres_facade.py
Labels: release-notes:improvement

#4080 Disable "Start simulation" button while running simulations
  src/ert/gui/simulation/simulation_panel.py
  tests/ert_tests/gui/test_gui_load.py
Labels: release-notes:bug-fix

#4067 Job runner yields Running event only when memory consumption has significant change
  src/_ert_job_runner/cli.py
  src/_ert_job_runner/job.py
  src/_ert_job_runner/reporting/message.py
  src/_ert_job_runner/runner.py
  tests/libres_tests/job_runner/test_job.py
Labels: release-notes:misc

#4086 Remove unused function `format_seed`
  src/ert/_c_wrappers/enkf/enkf_main.py
Labels: release-notes:maintenance

#4094 Show loading cursor when loading from runpath
  src/ert/gui/tools/load_results/load_results_tool.py
Labels: release-notes:improvement

#4093 Fix bug where not possible to initialize from scratch
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  tests/unit_tests/gui/tools/test_case_tool.py
Labels: release-notes:bug-fix

#4097 Remove HistorySourceEnum.SCHEDULE
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/sched/history_source_enum.py
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
Labels: release-notes:maintenance

#4099 Remove ert version number from run_ert2_test_data
  .github/workflows/run_ert_test_data_setups.yml
  README.md
Labels: release-notes:misc

#3958 Emit deprecation warning for non-ISO dates in observation config files
  setup.py
  src/clib/lib/config/conf_data.cpp
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
Labels: release-notes:misc

#4104 Update docs for DATA_FILE
  docs/reference/configuration/keywords.rst
  tests/unit_tests/c_wrappers/res/enkf/test_run_path_creation.py
Labels: documentation

#3733 Consume Protobuf events from dispatcher and pass them to the statemachine
  .github/workflows/typing.yml
  .gitignore
  .mypy-strict.ini
  .mypy.ini
  .pylintrc
  dev-requirements.txt
  docs/api_reference/experiment_server.rst
  docs/conf.py
  setup.py
  src/_ert_com_protocol/__init__.py
  src/_ert_com_protocol/_schema.proto
  src/_ert_com_protocol/_state_machine.py
  src/_ert_com_protocol/status_type_enum.py
  src/_ert_job_runner/reporting/protobuf.py
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/cli/main.py
  src/ert/ensemble_evaluator/builder/_ensemble.py
  src/ert/ensemble_evaluator/builder/_legacy.py
  src/ert/experiment_server/__init__.py
  src/ert/experiment_server/_experiment_protocol.py
  src/ert/experiment_server/_schema.proto
  src/ert/experiment_server/_server.py
  src/ert/experiment_server/_state_machine.py
  src/ert/shared/models/base_run_model.py
  src/ert/shared/models/ensemble_experiment.py
  src/ert/shared/models/ensemble_smoother.py
  src/ert/shared/models/iterated_ensemble_smoother.py
  src/ert/shared/models/multiple_data_assimilation.py
  tests/unit_tests/c_wrappers/job_runner/test_protobuf_reporter.py
  tests/unit_tests/experiment_server/test_server.py
  tests/unit_tests/experiment_server/test_statemachine.py
  types-requirements.txt
Labels: release-notes:new-feature, experiment-server

#4115 Change Union[*, None] typing to Optional[*]
  src/ert/analysis/_es_update.py
  src/ert/shared/models/base_run_model.py
Labels: release-notes:maintenance

#4119 Improve error message if a parameter is missing from storage
  src/clib/lib/analysis/update.cpp
  src/clib/lib/enkf/enkf_main.cpp
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:maintenance

#4113 Show restart button when all realisations fail
  src/ert/shared/models/base_run_model.py
  tests/unit_tests/models/test_base_run_model.py
Labels: release-notes:bug-fix

#3911 Support Torque job id without a dot character
  src/clib/lib/job_queue/qstat_proxy.sh
  src/clib/lib/job_queue/torque_driver.cpp
  tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py
  tests/unit_tests/c_wrappers/res/job_queue/test_job_queue_manager_torque.py
Labels: release-notes:improvement

#4127 Propagate error messages from job_queue_node
  src/ert/logging/logger.conf
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:bug-fix

#4137 Make forward_model only called from python
  src/clib/lib/enkf/enkf_main.cpp
  src/ert/_c_wrappers/enkf/enkf_main.py
Labels: payback

#4081 Define usage of setuptools_scm in pyproject.toml
  pyproject.toml
  setup.py
Labels: release-notes:maintenance

#4075 Remove bunch of stuff from ensemble config
  docs/reference/configuration/data_types.rst
  docs/reference/configuration/keywords.rst
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/enkf_node.cpp
  src/clib/lib/enkf/gen_data.cpp
  src/clib/lib/enkf/gen_data_config.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/enkf/gen_data.hpp
  src/clib/lib/include/ert/enkf/gen_data_config.hpp
  src/clib/old_tests/enkf/test_enkf_gen_data_config.cpp
  src/clib/old_tests/enkf/test_enkf_gen_data_config_parse.cpp
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/config/gen_data_config.py
  src/ert/_c_wrappers/enkf/data/gen_data.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: release-notes:maintenance

#4118 Solve pylint issues
  .github/workflows/style.yml
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/site_config.py
  src/ert/analysis/_es_update.py
  test-data/batch_sim/workflows/jobs/realization_number.py
  test-data/config/simulation_batch/jobs/copy_ext_param_script
  test-data/configuration_tests/input/jobs/snake_oil_diff.py
  test-data/configuration_tests/input/jobs/snake_oil_npv.py
  test-data/configuration_tests/input/jobs/snake_oil_simulator.py
  test-data/mini_ert/jobs/perlin.py
  test-data/mini_ert/jobs/perlin_fail.py
  test-data/poly_example/assert_runpath_file.py
  test-data/poly_template/poly_eval.py.j2
  test-data/row_scaling/workflows/scripts/row_scaling_job1.py
  test-data/snake_oil/jobs/snake_oil_diff.py
  test-data/snake_oil/jobs/snake_oil_npv.py
  test-data/snake_oil/jobs/snake_oil_simulator.py
  test-data/snake_oil_field/jobs/snake_oil_diff.py
  test-data/snake_oil_field/jobs/snake_oil_npv.py
  test-data/snake_oil_field/jobs/snake_oil_simulator.py
  test-data/snake_oil_structure/snake_oil/jobs/snake_oil_diff.py
  test-data/snake_oil_structure/snake_oil/jobs/snake_oil_npv.py
  test-data/snake_oil_structure/snake_oil/jobs/snake_oil_simulator.py
  tests/unit_tests/c_wrappers/job_runner/test_file_reporter.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
  tests/unit_tests/gui/ertwidgets/test_analysismodulevariablespanel.py
  tests/unit_tests/simulator/test_batch_sim.py
Labels: release-notes:maintenance

#4138 Propagate qstat options to qstat executable
  src/clib/lib/job_queue/torque_driver.cpp
  src/ert/_c_wrappers/job_queue/driver.py
  tests/unit_tests/c_wrappers/res/job_queue/test_job_queue_manager_torque.py
Labels: release-notes:bug-fix

#4141 Reintroduce reading init_files for GEN_KW
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/res_config.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:bug-fix

#4152 Remove todo and question from tests
  tests/test_config_parsing/config_dict_generator.py
Labels: release-notes:misc

#4145 Remove docs about keyword that does not exist
  docs/reference/configuration/keywords.rst
Labels: release-notes:maintenance

#4095 Split out sample prior from createRunPath
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ert_run_context.py
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  src/ert/shared/models/base_run_model.py
  src/ert/shared/models/ensemble_experiment.py
  src/ert/shared/models/ensemble_smoother.py
  src/ert/shared/models/iterated_ensemble_smoother.py
  src/ert/shared/models/multiple_data_assimilation.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_fs_manager.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_runpath.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_export.py
  tests/unit_tests/c_wrappers/res/enkf/test_priors.py
  tests/unit_tests/c_wrappers/res/enkf/test_row_scaling_case.py
  tests/unit_tests/c_wrappers/res/enkf/test_run_path_creation.py
  tests/unit_tests/c_wrappers/res/enkf/test_runpaths.py
  tests/unit_tests/storage/test_extraction.py
Labels: release-notes:maintenance

#4140 Reimplement formatted_fprintf in python
  src/clib/lib/include/ert/job_queue/environment_varlist.hpp
  src/clib/lib/include/ert/job_queue/ext_job.hpp
  src/clib/lib/include/ert/job_queue/forward_model.hpp
  src/clib/lib/include/ert/res_util/subst_list.hpp
  src/clib/lib/job_queue/environment_varlist.cpp
  src/clib/lib/job_queue/ext_job.cpp
  src/clib/lib/job_queue/forward_model.cpp
  src/clib/lib/job_queue/job_kw_definitions.cpp
  src/clib/old_tests/job_queue/CMakeLists.txt
  src/clib/old_tests/job_queue/test_ext_job.cpp
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/job_queue/environment_varlist.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/_c_wrappers/util/substitution_list.py
  src/ert/cli/main.py
  src/ert/gui/ertwidgets/models/ertsummary.py
  src/ert/gui/gert_main.py
  tests/unit_tests/c_wrappers/job_runner/test_jobmanager.py
  tests/unit_tests/c_wrappers/res/enkf/test_programmatic_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/job_queue/test_forward_model_formatted_print.py
  tests/unit_tests/c_wrappers/test_integration_config.py
  tests/unit_tests/gui/ertwidgets/models/test_ertsummary.py
Labels: payback

#4161 Add message box to load results manually instead of printing
  src/ert/gui/tools/load_results/load_results_panel.py
Labels: release-notes:improvement

#4163 Make enkf config node keys unique in test config dict generator
  tests/test_config_parsing/config_dict_generator.py
Labels: release-notes:misc
