Repository equinor/ert, pull requests merged in 2022-07, with the labels that each got.

#3598 Add a filter to the log messages in base_run_model
  ert_shared/models/base_run_model.py
Labels: release-notes:bug-fix

#3438 Introduce basic experiment server
  .mypy.ini
  docs/rst/manual/api_reference/experiment_server.rst
  docs/rst/manual/api_reference/index.rst
  ert/ensemble_evaluator/builder/_ensemble.py
  ert/ensemble_evaluator/builder/_legacy.py
  ert/ensemble_evaluator/builder/_prefect.py
  ert/ensemble_evaluator/identifiers.py
  ert/experiment_server/__init__.py
  ert/experiment_server/_experiment_protocol.py
  ert/experiment_server/_registry.py
  ert/experiment_server/_server.py
  ert/experiment_server/_state_machine.py
  ert_logging/logger.conf
  ert_shared/cli/main.py
  ert_shared/feature_toggling.py
  ert_shared/main.py
  ert_shared/models/base_run_model.py
  ert_shared/models/ensemble_experiment.py
  res/job_queue/queue.py
  setup.cfg
  tests/ert_tests/cli/test_integration_cli.py
  tests/ert_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/ert_tests/experiment_server/conftest.py
  tests/ert_tests/experiment_server/test_server.py
  tests/libres_tests/res/job_queue/test_job_queue.py
Labels: release-notes:new-feature, experiment-server

#3585 Solve pylint issue consider-using-generator
  .github/workflows/style.yml
  ert_gui/plottery/plots/histogram.py
  res/enkf/analysis_config.py
  res/enkf/queue_config.py
  res/enkf/res_config.py
  res/enkf/site_config.py
  res/job_queue/queue.py
Labels: release-notes:maintenance

#3583 Move handling of runpath and substitutions to python
  ert_shared/exporter.py
  ert_shared/hook_implementations/workflows/__init__.py
  ert_shared/hook_implementations/workflows/export_misfit_data.py
  ert_shared/hook_implementations/workflows/export_runpath.py
  ert_shared/share/ert/workflows/jobs/internal/config/EXPORT_RUNPATH
  libres/lib/enkf/enkf_main.cpp
  libres/lib/enkf/enkf_main_jobs.cpp
  libres/lib/enkf/enkf_main_manage_fs.cpp
  libres/lib/enkf/ert_run_context.cpp
  libres/lib/enkf/hook_manager.cpp
  libres/lib/enkf/model_config.cpp
  libres/lib/enkf/run_arg.cpp
  libres/lib/enkf/subst_config.cpp
  libres/lib/include/ert/enkf/enkf_main.hpp
  libres/lib/include/ert/enkf/ert_run_context.hpp
  libres/lib/include/ert/enkf/hook_manager.hpp
  libres/lib/include/ert/enkf/run_arg.hpp
  libres/lib/job_queue/workflow_job.cpp
  libres/old_tests/enkf/CMakeLists.txt
  libres/old_tests/enkf/test_enkf_ert_run_context.cpp
  libres/old_tests/enkf/test_enkf_export_inactive_cells.cpp
  libres/old_tests/enkf/test_enkf_forward_load_context.cpp
  libres/old_tests/enkf/test_enkf_gen_data_config.cpp
  libres/old_tests/enkf/test_enkf_magic_string_in_workflows.cpp
  libres/old_tests/enkf/test_enkf_run_arg.cpp
  libres/old_tests/enkf/test_enkf_state_manual_load.cpp
  libres/old_tests/enkf/test_enkf_state_report_step_compatible.cpp
  libres/old_tests/enkf/test_enkf_state_skip_summary_load.cpp
  libres/old_tests/enkf/test_enkf_umask_config.cpp
  libres/old_tests/enkf/test_enkf_workflow_job.cpp
  libres/old_tests/enkf/test_gen_kw.cpp
  libres/old_tests/enkf/test_gen_kw_logarithmic.cpp
  libres/tests/CMakeLists.txt
  libres/tests/enkf/test_ert_run_context.cpp
  res/enkf/enkf_fs_manager.py
  res/enkf/enkf_main.py
  res/enkf/enkf_simulation_runner.py
  res/enkf/ert_run_context.py
  res/enkf/hook_manager.py
  res/enkf/res_config.py
  res/enkf/run_arg.py
  res/enkf/runpaths.py
  res/enkf/substituter.py
  res/simulator/simulation_context.py
  res/util/path_format.py
  tests/ert_tests/all/plugins/test_export_runpath.py
  tests/ert_tests/cli/test_cli_workflow.py
  tests/libres_tests/res/enkf/test_enkf_main.py
  tests/libres_tests/res/enkf/test_ert_run_context.py
  tests/libres_tests/res/enkf/test_hook_manager.py
  tests/libres_tests/res/enkf/test_res_config.py
  tests/libres_tests/res/enkf/test_runpath_list_dump.py
  tests/libres_tests/res/enkf/test_runpath_list_ert.py
  tests/libres_tests/res/enkf/test_runpaths.py
  tests/libres_tests/res/enkf/test_site_config.py
  tests/libres_tests/res/enkf/test_substituter.py
  tests/libres_tests/res/simulator/test_simulation_context.py
Labels: release-notes:maintenance

#3586 Solve pylint issue arguments-renamed
  .github/workflows/style.yml
  ert_gui/ertwidgets/models/activerealizationsmodel.py
  ert_gui/ertwidgets/models/init_iter_value.py
  ert_gui/ertwidgets/models/targetcasemodel.py
  res/enkf/observations/block_data_config.py
  res/job_queue/job_status_type_enum.py
  res/job_queue/job_submit_status_type_enum.py
  res/job_queue/run_status_type_enum.py
Labels: release-notes:maintenance

#3550 Add a read_only flag to enkf_main
  ert_shared/dark_storage/enkf.py
  ert_shared/libres_facade.py
  libres/lib/enkf/enkf_fs.cpp
  libres/lib/enkf/enkf_main.cpp
  libres/lib/enkf/enkf_main_manage_fs.cpp
  libres/lib/enkf/ert_test_context.cpp
  libres/lib/include/ert/enkf/enkf_fs.hpp
  libres/lib/include/ert/enkf/enkf_main.hpp
  libres/old_tests/enkf/test_enkf_fs.cpp
  libres/tests/enkf/test_enkf_fs.cpp
  res/enkf/enkf_fs.py
  res/enkf/enkf_fs_manager.py
  res/enkf/enkf_main.py
  res/enkf/export/design_matrix_reader.py
  res/enkf/export/gen_data_collector.py
  res/enkf/export/gen_data_observation_collector.py
  res/enkf/export/gen_kw_collector.py
  res/enkf/export/misfit_collector.py
  res/enkf/export/summary_collector.py
  res/enkf/export/summary_observation_collector.py
Labels: release-notes:misc

#3629 Fix flaky timeout on ci
  tests/ert_tests/ert3/conftest.py
Labels: flaky-test

#3645 Skip flaky test of experiment server
  tests/ert_tests/cli/test_integration_cli.py
Labels: testing, ci-pipeline, skipped_test

#3651 Use Ubuntu 20.04 for running spe1 workflow
  .github/workflows/run_examples_spe1.yml
Labels: maintenance

#3652 Move ert3 examples
  .github/workflows/typing.yml
  ci/jenkins/testkomodo-ERT.sh
  ci/jenkins/testkomodo-repeat-flaky.sh
  ci/jenkins/testkomodo.sh
  setup.py
  src/ert/ert3/console/_console.py
  src/ert/ert3/examples/__init__.py
  src/ert/ert3/examples/polynomial/data/coefficients_record_doe.json
  src/ert/ert3/examples/polynomial/data/coefficients_record_doe3.json
  src/ert/ert3/examples/polynomial/data/storage_coefficients.json
  src/ert/ert3/examples/polynomial/experiments/doe.yml
  src/ert/ert3/examples/polynomial/experiments/doe3.yml
  src/ert/ert3/examples/polynomial/experiments/evaluation.yml
  src/ert/ert3/examples/polynomial/experiments/fast_sensitivity.yml
  src/ert/ert3/examples/polynomial/experiments/function_evaluation.yml
  src/ert/ert3/examples/polynomial/experiments/partial_sensitivity.yml
  src/ert/ert3/examples/polynomial/experiments/sensitivity.yml
  src/ert/ert3/examples/polynomial/experiments/uniform_evaluation.yml
  src/ert/ert3/examples/polynomial/experiments/uniform_sensitivity.yml
  src/ert/ert3/examples/polynomial/experiments/x_uncertainty.yml
  src/ert/ert3/examples/polynomial/function_steps/__init__.py
  src/ert/ert3/examples/polynomial/function_steps/functions.py
  src/ert/ert3/examples/polynomial/parameters.yml
  src/ert/ert3/examples/polynomial/run_demo
  src/ert/ert3/examples/polynomial/stages.yml
  src/ert/ert3/examples/polynomial/steps/bin/poly.py
  src/ert/ert3/examples/snake_oil/README
  src/ert/ert3/examples/snake_oil/designmatrixtxt2json.py
  src/ert/ert3/examples/snake_oil/experiments/doe.yml
  src/ert/ert3/examples/snake_oil/experiments/evaluation.yml
  src/ert/ert3/examples/snake_oil/experiments/sensitivity.yml
  src/ert/ert3/examples/snake_oil/parameters.yml
  src/ert/ert3/examples/snake_oil/render.py
  src/ert/ert3/examples/snake_oil/resources/designmatrix.xlsx
  src/ert/ert3/examples/snake_oil/resources/seed_tmpl
  src/ert/ert3/examples/snake_oil/resources/seedtxt
  src/ert/ert3/examples/snake_oil/resources/snake_oil_txt_tmpl
  src/ert/ert3/examples/snake_oil/run_demo
  src/ert/ert3/examples/snake_oil/snake_oil_simulator.py
  src/ert/ert3/examples/snake_oil/stages.yml
  src/ert/ert3/examples/spe1/README.md
  src/ert/ert3/examples/spe1/experiments/doe.yml
  src/ert/ert3/examples/spe1/experiments/evaluation.yml
  src/ert/ert3/examples/spe1/experiments/sensitivity.yml
  src/ert/ert3/examples/spe1/parameters.yml
  src/ert/ert3/examples/spe1/render.py
  src/ert/ert3/examples/spe1/resources/case/SPE1CASE2.DATA.jinja2
  src/ert/ert3/examples/spe1/resources/case/include/spe1.pvt
  src/ert/ert3/examples/spe1/resources/field_properties.json
  src/ert/ert3/examples/spe1/resources/wells.json
  src/ert/ert3/examples/spe1/run_demo
  src/ert/ert3/examples/spe1/stages.yml
Labels: release-notes:maintenance

#3654 Move ert_logging to ert.logging
  .github/workflows/style.yml
  .github/workflows/typing.yml
  setup.py
  src/ert/logging/__init__.py
  src/ert/logging/_log_util_abort.py
  src/ert/logging/logger.conf
  src/ert/logging/storage_log.conf
  src/ert_shared/main.py
  src/ert_shared/services/_storage_main.py
  tests/ert_tests/shared/test_log_abort.py
Labels: release-notes:maintenance
