Repository equinor/ert, pull requests merged in 2022-09, with the labels that each got.

#3824 Update documentation of SUMMARY keyword
  docs/reference/configuration/data_types.rst
Labels: documentation

#3848 Fix deprecation warning in py310 from setDaemon
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/plugins/plugin_runner.py
  src/ert/gui/tools/workflows/run_workflow_widget.py
Labels: release-notes:maintenance

#3842 Do not add summary keys from storage to config
  src/ert/_c_wrappers/enkf/enkf_main.py
  tests/ert_tests/shared/test_libres_facade.py
  tests/libres_tests/res/enkf/test_key_manager.py
  tests/libres_tests/res/enkf/test_summary_key_set.py
Labels: release-notes:breaking-change

#3852 Remove unused and disfunctional functions
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/job_queue/queue.py
Labels: release-notes:maintenance

#3846 Test update with INIT_FILES and FORWARD_INIT
  test-data/local/externally_sampled_params/FORWARD_MODEL
  test-data/local/externally_sampled_params/README.md
  test-data/local/externally_sampled_params/coeff.tmpl
  test-data/local/externally_sampled_params/coeff_priors
  test-data/local/externally_sampled_params/config.ert
  test-data/local/externally_sampled_params/forward_model.py
  test-data/local/externally_sampled_params/obs_data.txt
  test-data/local/externally_sampled_params/observations
  test-data/local/externally_sampled_params/time_map
  tests/libres_tests/res/enkf/test_es_update.py
Labels: release-notes:maintenance

#3834 Remove CONTAINER keyword
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/enkf/container.cpp
  src/clib/lib/enkf/container_config.cpp
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/enkf_node.cpp
  src/clib/lib/enkf/enkf_state.cpp
  src/clib/lib/enkf/enkf_state_nodes.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/clib/lib/include/ert/enkf/container.hpp
  src/clib/lib/include/ert/enkf/container_config.hpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/enkf/enkf_node.hpp
  src/clib/lib/include/ert/enkf/enkf_types.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/data/enkf_node.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/enums/ert_impl_type_enum.py
  test-data/local/configuration_tests/ensemble_config.ert
  tests/libres_tests/res/enkf/test_ensemble_config.py
Labels: release-notes:maintenance

#3814 Mute connection closed error from websocket
  src/ert/shared/ensemble_evaluator/client.py
  src/ert/shared/ensemble_evaluator/dispatch.py
  src/ert/shared/ensemble_evaluator/evaluator.py
Labels: release-notes:maintenance

#3864 Test size of covariance instead of variance
  tests/libres_tests/res/enkf/test_es_update.py
Labels: release-notes:maintenance

#3861 Add DisableParametersUpdate workflow
  src/ert/shared/hook_implementations/workflows/__init__.py
  src/ert/shared/hook_implementations/workflows/disable_parameters.py
  tests/ert_tests/all/plugins/test_parameter_disable.py
Labels: release-notes:new-feature

#3863 Fix bug where random seed would overflow
  src/ert/_c_wrappers/enkf/rng_config.py
  tests/libres_tests/res/enkf/test_enkf.py
Labels: release-notes:bug-fix

#3849 Close stdin/stdout/stderr files when done
  src/ert/job_runner/job.py
Labels: release-notes:maintenance

#3811 Generate experiment_id and propagate to communication channels
  src/ert/ensemble_evaluator/builder/_ensemble.py
  src/ert/ensemble_evaluator/builder/_legacy.py
  src/ert/experiment_server/_registry.py
  src/ert/experiment_server/_server.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/shared/cli/main.py
  src/ert/shared/cli/model_factory.py
  src/ert/shared/models/base_run_model.py
  src/ert/shared/models/ensemble_experiment.py
  src/ert/shared/models/ensemble_smoother.py
  src/ert/shared/models/iterated_ensemble_smoother.py
  src/ert/shared/models/multiple_data_assimilation.py
  src/ert/shared/models/single_test_run.py
  tests/ert_tests/cli/test_model_factory.py
  tests/ert_tests/cli/test_model_hook_order.py
  tests/ert_tests/models/test_base_run_model.py
  tests/ert_tests/status/test_evaluator_tracker.py
  tests/ert_tests/status/test_tracking_integration.py
Labels: release-notes:misc

#3883 Remove deprecation limit on ert.data.loader.load_general_data and load.summary.data
  src/ert/data/loader.py
Labels: release-notes:misc

#3884 Remove deprecation limit on ert.data.loader.load_general_data and load.summary.data
  src/ert/data/loader.py
Labels: release-notes:misc

#3855 Use built-in black in GitHub action
  .github/workflows/style.yml
Labels: release-notes:maintenance

#3874 Remove non-functional private mode for EnkfNode
  src/ert/_c_wrappers/enkf/data/enkf_node.py
Labels: release-notes:maintenance

#3856 Use variable defining matrix start size
  src/clib/lib/analysis/update.cpp
Labels: release-notes:maintenance

#3900 Move enkf_fs method from enkf_main to enkf_fs
  src/clib/lib/enkf/enkf_fs.cpp
  src/clib/lib/enkf/enkf_main.cpp
  src/clib/lib/include/ert/concurrency.hpp
  src/clib/lib/include/ert/enkf/enkf_main.hpp
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  tests/libres_tests/res/enkf/test_enkf_main.py
  tests/performance_tests/enkf/test_load_state.py
Labels: release-notes:maintenance

#3916 Free obs_data in load_observations_and_responses
  src/clib/lib/analysis/update.cpp
Labels: release-notes:maintenance

#3931 Remove reading of site_config directly from file
  src/clib/lib/enkf/site_config.cpp
  src/clib/lib/include/ert/enkf/site_config.hpp
  src/clib/tests/enkf/test_deprecated_umask.cpp
  src/ert/_c_wrappers/enkf/site_config.py
  tests/libres_tests/res/enkf/test_site_config.py
Labels: payback

#3933 Remove direct init of job_queue from file
  src/clib/lib/enkf/queue_config.cpp
  src/clib/lib/include/ert/enkf/queue_config.hpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_executable_path.cpp
  src/clib/old_tests/enkf/test_enkf_queue_config.cpp
  src/ert/_c_wrappers/enkf/queue_config.py
  tests/libres_tests/res/enkf/test_queue_config.py
Labels: payback

#3932 Remove unused analysis_config directly from file
  src/clib/lib/enkf/analysis_config.cpp
  src/clib/lib/include/ert/enkf/analysis_config.hpp
  src/ert/_c_wrappers/enkf/analysis_config.py
  tests/libres_tests/res/enkf/test_analysis_config.py
Labels: payback

#3928 Add string representation of ResConfig
  src/ert/_c_wrappers/enkf/res_config.py
Labels: enhancement

#3934 Remove unused model config functions
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/model_config.cpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/model_config.hpp
  src/clib/old_tests/enkf/test_enkf_model_config.cpp
Labels: payback

#3941 Clean up unused c code and superflous `extern "C"`
  src/clib/lib/enkf/meas_data.cpp
  src/clib/lib/enkf/obs_data.cpp
  src/clib/lib/include/ert/config/config_content.hpp
  src/clib/lib/include/ert/config/config_parser.hpp
  src/clib/lib/include/ert/enkf/enkf_fs.hpp
  src/clib/lib/include/ert/enkf/enkf_node.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/field_common.hpp
  src/clib/lib/include/ert/enkf/gen_data_config.hpp
  src/clib/lib/include/ert/enkf/meas_data.hpp
  src/clib/lib/include/ert/enkf/model_config.hpp
  src/clib/lib/include/ert/enkf/obs_data.hpp
  src/clib/lib/include/ert/enkf/summary_key_matcher.hpp
  src/clib/old_tests/enkf/test_enkf_meas_data.cpp
Labels: payback

#3768 Use Experiment server in all run models when feature is enabled
  src/ert/experiment_server/_server.py
  src/ert/shared/main.py
  src/ert/shared/models/base_run_model.py
  src/ert/shared/models/ensemble_experiment.py
  src/ert/shared/models/ensemble_smoother.py
  src/ert/shared/models/iterated_ensemble_smoother.py
  src/ert/shared/models/multiple_data_assimilation.py
  src/ert/shared/models/single_test_run.py
  tests/ert_tests/cli/test_integration_cli.py
Labels: enhancement, release-notes:new-feature, experiment-server

#3851 Solve pylint issue no-member
  .github/workflows/style.yml
  src/ert/_c_wrappers/__init__.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/gui/tools/event_viewer/panel.py
  src/ert/job_runner/cli.py
  src/ert/shared/ensemble_evaluator/narratives/proxy.py
  src/ert/shared/ensemble_evaluator/sync_ws_duplexer.py
  src/ert/shared/plugins/plugin_manager.py
  src/ert/shared/port_handler.py
  src/ert/storage/_storage.py
  test-data/local/snake_oil_field/make_data.py
  tests/ert_tests/all/plugins/test_parameter_disable.py
  tests/ert_tests/cli/test_cli_workflow.py
  tests/ert_tests/dark_storage/conftest.py
  tests/ert_tests/data/test_loader.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/test_contracts.py
  tests/ert_tests/ensemble_evaluator/test_sync_ws_duplexer.py
  tests/ert_tests/gui/test_gui_load.py
  tests/libres_tests/job_runner/test_protobuf_reporter.py
  tests/libres_tests/res/config/test_config_parser.py
  tests/libres_tests/res/enkf/test_active_list.py
  tests/libres_tests/res/enkf/test_field_config.py
  tests/libres_tests/res/job_queue/test_job_queue.py
  tests/performance_tests/conftest.py
  tests/utils.py
Labels: release-notes:maintenance

#3892 Remove UMASK config option
  docs/reference/configuration/keywords.rst
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/enkf/enkf_main.cpp
  src/clib/lib/enkf/site_config.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/clib/lib/include/ert/enkf/site_config.hpp
  src/clib/lib/include/ert/job_queue/forward_model.hpp
  src/clib/lib/job_queue/forward_model.cpp
  src/clib/tests/CMakeLists.txt
  src/clib/tests/enkf/test_deprecated_umask.cpp
  src/clib/tests/res_util/test_memory.cpp
  src/ert/_c_wrappers/enkf/site_config.py
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/job_runner/runner.py
  test-data/local/simple_config/config_umask
  test-data/local/snake_oil/snake_oil.ert
  test-data/local/snake_oil/storage/snake_oil/runpath/realization-0/iter-0/jobs.json
  test-data/local/snake_oil_structure/ert/model/user_config.ert
  tests/ert_tests/ensemble_evaluator/conftest.py
  tests/ert_tests/shared/test_main_entry.py
  tests/libres_tests/job_runner/test_job_dispatch.py
  tests/libres_tests/job_runner/test_job_manager_runtime_kw.py
  tests/libres_tests/job_runner/test_jobmanager.py
  tests/libres_tests/res/enkf/test_programmatic_res_config.py
  tests/libres_tests/res/enkf/test_res_config.py
  tests/libres_tests/res/enkf/test_site_config.py
  tests/libres_tests/res/job_queue/test_forward_model_formatted_print.py
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/test_res_config.py
  tests/test_config_parsing/test_site_config.py
Labels: release-notes:breaking-change

#3964 Fix has_data check in initRun
  src/ert/_c_wrappers/enkf/enkf_main.py
Labels: release-notes:bug-fix
