Repository equinor/ert, pull requests merged in 2022-04, with the labels that each got.

#3192 Update labels for automatic release notes generation
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
Labels: release-notes:misc

#3199 Add maintenance as release notes category
  .github/release.yml
Labels: release-notes:misc

#3200 Fix index out of bounds for active realizations < ensemble size in ESMDA
  ert_shared/models/multiple_data_assimilation.py
  tests/ert_tests/cli/test_integration_cli.py
Labels: release-notes:bug-fix

#3136 Add event viewer tool to gui
  ert_gui/gert_main.py
  ert_gui/tools/event_viewer/__init__.py
  ert_gui/tools/event_viewer/panel.py
  ert_gui/tools/event_viewer/tool.py
  tests/ert_tests/gui/logging/test_logging_tool.py
Labels: enhancement, qt, release-notes:improvement

#3193 Change default inversion to IES_INVERSION_EXACT
  docs/rst/manual/getting_started/configuration/poly_new/guide.rst
  docs/rst/manual/getting_started/configuration/poly_new/with_observations/poly_final.ert
  libres/lib/analysis/ies/ies_config.cpp
  libres/lib/analysis/update.cpp
  libres/old_tests/analysis/ies/test_ies_std_compare.cpp
  libres/tests/analysis/test_update.cpp
  test-data/local/row_scaling/config
  test-data/local/snake_oil/snake_oil.ert
Labels: release-notes:improvement

#3208 Undo pinning of click in dev-requirements
  .github/workflows/style.yml
  dev-requirements.txt
Labels: release-notes:maintenance

#3206 Delete unused test_analysis_test_external_module.c
  libres/old_tests/analysis/ies/test_ies_iteration.cpp
  libres/old_tests/analysis/test_analysis_test_external_module.c
Labels: release-notes:maintenance

#3218 Log the contents of the ERT2 configuration file
  ert_shared/main.py
  tests/ert_tests/shared/test_main_entry.py
Labels: release-notes:improvement

#3213 Update algorithm GUI config
  ert_gui/ertwidgets/analysismoduleselector.py
  ert_gui/ertwidgets/analysismodulevariablespanel.py
  ert_gui/ertwidgets/models/analysismodulevariablesmodel.py
  ert_shared/libres_facade.py
  libres/lib/analysis/analysis_module.cpp
  res/analysis/analysis_module.py
  tests/ert_tests/gui/ertwidgets/test_analysismodulevariablespanel.py
Labels: release-notes:improvement

#3236 Remove using matrix_type from serializer
  libres/lib/analysis/update.cpp
  libres/lib/enkf/enkf_node.cpp
  libres/lib/enkf/enkf_serialize.cpp
  libres/lib/enkf/field.cpp
  libres/lib/enkf/gen_data.cpp
  libres/lib/enkf/gen_kw.cpp
  libres/lib/enkf/summary.cpp
  libres/lib/enkf/surface.cpp
  libres/lib/include/ert/enkf/enkf_macros.hpp
  libres/lib/include/ert/enkf/enkf_node.hpp
  libres/lib/include/ert/enkf/enkf_serialize.hpp
Labels: maintenance, release-notes:maintenance

#3234 Remove unused covar from obs_data and replace replace matrix_type with eigen in meas_data
  libres/lib/enkf/block_obs.cpp
  libres/lib/enkf/enkf_obs.cpp
  libres/lib/enkf/gen_obs.cpp
  libres/lib/enkf/meas_data.cpp
  libres/lib/enkf/obs_data.cpp
  libres/lib/enkf/summary_obs.cpp
  libres/lib/include/ert/enkf/meas_data.hpp
  libres/lib/include/ert/enkf/obs_data.hpp
  libres/old_tests/enkf/test_enkf_update_log.cpp
  libres/old_tests/enkf/test_measured.cpp
  libres/old_tests/enkf/test_obs_mask_deactivate.cpp
  libres/tests/analysis/test_update.cpp
  libres/tests/enkf/test_obs_data.cpp
Labels: release-notes:maintenance

#3222 Fetch observation data from dark storage
  ert_gui/gert_main.py
  ert_gui/plottery/plots/observations.py
  ert_gui/tools/plot/plot_api.py
  ert_gui/tools/plot/plot_window.py
  tests/ert_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:new-feature

#3189 Have repeated flaky tests run new python instance
  ci/jenkins/testkomodo-repeat-flaky.sh
Labels: ci-pipeline

#3232 Upgrade and add more info to log message when failing to read SUMMARY
  libres/lib/enkf/enkf_state.cpp
Labels: release-notes:improvement

#3230 Remove flag for using aa_projection in IES and ES
  docs/rst/manual/advanced/Oscillator.ipynb
  docs/rst/manual/advanced/Oscillator.py
  docs/rst/manual/advanced/Polynomial.ipynb
  docs/rst/manual/advanced/Polynomial.py
  docs/rst/static_html/Oscillator.html
  docs/rst/static_html/Polynomial.html
  ert/analysis/ies/__init__.py
  ert_gui/ertwidgets/analysismodulevariablespanel.py
  libres/lib/analysis/analysis_module.cpp
  libres/lib/analysis/ies/ies.cpp
  libres/lib/analysis/ies/ies_config.cpp
  libres/lib/analysis/update.cpp
  libres/lib/include/ert/analysis/ies/ies.hpp
  libres/lib/include/ert/analysis/ies/ies_config.hpp
  libres/old_tests/analysis/ies/test_ies_iteration.cpp
  libres/old_tests/analysis/ies/test_ies_linalg.cpp
  libres/old_tests/analysis/ies/test_ies_std_compare.cpp
  res/analysis/analysis_module.py
  tests/libres_tests/res/enkf/test_es_update.py
Labels: analysis, release-notes:breaking-change

#3211 Fix scaling of ESMDA weights
  ert_shared/models/multiple_data_assimilation.py
  libres/lib/analysis/update.cpp
  tests/ert_tests/gui/test_multiple_data_assimilation.py
Labels: bug, release-notes:breaking-change

#3253 Address comments left over from pull 3219
  ert/ensemble_evaluator/builder/_ensemble.py
  ert/ensemble_evaluator/builder/_legacy.py
Labels: release-notes:maintenance

#3249 Filter out comments from logged configuration
  ert_shared/main.py
  tests/ert_tests/shared/test_main_entry.py
Labels: release-notes:maintenance

#3231 Replace deprecated `..index.is_all_dates` in plottery
  ert_gui/plottery/plots/ensemble.py
  ert_gui/plottery/plots/plot_tools.py
  ert_gui/plottery/plots/statistics.py
  tests/ert_tests/gui/plottery/plots/test_plot_tools.py
Labels: release-notes:maintenance

#3261 Pin PyQt5-sip to 12.9.1 or lower
  setup.py
Labels: packaging, release-notes:maintenance

#3257 Remove unused function -time_map_summary_upgrade107
  libres/lib/enkf/time_map.cpp
  libres/lib/include/ert/enkf/time_map.hpp
  res/enkf/util/time_map.py
Labels: release-notes:maintenance

#3247 Remove option of loading from non-unified summary files
  libres/lib/enkf/forward_load_context.cpp
Labels: release-notes:breaking-change

#3209 Add visualise parameter to ert3 for starting webviz-ert
  ert3/console/_console.py
Labels: release-notes:ert3

#3285 Remove pytest-runner
  setup.py
Labels: testing, packaging, release-notes:maintenance

#3256 Replace util_abort on time map with logging error and failing realisation
  libres/lib/enkf/enkf_main_manage_fs.cpp
  libres/lib/enkf/enkf_state.cpp
  libres/lib/enkf/time_map.cpp
  libres/lib/include/ert/enkf/time_map.hpp
  libres/old_tests/enkf/CMakeLists.txt
  libres/old_tests/enkf/test_enkf_time_map.cpp
  res/enkf/util/time_map.py
  tests/libres_tests/res/enkf/test_load_forward_model.py
  tests/libres_tests/res/enkf/test_time_map.py
Labels: release-notes:improvement

#2934 Add support for a scalar NumericalRecord
  ert/data/record/_record.py
  ert/storage/_storage.py
  ert3/algorithms/_sensitivity.py
  ert3/config/_parameters_config.py
  ert3/stats/_stats.py
  ert3_examples/snake_oil/designmatrixtxt2json.py
  ert3_examples/snake_oil/parameters.yml
  ert3_examples/snake_oil/resources/seed_tmpl
  ert3_examples/snake_oil/resources/snake_oil_txt_tmpl
  tests/ert_tests/ert3/algorithms/test_fast.py
  tests/ert_tests/ert3/algorithms/test_one_at_a_time.py
  tests/ert_tests/ert3/config/test_parameters_config.py
  tests/ert_tests/ert3/data/test_record.py
  tests/ert_tests/ert3/data/test_transmitters.py
  tests/ert_tests/ert3/stats/test_distributions.py
Labels: enhancement, ert3, release-notes:new-feature, release-notes:ert3

#3294 Use model factory in gui
  ert_gui/simulation/ensemble_experiment_panel.py
  ert_gui/simulation/ensemble_smoother_panel.py
  ert_gui/simulation/iterated_ensemble_smoother_panel.py
  ert_gui/simulation/multiple_data_assimilation_panel.py
  ert_gui/simulation/simulation_panel.py
  ert_gui/simulation/single_test_run_panel.py
  tests/ert_tests/gui/test_gui_load.py
Labels: release-notes:maintenance

#3306 Solve bug with main window closing too early
  ert_gui/gert_main.py
Labels: release-notes:misc

#3304 Decrease example size for polynomial doe
  ert3_examples/polynomial/experiments/doe/coefficients_record.json
  ert3_examples/polynomial/experiments/doe/ensemble.yml
Labels: release-notes:maintenance

#3173 Add report functionality to update step
  ert_shared/libres_facade.py
  ert_shared/storage/extraction.py
  libres/lib/analysis/update.cpp
  libres/lib/enkf/enkf_analysis.cpp
  libres/lib/enkf/local_ministep.cpp
  libres/lib/include/ert/analysis/update.hpp
  libres/lib/include/ert/enkf/enkf_analysis.hpp
  libres/lib/include/ert/enkf/local_ministep.hpp
  libres/old_tests/enkf/CMakeLists.txt
  libres/old_tests/enkf/test_enkf_update_log.cpp
  libres/tests/analysis/test_save_parameters.cpp
  res/enkf/enkf_main.py
  res/enkf/es_update.py
  res/enkf/local_ministep.py
  tests/libres_tests/res/enkf/snapshots/test_es_update/test_update_report/update_log
  tests/libres_tests/res/enkf/test_es_update.py
  tests/libres_tests/res/enkf/test_local_config.py
Labels: release-notes:maintenance

#3301 Remove the current parameter group concept
  ert3/config/_parameters_config.py
  ert3/console/_console.py
  ert3/engine/_record.py
  ert3/engine/_sensitivity.py
  ert3_examples/spe1/README.md
  tests/ert_tests/ert3/algorithms/test_one_at_a_time.py
  tests/ert_tests/ert3/config/test_parameters_config.py
  tests/ert_tests/ert3/engine/integration/test_engine.py
Labels: ert3, release-notes:ert3

#3308 Delete test-data snake_oil_no_data
  test-data/local/snake_oil_no_data/SEED
  test-data/local/snake_oil_no_data/jobs/SNAKE_OIL_DIFF
  test-data/local/snake_oil_no_data/jobs/SNAKE_OIL_NPV
  test-data/local/snake_oil_no_data/jobs/SNAKE_OIL_SIMULATOR
  test-data/local/snake_oil_no_data/jobs/snake_oil_diff.py
  test-data/local/snake_oil_no_data/jobs/snake_oil_npv.py
  test-data/local/snake_oil_no_data/jobs/snake_oil_simulator.py
  test-data/local/snake_oil_no_data/observations/observations.txt
  test-data/local/snake_oil_no_data/observations/wpr_diff_obs.txt
  test-data/local/snake_oil_no_data/parameters/snake_oil_parameters.txt
  test-data/local/snake_oil_no_data/refcase/SNAKE_OIL_FIELD.SMSPEC
  test-data/local/snake_oil_no_data/refcase/SNAKE_OIL_FIELD.UNSMRY
  test-data/local/snake_oil_no_data/refcase/refcase_readme.txt
  test-data/local/snake_oil_no_data/refcase/seed.txt
  test-data/local/snake_oil_no_data/refcase/snake_oil_params.txt
  test-data/local/snake_oil_no_data/refcase/time_map.txt
  test-data/local/snake_oil_no_data/snake_oil.ert
  test-data/local/snake_oil_no_data/snake_oil_GEN_DATA.ert
  test-data/local/snake_oil_no_data/snake_oil_GEO_ID.ert
  test-data/local/snake_oil_no_data/snake_oil_no_gen_kw.ert
  test-data/local/snake_oil_no_data/storage/snake_oil/runpath/realization-0/iter-0/SNAKE_OIL_FIELD.SMSPEC
  test-data/local/snake_oil_no_data/storage/snake_oil/runpath/realization-0/iter-0/SNAKE_OIL_FIELD.UNSMRY
  test-data/local/snake_oil_no_data/storage/snake_oil/runpath/realization-0/iter-0/snake_oil_gpr_diff_199.txt
  test-data/local/snake_oil_no_data/storage/snake_oil/runpath/realization-0/iter-0/snake_oil_npv.txt
  test-data/local/snake_oil_no_data/storage/snake_oil/runpath/realization-0/iter-0/snake_oil_opr_diff_199.txt
  test-data/local/snake_oil_no_data/storage/snake_oil/runpath/realization-0/iter-0/snake_oil_wpr_diff_199.txt
  test-data/local/snake_oil_no_data/templates/seed_template.txt
  test-data/local/snake_oil_no_data/templates/snake_oil_template.txt
  tests/conftest.py
  tests/libres_tests/res/enkf/test_enkf_runpath.py
  tests/libres_tests/res/enkf/test_enkf_transfer_env.py
  tests/libres_tests/res/enkf/test_runpath_list_dump.py
  tests/libres_tests/res/enkf/test_runpath_list_ert.py
Labels: release-notes:maintenance

#3302 Raise exception if analysis can not be performed
  ert_gui/tools/run_analysis/run_analysis_tool.py
  ert_shared/models/ensemble_smoother.py
  ert_shared/models/iterated_ensemble_smoother.py
  ert_shared/models/multiple_data_assimilation.py
  res/enkf/__init__.py
  res/enkf/es_update.py
  tests/ert_tests/gui/run_analysis/test_run_analysis.py
  tests/ert_tests/status/test_tracking_integration.py
  tests/ert_tests/storage/test_extraction.py
  tests/libres_tests/res/enkf/test_es_update.py
Labels: release-notes:breaking-change

#3315 Catch unexpected exceptions and clean up to avoid hanging GUI
  ert/ensemble_evaluator/tracker/evaluator_tracker.py
Labels: release-notes:bug-fix

#3317 Convert to int explicitly, avoid deprecation
  ert_gui/tools/plot/color_chooser.py
  ert_gui/tools/plot/widgets/clearable_line_edit.py
Labels: release-notes:maintenance
