Repository equinor/ert, pull requests merged in 2022-03, with the labels that each got.

#2948 Remove misfit_ensemble_alloc_empy
  libres/lib/enkf/misfit_ensemble.cpp
Labels: maintenance

#3003 Add release notes for 2.33
  docs/rst/manual/about/release_notes.rst
Labels: documentation

#2969 Add an out of bounds check
  libres/lib/python/enkf_fs_keyword_data.cpp
Labels: bug

#3019 Remove unused job_queue from BaseRunModel
  ert_gui/simulation/run_dialog.py
  ert_shared/models/base_run_model.py
  ert_shared/models/ensemble_experiment.py
  ert_shared/models/ensemble_smoother.py
  ert_shared/models/iterated_ensemble_smoother.py
  ert_shared/models/multiple_data_assimilation.py
  tests/ert_tests/models/test_base_run_model.py
Labels: payback, maintenance

#2964 Implement local_obsdata_node as C++ and wrap with pybind
  libres/lib/enkf/enkf_main.cpp
  libres/lib/enkf/enkf_obs.cpp
  libres/lib/enkf/local_ministep.cpp
  libres/lib/enkf/local_obsdata.cpp
  libres/lib/enkf/local_obsdata_node.cpp
  libres/lib/enkf/obs_vector.cpp
  libres/lib/include/ert/enkf/local_ministep.hpp
  libres/lib/include/ert/enkf/local_obsdata.hpp
  libres/lib/include/ert/enkf/local_obsdata_node.hpp
  libres/lib/include/ert/enkf/obs_vector.hpp
  libres/old_tests/enkf/test_enkf_local_obsdata.cpp
  libres/old_tests/enkf/test_enkf_local_obsdata_node.cpp
  libres/old_tests/enkf/test_obs_vector.cpp
  res/enkf/local_ministep.py
  res/enkf/local_obsdata.py
  res/enkf/local_obsdata_node.py
  tests/libres_tests/res/enkf/test_local_config.py
Labels: maintenance, analysis

#3027 clang-format: Remove version check
  script/clang-format
Labels: payback

#2976 Disable lazy_loading of summary-data by default
  libres/lib/enkf/forward_load_context.cpp
  tests/libres_tests/res/enkf/conftest.py
  tests/libres_tests/res/enkf/test_enkf_load_results_manually2.py
  tests/libres_tests/res/enkf/test_es_update.py
Labels: enhancement, documentation

#3006 Remove utility functions of the legacy tracker
  ert_gui/simulation/run_dialog.py
  ert_shared/cli/main.py
  ert_shared/status/tracker/evaluator.py
  ert_shared/status/tracker/factory.py
  ert_shared/status/utils.py
  tests/ert_tests/status/test_tracking_integration.py
  tests/ert_tests/status/test_utils.py
Labels: maintenance

#3042 Set strict=True when creating EnkfMain, make testname unique
  tests/libres_tests/res/enkf/test_enkf_load_results_manually2.py
Labels: bug, flaky-test

#3034 Undo removal of getAll* collectors
  res/enkf/export/gen_kw_collector.py
  res/enkf/export/misfit_collector.py
  res/enkf/export/summary_collector.py
  res/enkf/export/summary_observation_collector.py
  tests/libres_tests/res/enkf/export/test_summary_observation_collector.py
Labels: bug

#3045 Introduce read-only info class derived from EvaluatorServerConfig
  ert_gui/simulation/run_dialog.py
  ert_shared/cli/main.py
  ert_shared/ensemble_evaluator/config.py
  ert_shared/ensemble_evaluator/ensemble/prefect.py
  ert_shared/ensemble_evaluator/evaluator.py
  ert_shared/ensemble_evaluator/monitor.py
  ert_shared/status/tracker/evaluator.py
  ert_shared/status/tracker/factory.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/ert_tests/ensemble_evaluator/test_monitor.py
  tests/ert_tests/status/test_evaluator_tracker.py
  tests/ert_tests/status/test_tracking_integration.py
Labels: ensemble-evaluator

#3021 Remove usage of threadpool in block_fs_driver
  libres/lib/enkf/block_fs_driver.cpp
  libres/lib/enkf/enkf_fs.cpp
  tests/conftest.py
  tests/performance_tests/enkf/test_enkf_fs.py
Labels: payback

#3047 Correct exception name typo
  ert/exceptions/__init__.py
  ert/exceptions/_exceptions.py
  ert/storage/_storage.py
  tests/ert_tests/ert3/console/integration/test_cli.py
  tests/ert_tests/ert3/storage/test_storage.py
Labels: maintenance

#2966 Implement local_obsdata as C++
  libres/lib/analysis/update.cpp
  libres/lib/enkf/enkf_main.cpp
  libres/lib/enkf/enkf_obs.cpp
  libres/lib/enkf/local_config.cpp
  libres/lib/enkf/local_ministep.cpp
  libres/lib/enkf/local_obsdata.cpp
  libres/lib/enkf/local_obsdata_node.cpp
  libres/lib/include/ert/enkf/enkf_obs.hpp
  libres/lib/include/ert/enkf/local_config.hpp
  libres/lib/include/ert/enkf/local_ministep.hpp
  libres/lib/include/ert/enkf/local_obsdata.hpp
  libres/lib/include/ert/enkf/local_obsdata_node.hpp
  libres/lib/include/ert/python.hpp
  libres/old_tests/enkf/test_enkf_local_obsdata.cpp
  res/enkf/local_config.py
  res/enkf/local_ministep.py
  res/enkf/local_obsdata.py
  tests/libres_tests/res/enkf/test_local_config.py
  tests/libres_tests/res/enkf/test_local_obs_data.py
Labels: maintenance, analysis

#3072 Fix filename typo in tests
  tests/ert_tests/ensemble_evaluator/test_data_marshaller_and_unmarshaller.py
Labels: maintenance

#3082 Remove usage of matrix.hpp from lib/analysis
  libres/lib/analysis/analysis_module.cpp
  libres/lib/analysis/enkf_linalg.cpp
  libres/lib/analysis/ies/ies.cpp
  libres/lib/analysis/ies/ies_data.cpp
  libres/lib/analysis/update.cpp
  libres/lib/include/ert/analysis/analysis_module.hpp
  libres/lib/include/ert/analysis/enkf_linalg.hpp
  libres/lib/include/ert/analysis/ies/ies.hpp
  libres/lib/include/ert/analysis/ies/ies_data.hpp
  libres/lib/include/ert/analysis/update.hpp
  libres/lib/include/ert/res_util/es_testdata.hpp
  libres/lib/include/ert/res_util/matrix.hpp
  libres/lib/res_util/es_testdata.cpp
  libres/lib/res_util/matrix.cpp
  libres/old_tests/analysis/ies/test_ies_enkf_module.cpp
  libres/old_tests/analysis/ies/test_ies_iteration.cpp
  libres/old_tests/analysis/ies/test_ies_linalg.cpp
  libres/old_tests/analysis/ies/test_ies_std_compare.cpp
  libres/old_tests/res_util/test_es_testdata.cpp
  libres/tests/analysis/ies/test_ies_enkf_main.cpp
Labels: payback, analysis

#3025 Plugin-in transformation configuration and wider transformation usage
  .mypy-strict.ini
  .mypy.ini
  dev-requirements.txt
  docs/rst/manual/conf.py
  ert/data/__init__.py
  ert/data/record/_record.py
  ert/data/record/_transformation.py
  ert/storage/_storage.py
  ert3/__init__.py
  ert3/config/__init__.py
  ert3/config/_config_plugin_registry.py
  ert3/config/_ensemble_config.py
  ert3/config/_experiment_run_config.py
  ert3/config/_stages_config.py
  ert3/config/_validator.py
  ert3/config/plugins/__init__.py
  ert3/config/plugins/_base_configs.py
  ert3/config/plugins/implementations/__init__.py
  ert3/config/plugins/implementations/transformations.py
  ert3/console/_console.py
  ert3/engine/_export.py
  ert3/engine/_record.py
  ert3/evaluator/_builder.py
  ert3/plugins/__init__.py
  ert3/plugins/hook_specifications/__init__.py
  ert3/plugins/hook_specifications/config.py
  ert3/plugins/plugin_manager.py
  ert3/workspace/_workspace.py
  ert3_examples/polynomial/stages.yml
  ert3_examples/snake_oil/stages.yml
  ert3_examples/spe1/experiments/doe/ensemble.yml
  ert3_examples/spe1/experiments/evaluation/ensemble.yml
  ert3_examples/spe1/experiments/sensitivity/ensemble.yml
  ert3_examples/spe1/stages.yml
  ert_shared/ensemble_evaluator/ensemble/builder.py
  ert_shared/ensemble_evaluator/entity/unix_step.py
  setup.py
  tests/ert_tests/ensemble_evaluator/prefect/conftest.py
  tests/ert_tests/ensemble_evaluator/prefect/test_prefect_step.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/ert_tests/ert3/config/test_config_plugin_registry.py
  tests/ert_tests/ert3/config/test_ert3_ensemble_config.py
  tests/ert_tests/ert3/config/test_experiment_run_config.py
  tests/ert_tests/ert3/config/test_stages_config.py
  tests/ert_tests/ert3/conftest.py
  tests/ert_tests/ert3/console/integration/test_cli.py
  tests/ert_tests/ert3/data/test_record.py
  tests/ert_tests/ert3/data/test_transformations.py
  tests/ert_tests/ert3/data/test_transmitters.py
  tests/ert_tests/ert3/engine/integration/integration_utils.py
  tests/ert_tests/ert3/engine/integration/test_engine.py
  tests/ert_tests/ert3/evaluator/test_evaluator.py
  tests/ert_tests/ert3/workspace/test_workspace.py
Labels: payback, ert3, improvement

#3065 Add webviz-ert documentation
  docs/rst/manual/experimental/index.rst
  docs/rst/manual/experimental/webviz-ert.rst
Labels: documentation

#3083 Remove subtract_row_mean()
  libres/lib/analysis/ies/ies.cpp
Labels: maintenance

#3102 Drop experiment_run_config from load_resource
  ert3/engine/_export.py
  ert3/engine/_run.py
  ert3/workspace/_workspace.py
Labels: ert3

#3107 Fix typo, successfull -> successful
  docs/rst/manual/reference/configuration/keywords.rst
  ert_shared/cli/workflow.py
  ert_shared/ensemble_evaluator/evaluator.py
  ert_shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  libres/lib/include/ert/enkf/summary_config.hpp
  libres/lib/job_queue/workflow.cpp
  tests/ert_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: maintenance

#3110 Test tracker progress
  tests/ert_tests/status/test_evaluator_tracker.py
Labels: testing

#3161 Pin pylint to version <2.13.0
  dev-requirements.txt
Labels: maintenance

#3154 Add Python 3.10 to list of classifiers
  setup.py
Labels: maintenance, feature

#3156 Add support for log-uniform distribution
  ert3/config/_parameters_config.py
  ert3/stats/__init__.py
  ert3/stats/_stats.py
  tests/ert_tests/ert3/config/test_parameters_config.py
  tests/ert_tests/ert3/engine/integration/test_engine.py
  tests/ert_tests/ert3/stats/test_distributions.py
Labels: enhancement, user request, ert3

#3163 Fix to circumvent pylint bug
  dev-requirements.txt
  ert3/config/_config_plugin_registry.py
Labels: payback, maintenance

#3172 Pin click in dev-requirements to 8.0.2
  .github/workflows/style.yml
  dev-requirements.txt
Labels: maintenance

#3165 Add release notes for ert 2.34
  docs/rst/manual/about/release_notes.rst
Labels: maintenance, documentation
