Repository equinor/ert, pull requests merged in 2022-12, with the labels that each got.

#4244 Check if the runpath exists before starting simulations
  src/ert/cli/main.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/shared/models/base_run_model.py
  tests/unit_tests/gui/test_gui_load.py
  tests/unit_tests/models/test_base_run_model.py
Labels: release-notes:improvement

#4405 Bump mypy-protobuf<v3.4
  types-requirements.txt
Labels: release-notes:misc

#4426 Check if init_file contains %d after forward_init fails
  src/ert/ensemble_evaluator/callbacks.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:bug-fix

#4395 Move some tests to doctest
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/res/config/test_config_parser.py
Labels: testing

#4439 Move format_running_time tests to doctests
  src/ert/shared/status/utils.py
  tests/unit_tests/status/test_utils.py
Labels: testing

#4437 Move test_adding_priors to use poly_case fixture
  tests/unit_tests/c_wrappers/res/enkf/test_priors.py
Labels: testing

#4419 Skip test_report_with_reconnected_reporter_but_finished_jobs if macos
  tests/unit_tests/c_wrappers/job_runner/test_event_reporter.py
Labels: skipped_test, flaky-test, release-notes:misc

#4421 Substitute deprecated iteritems to items
  src/ert/shared/storage/extraction.py
Labels: bug, release-notes:misc

#4435 Move test_multiple_data_assimilation
  tests/unit_tests/models/test_multiple_data_assimilation.py
Labels: testing

#4441 Removed duplicate of rangestring test and more doc
  src/ert/_c_wrappers/config/rangestring.py
  tests/unit_tests/c_wrappers/res/config/test_rangestring.py
Labels: release-notes:misc

#4446 Use stderr for deprecation warnings in config file
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_res_config.py
Labels: bug

#4455 Create initial implementation of migration suggester
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_suggester.py
Labels: release-notes:new-feature

#4463 Fix bug where updates using SURFACE/FIELD failed after iter-0
  src/ert/ensemble_evaluator/callbacks.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:bug-fix

#4467 Cherry-pick: Fix bug where only one parameter was saved
  src/ert/ensemble_evaluator/callbacks.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:bug-fix

#4478 Fix false positive warning
  src/ert/_c_wrappers/enkf/res_config.py
Labels: bug

#4471 Fix typo
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
Labels: release-notes:maintenance

#4433 Mitigate flakiness in concurrent qstat testing
  tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py
Labels: flaky-test, release-notes:skip

#4476 Fix a bug with fixed point substitution
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/_c_wrappers/util/substitution_list.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: bug

#4466 Move error message if missing REFCASE/TIME_MAP from C to python
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/include/ert/enkf/enkf_obs.hpp
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
Labels: release-notes:improvement

#4495 Fixed gui not displaying runpath correctly
  src/ert/gui/simulation/single_test_run_panel.py
Labels: bug

#4492 Back port: Read summary keys from storage instead of config
  src/clib/lib/python/enkf_fs_summary_data.cpp
  src/ert/libres_facade.py
Labels: release-notes:bug-fix

#4499 Fix bug in suggester gui that caused run ert button to not work
  src/ert/gui/gert_main.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#4517 Remove Equinor test-data softlink
  ci/jenkins/testkomodo-ERT.sh
  ci/jenkins/testkomodo.sh
Labels: maintenance
