Repository equinor/ert, pull requests merged in 2022-05, with the labels that each got.

#3325 Add release notes for 2.35
  docs/rst/manual/about/release_notes.rst
Labels: release-notes:maintenance

#3077 Local test runs with data from storage
  ert3/console/_console.py
  ert3_examples/polynomial/experiments/doe3/coefficients_record.json
  ert3_examples/polynomial/experiments/doe3/ensemble.yml
  ert3_examples/polynomial/experiments/doe3/experiment.yml
  ert3_examples/polynomial/run_demo
  tests/ert_tests/ert3/console/integration/test_cli.py
Labels: release-notes:improvement, release-notes:ert3

#3305 Remove refcase in plotter
  ert_gui/gert_main.py
  ert_gui/plottery/plot_config.py
  ert_gui/plottery/plot_context.py
  ert_gui/plottery/plots/ensemble.py
  ert_gui/plottery/plots/refcase.py
  ert_gui/plottery/plots/statistics.py
  ert_gui/simulation/run_dialog.py
  ert_gui/tools/plot/customize/default_customization_view.py
  ert_gui/tools/plot/customize/style_customization_view.py
  ert_gui/tools/plot/plot_api.py
  ert_gui/tools/plot/plot_tool.py
  ert_gui/tools/plot/plot_window.py
  ert_shared/dark_storage/common.py
  ert_shared/libres_facade.py
  tests/ert_tests/gui/plottery/test_plot_style.py
  tests/ert_tests/gui/tools/plot/conftest.py
  tests/ert_tests/gui/tools/plot/test_plot_api.py
  tests/ert_tests/shared/test_libres_facade.py
Labels: release-notes:breaking-change

#3330 Fix edit analysis varables for run_analysis_panel
  ert_gui/tools/run_analysis/run_analysis_panel.py
Labels: payback, release-notes:bug-fix

#3331 Fix edit analysis varables for run_analysis_panel
  ert_gui/tools/run_analysis/run_analysis_panel.py
Labels: release-notes:bug-fix

#3334 Add timestamp to log file name
  ert_logging/__init__.py
  ert_logging/logger.conf
Labels: release-notes:improvement

#3324 Limit calls to job_queue_node_get_status()
  res/job_queue/job_queue_node.py
Labels: release-notes:bug-fix, release-notes:maintenance

#3342 Remove geos installation in GA workflow
  .github/workflows/build.yml
Labels: release-notes:maintenance

#3350 Fix bug from BoolVector replacement
  ert_gui/ertwidgets/models/ertmodel.py
Labels: release-notes:bug-fix

#3348 Address racy sync_ws_duplexer test "stop" code
  tests/ert_tests/ensemble_evaluator/test_sync_ws_duplexer.py
Labels: release-notes:bug-fix

#3167 Gui monitoring
  .mypy-strict.ini
  .mypy.ini
  ert/ensemble_evaluator/builder/_ensemble.py
  ert/ensemble_evaluator/builder/_ensemble_builder.py
  ert/ensemble_evaluator/builder/_job.py
  ert/ensemble_evaluator/builder/_template.py
  ert/ensemble_evaluator/identifiers.py
  ert/ensemble_evaluator/snapshot.py
  ert/ensemble_evaluator/util/_tool.py
  ert3/console/_console.py
  ert3/engine/_run.py
  ert3/evaluator/_builder.py
  ert3/evaluator/_evaluator.py
  ert_gui/model/node.py
  ert_gui/model/snapshot.py
  ert_gui/simulation/run_dialog.py
  ert_shared/ensemble_evaluator/evaluator.py
  job_runner/reporting/event.py
  tests/ert_tests/ensemble_evaluator/conftest.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/prefect/conftest.py
  tests/ert_tests/ensemble_evaluator/prefect/test_prefect_step.py
  tests/ert_tests/ensemble_evaluator/prefect/test_run_dialog_ert3.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/ert_tests/ensemble_evaluator/test_snapshot.py
  tests/ert_tests/gui/conftest.py
  tests/ert_tests/gui/simulation/test_run_dialog.py
  tests/libres_tests/job_runner/test_event_reporter.py
Labels: ert3, release-notes:new-feature, release-notes:ert3

#3360 Handle unexpected exceptions in EnsembleEvaluator
  ert_shared/ensemble_evaluator/evaluator.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: payback, release-notes:maintenance

#3361 Include thread-name also in the ert-log
  ert_logging/logger.conf
Labels: release-notes:improvement

#3311 Display error messages in ert GUI if dark storage request fails
  ert_gui/tools/plot/plot_api.py
  ert_gui/tools/plot/plot_window.py
  tests/ert_tests/gui/tools/plot/conftest.py
  tests/ert_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:improvement

#3364 Change "record" to "name" in the ensemble config
  ert3/config/_ensemble_config.py
  ert3/config/_experiment_run_config.py
  ert3/engine/_export.py
  ert3/engine/_run.py
  ert3_examples/polynomial/experiments/doe/ensemble.yml
  ert3_examples/polynomial/experiments/doe3/ensemble.yml
  ert3_examples/polynomial/experiments/evaluation/ensemble.yml
  ert3_examples/polynomial/experiments/fast_sensitivity/ensemble.yml
  ert3_examples/polynomial/experiments/function_evaluation/ensemble.yml
  ert3_examples/polynomial/experiments/partial_sensitivity/ensemble.yml
  ert3_examples/polynomial/experiments/sensitivity/ensemble.yml
  ert3_examples/polynomial/experiments/uniform_evaluation/ensemble.yml
  ert3_examples/polynomial/experiments/uniform_sensitivity/ensemble.yml
  ert3_examples/polynomial/experiments/x_uncertainty/ensemble.yml
  ert3_examples/snake_oil/experiments/doe/ensemble.yml
  ert3_examples/snake_oil/experiments/evaluation/ensemble.yml
  ert3_examples/snake_oil/experiments/sensitivity/ensemble.yml
  ert3_examples/spe1/experiments/doe/ensemble.yml
  ert3_examples/spe1/experiments/evaluation/ensemble.yml
  ert3_examples/spe1/experiments/sensitivity/ensemble.yml
  tests/ert_tests/ert3/config/test_ert3_ensemble_config.py
  tests/ert_tests/ert3/config/test_experiment_run_config.py
  tests/ert_tests/ert3/conftest.py
  tests/ert_tests/ert3/engine/integration/integration_utils.py
  tests/ert_tests/ert3/engine/integration/test_engine.py
  tests/ert_tests/ert3/workspace/test_workspace.py
Labels: user request, ert3, release-notes:breaking-change, release-notes:ert3

#3365 Use DATE and not RESTART in snake oil observations
  test-data/local/snake_oil/observations/observations.txt
  test-data/local/snake_oil_field/observations/observations.txt
  test-data/local/snake_oil_structure/ert/input/observations/obsfiles/observations.txt
Labels: release-notes:maintenance

#3373 Remove remaining Title Case from code and doc
  docs/rst/manual/getting_started/gui/gui.rst
  docs/rst/manual/installation/installation_guide.rst
  docs/rst/manual/reference/configuration/forward_model.rst
  docs/rst/manual/reference/configuration/magic_strings.rst
  docs/rst/manual/reference/configuration_file.rst
  docs/rst/manual/reference/queue.rst
  docs/rst/manual/reference/workflows/built_in.rst
  docs/rst/manual/reference/workflows/configuring_jobs.rst
  docs/rst/manual/reference/workflows/external.rst
  docs/rst/manual/reference/workflows/internal.rst
  ert_gui/model/snapshot.py
  ert_gui/simulation/multiple_data_assimilation_panel.py
  ert_gui/tools/file/file_dialog.py
  ert_gui/tools/manage_cases/case_init_configuration.py
  ert_gui/tools/plugins/process_job_dialog.py
  ert_gui/tools/workflows/run_workflow_widget.py
Labels: release-notes:maintenance

#3362 Catch exception and exit with meaningful error in shellscripts
  ert_shared/share/ert/shell_scripts/careful_copy_file
  ert_shared/share/ert/shell_scripts/copy_directory
  ert_shared/share/ert/shell_scripts/copy_file
  ert_shared/share/ert/shell_scripts/delete_directory
  ert_shared/share/ert/shell_scripts/delete_file
  ert_shared/share/ert/shell_scripts/make_directory
  ert_shared/share/ert/shell_scripts/move_file
  ert_shared/share/ert/shell_scripts/symlink
Labels: release-notes:improvement

#3390 Remove unused block_fs_sscanf_key
  libres/lib/enkf/block_fs_driver.cpp
  libres/lib/include/ert/enkf/block_fs_driver.hpp
Labels: release-notes:maintenance

#3395 Remove File menu from main window
  ert_gui/main_window.py
Labels: release-notes:maintenance

#3394 Remove unused functions flagged by compiler
  libres/lib/config/config_settings.cpp
  libres/lib/enkf/block_fs_driver.cpp
  libres/lib/enkf/enkf_config_node.cpp
  libres/lib/enkf/enkf_state.cpp
  libres/lib/enkf/field.cpp
  libres/lib/include/ert/enkf/enkf_state.hpp
  libres/lib/res_util/block_fs.cpp
  libres/lib/rms/rms_file.cpp
  libres/old_tests/enkf/test_enkf_export_inactive_cells.cpp
Labels: release-notes:maintenance

#3409 Allow resize of simulations failed message box
  ert_gui/ertwidgets/message_box.py
  ert_gui/simulation/run_dialog.py
  tests/ert_tests/gui/test_gui_load.py
Labels: release-notes:improvement

#3416 Mute FutureWarning from dask
  ert/ensemble_evaluator/builder/_prefect.py
Labels: release-notes:maintenance

#3391 Use f-strings everywhere
  .github/workflows/style.yml
  ert_shared/cli/main.py
  ert_shared/cli/model_factory.py
  ert_shared/cli/monitor.py
  ert_shared/dark_storage/common.py
  ert_shared/ensemble_evaluator/config.py
  ert_shared/feature_toggling.py
  ert_shared/hook_implementations/jobs.py
  ert_shared/ide/keywords/definitions/integer_argument.py
  ert_shared/libres_facade.py
  ert_shared/main.py
  ert_shared/models/ensemble_smoother.py
  ert_shared/models/iterated_ensemble_smoother.py
  ert_shared/models/multiple_data_assimilation.py
  ert_shared/plugins/plugin_manager.py
  ert_shared/plugins/workflow_config.py
  ert_shared/status/utils.py
  tests/ert_tests/ert_utils.py
  tests/ert_tests/gui/ide/test_integer_argument.py
  tests/ert_tests/gui/models/test_active_realizations_model.py
  tests/ert_tests/gui/plottery/test_plot_limits.py
  tests/libres_tests/import_tester.py
  tests/libres_tests/job_runner/test_file_reporter.py
  tests/libres_tests/job_runner/test_job.py
  tests/libres_tests/job_runner/test_jobmanager.py
  tests/libres_tests/libres_utils.py
  tests/libres_tests/res/enkf/test_enkf_fs_manager2.py
  tests/libres_tests/res/enkf/test_ert_templates.py
  tests/libres_tests/res/enkf/test_hook_manager.py
  tests/libres_tests/res/enkf/test_model_config.py
  tests/libres_tests/res/enkf/test_row_scaling_case.py
  tests/libres_tests/res/enkf/test_runpath_list.py
  tests/libres_tests/res/enkf/test_runpath_list_dump.py
  tests/libres_tests/res/enkf/test_runpath_list_ert.py
  tests/libres_tests/res/enkf/test_subst_config.py
  tests/libres_tests/res/enkf/test_time_map.py
  tests/libres_tests/res/fm/test_ecl_run.py
  tests/libres_tests/res/fm/test_ecl_run_new_config.py
  tests/libres_tests/res/fm/test_ecl_versioning_config.py
  tests/libres_tests/res/fm/test_rms_run.py
  tests/libres_tests/res/fm/test_templating.py
  tests/libres_tests/res/job_queue/test_equinor_jobmanager.py
  tests/libres_tests/res/job_queue/test_forward_model_formatted_print.py
  tests/libres_tests/res/job_queue/test_job_queue_manager.py
  tests/libres_tests/res/run/test_run.py
  tests/libres_tests/res/simulator/test_batch_sim.py
Labels: release-notes:maintenance

#3422 Remove unused defaults from enkf_defaults
  libres/lib/include/ert/enkf/enkf_defaults.hpp
Labels: release-notes:maintenance

#3426 Refactor analysis config min_required_realizations
  ert_shared/models/base_run_model.py
  libres/lib/enkf/analysis_config.cpp
  libres/lib/include/ert/enkf/analysis_config.hpp
  libres/old_tests/enkf/test_enkf_analysis_config.cpp
  res/enkf/analysis_config.py
  res/enkf/es_update.py
  tests/libres_tests/res/enkf/test_analysis_config.py
  tests/libres_tests/res/enkf/test_es_update.py
Labels: release-notes:breaking-change

#3430 FIx usage of manylinux2014 in the github actions build workflow
  .github/workflows/build.yml
  ci/github/build_linux_wheel.sh
Labels: maintenance, release-notes:maintenance

#3431 Make sure newlines are preserved in message box
  ert_gui/ertwidgets/message_box.py
  ert_gui/simulation/run_dialog.py
  tests/ert_tests/gui/test_gui_load.py
Labels: release-notes:improvement

#3406 Pybind enkf_main_create_run_path
  .github/workflows/typing.yml
  .mypy.ini
  libres/lib/enkf/enkf_main.cpp
  res/enkf/enkf_main.py
  res/enkf/enkf_simulation_runner.py
  res/enkf/enums/hook_runtime_enum.py
  res/enkf/ert_run_context.py
  tests/libres_tests/res/enkf/test_enkf_runpath.py
  tests/libres_tests/res/enkf/test_runpath_list_dump.py
  tests/libres_tests/res/enkf/test_simulation_batch.py
Labels: release-notes:maintenance

#3420 Test and clean meas_block_calculate_ens_stats
  libres/lib/enkf/meas_data.cpp
  libres/tests/CMakeLists.txt
  libres/tests/enkf/test_meas_data.cpp
Labels: release-notes:maintenance

#3433 Fix build script
  script/build
Labels: release-notes:maintenance

#3428 Use higher resolution when checking modification-time for target-file
  job_runner/job.py
Labels: release-notes:bug-fix

#3166 Update readme after first setup
  README.md
Labels: documentation, testing

#3447 Remember plot type when switching between types
  ert_gui/tools/plot/plot_window.py
Labels: release-notes:improvement

#3449 Use pd.concat instead of append
  ert_data/loader.py
Labels: release-notes:maintenance
