Repository equinor/ert, pull requests merged in 2022-08, with the labels that each got.

#3661 Migrate to flake8 5.0.0 compatible config
  .flake8
  setup.cfg
Labels: ci-pipeline

#3642 Small fix for running experiment_server
  src/ert/ensemble_evaluator/builder/_legacy.py
  src/ert_shared/cli/main.py
  tests/ert_tests/cli/test_integration_cli.py
  tests/ert_tests/ert3/conftest.py
Labels: experiment-server

#3664 Use --strict_markers for pytest
  pyproject.toml
  setup.cfg
Labels: release-notes:maintenance

#3632 Remove warning about use of restart
  src/libres/lib/enkf/obs_vector.cpp
Labels: release-notes:maintenance

#3672 Remove py36 specifics in tests
  tests/ert_tests/cli/test_integration_cli.py
  tests/ert_tests/experiment_server/conftest.py
  tests/ert_tests/experiment_server/test_server.py
Labels: release-notes:maintenance

#3668 Ensure jenkins tests see pyproject.toml
  ci/jenkins/testkomodo-ERT.sh
  ci/jenkins/testkomodo-libres-pytest.sh
  ci/jenkins/testkomodo-repeat-flaky.sh
  ci/jenkins/testkomodo.sh
Labels: release-notes:maintenance

#3665 Refactor ert/analysis import structure
  .github/workflows/style.yml
  .github/workflows/typing.yml
  src/ert/analysis/__init__.py
  src/ert/analysis/_es_update.py
  src/ert/analysis/_ies/__init__.py
  src/ert/gui/tools/run_analysis/run_analysis_tool.py
  src/ert_shared/libres_facade.py
  src/ert_shared/models/ensemble_smoother.py
  src/ert_shared/models/iterated_ensemble_smoother.py
  src/ert_shared/models/multiple_data_assimilation.py
  src/res/enkf/__init__.py
  src/res/enkf/enkf_main.py
  tests/ert_tests/cli/test_model_hook_order.py
  tests/ert_tests/gui/run_analysis/test_run_analysis.py
  tests/ert_tests/storage/test_extraction.py
  tests/libres_tests/res/enkf/test_es_update.py
  tests/libres_tests/res/enkf/test_row_scaling_case.py
Labels: maintenance

#3680 Add release notes for 2.36 and 2.37
  docs/rst/manual/about/release_notes.rst
Labels: release-notes:maintenance

#3122 Make IES-implementation similar to paper
  src/libres/lib/analysis/enkf_linalg.cpp
  src/libres/lib/analysis/ies/ies.cpp
  src/libres/lib/include/ert/analysis/enkf_linalg.hpp
  src/libres/lib/include/ert/analysis/utils.hpp
  src/libres/tests/analysis/ies/test_ies_enkf_main.cpp
Labels: release-notes:maintenance

#3675 Remove unused callback_arg
  src/libres/lib/CMakeLists.txt
  src/libres/lib/enkf/callback_arg.cpp
  src/libres/lib/enkf/enkf_state.cpp
  src/libres/lib/include/ert/enkf/callback_arg.hpp
Labels: release-notes:maintenance

#3655 Move ert_data to ert.data
  .github/workflows/coverage.yml
  .github/workflows/style.yml
  .github/workflows/typing.yml
  .mypy-strict.ini
  .mypy.ini
  docs/rst/manual/conf.py
  src/ert/__init__.py
  src/ert/data/__init__.py
  src/ert/data/loader.py
  src/ert/data/measured.py
  src/ert_data/__init__.py
  src/ert_shared/dark_storage/common.py
  src/ert_shared/storage/extraction.py
  tests/ert_tests/data/test_integration_data.py
  tests/ert_tests/data/test_loader.py
  tests/ert_tests/data/test_measured_data.py
Labels: release-notes:maintenance

#3641 Sort messages so they more likely ordered by realization
  src/ert_shared/models/base_run_model.py
Labels: release-notes:improvement

#3686 Add missing logger-method to _Proc
  .mypy.ini
  src/ert_shared/services/_base_service.py
  src/ert_shared/services/_storage_main.py
  src/ert_shared/services/_webviz_ert_main.py
  src/ert_shared/services/storage_service.py
Labels: release-notes:maintenance

#3357 Log maximum memory usage in main ERT thread
  src/ert_shared/main.py
  tests/ert_tests/shared/test_log_process_usage.py
Labels: telemetry

#3537 Retry qsub and qstat in case of failures
  src/libres/lib/job_queue/torque_driver.cpp
  tests/libres_tests/res/job_queue/test_job_queue_manager.py
  tests/libres_tests/res/job_queue/test_job_queue_manager_torque.py
Labels: release-notes:bug-fix

#3694 Remove python implementation of ForwardLoadContext
  src/res/enkf/__init__.py
  src/res/enkf/forward_load_context.py
  tests/libres_tests/res/enkf/data/test_gen_data_config.py
  tests/libres_tests/res/enkf/test_forward_load_context.py
Labels: release-notes:maintenance

#3691 Do not generate certificates for cli tests
  tests/ert_tests/cli/conftest.py
Labels: flaky-test

#3695 Remove outdated install script
  .build_install.sh
Labels: release-notes:maintenance

#3702 Replace util_binary_split_string with standard C++
  src/libres/lib/enkf/ensemble_config.cpp
  src/libres/lib/enkf/ert_template.cpp
  src/libres/lib/include/ert/res_util/string.hpp
  tests/libres_tests/res/enkf/test_ert_templates.py
Labels: release-notes:maintenance

#3709 Move test_stop_running into test_job_queue
  tests/libres_tests/res/enkf/test_enkf_simulation_runner.py
  tests/libres_tests/res/job_queue/test_job_queue.py
Labels: release-notes:maintenance

#3705 Join EnKFMain, _RealEnKFMain, EnkfFsManager and EnkfJobRunner in python
  .github/workflows/typing.yml
  .mypy.ini
  src/ert_shared/libres_facade.py
  src/ert_shared/models/base_run_model.py
  src/ert_shared/models/ensemble_experiment.py
  src/ert_shared/models/ensemble_smoother.py
  src/ert_shared/models/iterated_ensemble_smoother.py
  src/ert_shared/models/multiple_data_assimilation.py
  src/res/enkf/__init__.py
  src/res/enkf/analysis_config.py
  src/res/enkf/enkf_fs_manager.py
  src/res/enkf/enkf_main.py
  src/res/enkf/enkf_simulation_runner.py
  src/res/simulator/simulation_context.py
  tests/ert_tests/cli/test_model_hook_order.py
  tests/ert_tests/storage/test_extraction.py
  tests/libres_tests/integration/test_parameter_sample_types.py
  tests/libres_tests/res/enkf/test_enkf.py
  tests/libres_tests/res/enkf/test_enkf_fs_manager2.py
  tests/libres_tests/res/enkf/test_enkf_fs_manager_init.py
  tests/libres_tests/res/enkf/test_enkf_main.py
  tests/libres_tests/res/enkf/test_enkf_runpath.py
  tests/libres_tests/res/enkf/test_enkf_transfer_env.py
  tests/libres_tests/res/enkf/test_runpath_list_dump.py
  tests/libres_tests/res/enkf/test_runpath_list_ert.py
  tests/libres_tests/res/enkf/test_simulation_batch.py
  tests/libres_tests/res/enkf/test_site_config.py
  tests/libres_tests/test_integration_config.py
Labels: release-notes:breaking-change

#3715 Remove unused workflows EXPORT_FIELD_*
  src/ert_shared/share/ert/workflows/jobs/internal/config/EXPORT_FIELD
  src/ert_shared/share/ert/workflows/jobs/internal/config/EXPORT_FIELD_ECL_GRDECL
  src/ert_shared/share/ert/workflows/jobs/internal/config/EXPORT_FIELD_RMS_ROFF
  src/libres/lib/enkf/enkf_main.cpp
  src/libres/lib/enkf/enkf_main_jobs.cpp
  src/libres/lib/include/ert/enkf/enkf_main.hpp
  src/libres/lib/job_queue/workflow_job.cpp
  src/libres/old_tests/enkf/CMakeLists.txt
  src/libres/old_tests/enkf/test_enkf_export_field.cpp
Labels: release-notes:maintenance

#3553 Add proxy script for qstat
  dev-requirements.txt
  setup.py
  src/libres/lib/CMakeLists.txt
  src/libres/lib/include/ert/job_queue/torque_driver.hpp
  src/libres/lib/job_queue/qstat_proxy.sh
  src/libres/old_tests/job_queue/test_job_torque_submit.cpp
  tests/libres_tests/res/job_queue/test_ert_qstat_proxy.py
Labels: release-notes:bug-fix, release-notes:improvement

#3716 Remove last internal C workflows EXIT_ERT and PRE_SIMULATION_COPY
  docs/reference/configuration/site_wide.rst
  src/ert_shared/hook_implementations/jobs.py
  src/ert_shared/share/ert/site-config
  src/ert_shared/share/ert/workflows/jobs/internal/config/EXIT_ERT
  src/ert_shared/share/ert/workflows/jobs/internal/config/PRE_SIMULATION_COPY
  src/libres/lib/CMakeLists.txt
  src/libres/lib/enkf/enkf_main.cpp
  src/libres/lib/enkf/enkf_main_jobs.cpp
  src/libres/lib/include/ert/enkf/enkf_main.hpp
  src/libres/lib/job_queue/workflow_job.cpp
  src/libres/old_tests/data/enkf/config/test_context/wf_job
  src/libres/old_tests/data/enkf/workflow_jobs/CONF1
  src/libres/old_tests/data/enkf/workflow_jobs/CONF2
  src/libres/old_tests/data/enkf/workflow_jobs/CONF2@1
  src/libres/old_tests/data/enkf/workflow_jobs/CONF3@1.2.3
  src/libres/old_tests/data/enkf/workflow_jobs/CONF4@1.2.0
  src/libres/old_tests/data/enkf/workflow_jobs/CONF5@1.2
  src/libres/old_tests/data/enkf/workflow_jobs/CONF5@1.2.0
  src/libres/old_tests/data/job_queue/internalOK
  src/libres/old_tests/data/job_queue/internal_job
  src/libres/old_tests/enkf/CMakeLists.txt
  src/libres/old_tests/enkf/test_enkf_ert_test_context.cpp
  src/libres/old_tests/enkf/test_enkf_workflow_job.cpp
  src/libres/old_tests/enkf/test_enkf_workflow_job_test_directory.cpp
  src/libres/old_tests/job_queue/CMakeLists.txt
  src/libres/old_tests/job_queue/test_job_workflow.cpp
  tests/libres_tests/res/enkf/test_res_config.py
  tests/libres_tests/res/job_queue/test_function_ert_script.py
  tests/libres_tests/res/job_queue/test_workflow_job.py
Labels: release-notes:maintenance

#3731 Fix flaky bug in test_ert_qstat_proxy
  src/libres/lib/job_queue/qstat_proxy.sh
  tests/libres_tests/res/job_queue/test_ert_qstat_proxy.py
Labels: release-notes:maintenance

#3737 Remove END_DATE keyword
  docs/reference/configuration/keywords.rst
  src/libres/lib/enkf/config_keys.cpp
  src/libres/lib/enkf/ecl_config.cpp
  src/libres/lib/enkf/enkf_state.cpp
  src/libres/lib/include/ert/enkf/config_keys.hpp
  src/libres/lib/include/ert/enkf/ecl_config.hpp
  src/res/enkf/ecl_config.py
  test-data/local/configuration_tests/ecl_config.ert
  test-data/local/configuration_tests/model_config.ert
  test-data/local/configuration_tests/sched_file_as_history_source.ert
  tests/libres_tests/res/enkf/test_ecl_config.py
  tests/libres_tests/res/enkf/test_res_config.py
Labels: bug, release-notes:breaking-change

#3738 Fix flaky test for qstat concurrency
  tests/libres_tests/res/job_queue/test_ert_qstat_proxy.py
Labels: release-notes:maintenance

#3744 Adjust the still flaky qstat_concurrent_invocations
  tests/libres_tests/res/job_queue/test_ert_qstat_proxy.py
Labels: release-notes:maintenance

#3746 Remove RFTPATH keyword
  docs/reference/configuration/keywords.rst
  src/libres/lib/enkf/config_keys.cpp
  src/libres/lib/enkf/model_config.cpp
  src/libres/lib/include/ert/enkf/config_keys.hpp
  src/libres/lib/include/ert/enkf/enkf_defaults.hpp
  src/libres/lib/include/ert/enkf/model_config.hpp
  src/res/enkf/model_config.py
Labels: release-notes:breaking-change

#3734 Update sphinx build instructions
  CONTRIBUTING.md
Labels: release-notes:maintenance

#3605 Send fewer but larger dataChanged signals
  src/ert/gui/model/snapshot.py
Labels: release-notes:improvement

#3742 Update default branch name in README
  README.md
Labels: release-notes:maintenance

#3735 Remove unnecessary fixtures
  tests/libres_tests/integration/test_parameter_sample_types.py
Labels: release-notes:maintenance

#3745 Remove REFCASE_LIST keyword
  docs/reference/configuration/keywords.rst
  src/libres/lib/CMakeLists.txt
  src/libres/lib/enkf/config_keys.cpp
  src/libres/lib/enkf/ecl_config.cpp
  src/libres/lib/enkf/ecl_refcase_list.cpp
  src/libres/lib/include/ert/enkf/config_keys.hpp
  src/libres/lib/include/ert/enkf/ecl_config.hpp
  src/libres/lib/include/ert/enkf/ecl_refcase_list.hpp
  src/libres/old_tests/enkf/CMakeLists.txt
  src/libres/old_tests/enkf/test_enkf_ecl_config.cpp
  src/libres/old_tests/enkf/test_enkf_ecl_config_config.cpp
  src/libres/old_tests/enkf/test_enkf_refcase_list.cpp
  src/res/enkf/ecl_config.py
  test-data/local/configuration_tests/ecl_config.ert
  tests/libres_tests/res/enkf/test_ecl_config.py
Labels: release-notes:breaking-change

#3753 Stopp logging to stderr in the config_parser
  src/ert/logging/logger.conf
  src/ert/logging/storage_log.conf
  src/libres/lib/config/config_parser.cpp
  src/libres/lib/enkf/model_config.cpp
Labels: release-notes:improvement

#3721 Remove unused function enkf_config_node_get_FIELD_fill_file
  src/libres/lib/enkf/enkf_config_node.cpp
  src/libres/lib/include/ert/enkf/enkf_config_node.hpp
Labels: release-notes:maintenance

#3764 Solve warnings emitted during pytesting
  tests/libres_tests/res/config/test_config.py
  tests/libres_tests/res/enkf/export/test_export_join.py
  tests/libres_tests/res/job_queue/test_job_queue_manager.py
Labels: release-notes:maintenance

#3615 Use standard Qt APIs in GUI proxy models
  src/ert/gui/model/job_list.py
  src/ert/gui/model/progress_proxy.py
  src/ert/gui/model/real_list.py
  src/ert/gui/model/snapshot.py
Labels: release-notes:improvement

#3766 Update path version in gitignore
  .gitignore
Labels: maintenance

#3755 Change dates written by ERT to ISO-8601
  docs/reference/configuration/magic_strings.rst
  src/libres/lib/enkf/enkf_main.cpp
  src/libres/lib/enkf/obs_vector.cpp
  src/libres/lib/enkf/subst_config.cpp
  src/libres/lib/enkf/time_map.cpp
  src/libres/lib/sched/history.cpp
  tests/libres_tests/res/enkf/test_subst_config.py
Labels: release-notes:breaking-change

#3771 Pin setuptools to <64
  pyproject.toml
Labels: release-notes:maintenance

#3719 Remove init_internalization from enkf_main
  src/libres/lib/enkf/enkf_main.cpp
  src/res/enkf/enkf_main.py
Labels: release-notes:maintenance

#3770 Unpin fastapi
  setup.py
Labels: enhancement

#3776 Fix broken shell scripts
  src/ert/shared/share/ert/shell_scripts/careful_copy_file
  src/ert/shared/share/ert/shell_scripts/copy_directory
  src/ert/shared/share/ert/shell_scripts/copy_file
  src/ert/shared/share/ert/shell_scripts/delete_directory
  src/ert/shared/share/ert/shell_scripts/delete_file
  src/ert/shared/share/ert/shell_scripts/make_directory
  src/ert/shared/share/ert/shell_scripts/move_file
  src/ert/shared/share/ert/shell_scripts/symlink
  tests/conftest.py
  tests/libres_tests/res/fm/test_shell.py
Labels: bug

#3773 Remove enkf_main alloc enkf_fs from symlink
  src/clib/lib/enkf/enkf_main.cpp
  src/clib/lib/include/ert/enkf/enkf_defaults.hpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_main_fs_current_file.cpp
Labels: release-notes:breaking-change

#3767 Fetch storage server name, i.e. the config name, and use as title in webviz-ert
  setup.py
  src/ert/shared/dark_storage/endpoints/__init__.py
  src/ert/shared/dark_storage/endpoints/server.py
  src/ert/shared/main.py
  src/ert/shared/services/webviz_ert_service.py
Labels: enhancement

#3620 Protobuf job_runner.reporter
  .gitignore
  .mypy-strict.ini
  .mypy.ini
  .pylintrc
  README.md
  dev-requirements.txt
  pyproject.toml
  setup.cfg
  setup.py
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/ensemble_evaluator/builder/_legacy.py
  src/ert/experiment_server/_schema.proto
  src/ert/experiment_server/_server.py
  src/ert/job_runner/cli.py
  src/ert/job_runner/reporting/__init__.py
  src/ert/job_runner/reporting/event.py
  src/ert/job_runner/reporting/message.py
  src/ert/job_runner/reporting/protobuf.py
  src/ert/job_runner/reporting/statemachine.py
  src/ert/job_runner/runner.py
  tests/ert_tests/experiment_server/test_server.py
  tests/libres_tests/job_runner/test_event_reporter.py
  tests/libres_tests/job_runner/test_protobuf_reporter.py
  tests/libres_tests/res/job_queue/test_job_queue.py
Labels: release-notes:misc, experiment-server

#3779 Remove case-log that was not being used
  src/clib/lib/enkf/enkf_main.cpp
  src/clib/lib/include/ert/enkf/enkf_defaults.hpp
Labels: release-notes:breaking-change

#3724 Use id for ensemble instead of ensemble evaluator
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/ensemble_evaluator/builder/_ensemble.py
  src/ert/ensemble_evaluator/builder/_ensemble_builder.py
  src/ert/ensemble_evaluator/builder/_function_task.py
  src/ert/ensemble_evaluator/builder/_job.py
  src/ert/ensemble_evaluator/builder/_legacy.py
  src/ert/ensemble_evaluator/builder/_prefect.py
  src/ert/ensemble_evaluator/builder/_realization.py
  src/ert/ensemble_evaluator/builder/_step.py
  src/ert/ensemble_evaluator/builder/_template.py
  src/ert/ensemble_evaluator/builder/_unix_task.py
  src/ert/ert3/engine/_run.py
  src/ert/ert3/evaluator/_builder.py
  src/ert/job_runner/cli.py
  src/ert/job_runner/reporting/event.py
  src/ert/job_runner/reporting/message.py
  src/ert/job_runner/reporting/protobuf.py
  src/ert/job_runner/runner.py
  src/ert/shared/ensemble_evaluator/evaluator.py
  src/ert/shared/ensemble_evaluator/narratives/monitor_failing_evaluation.py
  src/ert/shared/ensemble_evaluator/narratives/monitor_successful_ensemble.py
  src/ert/shared/models/base_run_model.py
  tests/ert_tests/ensemble_evaluator/conftest.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/prefect/conftest.py
  tests/ert_tests/ensemble_evaluator/prefect/test_prefect_ensemble.py
  tests/ert_tests/ensemble_evaluator/prefect/test_prefect_step.py
  tests/ert_tests/ensemble_evaluator/prefect/test_run_dialog_ert3.py
  tests/ert_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/ert_tests/ensemble_evaluator/test_monitor.py
  tests/ert_tests/ert3/evaluator/test_evaluator.py
  tests/libres_tests/job_runner/test_event_reporter.py
  tests/libres_tests/job_runner/test_job_dispatch.py
  tests/libres_tests/job_runner/test_protobuf_reporter.py
  tests/libres_tests/res/job_queue/test_job_queue.py
Labels: release-notes:maintenance, experiment-server

#3777 Change how EnkfFs classmethod is instantiated
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  tests/libres_tests/res/enkf/test_enkf_fs.py
Labels: release-notes:breaking-change

#3784 Upgrade to cloudevents 1.6.0
  setup.py
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/ensemble_evaluator/builder/_ensemble.py
  src/ert/ensemble_evaluator/builder/_prefect.py
  src/ert/job_runner/reporting/event.py
  src/ert/shared/ensemble_evaluator/client.py
  src/ert/shared/ensemble_evaluator/evaluator.py
  src/ert/shared/ensemble_evaluator/monitor.py
  src/ert/shared/ensemble_evaluator/narratives/narrative.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/test_contracts.py
  tests/ert_tests/ensemble_evaluator/test_data_marshaller_and_unmarshaller.py
  tests/ert_tests/experiment_server/test_server.py
Labels: release-notes:maintenance

#3786 Remove hidden case consept
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/gui/ertwidgets/caselist.py
  src/ert/gui/ertwidgets/caseselector.py
  src/ert/gui/ertwidgets/models/all_cases_model.py
  src/ert/gui/ertwidgets/models/ertmodel.py
  src/ert/libres_facade.py
  tests/ert_tests/shared/test_libres_facade.py
Labels: release-notes:breaking-change

#3788 Refactor FileSystemRotator
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_fs_manager.py
  src/ert/_c_wrappers/enkf/enkf_main.py
Labels: release-notes:maintenance

#3772 Fix the logging path when running the GUI
  src/ert/logging/__init__.py
  src/ert/logging/storage_log.conf
  src/ert/shared/main.py
Labels: release-notes:improvement

#3750 Remove ecl_write from EnkfNode
  src/ert/_c_wrappers/enkf/data/enkf_node.py
  tests/libres_tests/res/enkf/data/test_enkf_node.py
Labels: release-notes:maintenance

#3799 Update cmake build instructions in readme
  README.md
Labels: release-notes:maintenance

#3805 Fix bug where RUN_TEMPLATE would fail on relative path
  src/ert/_c_wrappers/enkf/enkf_main.py
  tests/libres_tests/res/enkf/test_run_path_creation.py
Labels: release-notes:bug-fix

#3796 Test initializing from config_dict via hypothesis
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  dev-requirements.txt
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/_c_wrappers/enkf/ecl_config.py
  src/ert/_c_wrappers/enkf/ert_workflow_list.py
  src/ert/_c_wrappers/enkf/queue_config.py
  src/ert/_c_wrappers/enkf/subst_config.py
  tests/conftest.py
  tests/test_config_parsing/__init__.py
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/conftest.py
  tests/test_config_parsing/egrid_generator.py
  tests/test_config_parsing/test_analysis_config.py
  tests/test_config_parsing/test_ecl_config.py
  tests/test_config_parsing/test_queue_config.py
  tests/test_config_parsing/test_res_config.py
  tests/test_config_parsing/test_rng_config.py
  tests/test_config_parsing/test_site_config.py
  tests/test_config_parsing/test_subst_config.py
  tests/test_config_parsing/test_workflow_list.py
Labels: bug

#3820 Stop special casing PRED as a GEN_KW
  docs/reference/configuration/keywords.rst
  src/clib/lib/enkf/enkf_main.cpp
Labels: release-notes:breaking-change

#3819 Add a cli argument for specifying a log dir
  src/ert/logging/logger.conf
  src/ert/shared/main.py
Labels: release-notes:new-feature

#3827 Remove unused template
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/res_util/template.hpp
  src/clib/lib/include/ert/res_util/template_type.hpp
  src/clib/lib/res_util/template.cpp
  src/clib/lib/res_util/template_loop.cpp
Labels: release-notes:maintenance

#3459 Remove unused function state_map::count_matching
  src/clib/lib/enkf/state_map.cpp
  src/clib/lib/include/ert/enkf/state_map.hpp
  src/clib/old_tests/enkf/test_enkf_state_map.cpp
Labels: release-notes:maintenance

#3826 Mute matplotlib debug messages
  src/ert/logging/logger.conf
Labels: release-notes:maintenance

#3821 Remove Title Case from documentation
  docs/experimental/webviz-ert.rst
  docs/getting_started/configuration/poly_new/guide.rst
  docs/reference/configuration/data_types.rst
  docs/reference/configuration/keywords.rst
  docs/theory/ensemble_based_methods.rst
Labels: documentation, release-notes:maintenance

#3818 Fix typo and formatting in keyword documentation
  docs/reference/configuration/keywords.rst
Labels: documentation, release-notes:maintenance

#3832 Fix unnecessary cast from const double to double
  src/clib/lib/enkf/gen_obs.cpp
Labels: payback

#3793 Propagate ensemble id for source when building
  src/ert/ensemble_evaluator/builder/_ensemble_builder.py
  src/ert/ensemble_evaluator/builder/_function_task.py
  src/ert/ensemble_evaluator/builder/_job.py
  src/ert/ensemble_evaluator/builder/_prefect.py
  src/ert/ensemble_evaluator/builder/_realization.py
  src/ert/ensemble_evaluator/builder/_step.py
  src/ert/ensemble_evaluator/builder/_template.py
  src/ert/ensemble_evaluator/builder/_unix_task.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_builder.py
Labels: release-notes:misc

#3837 Increase readability of rng-config test
  tests/libres_tests/res/enkf/test_rng_config.py
Labels: testing
