Repository equinor/ert, pull requests merged in 2022-01, with the labels that each got.

#2641 Support YYYY-MM-DD (ISO-8601) in observation files, timemap files and END_DATE keyword.
  docs/rst/manual/reference/configuration/keywords.rst
  docs/rst/manual/reference/configuration/observations.rst
  libres/lib/config/conf_data.cpp
  libres/lib/enkf/ecl_config.cpp
  libres/lib/enkf/time_map.cpp
  res/enkf/ecl_config.py
  res/enkf/res_config.py
  res/enkf/util/time_map.py
  test-data/local/configuration_tests/ecl_config.ert
  test-data/local/snake_oil/jobs/snake_oil_simulator.py
  test-data/local/snake_oil/observations/observations.txt
  test-data/local/snake_oil/refcase/time_map.txt
  tests/ert_tests/data/test_integration_data.py
  tests/libres_tests/res/enkf/test_ecl_config.py
  tests/libres_tests/res/enkf/test_res_config.py
  tests/libres_tests/res/enkf/test_time_map.py
Labels: user request, Configuration

#2628 Test run_analysis_update_without_rowscaling
  libres/lib/analysis/update.cpp
  libres/lib/enkf/obs_data.cpp
  libres/lib/include/ert/analysis/update.hpp
  libres/tests/CMakeLists.txt
  libres/tests/analysis/test_update.cpp
Labels: maintenance, testing

#2668 Support numerical characters in parameter names
  ert3/config/_parameters_config.py
  tests/ert_tests/ert3/config/test_parameters_config.py
Labels: ert3

#2692 Use lowercase letters when specifying psb resources
  ert_shared/ensemble_evaluator/ensemble/prefect.py
Labels: bug, ert3

#2689 Fix failure when using pbs driver
  ert_shared/ensemble_evaluator/ensemble/prefect.py
  tests/ert_tests/ensemble_evaluator/prefect/test_prefect_step.py
Labels: bug, ert3

#2695 Don't ask for storage as an extras in CI
  .github/workflows/run_examples_polynomial.yml
  .github/workflows/run_examples_spe1.yml
Labels: payback, maintenance

#2685 Fix SPE1 yaml config for smry_keys
  .github/workflows/run_examples_spe1.yml
  ert/storage/_storage.py
  ert3/console/_console.py
  ert3_examples/spe1/experiments/doe/ensemble.yml
  ert3_examples/spe1/experiments/evaluation/ensemble.yml
  ert3_examples/spe1/experiments/sensitivity/ensemble.yml
  ert3_examples/spe1/stages.yml
  ert3_examples/spe1/summary2json.py
  tests/ert_tests/ert3/console/integration/test_cli.py
Labels: bug, ert3

#2696 Remove leftover dd/mm/yyyy mention in docs
  docs/rst/manual/reference/configuration/keywords.rst
  libres/lib/enkf/enkf_obs.cpp
Labels: documentation

#2699 Writeup of posterior properties
  docs/rst/manual/theory/ensemble_based_methods.rst
  docs/rst/manual/theory/images/posterior_path.png
  libres/tests/analysis/test_update.cpp
Labels: documentation

#2665 Remove broken test configuration file
  test-data/local/config/simple_config
  tests/libres_tests/res/config/test_config.py
Labels: payback

#2664 Remove unused functions in enkf_fs_manager
  ert_shared/share/ert/gui/doc/info.txt
  libres/lib/enkf/enkf_fs.cpp
  libres/lib/enkf/enkf_main_manage_fs.cpp
  libres/lib/enkf/time_map.cpp
  libres/lib/include/ert/enkf/enkf_fs.hpp
  libres/lib/include/ert/enkf/enkf_main.hpp
  libres/lib/include/ert/enkf/time_map.hpp
  libres/old_tests/enkf/test_enkf_time_map.cpp
  res/enkf/enkf_fs_manager.py
Labels: breaking-change

#2662 Remove outdated documentation about developing analysis modules
  docs/rst/manual/reference/configuration/keywords.rst
Labels: documentation

#2705 Remove unused enkf_linalg_svd_truncation
  libres/lib/analysis/enkf_linalg.cpp
  libres/lib/include/ert/analysis/enkf_linalg.hpp
Labels: maintenance

#2697 Test update with row scaling
  libres/tests/analysis/test_update.cpp
Labels: testing

#2681 Use `ies::config::config` class for configuration also of std enkf module
  libres/lib/analysis/ies/ies.cpp
  libres/lib/analysis/ies/ies_config.cpp
  libres/lib/analysis/std_enkf.cpp
  libres/lib/include/ert/analysis/ies/ies_config.hpp
  libres/tests/CMakeLists.txt
  libres/tests/analysis/ies/test_ies_config.cpp
Labels: analysis

#2709 Use std variant
  libres/lib/analysis/enkf_linalg.cpp
  libres/lib/analysis/ies/ies.cpp
  libres/lib/analysis/ies/ies_config.cpp
  libres/lib/analysis/std_enkf.cpp
  libres/lib/include/ert/analysis/enkf_linalg.hpp
  libres/lib/include/ert/analysis/ies/ies.hpp
  libres/lib/include/ert/analysis/ies/ies_config.hpp
  libres/lib/include/ert/analysis/std_enkf.hpp
  libres/tests/analysis/test_compare_initX.cpp
Labels: maintenance, analysis

#2638 Replace parsing of excluded hostnames in lsf with standard library functions
  libres/lib/include/ert/job_queue/lsf_driver.hpp
  libres/lib/include/ert/res_util/string.hpp
  libres/lib/job_queue/lsf_driver.cpp
  libres/old_tests/job_queue/test_job_lsf_exclude_hosts.cpp
  libres/tests/CMakeLists.txt
  libres/tests/job_queue/test_lsf_driver.cpp
  libres/tests/res_util/test_string.cpp
Labels: payback

#2702 Improve error messages in ert3 config validation
  ert/storage/_storage.py
  ert3/config/_experiment_run_config.py
  ert3/workspace/_workspace.py
  tests/ert_tests/ert3/config/test_experiment_run_config.py
  tests/ert_tests/ert3/engine/integration/test_engine.py
  tests/ert_tests/ert3/workspace/test_workspace.py
Labels: ert3

#2723 Use ert port range for pbs driver
  ert3/evaluator/_evaluator.py
  ert_shared/ensemble_evaluator/ensemble/prefect.py
Labels: bug, ert3

#2732 Make ert3 log to console when realisations complete
  ert3/evaluator/_evaluator.py
Labels: ert3

#2602 Use ies
  libres/lib/analysis/ies/ies.cpp
  libres/lib/analysis/std_enkf.cpp
  libres/lib/include/ert/analysis/ies/ies.hpp
  libres/lib/include/ert/analysis/std_enkf.hpp
  libres/tests/analysis/test_compare_initX.cpp
Labels: maintenance, analysis

#2727 Raise meaningful exception when accessing non existing analysis module
  libres/lib/enkf/analysis_config.cpp
  libres/tests/enkf/test_analysis_config.cpp
Labels: payback

#2725 Remove unused python obs and measure
  libres/lib/enkf/enkf_obs.cpp
  libres/lib/include/ert/enkf/enkf_obs.hpp
  libres/old_tests/enkf/test_enkf_obs.cpp
  res/enkf/enkf_obs.py
  res/enkf/observations/obs_vector.py
  tests/libres_tests/res/enkf/test_enkf_obs.py
Labels: breaking-change

#2716 Remove unused code in python interface with analysis module
  res/analysis/analysis_module.py
  tests/libres_tests/res/analysis/test_analysis_module.py
  tests/libres_tests/res/analysis/test_ies.py
  tests/libres_tests/res/enkf/test_update.py
Labels: breaking-change

#2701 Allow the user to setup backend DB url in ert3
  ert3/console/_console.py
  tests/ert_tests/ert3/console/integration/test_cli.py
Labels: enhancement, ert3

#2740 Allow inline shell script in stages
  ert3/evaluator/_builder.py
  tests/ert_tests/ert3/evaluator/test_evaluator.py
Labels: Configuration, ert3

#2754 Describe SIMULATION_JOB
  libres/lib/enkf/config_keys.cpp
Labels: documentation

#2717 Add test for analysis::copy_parameters
  libres/tests/CMakeLists.txt
  libres/tests/analysis/test_copy_parameters.cpp
Labels: testing

#2721 Add tests for save/load parameters with rowscaling
  libres/lib/analysis/update.cpp
  libres/tests/analysis/test_save_parameters.cpp
Labels: testing

#2771 Always handle connection errors when monitoring the ensemble
  ert_shared/ensemble_evaluator/evaluator.py
  tests/ert_tests/cli/test_integration_cli.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: bug, ensemble-evaluator

#2773 Backport connection closed error
  ert_shared/ensemble_evaluator/evaluator.py
  tests/ert_tests/cli/test_integration_cli.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: bug, ensemble-evaluator

#2779 Improve error handling around ert3 initialization
  ert/storage/__init__.py
  ert/storage/_storage.py
  ert3/console/_console.py
  ert3/workspace/_workspace.py
Labels: bug, ert3

#2783 Stop using a Client instance over long time spans
  ert_shared/ensemble_evaluator/entity/unix_step.py
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert_tests/ensemble_evaluator/prefect/scripts/unix_test_script.py
  tests/ert_tests/ensemble_evaluator/prefect/test_prefect_step.py
Labels: bug, ert3

#2786 Make AutorunTestEnsemble cancellable
  tests/ert_tests/ensemble_evaluator/ensemble_evaluator_utils.py
Labels: bug, ensemble-evaluator, flaky-test

#2807 Do not build vanilla step on unexpected step type
  ert_shared/ensemble_evaluator/ensemble/builder.py
  tests/ert_tests/ensemble_evaluator/test_ensemble_builder.py
Labels: bug

#2808 Drop threads when collecting summary-data
  libres/lib/enkf/enkf_plot_data.cpp
  libres/lib/enkf/enkf_plot_tvector.cpp
  libres/lib/include/ert/enkf/enkf_plot_tvector.hpp
Labels: improvement
