Repository equinor/ert, pull requests merged in 2023-01, with the labels that each got.

#4526 Improve type hints of `_get_A_matrix`
  src/ert/analysis/_es_update.py
Labels: maintenance

#4508 Remove unused keyword ENKF_RERUN
  docs/reference/configuration/keywords.rst
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/analysis_config.py
  tests/test_config_parsing/config_dict_generator.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_config_content_as_dict.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: release-notes:maintenance

#4528 Rename badly named test
  tests/test_config_parsing/test_defines.py
Labels: release-notes:misc

#4538 Add check for ECLBASE being present when config contains SUMMARY
  src/ert/_c_wrappers/enkf/res_config.py
  test-data/configuration_tests/ensemble_config.ert
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
Labels: release-notes:improvement

#4545 Add check for ECLBASE being present when config contains SUMMARY
  src/ert/_c_wrappers/enkf/res_config.py
  test-data/configuration_tests/ensemble_config.ert
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
Labels: release-notes:improvement

#4511 Fix bug in pylint check workflow
  .github/workflows/style.yml
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  tests/test_config_parsing/config_dict_generator.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_export.py
Labels: release-notes:maintenance

#4535 Move ens path from model config to res config
  src/ert/__main__.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/cli/main.py
  src/ert/libres_facade.py
  tests/test_config_parsing/test_model_config.py
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_programmatic_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: release-notes:skip

#4537 Remove false positive warning for INSTALL_JOB_DIRECTORY
  src/ert/_c_wrappers/enkf/res_config.py
Labels: release-notes:maintenance

#4547 Remove false positive warning for INSTALL_JOB_DIRECTORY
  src/ert/_c_wrappers/enkf/res_config.py
Labels: release-notes:maintenance

#4546 Provide better error message when there are infinite loops in the defines
  src/clib/lib/config/config_parser.cpp
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:improvement

#4555 Set SIMULATION_JOB arglist correctly and add read_site_config method
  src/ert/_c_wrappers/enkf/res_config.py
Labels: release-notes:skip

#4548 Provide better error message when there are infinite loops in the defines
  src/clib/lib/config/config_parser.cpp
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:improvement

#4527 Changed --workdir to -D to maintain compatibility with all Slurm versions
  src/clib/lib/job_queue/slurm_driver.cpp
Labels: release-notes:improvement

#4554 Align test config_dict with dict generated from config content
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/test_config_parsing/config_dict_generator.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: payback

#4514 Let delete_file delete broken symlinks
  src/ert/shared/share/ert/shell_scripts/delete_directory.py
  tests/unit_tests/shared/share/test_shell.py
Labels: release-notes:bug-fix

#4558 Provide suggestion for replacing deprecated RUNPATH %d specifiers
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  tests/test_config_parsing/test_suggester.py
Labels: release-notes:improvement

#4505 Remove skip for test_load_state.py
  tests/performance_tests/enkf/test_load_state.py
Labels: release-notes:skip

#4563 Type-check enkf_main and enkf_fs_manager
  .mypy-strict.ini
  .mypy.ini
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_fs_manager.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_workflow_list.py
  src/ert/_c_wrappers/enkf/queue_config.py
  src/ert/_c_wrappers/enkf/runpaths.py
  src/ert/_c_wrappers/util/substitution_list.py
  src/ert/experiment_server/_experiment_protocol.py
  src/ert/experiment_server/_server.py
  src/ert/shared/models/ensemble_smoother.py
  src/ert/simulator/simulation_context.py
Labels: release-notes:maintenance

#4570 Avoid overwriting runpath keyword during loop
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ert_run_context.py
  tests/unit_tests/c_wrappers/res/enkf/test_run_path_creation.py
Labels: release-notes:bug-fix, release-notes:maintenance

#4576 Provide better error messages for subst failures
  src/clib/lib/include/ert/res_util/subst_list.hpp
  src/clib/lib/res_util/subst_list.cpp
Labels: release-notes:skip

#4567 Let delete_file() in delete_directory.py delete symlinks
  src/ert/_c_wrappers/fm/shell/shell.py
  tests/unit_tests/c_wrappers/res/fm/test_shell.py
  types-requirements.txt
Labels: release-notes:bug-fix

#4585 Change infinite substitution loop errors to warn
  src/clib/lib/config/config_parser.cpp
  src/clib/lib/res_util/subst_list.cpp
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:skip

#4593 Fix gui not keeping storage running
  src/ert/gui/gert_main.py
  tests/unit_tests/gui/test_gui_load.py
Labels: bug, release-notes:skip

#4596 Backport gui storage fix
  src/ert/gui/gert_main.py
  tests/unit_tests/gui/test_gui_load.py
Labels: bug, release-notes:skip

#4578 Remove types-six, not needed any longer
  types-requirements.txt
Labels: release-notes:skip

#4589 Bump ies to version 0.0.5
  setup.py
Labels: release-notes:maintenance

#4600 Add missing space in user-facing warning
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
Labels: release-notes:skip

#4582 Warn when QUEUE_OPTION MAX_RUNNING is invalid / negative
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:maintenance

#4598 Fix runpath format displayed in QT GUI
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/simulation_config_panel.py
  src/ert/gui/simulation/single_test_run_panel.py
Labels: release-notes:bug-fix

#4603 Avoid overwriting existing run context substitutions
  src/ert/_c_wrappers/enkf/ert_run_context.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
Labels: release-notes:maintenance

#4613 Remove unused property: dynamic
  src/clib/lib/enkf/gen_data.cpp
  src/clib/lib/enkf/gen_data_config.cpp
  src/clib/lib/include/ert/enkf/gen_data_config.hpp
  src/clib/old_tests/enkf/test_enkf_gen_data_config.cpp
Labels: release-notes:maintenance

#4621 Reimplement WorkflowJob.configParser in python
  src/clib/lib/include/ert/job_queue/workflow_job.hpp
  src/clib/lib/job_queue/workflow_job.cpp
  src/ert/_c_wrappers/job_queue/workflow_job.py
Labels: payback, release-notes:skip

#4612 Throw exception of gen_obs data_index is outside range of gen_data
  src/clib/lib/enkf/gen_obs.cpp
  src/ert/analysis/_es_update.py
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:improvement

#4620 Remove EnkfNode and related C++ code
  src/clib/lib/CMakeLists.txt
  src/clib/lib/analysis/update.cpp
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/enkf_fs.cpp
  src/clib/lib/enkf/enkf_node.cpp
  src/clib/lib/enkf/enkf_state.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/enkf/enkf_node.hpp
  src/clib/lib/include/ert/enkf/enkf_state.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/fs_driver.hpp
  src/clib/lib/include/ert/enkf/obs_vector.hpp
  src/clib/old_tests/enkf/test_enkf_gen_data_config.cpp
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/data/__init__.py
  src/ert/_c_wrappers/enkf/data/enkf_node.py
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/node_id.py
  src/ert/analysis/_es_update.py
  src/ert/ensemble_evaluator/callbacks.py
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  src/ert/libres_facade.py
  src/ert/simulator/batch_simulator_context.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_fs_manager.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_export.py
Labels: release-notes:maintenance

#4626 Remove unused rms_*.cpp
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/field_config.cpp
  src/clib/lib/include/ert/enkf/field_config.hpp
  src/clib/lib/rms/rms_file.cpp
  src/clib/lib/rms/rms_tag.cpp
  src/clib/lib/rms/rms_tagkey.cpp
  src/clib/lib/rms/rms_type.cpp
  src/clib/lib/rms/rms_util.cpp
  src/ert/_c_wrappers/enkf/config/field_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_config.py
Labels: release-notes:maintenance

#4602 Increase timeout for qstat flakyness
  src/clib/lib/job_queue/torque_driver.cpp
Labels: release-notes:bug-fix

#4633 Always sort summary keys
  src/ert/_c_wrappers/enkf/summary_key_set.py
  src/ert/libres_facade.py
Labels: release-notes:maintenance

#4639 Use package resources
  src/ert/_c_wrappers/enkf/res_config.py
Labels: release-notes:maintenance

#4646 Remove warn indication icon when observations not present
  src/ert/gui/simulation/simulation_panel.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#4645 Increase timeout for qstat flakyness
  src/clib/lib/job_queue/torque_driver.cpp
Labels: release-notes:bug-fix

#4660 Setup UI before suggester to extend Qt components lifetime
  src/ert/gui/gert_main.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#4661 Remove warn indication icon when observations not present
  src/ert/gui/simulation/simulation_panel.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#4663 Avoid util_abort when INCLUDEing non existing file in config
  src/clib/lib/config/config_parser.cpp
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: release-notes:bug-fix

#4666 Simplify tests checking for dict and file equality
  tests/test_config_parsing/test_analysis_config.py
  tests/test_config_parsing/test_ensemble_config.py
  tests/test_config_parsing/test_model_config.py
  tests/test_config_parsing/test_queue_config.py
  tests/test_config_parsing/test_res_config.py
  tests/test_config_parsing/test_substitution_list.py
  tests/test_config_parsing/test_workflow_list.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: release-notes:skip

#4672 Make empty/missing job directories give better error messages
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:improvement

#4628 Ensure that incorrectly configured workflow jobs give descriptive error messages
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/job_queue/workflow_job.hpp
  src/clib/lib/job_queue/workflow_job.cpp
  src/ert/_c_wrappers/config/schema_item.py
  src/ert/_c_wrappers/enkf/ert_workflow_list.py
  src/ert/_c_wrappers/job_queue/ert_script.py
  src/ert/_c_wrappers/job_queue/workflow.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  src/ert/gui/tools/plugins/plugin.py
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_workflow_list.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ert_script.py
  tests/unit_tests/c_wrappers/res/job_queue/test_function_ert_script.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow_job.py
  tests/unit_tests/shared/share/test_shell.py
Labels: release-notes:improvement

#4664 Stop substituting in FORWARD_MODEL argument names
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/config/config_parser.cpp
  src/clib/lib/config/config_schema_item.cpp
  src/clib/lib/include/ert/config/config_schema_item.hpp
  src/ert/_c_wrappers/job_queue/forward_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: release-notes:user-impact

#4684 Replace AnalysisConfigError with ConfigValidationError
  src/ert/_c_wrappers/enkf/analysis_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
Labels: release-notes:improvement

#4614 Add matching list for field transformations
  docs/reference/configuration/data_types.rst
  docs/reference/configuration/keywords.rst
  src/clib/lib/enkf/field_trans.cpp
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/test_ensemble_config.py
Labels: release-notes:maintenance

#4677 Replace the string gert by ert
  src/ert/__main__.py
  src/ert/gui/main.py
  src/ert/gui/main_window.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#4686 Add filename to configuration tokenizer feedback
  src/clib/lib/config/conf.cpp
Labels: release-notes:maintenance

#4690 Fix time map within tolerance check and raise python exception instead of util_abort
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
  src/clib/lib/include/ert/enkf/enkf_obs.hpp
  src/ert/_c_wrappers/enkf/enkf_obs.py
  tests/unit_tests/c_wrappers/res/enkf/test_summary_observation.py
Labels: release-notes:maintenance

#4693 Raise ConfigValidationError on invalid Workflow runmode
  src/ert/_c_wrappers/enkf/ert_workflow_list.py
Labels: release-notes:maintenance

#4695 Make config warnings show up in the GUI
  src/ert/_c_wrappers/config/__init__.py
  src/ert/_c_wrappers/config/config_parser.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/cli/main.py
  src/ert/gui/main.py
  tests/test_config_parsing/test_res_config.py
Labels: improvement, release-notes:improvement

#4581 Add context to circular define warnings
  src/clib/lib/config/config_content.cpp
  src/clib/lib/config/config_parser.cpp
  src/clib/lib/include/ert/res_util/subst_list.hpp
  src/clib/lib/res_util/subst_list.cpp
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/_c_wrappers/util/substitution_list.py
Labels: release-notes:skip

#4688 Add startup suggestion for removing deprecated keyword PLOT_SETTINGS
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  tests/test_config_parsing/test_suggester.py
Labels: release-notes:improvement

#4698 Catch only ConfigValidationError in ERT GUI
  src/ert/gui/main.py
Labels: release-notes:improvement

#4697 Move warning about deprecated defines without angle brackets to the suggester
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_res_config.py
  tests/test_config_parsing/test_suggester.py
Labels: release-notes:maintenance

#4711 Fix parsing of forward model with quotes
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:bug-fix

#4712 Fix bug where prior was overwritten
  src/ert/shared/models/ensemble_experiment.py
Labels: bug

#4717 Fix parsing of forward model with quotes
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  tests/test_config_parsing/test_res_config.py
Labels: bug, release-notes:bug-fix

#4699 Remove special casing from AnalysisConfig
  src/ert/_c_wrappers/enkf/analysis_config.py
  tests/test_config_parsing/config_dict_generator.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
Labels: release-notes:skip

#4715 Restrict flake8 requirements
  dev-requirements.txt
  setup.cfg
  src/_ert_com_protocol/__init__.py
  src/ert/__main__.py
  src/ert/_c_wrappers/__init__.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/util/__init__.py
  src/ert/data/__init__.py
  src/ert/gui/tools/__init__.py
  src/ert/gui/tools/export/__init__.py
  src/ert/gui/tools/file/__init__.py
  src/ert/gui/tools/load_results/__init__.py
  src/ert/gui/tools/manage_cases/__init__.py
  src/ert/gui/tools/plot/widgets/__init__.py
  src/ert/gui/tools/run_analysis/__init__.py
  src/ert/gui/tools/workflows/__init__.py
  src/ert/shared/ide/keywords/data/__init__.py
  src/ert/shared/plugins/hook_specifications/__init__.py
  tests/unit_tests/all/test_main.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_export.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow_runner.py
  tests/unit_tests/ensemble_evaluator/prefect/conftest.py
  tests/unit_tests/gui/plottery/test_plot_limits.py
  tests/unit_tests/models/test_base_run_model.py
Labels: release-notes:skip

#4724 Add logging of suggester messages
  src/ert/gui/gert_main.py
Labels: release-notes:skip

#4704 Add error context information to FORWARD_MODEL parsing
  src/clib/lib/res_util/subst_list.cpp
  src/clib/old_tests/res_util/test_ert_util_subst_list_add_from_string.cpp
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/util/substitution_list.py
Labels: release-notes:maintenance

#4731 Use zero as default for load manual results
  src/ert/gui/tools/load_results/load_results_panel.py
Labels: release-notes:maintenance

#4735 Fix issue suggester parsing fails
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_suggester.py
Labels: release-notes:bug-fix

#4736 Fix an issue with false-positive config errors
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_suggester.py
Labels: bug, release-notes:bug-fix

#4723 Stop parsing workflow during init
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/workflow.py
  src/ert/_c_wrappers/job_queue/workflow_runner.py
  src/ert/cli/workflow.py
  src/ert/gui/tools/workflows/run_workflow_widget.py
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow_runner.py
Labels: bug, release-notes:skip

#4738 Demote csv_export to ErtScript
  src/ert/_c_wrappers/util/substitution_list.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/csv_export.py
Labels: payback

#4740 Add checklist items for documentation and tests in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-notes:skip

#4734 Improve error message for missing path in config
  src/clib/lib/config/config_schema_item.cpp
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:improvement

#4745 Fix wrong time step nr in mismach error message
  src/ert/_c_wrappers/enkf/enkf_state.py
Labels: release-notes:bug-fix

#4749 Fix issue where valid RUNPATH would logged as invalid
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/runpaths.py
  tests/test_config_parsing/test_model_config.py
Labels: release-notes:bug-fix

#4760 Make private args be substituted only once
  src/clib/lib/config/config_content.cpp
  src/clib/lib/config/config_parser.cpp
  src/clib/lib/include/ert/res_util/subst_list.hpp
  src/clib/lib/res_util/subst_list.cpp
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/_c_wrappers/util/substitution_list.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: release-notes:user-impact

#4762 Make private args be substituted only once
  src/clib/lib/config/config_content.cpp
  src/clib/lib/config/config_parser.cpp
  src/clib/lib/include/ert/res_util/subst_list.hpp
  src/clib/lib/res_util/subst_list.cpp
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/_c_wrappers/util/substitution_list.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: release-notes:bug-fix
