Repository equinor/ert, pull requests merged in 2023-07, with the labels that each got.

#5652 Fix flaky block_storage test
  src/ert/storage/migration/block_fs.py
  tests/unit_tests/storage/migration/test_block_fs_snake_oil.py
Labels: release-notes:skip

#4994 Fix README formatting in performance test files
  test-data/poly_template/README.md
  tests/performance_tests/README.md
Labels: release-notes:skip

#5689 Remove remnants of prefect
  setup.py
  src/ert/ensemble_evaluator/_builder/_ensemble_builder.py
  src/ert/ensemble_evaluator/_builder/_function_task.py
  src/ert/ensemble_evaluator/_builder/_io_map.py
  src/ert/ensemble_evaluator/_builder/_job.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/ensemble_evaluator/_builder/_prefect.py
  src/ert/ensemble_evaluator/_builder/_prefect_forkserver_preload.py
  src/ert/ensemble_evaluator/_builder/_step.py
  src/ert/ensemble_evaluator/_builder/_unix_task.py
  tests/unit_tests/ensemble_evaluator/prefect/__init__.py
  tests/unit_tests/ensemble_evaluator/prefect/conftest.py
  tests/unit_tests/ensemble_evaluator/prefect/scripts/__init__.py
  tests/unit_tests/ensemble_evaluator/prefect/scripts/evaluate_coeffs.py
  tests/unit_tests/ensemble_evaluator/prefect/scripts/poly_eval_with_args.py
  tests/unit_tests/ensemble_evaluator/prefect/scripts/sum_coeffs.py
  tests/unit_tests/ensemble_evaluator/prefect/scripts/unix_test_retry_script.py
  tests/unit_tests/ensemble_evaluator/prefect/scripts/unix_test_script.py
  tests/unit_tests/ensemble_evaluator/prefect/test_prefect_ensemble.py
  tests/unit_tests/ensemble_evaluator/prefect/test_prefect_step.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
Labels: release-notes:maintenance

#5669 Add a performance test code for snapshot
  tests/performance_tests/test_snapshot.py
Labels: release-notes:skip

#5693 Inline test data in tests
  test-data/config/simulation_batch/config.ert
  test-data/config/simulation_batch/jobs/COPY_EXT_PARAM
  test-data/config/simulation_batch/jobs/copy_ext_param_script
  test-data/config/workflows/config
  test-data/config/workflows/workflowjobs/MAGIC_PRINT
  test-data/config/workflows/workflowjobs/bin/magic_print.py
  test-data/config/workflows/workflows/MAGIC_PRINT
  test-data/simple_config/analysis_config
  test-data/simple_config/minimum_config
  test-data/simple_config/script.sh
  test-data/simple_config/slurm_config
  tests/conftest.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_queue_config.py
  tests/unit_tests/models/test_base_run_model.py
Labels: release-notes:maintenance

#5626 Run integration tests with Eclipse in komodo
  ci/jenkins/testkomodo-libres-pytest.sh
  ci/testkomodo.sh
Labels: release-notes:skip

#5699 Fix testing SummaryConfing equality when no refcase is defined.
  src/ert/_c_wrappers/enkf/config/summary_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_summary_config.py
Labels: bug

#5696 Replace range check by comparison
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:skip

#5707 Do not propagate websockets logs to ert file
  src/ert/logging/logger.conf
Labels: release-notes:skip

#5708 Add test for flow reservoir simulator on a DATA deck with PARALLEL
  tests/unit_tests/shared/share/test_ecl_run.py
Labels: release-notes:skip

#5705 Increase sleeptime in qstat concurrency test
  tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py
Labels: release-notes:skip

#5703 Update paths and versions of Eclipse and MPI
  src/ert/shared/share/ert/forward-models/res/script/ecl_config.py
  tests/unit_tests/shared/share/test_ecl_run.py
Labels: release-notes:skip

#5676 Move parameter configurations
  .mypy-strict.ini
  .mypy.ini
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/analysis/_es_update.py
  src/ert/callbacks.py
  src/ert/config/__init__.py
  src/ert/config/ext_param_config.py
  src/ert/config/field_config.py
  src/ert/config/gen_data_config.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parameter_config.py
  src/ert/config/response_config.py
  src/ert/config/summary_config.py
  src/ert/config/surface_config.py
  src/ert/gui/main.py
  src/ert/libres_facade.py
  src/ert/logging/logger.conf
  src/ert/simulator/batch_simulator.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  src/ert/storage/migration/block_fs.py
  tests/performance_tests/test_memory_usage.py
  tests/test_config_parsing/config_dict_generator.py
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/config/__init__.py
  tests/unit_tests/config/test_ext_param_config.py
  tests/unit_tests/config/test_gen_data_config.py
  tests/unit_tests/config/test_gen_kw_config.py
  tests/unit_tests/config/test_summary_config.py
  tests/unit_tests/config/test_surface_config.py
Labels: release-notes:skip

#5714 Log full exception in batching dispatcher
  src/ert/ensemble_evaluator/dispatch.py
Labels: release-notes:skip

#5719 Save template for GenKW in experiment
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/config/gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
  tests/unit_tests/config/test_gen_kw_config.py
Labels: release-notes:improvement

#5723 Only set config dict entry to None if not multi occurrence
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_ert_config_parsing.py
Labels: release-notes:skip

#5724 Raise error on faulty result file and missing report steps
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_parser_error_collection.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
Labels: release-notes:skip

#5728 Wrap UnexpectedCharacters error as ObservationConfigError
  src/ert/parsing/new_observations_parser.py
  tests/test_config_parsing/test_new_observations_parser.py
Labels: release-notes:skip

#5740 Use new ConfigKeys
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/clib/lib/include/ert/job_queue/slurm_driver.hpp
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/_c_wrappers/enkf/analysis_iter_config.py
  src/ert/_c_wrappers/enkf/config_keys.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/parsing/config_keywords.py
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/test_ert_config_parsing.py
  tests/test_config_parsing/test_num_cpu.py
  tests/test_config_parsing/test_substitution_list.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
Labels: release-notes:skip

#5741 Fix typing of __eq__ functions
  src/ert/_c_wrappers/analysis/analysis_module.py
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/observations/gen_observation.py
  src/ert/gui/plottery/plot_limits.py
  src/ert/gui/plottery/plot_style.py
  tests/test_config_parsing/egrid_generator.py
Labels: release-notes:skip

#5744 add type_hints to analysis_config
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/_c_wrappers/enkf/analysis_iter_config.py
Labels: release-notes:skip

#5745 Make filename optional in ErrorInfo
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/job_queue/workflow.py
  src/ert/parsing/__init__.py
  src/ert/parsing/config_schema_item.py
  src/ert/parsing/error_info.py
  src/ert/parsing/lark_parser.py
  src/ert/parsing/new_observations_parser.py
  tests/test_config_parsing/test_parser_error_collection.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
Labels: release-notes:skip

#5742 Fix Parameter validation
  src/ert/_c_wrappers/analysis/configuration.py
  src/ert/_c_wrappers/update.py
  tests/unit_tests/c_wrappers/res/analysis/test_update_configuration.py
Labels: release-notes:skip

#5700 Fix plotting of parameters from ensembles made with manual update
  src/ert/analysis/_es_update.py
Labels: bug, release-notes:bug-fix

#5748 Add some type hints to config classes
  src/ert/_c_wrappers/analysis/analysis_module.py
  src/ert/_c_wrappers/analysis/configuration.py
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/observations/gen_observation.py
  src/ert/_c_wrappers/enkf/observations/obs_vector.py
  src/ert/analysis/_es_update.py
  src/ert/config/ext_param_config.py
  src/ert/config/field_config.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parameter_config.py
  src/ert/parsing/context_values.py
  src/ert/parsing/deprecation_info.py
  src/ert/parsing/error_info.py
  src/ert/parsing/file_context_token.py
  src/ert/parsing/schema_dict.py
  src/ert/parsing/workflow_job_schema.py
  src/ert/parsing/workflow_schema.py
Labels: release-notes:skip

#5749 Move field_utils to ert toplevel
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/config/field_config.py
  src/ert/field_utils/__init__.py
  src/ert/field_utils/field_utils.py
  src/ert/field_utils/grdecl_io.py
  src/ert/field_utils/roff_io.py
Labels: release-notes:skip

#5750 Log messages from job queue
  src/ert/logging/logger.conf
Labels: release-notes:skip
