Repository equinor/ert, pull requests merged in 2023-06, with the labels that each got.

#5511 Fix typo in repr for ext_param_config
  src/ert/_c_wrappers/enkf/config/ext_param_config.py
Labels: release-notes:skip

#5518 Ensure cwd is unchanged when running tests in CI
  ci/testkomodo.sh
Labels: release-notes:skip

#5516 Add pipe character to grammar
  src/ert/parsing/lark_parser.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
Labels: release-notes:skip

#5502 Make experiment server websockets>=11.0 compatible
  setup.py
  tests/unit_tests/experiment_server/conftest.py
  tests/unit_tests/experiment_server/test_server.py
Labels: enhancement, release-notes:skip

#5498 Add deprecations to new parser
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/parsing/__init__.py
  src/ert/parsing/config_dict.py
  src/ert/parsing/config_errors.py
  src/ert/parsing/config_linting.py
  src/ert/parsing/config_schema.py
  src/ert/parsing/config_schema_deprecations.py
  src/ert/parsing/config_schema_item.py
  src/ert/parsing/context_values.py
  src/ert/parsing/deprecation_info.py
  src/ert/parsing/error_info.py
  src/ert/parsing/ext_job_schema.py
  src/ert/parsing/lark_parser.py
  src/ert/parsing/schema_dict.py
  src/ert/parsing/types.py
  src/ert/parsing/workflow_job_schema.py
  tests/test_config_parsing/test_parser_error_collection.py
  tests/test_config_parsing/test_suggester.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:skip

#5531 Fix missing empty line in RST file
  docs/reference/configuration/keywords.rst
Labels: documentation, release-notes:skip

#5391 Use 32 bit datatypes in tests
  tests/performance_tests/performance_utils.py
  tests/test_config_parsing/summary_generator.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/ensemble_evaluator/prefect/test_prefect_ensemble.py
Labels: release-notes:skip

#5512 Fix closing the RunDialog with a file open takes down the entire application
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/file/file_dialog.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:bug-fix

#5507 Fixed a bug where std_scaling of manual analysis and ies_update was effected by having run esmda first
  src/clib/lib/enkf/config_keys.cpp
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/analysis/_es_update.py
  src/ert/libres_facade.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
Labels: release-notes:bug-fix, release-notes:skip

#5538 Add more type hints
  src/ert/_c_wrappers/__init__.py
  src/ert/_c_wrappers/config/config_parser.py
  src/ert/_c_wrappers/util/substitution_list.py
  src/ert/ensemble_evaluator/_builder/_io_.py
  src/ert/parsing/config_errors.py
  src/ert/parsing/schema_item_type.py
Labels: release-notes:skip

#5534 Trust a nonzero exit value from qstat
  src/clib/lib/job_queue/torque_driver.cpp
Labels: release-notes:bug-fix

#5539 Even more type hints
  src/ert/_c_wrappers/config/config_content.py
  src/ert/_c_wrappers/enkf/run_arg.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/job_queue/driver.py
  src/ert/_c_wrappers/job_queue/ert_plugin.py
  src/ert/_c_wrappers/job_queue/ert_script.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/_c_wrappers/job_queue/external_ert_script.py
  src/ert/_c_wrappers/job_queue/job_queue_manager.py
  src/ert/_c_wrappers/job_queue/job_queue_node.py
  src/ert/_c_wrappers/job_queue/job_status_type_enum.py
  src/ert/_c_wrappers/job_queue/job_submit_status_type_enum.py
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/_c_wrappers/job_queue/queue_differ.py
  src/ert/_c_wrappers/job_queue/run_status_type_enum.py
  src/ert/_c_wrappers/job_queue/thread_status_type_enum.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  src/ert/_c_wrappers/job_queue/workflow_runner.py
  src/ert/ensemble_evaluator/__init__.py
  src/ert/ensemble_evaluator/_builder/__init__.py
  src/ert/simulator/simulation_context.py
Labels: release-notes:skip

#5547 Guard against div-by-zero when min_required_realizations is zero
  src/ert/_c_wrappers/job_queue/job_queue_node.py
  src/ert/_c_wrappers/job_queue/queue.py
Labels: release-notes:bug-fix

#5550 Add new observations parser
  src/ert/parsing/new_observations_parser.py
  tests/test_config_parsing/test_new_observations_parser.py
Labels: release-notes:skip

#5554 Remove unused facade functions
  src/ert/libres_facade.py
Labels: release-notes:maintenance

#5540 Remove outdated docs
  docs/reference/workflows/built_in.rst
  docs/reference/workflows/index.rst
  docs/reference/workflows/internal.rst
Labels: documentation, release-notes:maintenance

#5570 Unpin SciPy in Ert
  setup.py
Labels: release-notes:maintenance

#5573 Fix bug where y and x increments were set to orientation
  src/ert/_c_wrappers/enkf/config/surface_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_surface_config.py
Labels: release-notes:maintenance

#5568 Avoid trusting zero exit code from qstat (backport to version-5.0)
  src/clib/lib/job_queue/torque_driver.cpp
  tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py
  tests/unit_tests/c_wrappers/res/job_queue/test_job_queue_manager_torque.py
Labels: release-notes:bug-fix

#5387 Remove irrelevant keywords in snake_oil.ert
  test-data/snake_oil/snake_oil.ert
Labels: release-notes:skip

#5576 Fix bug where %d was present in ECLBASE
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/scenarios/test_summary_response.py
Labels: release-notes:skip

#5581 Fix an issue with flakiness in gui test
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
Labels: release-notes:skip

#5584 remove unused isRealizationQueued
  src/ert/simulator/simulation_context.py
Labels: release-notes:skip

#5545 Clean up typing of callbacks
  src/ert/_c_wrappers/job_queue/job_queue_node.py
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/callbacks.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/ensemble_evaluator/_builder/_step.py
  src/ert/run_models/base_run_model.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/c_wrappers/res/job_queue/test_job_queue.py
  tests/unit_tests/c_wrappers/res/job_queue/test_job_queue_manager.py
  tests/unit_tests/c_wrappers/res/job_queue/test_job_queue_manager_torque.py
  tests/unit_tests/ensemble_evaluator/conftest.py
Labels: release-notes:skip

#5582 Turn off hypothesis timeouts always
  .github/workflows/check_old_parser.yml
  .github/workflows/coverage.yml
  .github/workflows/test_ert.yml
  ci/jenkins/testkomodo-ERT.sh
  ci/jenkins/testkomodo-repeat-flaky.sh
  ci/testkomodo.sh
  tests/conftest.py
Labels: release-notes:skip

#5585 Remove unused get_run_context
  src/ert/simulator/simulation_context.py
Labels: release-notes:skip

#5528 Update eclrun tests
  src/ert/shared/share/ert/forward-models/res/script/ecl_config.py
  tests/unit_tests/shared/share/test_ecl_run.py
  tests/unit_tests/shared/share/test_ecl_versioning_config.py
  tests/utils.py
Labels: release-notes:skip

#5596 Convert TransferFunction to dataclass
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
Labels: release-notes:maintenance

#5603 Change TransformationDirection.__str__ for mypy
  src/ert/data/record/_transformation.py
Labels: release-notes:skip

#5578 Add to_dict() for genKw
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/config/parameter_config.py
  src/ert/storage/local_experiment.py
Labels: maintenance

#5610 Pass Path to _generate_parameter_files
  src/ert/_c_wrappers/enkf/enkf_main.py
Labels: maintenance, release-notes:skip

#5574 Update intro to data types
  docs/reference/configuration/data_types.rst
Labels: documentation, release-notes:skip

#5611 Fix observations returned from dark storage
  src/ert/dark_storage/common.py
  src/ert/dark_storage/endpoints/records.py
  tests/performance_tests/test_dark_storage_performance.py
Labels: bug

#5638 Add a missing popd in testkomodo.sh
  ci/testkomodo.sh
Labels: bug, release-notes:skip

#5641 Accept only xr.Dataset in save_parameters
  src/ert/_c_wrappers/enkf/config/surface_config.py
  src/ert/analysis/_es_update.py
  src/ert/storage/local_ensemble.py
  src/ert/storage/migration/block_fs.py
Labels: release-notes:skip

#5589 Move random seed back in ert config
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/config/parameter_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_config.py
Labels: release-notes:skip

#5645 Add JobStatusType as public symbol as it is accessible through the BatchSimulator interface
  src/ert/__init__.py
Labels: release-notes:dependency

#5644 Remove no longer used queue functions
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/job_queue/job_node.cpp
Labels: release-notes:skip

#5646 Rephrase webviz-ert introduction in docs
  docs/getting_started/webviz-ert/webviz-ert.rst
Labels: release-notes:maintenance

#5643 Fix bug where log values were not included in facade function for gen kw
  src/ert/libres_facade.py
  tests/unit_tests/snapshots/test_libres_facade/test_gen_kw_collector/0/gen_kw_collector.csv
  tests/unit_tests/snapshots/test_libres_facade/test_load_gen_kw_not_sorted/gen_kw_unsorted
  tests/unit_tests/test_libres_facade.py
Labels: release-notes:bug-fix

#5651 Add mailmap to disambiguate emails
  .mailmap
Labels: configuration, release-notes:skip

#5635 Add flake8-bugbear to CI
  dev-requirements.txt
  setup.cfg
Labels: release-notes:misc

#5659 Remove new parser adapter
  src/ert/_c_wrappers/enkf/enkf_obs.py
Labels: release-notes:skip

#5661 Save parameter with .nc extension
  src/ert/_c_wrappers/enkf/config/field_config.py
  src/ert/storage/local_ensemble.py
  tests/unit_tests/storage/test_local_ensemble.py
Labels: release-notes:skip
