Repository equinor/ert, pull requests merged in 2023-03, with the labels that each got.

#4968 Move About to end of help menu
  src/ert/gui/main_window.py
Labels: release-notes:improvement

#4965 Show warning in suggestion dialog when GEN_DATA INPUT_FORMAT missing or unsupported.
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
Labels: release-notes:improvement

#4972 Remove duplicate LibresFacade from run_cli
  src/ert/cli/main.py
Labels: maintenance

#4963 Show error in suggester dialog when GEN_DATA RESULT_FILE is missing or malformed
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
Labels: release-notes:improvement

#4933 Add help buttons to suggester UI
  src/ert/gui/about_dialog.py
  src/ert/gui/main.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:improvement

#4987 Copying label confirmed with "check" icon instead of text
  src/ert/gui/ertwidgets/copyablelabel.py
Labels: release-notes:skip

#4995 Fix failed workflow jobs failing with unexpected exception, now warns and skips loading
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: release-notes:bug-fix

#4996 Fix failed workflow jobs failing with unexpected exception, now warns and skips loading
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: release-notes:bug-fix

#4998 Fix stop_long_running_keyword not being recognized
  src/clib/lib/config/config_keywords.cpp
  tests/test_config_parsing/config_dict_generator.py
Labels: release-notes:bug-fix

#4999 Fix stop_long_running_keyword not being recognized
  src/clib/lib/config/config_keywords.cpp
  tests/test_config_parsing/config_dict_generator.py
Labels: release-notes:bug-fix

#5003 Test QMessageBox text() so it works on mac as well
  tests/unit_tests/gui/test_main_window.py
Labels: maintenance

#5004 Reduce time-out in esmda_has_run so it quits earlier
  tests/unit_tests/gui/test_main_window.py
Labels: maintenance

#5006 Fix bug where time index was loaded incorrectly for prediction run
  src/clib/lib/enkf/summary.cpp
  src/clib/lib/enkf/time_map.cpp
  tests/unit_tests/c_wrappers/res/enkf/snapshots/test_summary_response/test_load_summary_response_restart_not_zero/summary_restart
  tests/unit_tests/c_wrappers/res/enkf/summary_response/PRED_RUN.SMSPEC
  tests/unit_tests/c_wrappers/res/enkf/summary_response/PRED_RUN.UNSMRY
  tests/unit_tests/c_wrappers/res/enkf/test_summary_response.py
Labels: release-notes:bug-fix

#4860 Modified the confusing prompt - existing runpath dialog
  src/ert/gui/simulation/simulation_panel.py
Labels: release-notes:improvement

#5009 Fix bug where undefined summary values were plotted
  src/clib/lib/enkf/summary.cpp
  src/clib/lib/python/enkf_fs_summary_data.cpp
Labels: release-notes:bug-fix

#4969 Add new parser which can be enabled through feature flag
  .github/workflows/check_new_parser.yml
  setup.py
  src/ert/_c_wrappers/enkf/config_keywords.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/enkf/lark_parser.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/util/substitution_list.py
  src/ert/cli/main.py
  src/ert/gui/main.py
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_queue_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:skip

#4989 Require parameters when using smoother simulation modes
  src/ert/cli/main.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/libres_facade.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:improvement

#4988 Increase robustness of restart run of es-mda
  docs/getting_started/gui/gui.rst
  docs/getting_started/gui/restart-es-mda.png
  src/ert/cli/model_factory.py
  src/ert/gui/ertwidgets/models/init_iter_value.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/shared/models/multiple_data_assimilation.py
  tests/unit_tests/cli/test_model_factory.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
Labels: release-notes:improvement

#5029 Silence warnings from lark parser
  src/ert/cli/main.py
  src/ert/gui/main.py
Labels: release-notes:skip

#5024 Handle cyclical includes in lark parser
  docs/reference/configuration/keywords.rst
  src/ert/_c_wrappers/enkf/lark_parser.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:skip

#5032 Fix false positive in environment variables change
  tests/conftest.py
Labels: bug, release-notes:skip

#4915 Use new IES API
  setup.py
  src/ert/analysis/_es_update.py
  src/ert/libres_facade.py
  src/ert/shared/models/iterated_ensemble_smoother.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/c_wrappers/res/enkf/test_row_scaling.py
Labels: release-notes:maintenance

#5051 Remove key concepts from documentation
  docs/getting_started/index.rst
  docs/getting_started/key_concepts.rst
Labels: release-notes:maintenance

#5040 Replace deprecated matplotlib layout function
  src/ert/gui/tools/plot/plot_widget.py
Labels: release-notes:skip

#5034 Enable workflow button when workflows available
  src/ert/gui/tools/workflows/workflows_tool.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:maintenance

#5042 Provide feedback if not valid weights provided for ES_MDA
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/shared/models/multiple_data_assimilation.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:improvement

#4631 Add snapshot assertion to es-mda cli test
  tests/unit_tests/cli/snapshots/test_integration_cli/test_es_mda/es_mda_integration_snapshot
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:maintenance

#5044 Initialize lark parser when module loads
  src/ert/_c_wrappers/enkf/lark_parser.py
Labels: release-notes:skip

#5054 Make qt gui main window tests more stable / less brittle
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/manage_cases/manage_cases_tool.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:skip

#5046 Remove define_args from ExtJob
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/ext_job.py
Labels: release-notes:skip

#5076 Remove duplicate installation from documentation
  docs/getting_started/setup.rst
  docs/index.rst
  docs/installation/index.rst
  docs/installation/installation_guide.rst
Labels: release-notes:maintenance

#5075 Make steplength settable again in IES
  src/ert/_c_wrappers/analysis/analysis_module.py
  src/ert/shared/models/iterated_ensemble_smoother.py
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:bug-fix

#5078 Make config warning the only category shown in GUI
  src/ert/gui/main.py
Labels: release-notes:skip

#5090 Refactor handling extjob creation in ErtConfig
  src/ert/_c_wrappers/enkf/ert_config.py
Labels: release-notes:skip

#5060 Describe squashing more precisely
  CONTRIBUTING.md
Labels: documentation, release-notes:skip

#5103 Mute test output from job_runner_performance
  tests/performance_tests/test_job_runner_performance.py
Labels: release-notes:skip

#5066 Verify if active realizations is less than minimum set
  src/ert/shared/models/base_run_model.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
  tests/unit_tests/models/test_base_run_model.py
Labels: release-notes:bug-fix

#5112 Backport: Fix bug where timed out realizations would be marked as success
  src/ert/_c_wrappers/job_queue/job_queue_node.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:bug-fix

#5091 Change saving gen_kw from single file to mulitple
  src/ert/storage/local_ensemble.py
Labels: release-notes:skip

#5110 Avoid Pandas deprecation warning on frame.append
  src/ert/data/loader.py
Labels: release-notes:skip

#5101 Reuse plugin manager rather than create new
  src/ert/__main__.py
  src/ert/cli/main.py
  src/ert/gui/main.py
  src/ert/gui/main_window.py
  src/ert/namespace.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#5116 Improve documentation for disable_monitoring
  src/ert/__main__.py
Labels: documentation, release-notes:misc

#5122 Fix typo paramerter -> parameter
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
Labels: release-notes:skip

#5111 Solve four pylint issues
  .pylintrc
  script/pylint
  src/ert/_c_wrappers/enkf/lark_parser.py
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  src/ert/shared/storage/extraction.py
  tests/unit_tests/data/test_measured_data.py
Labels: release-notes:skip

#5059 Refactor code in lark_parser, also fix define/include interactions
  src/ert/_c_wrappers/enkf/config_keywords.py
  src/ert/_c_wrappers/enkf/lark_parser.py
  src/ert/_c_wrappers/enkf/lark_parser_common.py
  tests/test_config_parsing/test_ert_config_parsing.py
  tests/unit_tests/c_wrappers/res/enkf/test_config_content_as_dict.py
Labels: release-notes:skip

#5126 Scale obs errors before outlier detection
  src/ert/analysis/_es_update.py
Labels: release-notes:bug-fix

#5102 Move storage meta data from ensemble -> experiment
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/field_config.cpp
  src/clib/lib/enkf/surface_config.cpp
  src/clib/lib/include/ert/enkf/field_config.hpp
  src/clib/lib/include/ert/enkf/surface_config.hpp
  src/ert/_c_wrappers/enkf/config/field_config.py
  src/ert/_c_wrappers/enkf/config/surface_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/analysis/_es_update.py
  src/ert/callbacks.py
  src/ert/cli/main.py
  src/ert/gui/ertwidgets/caselist.py
  src/ert/gui/main.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/libres_facade.py
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_runpath.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_export.py
  tests/unit_tests/c_wrappers/res/enkf/test_priors.py
  tests/unit_tests/c_wrappers/res/enkf/test_runpaths.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_gui_load.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:improvement

#5113 Fix bug where timed out realizations would be marked as success
  src/ert/_c_wrappers/job_queue/job_queue_node.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:bug-fix

#5140 Remove unused field export function
  src/ert/libres_facade.py
  src/ert/storage/local_ensemble.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_export.py
Labels: release-notes:breaking-change

#5163 Raise expection if no file for refcase
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
Labels: release-notes:bug-fix

#5166 Add timestamps to torque debug log statements
  src/clib/lib/job_queue/torque_driver.cpp
Labels: enhancement, release-notes:improvement

#5183 Fix issue with incorrectly generated dates
  tests/test_config_parsing/observations_generator.py
Labels: release-notes:skip

#5160 Validate distribution parameters
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
Labels: bug, release-notes:bug-fix

#5181 Refresh storage when loading from api
  src/ert/dark_storage/enkf.py
Labels: release-notes:skip

#5149 Update running workflows after merge of storage branch
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/job_queue/ert_script.py
  src/ert/_c_wrappers/job_queue/external_ert_script.py
  src/ert/_c_wrappers/job_queue/workflow.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  src/ert/_c_wrappers/job_queue/workflow_runner.py
  src/ert/data/_measured_data.py
  src/ert/gui/tools/plugins/plugin.py
  src/ert/gui/tools/plugins/plugin_runner.py
  src/ert/gui/tools/workflows/run_workflow_widget.py
  src/ert/gui/tools/workflows/workflows_tool.py
  src/ert/shared/models/ensemble_experiment.py
  src/ert/shared/models/ensemble_smoother.py
  src/ert/shared/models/iterated_ensemble_smoother.py
  src/ert/shared/models/multiple_data_assimilation.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow_job.py
  tests/unit_tests/cli/test_model_hook_order.py
Labels: release-notes:skip

#5182 Solve race condition in qstat_proxy.sh
  src/ert/_c_wrappers/job_queue/qstat_proxy.sh
  tests/unit_tests/c_wrappers/res/job_queue/test_ert_qstat_proxy.py
Labels: release-notes:bug-fix
