Repository equinor/ert, pull requests merged in 2023-12, with the labels that each got.

#6731 Raise error on invalid use of runpath placeholders
  docs/reference/configuration/keywords.rst
  src/ert/config/model_config.py
  tests/unit_tests/test_run_path_creation.py
Labels: release-notes:maintenance

#6730 Decrease timeout when connecting to websocket
  src/ert/ensemble_evaluator/sync_ws_duplexer.py
Labels: release-notes:skip

#6754 Revert ensemble size for Single Test Run
  src/ert/cli/model_factory.py
Labels: release-notes:bug-fix

#6688 Add experiment name
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/gui/simulation/single_test_run_panel.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  src/ert/storage/migration/experiment_id.py
Labels: release-notes:new-feature

#6750 Remove unused keyword ANALYSIS_SELECT
  docs/reference/configuration/keywords.rst
  src/ert/config/analysis_config.py
  src/ert/config/parsing/config_keywords.py
  src/ert/config/parsing/config_schema.py
  src/ert/config/parsing/config_schema_deprecations.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/config/config_dict_generator.py
Labels: release-notes:maintenance

#6765 Fix restart button
  src/ert/ensemble_evaluator/_builder/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/gui/test_restart_ensemble_experiment.py
Labels: release-notes:bug-fix

#6763 Fix restart button
  src/ert/ensemble_evaluator/_builder/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/gui/test_restart_ensemble_experiment.py
Labels: release-notes:bug-fix

#6531 Add unit test for memory usage on run_dialog
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: documentation

#6777 Fix bug where some parameters were not present in child ensemble
  src/ert/analysis/_es_update.py
  src/ert/config/ext_param_config.py
  src/ert/config/field.py
  src/ert/config/gen_kw_config.py
  src/ert/libres_facade.py
  src/ert/storage/local_ensemble.py
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:bug-fix

#6745 Add GitHub workflow for benchmarking
  .github/workflows/benchmark.yml
  pyproject.toml
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:skip

#6682 Document Adaptive Localization
  .github/workflows/build_and_test.yml
  docs/conf.py
  docs/getting_started/howto/adaptive_localization.ipynb
  docs/getting_started/howto/ert_screenshot_adaptive_loc.png
  docs/index.rst
  pyproject.toml
Labels: documentation, release-notes:skip

#6786 Let publisher_task exit gracefully when nothing to do
  src/ert/scheduler/scheduler.py
Labels: release-notes:skip, scheduler

#6793 Raise if params not registered are saved
  src/ert/storage/local_ensemble.py
  tests/unit_tests/config/test_surface_config.py
  tests/unit_tests/storage/migration/test_block_fs_snake_oil.py
  tests/unit_tests/storage/test_local_ensemble.py
Labels: bug, release-notes:skip

#6804 Only perturb observations once
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6805 Add fixture for running tests with scheduler and job queue
  pyproject.toml
  tests/conftest.py
Labels: testing

#5675 Change BaseRunModel to throw an exception with stacktrace
  src/ert/cli/main.py
  src/ert/gui/tools/load_results/load_results_panel.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/shared/test_log_capture.py
Labels: release-notes:skip

#6747 Fix bug in run analysis tool
  src/ert/gui/ertwidgets/statusdialog.py
  src/ert/gui/tools/run_analysis/run_analysis_panel.py
  src/ert/gui/tools/run_analysis/run_analysis_tool.py
Labels: bug, release-notes:bug-fix

#6782 Add retry loop into the scheduler handling resubmitting when running state failed
  src/ert/scheduler/driver.py
  src/ert/scheduler/job.py
  src/ert/scheduler/local_driver.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: improvement, scheduler

#6817 Fix off-by-one error in split_by_batchsize
  src/ert/analysis/_es_update.py
Labels: bug, release-notes:bug-fix

#6788 Implement MockDriver
  src/ert/async_utils.py
  src/ert/scheduler/driver.py
  src/ert/scheduler/local_driver.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/conftest.py
  tests/unit_tests/scheduler/test_local_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip, scheduler

#6812 Test unit_tests/cli with queue and scheduler
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:skip, scheduler

#6792 Raise error when loading param via response api
  src/ert/storage/local_ensemble.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/storage/migration/test_block_fs_snake_oil.py
  tests/unit_tests/storage/test_local_ensemble.py
  tests/unit_tests/test_libres_facade.py
Labels: bug, release-notes:skip

#6816 Implement adaptive batch size
  pyproject.toml
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6815 Make sure some, but not all parameters were updated.
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:skip

#6826 Upgrade publish job
  .github/workflows/build_and_test.yml
Labels: release-notes:maintenance

#6831 Remove recalculation of mean and std in misfit
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6807 Add scheduler unit test for propagation of dispatch information to jobs file
  src/ert/scheduler/local_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#6819 Mark status tests for testing with Scheduler
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:skip

#6787 Have integration tests run with both scheduler and job queue
  tests/integration_tests/analysis/__init__.py
  tests/integration_tests/analysis/snapshots/test_es_update/test_update_only_using_subset_observations/0/update_log
  tests/integration_tests/analysis/snapshots/test_es_update/test_update_report/0-False/update_log
  tests/integration_tests/analysis/snapshots/test_es_update/test_update_report/0-True/update_log
  tests/integration_tests/analysis/test_adaptive_localization.py
  tests/integration_tests/analysis/test_es_update.py
  tests/integration_tests/cli/__init__.py
  tests/integration_tests/cli/snapshots/test_integration_cli/test_es_mda/False/es_mda_integration_snapshot
  tests/integration_tests/cli/snapshots/test_integration_cli/test_es_mda/True/es_mda_integration_snapshot
  tests/integration_tests/cli/snapshots/test_integration_cli/test_es_mda/es_mda_integration_snapshot
  tests/integration_tests/cli/test_integration_cli.py
  tests/integration_tests/job_queue/__init__.py
  tests/integration_tests/job_queue/test_lsf_driver.py
  tests/integration_tests/shared/__init__.py
  tests/integration_tests/shared/share/__init__.py
  tests/integration_tests/shared/share/test_shell.py
  tests/integration_tests/status/__init__.py
  tests/integration_tests/status/test_tracking_integration.py
  tests/integration_tests/storage/__init__.py
  tests/integration_tests/storage/test_field_parameter.py
  tests/integration_tests/storage/test_parameter_sample_types.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/analysis/test_misfit_preprocessor.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/cli/test_model_factory.py
  tests/unit_tests/shared/share/test_shell.py
  tests/unit_tests/storage/test_field_parameter.py
  tests/unit_tests/storage/test_parameter_sample_types.py
Labels: release-notes:skip

#6834 Rewrite doc for MAX_RUNNING
  docs/reference/configuration/queue.rst
Labels: documentation, release-notes:skip

#6840 Move check for obs in to loading function
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6842 Remove global scaling from IES
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6803 Test ensemble_evaluator with new scheduler
  src/ert/scheduler/job.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
Labels: release-notes:skip, scheduler

#6835 New design for the "Some problems detected" window
  src/ert/gui/ertwidgets/__init__.py
  src/ert/gui/ertwidgets/suggestor_message.py
  src/ert/gui/main.py
  src/ert/gui/resources/gui/img/bell.svg
  src/ert/gui/resources/gui/img/error.svg
  src/ert/gui/resources/gui/img/warning.svg
  src/ert/gui/resources/gui/img/warning_bgcircle.svg
  src/ert/gui/suggestor/__init__.py
  src/ert/gui/suggestor/_colors.py
  src/ert/gui/suggestor/_suggestor_message.py
  src/ert/gui/suggestor/suggestor.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:improvement

#6847 Update adloc docs
  docs/getting_started/howto/adaptive_localization.ipynb
Labels: documentation, release-notes:skip

#6860 Instruct how to activate adloc via config
  docs/getting_started/howto/adaptive_localization.ipynb
Labels: documentation, release-notes:skip
