Repository equinor/ert, pull requests merged in 2023-02, with the labels that each got.

#4767 Stop substituting in FORWARD_MODEL argument names version-4.2 backport
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/config/config_parser.cpp
  src/clib/lib/config/config_schema_item.cpp
  src/clib/lib/include/ert/config/config_schema_item.hpp
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: release-notes:bug-fix

#4768 Add log statement for new forward model behavior
  src/ert/_c_wrappers/job_queue/forward_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: release-notes:skip

#4780 Verify that refcase is found for history observations
  src/clib/lib/enkf/enkf_obs.cpp
  src/ert/_c_wrappers/enkf/enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
Labels: release-notes:bug-fix

#4763 Verify that refcase is found for history observations
  src/clib/lib/enkf/enkf_obs.cpp
  src/ert/_c_wrappers/enkf/enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
Labels: release-notes:bug-fix

#4783 Make private arg log message happen only once.
  src/ert/_c_wrappers/job_queue/forward_model.py
Labels: release-notes:skip

#4785 Make the private arg log quieter
  src/ert/_c_wrappers/job_queue/forward_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: release-notes:skip

#4790 Fix creation of paths in subfolders for outfile in GEN_KW
  src/clib/lib/config/config_keywords.cpp
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/test_integration_config.py
Labels: release-notes:skip

#4791 Fix creation of paths in subfolders for outfile in GEN_KW, backport to 4.2
  src/clib/lib/config/config_keywords.cpp
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/test_integration_config.py
Labels: release-notes:bug-fix

#4789 Fix run_workflow_widget
  src/ert/gui/tools/workflows/run_workflow_widget.py
  tests/unit_tests/gui/test_gui_load.py
Labels: bug, release-notes:skip

#4810 Fix __all__ not being a list of strings
  src/ert/_c_wrappers/__init__.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/util/__init__.py
  src/ert/gui/tools/__init__.py
  src/ert/gui/tools/export/__init__.py
  src/ert/gui/tools/file/__init__.py
  src/ert/gui/tools/manage_cases/__init__.py
  src/ert/gui/tools/plot/widgets/__init__.py
  src/ert/gui/tools/run_analysis/__init__.py
  src/ert/gui/tools/workflows/__init__.py
  src/ert/shared/ide/keywords/data/__init__.py
Labels: release-notes:skip

#4814 Use string for __all__ in hook_specifications
  src/ert/shared/plugins/hook_specifications/__init__.py
Labels: release-notes:skip

#4739 Remove UPDATE_PATH keyword and simplify SETENV behaviour
  docs/reference/configuration/keywords.rst
  src/_ert_job_runner/runner.py
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/job_queue/environment_varlist.hpp
  src/clib/lib/include/ert/res_util/res_env.hpp
  src/clib/lib/job_queue/environment_varlist.cpp
  src/clib/lib/res_util/res_env.cpp
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/job_queue/environment_varlist.py
  src/ert/_c_wrappers/job_queue/forward_model.py
  tests/unit_tests/c_wrappers/job_runner/test_jobmanager.py
  tests/unit_tests/c_wrappers/res/job_queue/test_forward_model_formatted_print.py
  tests/unit_tests/c_wrappers/test_integration_config.py
Labels: payback, release-notes:user-impact

#4781 Add runpath and jobname to substitution list before job args validation
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/enkf/runpaths.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_runpaths.py
Labels: release-notes:maintenance

#4820 Fix typing storage service to new version of mypy
  src/ert/services/_storage_main.py
Labels: release-notes:skip

#4819 Backport fix of forward model
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:bug-fix

#4818 Fix a bug where job_name did not get substituted with DEFINEs
  src/ert/_c_wrappers/enkf/res_config.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:bug-fix

#4817 Only pass summary keys as list from enkf_fs
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/dark_storage/common.py
  src/ert/dark_storage/endpoints/records.py
  src/ert/libres_facade.py
  tests/unit_tests/c_wrappers/res/enkf/test_summary_key_set.py
Labels: release-notes:breaking-change

#4011 Remove upper version-bound on beartype
  setup.py
Labels: release-notes:maintenance

#4815 Remove unused arguments in setup_suggester
  src/ert/gui/main.py
Labels: release-notes:skip

#4826 Fix progress bar exceeding 100 percent
  src/ert/ensemble_evaluator/evaluator_tracker.py
  src/ert/gui/simulation/run_dialog.py
  tests/unit_tests/ensemble_evaluator/test_evaluator_tracker.py
Labels: release-notes:bug-fix

#4769 Make field parameter self contained in enkf_fs
  src/ert/_c_wrappers/enkf/config/field_config.py
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/enums/enkf_truncation_type.py
  src/ert/analysis/_es_update.py
  src/ert/ensemble_evaluator/callbacks.py
  src/ert/libres_facade.py
  src/ert/storage/__init__.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_export.py
Labels: release-notes:breaking-change

#4829 Dont overwrite prior in ensemble_experiment run model
  src/ert/shared/models/ensemble_experiment.py
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:skip

#4825 Fix issue with env variables not being inserted in forward model jobs
  src/clib/lib/config/config_parser.cpp
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
Labels: release-notes:bug-fix

#4806 Refactor Forward Model into Res Config
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/cli/main.py
  src/ert/gui/ertwidgets/models/ertsummary.py
  src/ert/gui/main.py
  src/ert/shared/models/base_run_model.py
  tests/test_config_parsing/test_res_config.py
  tests/unit_tests/c_wrappers/job_runner/test_jobmanager.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/test_forward_model_json.py
  tests/unit_tests/gui/ertwidgets/models/test_ertsummary.py
Labels: release-notes:maintenance

#4830 Reduce memory usage in parameter update step
  src/ert/analysis/_es_update.py
  tests/unit_tests/analysis/test_es_update.py
Labels: bug

#4844 Add logging when workflow is starting
  src/ert/_c_wrappers/job_queue/workflow.py
Labels: enhancement, release-notes:new-feature

#4848 Fix errors in workflow referring to temporary file
  src/ert/_c_wrappers/job_queue/workflow.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
Labels: release-notes:skip

#4849 Fix a crash occurring when the run dialog was closed before the plot window
  src/ert/gui/main.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/gui/tools/plot/plot_tool.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:bug-fix

#4857 Extend linting to test-data directory
  .github/workflows/style.yml
  pyproject.toml
  test-data/configuration_tests/input/jobs/snake_oil_simulator.py
  test-data/poly_template/poly_eval.py.j2
  test-data/snake_oil_field/jobs/snake_oil_simulator.py
Labels: release-notes:skip

#4130 Use the Self type to resolve typing problems with `ert.ensemble_builder`
  setup.py
  src/_ert_job_runner/client.py
  src/ert/ensemble_evaluator/_builder/_ensemble_builder.py
  src/ert/ensemble_evaluator/_builder/_io_.py
  src/ert/ensemble_evaluator/_builder/_io_map.py
  src/ert/ensemble_evaluator/_builder/_job.py
  src/ert/ensemble_evaluator/_builder/_realization.py
  src/ert/ensemble_evaluator/_builder/_stage.py
  src/ert/shared/models/base_run_model.py
Labels: release-notes:skip

#4836 Add more explanation to the bad refcase error
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
Labels: release-notes:improvement

#4743 Move res_config to ert_config, and simplify code. Add from_file and from_dict functions
  src/ert/__main__.py
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/forward_model.py
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/cli/main.py
  src/ert/dark_storage/enkf.py
  src/ert/gui/main.py
  src/ert/libres_facade.py
  src/ert/simulator/batch_simulator.py
  src/ert/simulator/simulation_context.py
  tests/conftest.py
  tests/performance_tests/enkf/test_enkf_fs_performance.py
  tests/performance_tests/enkf/test_load_state.py
  tests/performance_tests/test_dark_storage_performance.py
  tests/test_config_parsing/test_defines.py
  tests/test_config_parsing/test_ensemble_config.py
  tests/test_config_parsing/test_num_cpu.py
  tests/test_config_parsing/test_queue_config.py
  tests/test_config_parsing/test_res_config.py
  tests/test_config_parsing/test_substitution_list.py
  tests/test_config_parsing/test_suggester.py
  tests/unit_tests/all/plugins/test_parameter_disable.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/c_wrappers/job_runner/test_jobmanager.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_fs_manager.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_runpath.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_load_forward_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_priors.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_run_path_creation.py
  tests/unit_tests/c_wrappers/res/enkf/test_runpaths.py
  tests/unit_tests/c_wrappers/res/enkf/test_summary_key_set.py
  tests/unit_tests/c_wrappers/res/enkf/test_summary_observation.py
  tests/unit_tests/c_wrappers/res/test_forward_model_json.py
  tests/unit_tests/c_wrappers/test_integration_config.py
  tests/unit_tests/cli/test_cli_workflow.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/data/test_integration_data.py
  tests/unit_tests/gui/test_gui_load.py
  tests/unit_tests/gui/tools/test_case_tool.py
  tests/unit_tests/shared/share/test_shell.py
  tests/unit_tests/simulator/test_batch_sim.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:skip

#4872 Fix errors in workflow referring to temporary file
  src/ert/_c_wrappers/job_queue/workflow.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
Labels: release-notes:skip

#4875 Raise ConfigValidation exception on invalid arguments for analysis module
  src/ert/_c_wrappers/analysis/analysis_module.py
  tests/unit_tests/c_wrappers/res/analysis/test_analysis_module.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
Labels: release-notes:maintenance

#4877 Fix use of non imported ResConfig, and use LibresFacade.from_config_file instead
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:skip

#4796 Allow each realization to have different time map
  src/ert/_c_wrappers/enkf/enkf_fs.py
  src/ert/analysis/_es_update.py
  src/ert/storage/__init__.py
  tests/unit_tests/scenarios/__init__.py
  tests/unit_tests/scenarios/test_summary_response.py
  tests/unit_tests/snapshots/test_libres_facade/test_summary_collector/summary_collector_1.csv
Labels: release-notes:improvement

#4671 Write forward model stdout and stderr to logs/
  src/ert/shared/share/ert/forward-models/old_style/CAREFUL_COPY_FILE
  src/ert/shared/share/ert/forward-models/old_style/COPY_DIRECTORY
  src/ert/shared/share/ert/forward-models/old_style/COPY_FILE
  src/ert/shared/share/ert/forward-models/old_style/DELETE_DIRECTORY
  src/ert/shared/share/ert/forward-models/old_style/DELETE_FILE
  src/ert/shared/share/ert/forward-models/old_style/MAKE_DIRECTORY
  src/ert/shared/share/ert/forward-models/old_style/MAKE_SYMLINK
  src/ert/shared/share/ert/forward-models/old_style/MOVE_FILE
  src/ert/shared/share/ert/forward-models/old_style/SYMLINK
Labels: release-notes:maintenance

#4878 Fix RunDialog unintentionally becoming modal
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/simulation_panel.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#4871 Improved error message for incorrect REFCASE
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
Labels: release-notes:skip

#4862 Add error message to replace PORTABLE_EXE with EXECUTABLE
  src/ert/_c_wrappers/job_queue/ext_job.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
Labels: release-notes:improvement

#4883 Backport log message fix
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/cli/main.py
  src/ert/gui/main.py
Labels: release-notes:skip

#4882 Fix logging messages that failed with telemetry
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/cli/main.py
  src/ert/gui/main.py
Labels: release-notes:skip

#4885 Fix flaky failure of gui tests
  tests/unit_tests/gui/test_gui_load.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:skip

#4838 Catch exceptions thrown in forward model callbacks
  src/ert/ensemble_evaluator/callbacks.py
Labels: release-notes:improvement

#4891 Remove unused ert.data functions
  src/ert/data/__init__.py
  src/ert/data/record/_record.py
  src/ert/data/record/_transformation.py
Labels: release-notes:skip

#4905 Improved error message on time mismatch in refcase
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
  tests/unit_tests/c_wrappers/res/enkf/test_summary_observation.py
Labels: release-notes:improvement

#4908 Improve error message in ExtJobInvalidArgsException
  src/ert/_c_wrappers/job_queue/ext_job.py
Labels: release-notes:skip

#4874 Update case info tab after case is initialized
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  tests/unit_tests/gui/tools/test_case_tool.py
Labels: release-notes:bug-fix

#4906 Improve refcase time mismatch error message
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
  tests/unit_tests/c_wrappers/res/enkf/test_summary_observation.py
Labels: release-notes:improvement

#4911 Improve error message for invalid job args
  src/ert/_c_wrappers/job_queue/ext_job.py
Labels: release-notes:skip

#4887 Make get_machine_name predictive for multiple PTR
  src/ert/ensemble_evaluator/config.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator_config.py
Labels: release-notes:bug-fix

#4925 Remove res_config
  src/ert/__main__.py
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/res_config.py
  src/ert/_c_wrappers/job_queue/queue.py
  src/ert/cli/main.py
  src/ert/gui/main.py
  src/ert/services/storage_service.py
  src/ert/simulator/batch_simulator.py
  src/ert/simulator/batch_simulator_context.py
  tests/test_config_parsing/test_defines.py
  tests/test_config_parsing/test_num_cpu.py
  tests/test_config_parsing/test_res_config.py
  tests/test_config_parsing/test_substitution_list.py
  tests/unit_tests/all/plugins/test_export_runpath.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_fs_manager.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_runpath.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_load_forward_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_queue_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_run_path_creation.py
  tests/unit_tests/c_wrappers/res/enkf/test_runpaths.py
  tests/unit_tests/c_wrappers/res/enkf/test_summary_key_set.py
  tests/unit_tests/c_wrappers/res/enkf/test_summary_observation.py
  tests/unit_tests/data/test_integration_data.py
  tests/unit_tests/gui/test_gui_load.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/shared/share/test_shell.py
  tests/unit_tests/shared/test_main_entry.py
  tests/unit_tests/simulator/test_batch_sim.py
  tests/unit_tests/simulator/test_simulation_context.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:skip

#4935 Pin conan<2 and conan-cmake=0.18.1
  .github/workflows/annotate_cpp.yml
  .github/workflows/build.yml
  ci/jenkins/test_libres_jenkins.sh
  pyproject.toml
  src/clib/CMakeLists.txt
Labels: release-notes:skip

#4930 Show a warning when there are duplicate forward model jobs
  src/ert/_c_wrappers/enkf/ert_config.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:user-impact

#4932 Workflows with errors are no longer loaded, before they would give error when run
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/workflow.py
  test-data/snake_oil_structure/ert/bin/workflows/MAGIC_PRINT
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:user-impact

#4919 Indicate severity in the suggestor list of messages
  src/ert/gui/ertwidgets/__init__.py
  src/ert/gui/ertwidgets/suggestor_message.py
  src/ert/gui/main.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:improvement

#4942 Replace button selection in gui tests
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#4950 Rename SUGGESTION label to DEPRECATION also update colour to yellow.
  src/ert/gui/ertwidgets/suggestor_message.py
  src/ert/gui/main.py
Labels: release-notes:improvement

#4951 Improve ext job validation message
  src/ert/_c_wrappers/job_queue/ext_job.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:skip

#4953 Made the Runpath text in the GUI is selectable, and added a copy button
  src/ert/gui/ertwidgets/copyablelabel.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/simulation_config_panel.py
  src/ert/gui/simulation/single_test_run_panel.py
  tests/unit_tests/gui/ertwidgets/test_copyablelabel.py
Labels: release-notes:improvement

#4961 Fix bug where inversion type could not be set via GUI
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
  src/ert/gui/ertwidgets/closabledialog.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  tests/unit_tests/gui/ertwidgets/test_analysismodulevariablespanel.py
  tests/unit_tests/gui/test_main_window.py
Labels: bug, release-notes:bug-fix

#4778 Add test for field parameter
  dev-requirements.txt
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:skip

#4974 Pass in lower-case fformat when saving grid to file
  src/ert/storage/local_ensemble.py
Labels: bug
