Repository equinor/ert, pull requests merged in 2023-05, with the labels that each got.

#5317 Remove SCHEDULE_PREDICTION_FILE & GEN_KW PRED
  docs/reference/configuration/keywords.rst
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/parsing/config_keywords.py
  src/ert/shared/hook_implementations/workflows/__init__.py
  test-data/configuration_tests/ecl_config.ert
  test-data/configuration_tests/ensemble_config.ert
  tests/test_config_parsing/test_suggester.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
Labels: release-notes:maintenance

#5318 Update current case when running run models
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/shared/models/iterated_ensemble_smoother.py
Labels: bug

#5324 Fix possible error source in qstat-proxy script
  src/ert/_c_wrappers/job_queue/qstat_proxy.sh
Labels: release-notes:skip

#5321 Add some more logging
  src/ert/_c_wrappers/enkf/config/field_config.py
  src/ert/_c_wrappers/enkf/config/surface_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/analysis/_es_update.py
  src/ert/logging/logger.conf
Labels: release-notes:improvement

#5325 Reformat lint cli message
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/parsing/config_errors.py
  src/ert/parsing/config_keywords.py
  src/ert/parsing/error_info.py
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_ert_config_parsing.py
  tests/test_config_parsing/test_forward_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
Labels: release-notes:skip

#5313 Fix some function names
  src/ert/dark_storage/common.py
  src/ert/dark_storage/endpoints/records.py
  src/ert/libres_facade.py
  src/ert/shared/hook_implementations/workflows/export_misfit_data.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  src/ert/storage/local_ensemble.py
Labels: release-notes:maintenance

#5335 Refactor _generate_gen_kw_parameter_file
  src/ert/_c_wrappers/enkf/enkf_main.py
Labels: release-notes:maintenance

#5338 Silence flake8 W503 and E203
  .github/workflows/annotate_python.yml
Labels: release-notes:skip

#5332 Handle errors in _parse_file
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip

#5315 Add error collection to handle_includes
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip

#5336 Localize errors in workflow job and workflow job directory
  src/ert/_c_wrappers/enkf/ert_config.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip

#5328 Remove unused stages from RealizationBuilder
  src/ert/ensemble_evaluator/_builder/_realization.py
Labels: maintenance, release-notes:skip

#5349 Fix new parser not striping empty spaces form forward model arguments if present.
  src/ert/parsing/lark_parser.py
Labels: release-notes:skip

#5351 Remove unused RecordCollection
  src/ert/data/__init__.py
  src/ert/data/record/_record.py
Labels: release-notes:skip

#5316 Move observation handling functions into python
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
  src/clib/lib/include/ert/enkf/enkf_obs.hpp
  src/clib/lib/include/ert/enkf/obs_vector.hpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_obs.cpp
  src/clib/old_tests/enkf/test_enkf_obs_vector.cpp
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/observations/obs_vector.py
  tests/test_config_parsing/test_enkf_obs_parsing.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/c_wrappers/res/enkf/test_summary_observation.py
  tests/unit_tests/data/test_integration_data.py
  tests/unit_tests/test_libres_facade.py
Labels: release-notes:skip

#5358 Backport to v4.5: Fix possible error source in qstat-proxy script
  src/ert/_c_wrappers/job_queue/qstat_proxy.sh
Labels: release-notes:bug-fix

#5360 Exclude TYPE_CHECKING imports from coverage
  .coveragerc
Labels: release-notes:skip

#5251 Lower memory usage significantly when handling fields/grids
  .mypy-strict.ini
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/ert/_c_wrappers/enkf/config/field_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/analysis/_es_update.py
  src/ert/libres_facade.py
  src/ert/storage/field_utils/__init__.py
  src/ert/storage/field_utils/field_utils.py
  src/ert/storage/field_utils/grdecl_io.py
  src/ert/storage/field_utils/roff_io.py
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_field_export.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/storage/test_field_utils.py
  tests/unit_tests/storage/test_local_ensemble.py
Labels: release-notes:improvement

#5373 Fix an issue with forward_model adding
  src/ert/parsing/file_context_token.py
  tests/test_config_parsing/test_forward_model.py
Labels: release-notes:skip

#5366 Fix gui error message from observations
  src/clib/lib/enkf/enkf_obs.cpp
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/parsing/config_errors.py
  tests/test_config_parsing/test_ert_config_parsing.py
Labels: release-notes:skip

#5377 Reduce the amount of test runners
  .github/workflows/build.yml
Labels: release-notes:skip

#4986 Add progress updates to Run analysis
  src/ert/analysis/__init__.py
  src/ert/analysis/_es_update.py
  src/ert/gui/ertwidgets/closabledialog.py
  src/ert/gui/ertwidgets/statusdialog.py
  src/ert/gui/tools/run_analysis/__init__.py
  src/ert/gui/tools/run_analysis/run_analysis_tool.py
  src/ert/libres_facade.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/gui/run_analysis/test_run_analysis.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
Labels: release-notes:improvement

#5376 Remove superfluous code in test
  tests/unit_tests/c_wrappers/res/enkf/test_load_forward_model.py
Labels: release-notes:skip

#5379 Fix warning message for workflows
  src/ert/_c_wrappers/enkf/ert_config.py
  tests/test_config_parsing/test_ert_config_parsing.py
Labels: release-notes:skip

#5381 Use np.loadtxt instead of open() to load gen_data
  src/ert/_c_wrappers/enkf/enkf_state.py
Labels: release-notes:skip

#5386 Filter away expected warnings from running tests
  tests/test_config_parsing/test_enkf_obs_parsing.py
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/data/test_integration_data.py
Labels: release-notes:skip

#5394 [BACKPORT] Add config path and file name to jobs.json
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ert_config.py
  tests/unit_tests/c_wrappers/job_runner/test_jobmanager.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
  tests/unit_tests/c_wrappers/res/test_forward_model_json.py
Labels: release-notes:new-feature

#5147 Add test for memory usage on smoother
  dev-requirements.txt
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:skip

#5396 ECLBASE now behaves separately from JOBNAME
  docs/reference/configuration/keywords.rst
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/enkf_state.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/enkf/ert_run_context.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/run_arg.py
  src/ert/_c_wrappers/enkf/runpaths.py
  src/ert/simulator/simulation_context.py
  test-data/snake_oil_field/snake_oil.ert
  test-data/snake_oil_field/snake_oil_field.ert
  test-data/snake_oil_field/snake_oil_surface.ert
  tests/test_config_parsing/test_ert_config_parsing.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_main.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_sim_model.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_run_context.py
  tests/unit_tests/c_wrappers/res/enkf/test_runpaths.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:user-impact

#5388 Move testkomodo.sh to new location
  ci/testkomodo.sh
Labels: release-notes:skip

#5408 Add base surface metadata into SurfaceConfig
  src/ert/_c_wrappers/enkf/config/surface_config.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
Labels: maintenance, release-notes:skip

#5414 Change to a faster timeout for a timeout test
  tests/unit_tests/services/test_base_service.py
Labels: release-notes:skip

#5417 Explicitly use mixed format when converting to dates, avoiding warning
  src/ert/gui/tools/plot/plot_api.py
Labels: release-notes:maintenance

#5413 Use cpp classes for conf
  src/clib/lib/config/conf.cpp
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/include/ert/config/conf.hpp
  src/clib/lib/include/ert/enkf/enkf_obs.hpp
  src/clib/tests/enkf/enkf_obs_paths_detailed.cpp
Labels: release-notes:skip

#5421 Fix invalid queue_option potentially being unbound
  src/ert/_c_wrappers/enkf/ert_config.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip

#5344 Refactor GEN_DATA and SUMMARY configuration
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/gen_common.cpp
  src/clib/lib/enkf/gen_data_config.cpp
  src/clib/lib/enkf/gen_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
  src/clib/lib/enkf/summary_config.cpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/enkf/enkf_obs.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/gen_common.hpp
  src/clib/lib/include/ert/enkf/gen_data_config.hpp
  src/clib/lib/include/ert/enkf/gen_obs.hpp
  src/clib/lib/include/ert/enkf/obs_vector.hpp
  src/clib/lib/include/ert/enkf/summary_config.hpp
  src/clib/lib/include/ert/enkf/summary_obs.hpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_gen_data_config.cpp
  src/clib/old_tests/enkf/test_obs_vector.cpp
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/config/gen_data_config.py
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/config/summary_config.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/enkf_state.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/enums/__init__.py
  src/ert/_c_wrappers/enkf/enums/gen_data_file_type_enum.py
  src/ert/_c_wrappers/enkf/observations/gen_observation.py
  src/ert/_c_wrappers/enkf/observations/obs_vector.py
  src/ert/libres_facade.py
  src/ert/simulator/batch_simulator.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_data_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_summary_config.py
  tests/unit_tests/c_wrappers/res/enkf/data/test_enkf_config_node.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_simulation_batch.py
Labels: release-notes:maintenance

#5422 Move ert.shared.ide to ert.validation
  src/ert/__main__.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/tools/load_results/load_results_panel.py
  src/ert/shared/ide/__init__.py
  src/ert/shared/ide/keywords/__init__.py
  src/ert/shared/ide/keywords/data/__init__.py
  src/ert/validation/__init__.py
  src/ert/validation/argument_definition.py
  src/ert/validation/integer_argument.py
  src/ert/validation/number_list_string_argument.py
  src/ert/validation/proper_name_argument.py
  src/ert/validation/proper_name_format_argument.py
  src/ert/validation/range_string_argument.py
  src/ert/validation/validation_status.py
  tests/unit_tests/gui/ide/test_integer_argument.py
  tests/unit_tests/gui/ide/test_proper_name_argument.py
  tests/unit_tests/gui/ide/test_proper_name_format_argument.py
  tests/unit_tests/gui/ide/test_range_string_argument.py
Labels: release-notes:skip

#5419 Remove ext job validation
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  tests/test_config_parsing/test_forward_model.py
Labels: release-notes:skip

#5430 Remove unused path_fmt
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/job_queue/job_queue.hpp
  src/clib/lib/include/ert/res_util/path_fmt.hpp
  src/clib/lib/res_util/path_fmt.cpp
Labels: release-notes:skip

#5429 Use qpa platform minimal
  .github/workflows/check_old_parser.yml
  .github/workflows/coverage.yml
  .github/workflows/test_ert.yml
  tests/conftest.py
Labels: release-notes:skip

#5365 Refactor & use new parser for workflow jobs
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  src/ert/_c_wrappers/job_queue/workflow_runner.py
  src/ert/gui/main.py
  src/ert/parsing/__init__.py
  src/ert/parsing/config_keywords.py
  src/ert/parsing/config_schema.py
  src/ert/parsing/config_schema_item.py
  src/ert/parsing/context_values.py
  src/ert/parsing/lark_parser.py
  src/ert/parsing/schema_dict.py
  src/ert/parsing/schema_item_type.py
  src/ert/parsing/types.py
  src/ert/parsing/workflow_job_keywords.py
  src/ert/parsing/workflow_job_schema.py
  tests/unit_tests/c_wrappers/res/enkf/test_config_content_as_dict.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow_job.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow_runner.py
Labels: release-notes:skip

#5437 Remove print statement from make_poly_example
  tests/performance_tests/performance_utils.py
Labels: release-notes:skip

#5427 Make enkf_obs python only
  src/clib/lib/analysis/update.cpp
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/include/ert/enkf/enkf_obs.hpp
  src/clib/tests/enkf/enkf_obs_paths_detailed.cpp
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/libres_facade.py
  src/ert/shared/storage/extraction.py
  tests/test_config_parsing/test_enkf_obs_parsing.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/data/test_integration_data.py
Labels: release-notes:skip

#5439 Refactor gen_obs extraction of observation values
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/gen_common.cpp
  src/clib/lib/enkf/gen_obs.cpp
  src/clib/lib/include/ert/enkf/gen_common.hpp
  src/clib/lib/include/ert/enkf/gen_obs.hpp
  src/clib/old_tests/enkf/test_obs_vector.cpp
Labels: release-notes:maintenance

#5436 Refactor EnsembleConfig, EnkfConfigNode & ExtParamConfig
  src/clib/lib/CMakeLists.txt
  src/clib/lib/analysis/update.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/ext_param_config.cpp
  src/clib/lib/include/ert/analysis/update.hpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/ext_param_config.hpp
  src/clib/lib/include/ert/enkf/obs_vector.hpp
  src/clib/lib/python/init.cpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_config_node.cpp
  src/clib/old_tests/enkf/test_enkf_ensemble.cpp
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/config/__init__.py
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/config/ext_param_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/simulator/batch_simulator.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_ext_param_config.py
  tests/unit_tests/c_wrappers/res/enkf/data/test_enkf_config_node.py
  tests/unit_tests/c_wrappers/res/enkf/test_simulation_batch.py
  tests/unit_tests/simulator/test_batch_sim.py
Labels: release-notes:maintenance

#5458 Remove unused analysis_module_options_enum
  src/ert/_c_wrappers/analysis/enums/analysis_module_options_enum.py
Labels: release-notes:skip

#5454 Handle deprecations in new parser
  src/ert/parsing/error_info.py
  src/ert/parsing/schema_dict.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip

#5460 Add handling of executable as dir + test
  src/ert/parsing/config_schema_item.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip

#5461 Make filedialog test run
  src/ert/gui/tools/file/file_dialog.py
  src/ert/gui/tools/file/file_update_worker.py
  tests/unit_tests/gui/tools/file/filedialog.py
  tests/unit_tests/gui/tools/file/test_filedialog.py
Labels: release-notes:skip

#5466 Handle dirs with and without trailing slash in new parser
  src/ert/parsing/config_schema_item.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip

#5463 Add test that shows all plots for snake_oil
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
Labels: release-notes:skip

#5418 Fix bug where base surface was copied to all reals
  src/ert/_c_wrappers/enkf/config/surface_config.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: bug, release-notes:skip

#5467 Improve check of sufficient reals in test run
  src/ert/run_models/single_test_run.py
Labels: maintenance, release-notes:skip

#5468 Make plotting test use pytest-mpl for snapshot
  .github/workflows/check_old_parser.yml
  .github/workflows/test_ert.yml
  dev-requirements.txt
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_0-FOPR-Ensemble.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_0-FOPR-Statistics.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_0-SNAKE_OIL_PARAM:OP1_OCTAVES-Cross case statistics.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_0-SNAKE_OIL_PARAM:OP1_OCTAVES-Distribution.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_0-SNAKE_OIL_PARAM:OP1_OCTAVES-Gaussian KDE.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_0-SNAKE_OIL_PARAM:OP1_OCTAVES-Histogram.png
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
Labels: release-notes:skip

#5441 Use new parser for ext jobs
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/_c_wrappers/job_queue/parse_arg_types_list.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  src/ert/parsing/__init__.py
  src/ert/parsing/config_parsing_helpers.py
  src/ert/parsing/config_schema.py
  src/ert/parsing/ext_job_keywords.py
  src/ert/parsing/ext_job_schema.py
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_parser_error_collection.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
Labels: release-notes:skip

#5473 Make obs_vector python only
  dev-requirements.txt
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
  src/clib/lib/include/ert/enkf/obs_vector.hpp
  src/clib/lib/python/init.cpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_obs_vector.cpp
  src/ert/_c_wrappers/enkf/enums/enkf_obs_impl_type_enum.py
  src/ert/_c_wrappers/enkf/observations/obs_vector.py
  src/ert/data/loader.py
  src/ert/libres_facade.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/data/test_integration_data.py
  tests/unit_tests/data/test_loader.py
Labels: release-notes:skip

#5451 Remove config-node-meta structure, ErtImplType & EnkfVarType enums
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/config/ext_param_config.py
  src/ert/_c_wrappers/enkf/config/gen_data_config.py
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/config/parameter_config.py
  src/ert/_c_wrappers/enkf/config/summary_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/enums/__init__.py
  src/ert/_c_wrappers/enkf/enums/enkf_var_type_enum.py
  src/ert/_c_wrappers/enkf/enums/ert_impl_type_enum.py
  src/ert/analysis/_es_update.py
  src/ert/gui/ertwidgets/models/ertsummary.py
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  src/ert/libres_facade.py
  src/ert/simulator/batch_simulator.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_summary_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_simulation_batch.py
  tests/unit_tests/gui/ertwidgets/models/test_ertsummary.py
Labels: release-notes:maintenance

#5481 Make lark parser support character "^"
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/parsing/lark_parser.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
Labels: release-notes:skip

#5494 Revert "Reduce the amount of test runners"
  .github/workflows/build.yml
Labels: release-notes:skip

#5486 Refactor responses using dataclasses
  src/ert/_c_wrappers/enkf/config/gen_data_config.py
  src/ert/_c_wrappers/enkf/config/response_config.py
  src/ert/_c_wrappers/enkf/config/summary_config.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/simulator/batch_simulator.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_data_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_summary_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_simulation_batch.py
Labels: release-notes:maintenance

#5472 ExtParamConfig and GenKwConfig refactor
  src/ert/_c_wrappers/enkf/config/ext_param_config.py
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/config/parameter_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/analysis/_es_update.py
  src/ert/callbacks.py
  src/ert/gui/main.py
  src/ert/libres_facade.py
  src/ert/simulator/batch_simulator.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_ext_param_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
Labels: release-notes:maintenance

#5496 Remove unused: target format from gen_kw_config
  docs/reference/configuration/keywords.rst
  src/clib/lib/config/config_keywords.cpp
  src/clib/lib/enkf/config_keys.cpp
  src/clib/lib/include/ert/enkf/config_keys.hpp
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  src/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/parsing/config_keywords.py
  src/ert/parsing/config_schema.py
  tests/unit_tests/c_wrappers/res/enkf/test_config_content_as_dict.py
Labels: release-notes:maintenance

#5491 Convert EvaluatorConnectionInfo to a dataclass
  src/ert/ensemble_evaluator/evaluator_connection_info.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: maintenance, release-notes:skip

#5489 simplify summary observation
  src/ert/_c_wrappers/enkf/observations/obs_vector.py
  src/ert/_c_wrappers/enkf/observations/summary_observation.py
  src/ert/libres_facade.py
  tests/test_config_parsing/test_enkf_obs_parsing.py
  tests/unit_tests/c_wrappers/res/enkf/test_enkf_obs.py
  tests/unit_tests/c_wrappers/res/enkf/test_summary_observation.py
Labels: release-notes:skip

#5484 Substitute existing defines in lark parser
  src/ert/parsing/config_schema.py
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_ert_config_parsing.py
Labels: release-notes:skip

#5499 Change current working directory to config path
  src/ert/cli/main.py
  src/ert/gui/main.py
  tests/conftest.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:bug-fix

#5476 Use new parser for workflows
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/workflow.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  src/ert/parsing/__init__.py
  src/ert/parsing/config_schema_item.py
  src/ert/parsing/context_values.py
  src/ert/parsing/lark_parser.py
  src/ert/parsing/workflow_job_schema.py
  src/ert/parsing/workflow_keywords.py
  src/ert/parsing/workflow_schema.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
Labels: release-notes:skip

#5505 Add docstrings to libres facade
  src/ert/libres_facade.py
Labels: release-notes:skip
