Repository equinor/ert, pull requests merged in 2023-10, with the labels that each got.

#6214 Fix codecov badge
  README.md
Labels: release-notes:skip

#6204 Move C functions to pybind with GIL release
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/ert/job_queue/job_queue_node.py
Labels: release-notes:maintenance

#6203 Remove milestones from documentation
  docs/developer_documentation/milestones.rst
  docs/index.rst
Labels: documentation, release-notes:skip

#6206 Remove unused jobstatuses
  src/clib/lib/include/ert/job_queue/job_queue_status.hpp
  src/clib/lib/include/ert/job_queue/job_status.hpp
  src/clib/old_tests/job_queue/test_job_status.cpp
  src/ert/job_queue/job_status.py
  src/ert/job_queue/queue.py
  tests/unit_tests/job_queue/test_job_queue_node.py
Labels: release-notes:skip

#6208 Rename ert2 to ert in github action jobs
  .github/workflows/run_ert_test_data_setups.yml
Labels: release-notes:skip

#6217 Use c++ reading of datetimes for performance
  src/clib/lib/enkf/read_summary.cpp
  src/clib/lib/include/ert/python.hpp
  src/ert/config/summary_config.py
Labels: release-notes:skip

#6212 Use scipy cdf instead of own
  src/ert/config/gen_kw_config.py
Labels: maintenance, release-notes:skip

#6228 Pin Pylint<3.0.0
  pyproject.toml
Labels: release-notes:skip

#6227 Revert "Use c++ reading of datetimes for performance"
  src/clib/lib/enkf/read_summary.cpp
  src/clib/lib/include/ert/python.hpp
  src/ert/config/summary_config.py
Labels: release-notes:skip

#6230 Remove mentions of pyqt4
  .mypy.ini
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
Labels: maintenance

#6211 Create param data in same way as response data
  src/ert/storage/local_experiment.py
Labels: maintenance, release-notes:skip

#6216 Refactor collecting job_status_get_count
  src/clib/lib/job_queue/job_queue_status.cpp
  src/clib/old_tests/job_queue/test_job_status.cpp
Labels: release-notes:maintenance

#6239 Invert torque driver option for qsub output
  src/clib/lib/job_queue/torque_driver.cpp
Labels: release-notes:maintenance

#6226 Update status border color based on job status
  src/ert/gui/simulation/view/realization.py
  tests/unit_tests/gui/simulation/view/test_realization.py
Labels: release-notes:maintenance

#6246 Fix flaky test_full_manual_update_workflow
  tests/unit_tests/gui/test_full_manual_update_workflow.py
Labels: release-notes:skip

#6195 Remove usage of updatestep when calculating projection
  src/ert/analysis/_es_update.py
Labels: maintenance, release-notes:skip

#6255 Force doubles when row scaling
  src/ert/analysis/_es_update.py
Labels: release-notes:bug-fix

#6249 Allow to delete top most plot case
  src/ert/gui/tools/plot/plot_case_selection_widget.py
Labels: release-notes:maintenance

#6256 Use WAIT status when jobs PENDING and queue WAIT
  src/ert/gui/simulation/view/realization.py
Labels: release-notes:maintenance

#6259 Remove flaky property test of truncated normal
  tests/unit_tests/config/test_transfer_functions.py
Labels: release-notes:skip

#6254 Make the entire realization box go green on finish
  src/ert/gui/simulation/view/realization.py
Labels: release-notes:maintenance

#6251 Do not try getting item_num from run models
  src/ert/run_models/ensemble_experiment.py
Labels: release-notes:bug-fix

#6213 Remove X from triangular params
  docs/reference/configuration/data_types.rst
  src/ert/config/gen_kw_config.py
  src/ert/shared/storage/extraction.py
  tests/unit_tests/config/test_gen_kw_config.py
Labels: maintenance, release-notes:skip

#6243 Solve flakyness by mocking test-irrelevant code paths
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator_config.py
Labels: flaky-test, release-notes:skip

#6264 Speed up komodo tests
  ci/testkomodo.sh
Labels: release-notes:skip

#6261 Add a one time retry of license failure
  src/ert/shared/share/ert/forward-models/res/script/ecl_run.py
  tests/unit_tests/shared/share/test_ecl_run.py
Labels: release-notes:user-impact

#6257 Speed up summary_config by converting ecl_sum to datetime in C++
  src/clib/lib/enkf/read_summary.cpp
  src/ert/config/summary_config.py
Labels: release-notes:skip

#6268 Fix flakiness in job_queue_node tests
  tests/unit_tests/job_queue/test_job_queue_node.py
Labels: release-notes:skip

#6274 Delete unused types.py from run models
  src/ert/run_models/types.py
Labels: maintenance, release-notes:skip

#6277 Clean up torque driver
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/job_queue/test_job_torque.cpp
Labels: release-notes:skip

#6288 Simplify pytest invocation on komodo
  ci/testkomodo.sh
Labels: release-notes:skip

#6289 Require tables for all Python versions
  pyproject.toml
Labels: release-notes:skip

#6273 Add end_time when TIMEOUT
  src/ert/ensemble_evaluator/snapshot.py
Labels: release-notes:maintenance

#6247 Convert simulation arguments to dataclass
  src/ert/cli/model_factory.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/run_models/run_arguments.py
  src/ert/run_models/single_test_run.py
  src/ert/storage/local_experiment.py
  tests/unit_tests/cli/test_model_factory.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
  tests/unit_tests/run_models/test_base_run_model.py
  tests/unit_tests/run_models/test_ensemble_experiment.py
Labels: maintenance, release-notes:skip

#6286 Fix job colors in detailed view GUI
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/view/realization.py
Labels: release-notes:maintenance

#6299 Remove type ignore because new mypy complains
  src/ert/__main__.py
Labels: release-notes:skip

#6298 Delete unused async run functions
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
Labels: release-notes:skip

#6303 Add validation of gen kw from runpath
  src/ert/config/gen_kw_config.py
  tests/unit_tests/config/test_gen_kw_config.py
Labels: release-notes:bug-fix

#6300 Remove _get_A_matrix
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6282 Disallow empty string for define value
  src/ert/config/parsing/lark_parser.py
  tests/unit_tests/config/test_parser_error_collection.py
Labels: release-notes:skip

#6305 Move call to .fit outisde of param loop
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6314 Fix issue where ert would not work if you are using vpn
  src/ert/shared/port_handler.py
Labels: release-notes:bug-fix

#6325 Revert "Use start_simulations_thread in gui as in cli"
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:skip

#6294 Test ert slurm driver with ad-hoc cluster
  .github/workflows/build_and_test.yml
  .github/workflows/test_ert_with_slurm.yml
Labels: improvement, release-notes:maintenance

#6321 Only set realization color to running when jobs running
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/view/realization.py
  tests/unit_tests/gui/simulation/view/test_realization.py
Labels: release-notes:skip

#6234 Rewrite gui snapshot handling
  src/ert/ensemble_evaluator/evaluator_tracker.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/model/snapshot.py
Labels: enhancement

#6316 Implement streaming algorithm
  src/ert/analysis/_es_update.py
  src/ert/storage/local_ensemble.py
  tests/unit_tests/analysis/test_es_update.py
Labels: improvement, release-notes:improvement

#6326 Remove ert3 legacy
  src/ert/data/__init__.py
  src/ert/data/record/__init__.py
  src/ert/data/record/_record.py
  src/ert/data/record/_transformation.py
  src/ert/data/record/_transmitter.py
  src/ert/serialization/__init__.py
  src/ert/serialization/_registry.py
  src/ert/serialization/_serializer.py
  tests/unit_tests/data/test_transformation_direction.py
Labels: maintenance, release-notes:skip

#6350 Introduce param_correlation_sets
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6352 Remove unused queue_driver_get_option_list
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/include/ert/job_queue/job_status.hpp
  src/clib/lib/include/ert/job_queue/local_driver.hpp
  src/clib/lib/include/ert/job_queue/queue_driver.hpp
  src/clib/lib/include/ert/job_queue/slurm_driver.hpp
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
  src/clib/lib/job_queue/local_driver.cpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/queue_driver.cpp
  src/clib/lib/job_queue/slurm_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/job_queue/test_job_queue_driver.cpp
  src/clib/old_tests/job_queue/test_job_torque.cpp
Labels: release-notes:skip

#6355 Remove usage of stringlist in lsf exclude hosts
  src/clib/lib/job_queue/lsf_driver.cpp
  tests/unit_tests/job_queue/test_job_queue_node.py
Labels: release-notes:skip

#6366 Remove canceling of grouped github actions
  .github/workflows/annotate_cpp.yml
  .github/workflows/build_and_test.yml
  .github/workflows/coverage.yml
  .github/workflows/doctest.yml
  .github/workflows/style.yml
  .github/workflows/test_semeio.yml
  .github/workflows/typing.yml
Labels: release-notes:skip

#6356 Remove usage of stringlist in lsf driver
  src/clib/lib/include/ert/job_queue/lsf_driver.hpp
  src/clib/lib/include/ert/job_queue/spawn.hpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/spawn.cpp
  src/clib/old_tests/job_queue/CMakeLists.txt
  src/clib/old_tests/job_queue/test_job_lsf.cpp
  src/clib/old_tests/job_queue/test_job_lsf_exclude_hosts.cpp
  src/clib/old_tests/job_queue/test_job_lsf_parse_bsub_stdout.cpp
  tests/unit_tests/job_queue/test_job_queue_node.py
Labels: release-notes:skip

#6371 Remove usage of util_calloc
  src/clib/lib/include/ert/abort.hpp
  src/clib/lib/include/ert/job_queue/string_utils.hpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/slurm_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/job_queue/test_job_status.cpp
Labels: release-notes:skip

#6370 Implement adaptive localization
  src/ert/analysis/_es_update.py
  src/ert/config/analysis_module.py
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
  tests/unit_tests/analysis/test_adaptive_localization.py
  tests/unit_tests/analysis/test_analysis_module.py
Labels: release-notes:improvement

#6372 Remove util string copy
  src/clib/lib/include/ert/job_queue/string_utils.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
Labels: release-notes:skip

#6375 Avoid unsafe memory handling in lsf scanf
  src/clib/lib/job_queue/lsf_driver.cpp
Labels: release-notes:skip

#6369 Remove Protocol Buffers snippet from readme
  README.md
Labels: release-notes:skip

#6378 Remove unused var C_YY
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6379 Revert "Avoid unsafe memory handling in lsf scanf"
  src/clib/lib/job_queue/lsf_driver.cpp
Labels: release-notes:skip

#6376 Remove usage of util_fopen
  src/clib/lib/job_queue/job_node.cpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/queue_driver.cpp
  src/clib/lib/job_queue/slurm_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/job_queue/test_job_mock_slurm.cpp
  src/clib/old_tests/job_queue/test_job_slurm_runtest.cpp
  src/clib/old_tests/job_queue/test_job_slurm_submit.cpp
  src/clib/old_tests/job_queue/test_job_torque_submit.cpp
Labels: release-notes:skip

#6363 Fix MockTracker track bug
  src/ert/gui/simulation/run_dialog.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: flaky-test, release-notes:skip

#6382 Run tests offscreen on mac
  tests/conftest.py
Labels: release-notes:skip

#6377 Remove stringlist in job_queue_node_init
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/include/ert/job_queue/local_driver.hpp
  src/clib/lib/include/ert/job_queue/lsf_driver.hpp
  src/clib/lib/include/ert/job_queue/queue_driver.hpp
  src/clib/lib/include/ert/job_queue/slurm_driver.hpp
  src/clib/lib/include/ert/job_queue/spawn.hpp
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/clib/lib/job_queue/local_driver.cpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/queue_driver.cpp
  src/clib/lib/job_queue/slurm_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/job_queue/test_job_mock_slurm.cpp
  src/clib/old_tests/job_queue/test_job_slurm_runtest.cpp
  src/clib/old_tests/job_queue/test_job_slurm_submit.cpp
  src/clib/old_tests/job_queue/test_job_torque_submit.cpp
  src/clib/tests/job_queue/test_job_list.cpp
  src/clib/tests/job_queue/test_job_node.cpp
  src/ert/job_queue/job_queue_node.py
  tests/unit_tests/job_queue/test_torque_driver.py
Labels: release-notes:skip

#6390 Make random seed be int only
  docs/reference/configuration/keywords.rst
  src/ert/config/ert_config.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parameter_config.py
  src/ert/config/parsing/config_schema.py
  src/ert/enkf_main.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/test_enkf_main.py
Labels: release-notes:breaking-change, release-notes:user-impact

#6397 Mark memory usage count test as flaky
  tests/unit_tests/job_runner/test_job.py
Labels: release-notes:skip

#6402 Use renamed resfo (formerly known as ecl_data_io)
  .mypy.ini
  pyproject.toml
  src/ert/field_utils/field_utils.py
  src/ert/field_utils/grdecl_io.py
  test-data/poly_template/poly_eval.py.j2
  tests/performance_tests/performance_utils.py
  tests/unit_tests/config/egrid_generator.py
  tests/unit_tests/config/summary_generator.py
  tests/unit_tests/field_utils/test_grdecl_io.py
  tests/unit_tests/storage/test_parameter_sample_types.py
Labels: release-notes:skip

#6403 Move shared rng to run models
  src/ert/enkf_main.py
  src/ert/gui/tools/run_analysis/run_analysis_tool.py
  src/ert/libres_facade.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/gui/run_analysis/test_run_analysis.py
  tests/unit_tests/storage/test_parameter_sample_types.py
Labels: release-notes:improvement

#6380 Remove all util from tests and use catch2 instead
  src/clib/CMakeLists.txt
  src/clib/lib/CMakeLists.txt
  src/clib/old_tests/CMakeLists.txt
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/job_queue/CMakeLists.txt
  src/clib/old_tests/job_queue/test_job_slurm_driver.cpp
  src/clib/old_tests/job_queue/test_job_slurm_submit.cpp
  src/clib/old_tests/job_queue/test_job_torque_submit.cpp
  src/clib/tests/CMakeLists.txt
  src/clib/tests/data/job_queue/qsub_emulators/qdel
  src/clib/tests/data/job_queue/qsub_emulators/qstat
  src/clib/tests/data/job_queue/qsub_emulators/qsub
  src/clib/tests/enkf/test_row_scaling.cpp
  src/clib/tests/job_queue/test_job_mock_slurm.cpp
  src/clib/tests/job_queue/test_job_slurm_driver.cpp
  src/clib/tests/job_queue/test_job_slurm_runtest.cpp
  src/clib/tests/job_queue/test_job_slurm_submit.cpp
  src/clib/tests/job_queue/test_job_torque_submit.cpp
  src/clib/tests/tmpdir.cpp
  src/clib/tests/tmpdir.hpp
  src/ert/job_queue/qstat_proxy.sh
Labels: release-notes:maintenance

#6400 Remove unused dependencies
  pyproject.toml
Labels: release-notes:skip

#6407 Replace remaining test_asserts
  src/clib/tests/job_queue/test_job_slurm_runtest.cpp
Labels: release-notes:maintenance

#6275 Add status missing to update snapshot
  src/ert/analysis/_es_update.py
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_only_using_subset_observations/0/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0/update_log
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/analysis/update_log/id.txt
Labels: release-notes:improvement

#6409 Fix issue with double free in 0b46bc1
  src/clib/lib/job_queue/lsf_driver.cpp
  tests/unit_tests/job_queue/test_job_queue_node.py
Labels: release-notes:skip

#6412 Fix visible and copyable run_path stripped of placeholders
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/single_test_run_panel.py
  src/ert/libres_facade.py
  tests/unit_tests/test_libres_facade.py
Labels: release-notes:bug-fix

#6394 Avoid logging substitutions of the same value in queue config and forward model
  src/ert/config/ert_config.py
  src/ert/config/queue_config.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_queue_config.py
Labels: release-notes:maintenance

#6410 Improve flaky test_port_handler _simulate_server function
  tests/unit_tests/shared/test_port_handler.py
Labels: flaky-test, release-notes:skip

#6406 Make torque driver compatible with slurm-wlm-torque
  src/clib/lib/job_queue/torque_driver.cpp
  tests/unit_tests/job_queue/test_torque_driver.py
Labels: release-notes:improvement

#6408 Fix minimal example GUI crash
  src/ert/gui/model/snapshot.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:maintenance

#6420 Pass int array to _get_obs_and_measure_data
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6417 Fix bug where row scaling was applied wrong
  src/ert/analysis/_es_update.py
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:skip

#6423 Keep run_dialog open on terminate experiment
  src/ert/gui/simulation/run_dialog.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:maintenance

#6424 Move calc of Sigma_Y outside params loop
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6431 Resolve logical issue with counting bjobs cache
  src/clib/lib/job_queue/lsf_driver.cpp
Labels: release-notes:skip

#6425 Prevent the possibility of starting multiple concurrent experiments
  src/ert/gui/simulation/simulation_panel.py
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:maintenance

#6442 Emit finished signal when closing run dialog
  src/ert/gui/simulation/run_dialog.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:skip

#6433 Remove _active_realizations from base run model
  src/ert/run_models/base_run_model.py
  tests/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:skip

#6445 Reduce the number of threads used in komodo to 4
  ci/testkomodo.sh
Labels: release-notes:skip

#6428 Fix Ert GUI crashes on esc press
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:maintenance

#6432 Return numpy bool from _realizations
  src/ert/cli/model_factory.py
  tests/unit_tests/cli/test_model_factory.py
Labels: release-notes:skip

#6447 Remove docs/advanced/api.rst
  docs/advanced/api.rst
  docs/index.rst
Labels: release-notes:skip

#6392 Replace custom debug options with logging
  docs/reference/configuration/keywords.rst
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/lib/python/logging.cpp
  src/ert/logging/logger.conf
  tests/unit_tests/test_logging.py
Labels: release-notes:skip
