Repository equinor/ert, pull requests merged in 2023-04, with the labels that each got.

#5087 Ensemble Config & Enkf Config Node refactor
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/field_config.cpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/field_config.hpp
  src/clib/lib/python/ensemble_config.cpp
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/enkf_state.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/enums/__init__.py
  src/ert/_c_wrappers/enkf/enums/field_file_format_type_enum.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/callbacks.py
  src/ert/simulator/batch_simulator.py
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/c_wrappers/res/enkf/data/test_enkf_config_node.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_local_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_simulation_batch.py
Labels: release-notes:maintenance

#5185 Use ISO-date in poly README
  test-data/poly_example/README.md
Labels: release-notes:skip

#5189 Add random sleep to qstat in torque driver
  src/clib/lib/job_queue/torque_driver.cpp
Labels: release-notes:misc

#5198 Change weights via method instead of GUI during test
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:maintenance

#5184 Replace text for run button in ERT to 'Open ERT'
  src/ert/gui/main.py
Labels: release-notes:improvement

#5050 Reduce memory usage by not unnecessarily creating a copy of the parameters
  src/ert/analysis/_es_update.py
Labels: release-notes:bug-fix

#5153 Increase timeout on job runner startup overhead
  tests/performance_tests/test_forward_model_script_overhead.py
Labels: release-notes:skip

#5215 Backport fix for 5202 (flaky gui test) to 4.5
  tests/unit_tests/gui/conftest.py
Labels: release-notes:skip

#5195 Show Error in suggestor when non-UTF-8 found in DATA file
  src/ert/_c_wrappers/config/config_parser.py
  src/ert/_c_wrappers/enkf/ert_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_config_content_as_dict.py
  tests/unit_tests/c_wrappers/res/enkf/test_res_config.py
Labels: release-notes:bug-fix

#5219 Test that valid observations are added to enkf_obs
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/observations_generator.py
  tests/test_config_parsing/summary_generator.py
  tests/test_config_parsing/test_enkf_obs_parsing.py
Labels: release-notes:skip

#5193 Enable new parser DEFINE key to allow multiple arguments
  src/ert/_c_wrappers/enkf/config_keywords.py
  tests/test_config_parsing/test_ert_config_parsing.py
Labels: release-notes:bug-fix

#5221 Delete unnecessary test of gen_data_config
  src/ert/_c_wrappers/enkf/config/gen_data_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_data_config.py
Labels: release-notes:maintenance

#5218 Change Torque option TIMEOUT to QUEUE_QUERY_TIMEOUT
  docs/reference/configuration/keywords.rst
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/job_queue/test_job_torque.cpp
Labels: Configuration, release-notes:misc, release-notes:maintenance

#5223 Fix strange `gui` case name appearing for each run of EnsembleSmoother
  src/ert/gui/simulation/ensemble_smoother_panel.py
Labels: release-notes:bug-fix

#5212 Make parsing module, move new parser code there
  .mypy-strict.ini
  .mypy.ini
  src/ert/__main__.py
  src/ert/_c_wrappers/analysis/analysis_module.py
  src/ert/_c_wrappers/config/__init__.py
  src/ert/_c_wrappers/config/config_parser.py
  src/ert/_c_wrappers/enkf/_config_content_as_dict.py
  src/ert/_c_wrappers/enkf/analysis_config.py
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/enkf/queue_config.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/_c_wrappers/job_queue/workflow.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  src/ert/gui/main.py
  src/ert/parsing/__init__.py
  src/ert/parsing/config_errors.py
  src/ert/parsing/config_keywords.py
  src/ert/parsing/lark_parser.py
  src/ert/parsing/lark_parser_types.py
  tests/test_config_parsing/test_ert_config_parsing.py
  tests/test_config_parsing/test_forward_model.py
  tests/test_config_parsing/test_queue_config.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/c_wrappers/res/analysis/test_analysis_module.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_analysis_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_config_content_as_dict.py
  tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_model_config.py
  tests/unit_tests/c_wrappers/res/job_queue/test_ext_job.py
  tests/unit_tests/c_wrappers/res/job_queue/test_function_ert_script.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:skip

#5225 Solve pylint issue simplifiable-if-expression
  script/pylint
  src/ert/analysis/_es_update.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:skip

#5226 Solve pylint issue unnecessary-dict-index-lookup
  script/pylint
  src/ert/shared/storage/extraction.py
Labels: release-notes:skip

#5237 Use module logger instead of root logger in main
  src/ert/gui/main.py
Labels: release-notes:skip

#5239 Fix instansiation of logger in gui main
  src/ert/gui/main.py
Labels: release-notes:skip

#5233 Fix not assertion noted py python linting
  src/ert/dark_storage/common.py
  src/ert/shared/storage/extraction.py
Labels: release-notes:skip

#5240 Remove unused FunctionErtScript
  src/ert/_c_wrappers/job_queue/__init__.py
  src/ert/_c_wrappers/job_queue/function_ert_script.py
  src/ert/_c_wrappers/job_queue/workflow_job.py
  tests/unit_tests/c_wrappers/res/job_queue/test_function_ert_script.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow_job.py
  tests/unit_tests/c_wrappers/res/job_queue/workflow_common.py
Labels: release-notes:skip

#5243 Use config_dict instead of ensemble_config
  src/ert/_c_wrappers/enkf/ert_config.py
Labels: release-notes:skip

#5235 Collect config errors before displaying
  src/ert/__main__.py
  src/ert/_c_wrappers/config/config_parser.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/job_queue/ext_job.py
  src/ert/gui/main.py
  src/ert/parsing/config_errors.py
  tests/test_config_parsing/test_ert_config_parsing.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
Labels: release-notes:improvement

#5247 Remove .DATA suffix from REFCASE path
  src/ert/_c_wrappers/enkf/ensemble_config.py
Labels: release-notes:bug-fix

#5245 Remove .DATA suffix from REFCASE path
  src/ert/_c_wrappers/enkf/ensemble_config.py
Labels: release-notes:maintenance

#5227 Fix saving surface to file
  src/ert/storage/local_ensemble.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: bug

#5269 Raise AssertionError instead of assert False
  tests/performance_tests/test_dark_storage_performance.py
  tests/test_config_parsing/observations_generator.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:skip

#5263 Ignore B028 in annotations
  .github/workflows/annotate_python.yml
Labels: release-notes:skip

#5271 Avoid generating test dicts that have warnings
  tests/test_config_parsing/config_dict_generator.py
  tests/test_config_parsing/observations_generator.py
Labels: release-notes:skip

#5275 Fix misfit labels being incorrect
  src/ert/libres_facade.py
  tests/unit_tests/snapshots/test_libres_facade/test_misfit_collector/misfit_collector.csv
Labels: release-notes:skip

#5274 Fix test for missing response
  src/ert/analysis/_es_update.py
  src/ert/storage/local_ensemble.py
  tests/unit_tests/scenarios/test_summary_response.py
Labels: release-notes:bug-fix

#5175 Merge tests that were both updating field
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:maintenance

#5249 Added command line option to lint the configuration setup
  src/ert/__main__.py
  src/ert/_c_wrappers/config/config_parser.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/parsing/config_errors.py
  src/ert/parsing/config_keywords.py
  src/ert/parsing/config_linting.py
  src/ert/parsing/context_values.py
  src/ert/parsing/error_info.py
  src/ert/parsing/file_context_token.py
  src/ert/parsing/lark_parser.py
  src/ert/parsing/types.py
  tests/test_config_parsing/test_ert_config_parsing.py
  tests/test_config_parsing/test_parser_error_collection.py
  tests/unit_tests/c_wrappers/res/job_queue/test_workflow.py
Labels: release-notes:new-feature

#5281 Replace text for run button in ERT to 'Open ERT'
  src/ert/gui/main.py
Labels: release-notes:bug-fix

#5278 Validate distribution parameters
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
Labels: release-notes:bug-fix

#5288 Backport Add some chars to UNQUOTED in lark grammar
  src/ert/_c_wrappers/enkf/lark_parser.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:skip

#5283 Add some chars to UNQUOTED in lark grammar
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_ert_config_parsing.py
Labels: release-notes:skip

#5294 Stop flaky gui tests
  .github/workflows/check_new_parser.yml
  .github/workflows/coverage.yml
  .github/workflows/test_ert.yml
Labels: release-notes:skip

#5295 Improve assert in manual update test
  tests/unit_tests/gui/test_full_manual_update_workflow.py
Labels: release-notes:skip

#5286 Fix flake8-bugbear's B007 on unused loop control variables
  src/ert/cli/monitor.py
  src/ert/gui/plottery/plots/ccsp.py
  src/ert/shared/models/iterated_ensemble_smoother.py
  src/ert/shared/share/ert/forward-models/res/script/rms.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:misc

#5297 Bump the queue_query timeout in Torque driver
  docs/reference/configuration/keywords.rst
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
Labels: release-notes:misc

#5302 Fix up old style typing
  src/ert/gui/ertwidgets/checklist.py
  src/ert/gui/ertwidgets/customdialog.py
  src/ert/gui/ertwidgets/validationsupport.py
  src/ert/gui/plottery/plot_config.py
  src/ert/gui/plottery/plot_limits.py
  src/ert/gui/plottery/plots/ccsp.py
  src/ert/gui/plottery/plots/distribution.py
  src/ert/gui/plottery/plots/ensemble.py
  src/ert/gui/plottery/plots/gaussian_kde.py
  src/ert/gui/plottery/plots/history.py
  src/ert/gui/plottery/plots/observations.py
  src/ert/gui/plottery/plots/plot_tools.py
  src/ert/gui/plottery/plots/statistics.py
  src/ert/gui/simulation/simulation_config_panel.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/gui/tools/plot/customize/default_customization_view.py
  src/ert/gui/tools/plot/customize/limits_customization_view.py
  src/ert/gui/tools/plot/customize/statistics_customization_view.py
  src/ert/gui/tools/plot/customize/style_customization_view.py
  src/ert/gui/tools/plugins/plugin_runner.py
  src/ert/gui/tools/plugins/plugins_tool.py
Labels: release-notes:skip

#5228 Move enkf_obs_load into python
  src/clib/lib/config/conf.cpp
  src/clib/lib/enkf/enkf_obs.cpp
  src/clib/lib/enkf/obs_vector.cpp
  src/clib/lib/include/ert/config/conf.hpp
  src/clib/lib/include/ert/enkf/enkf_obs.hpp
  src/clib/lib/include/ert/enkf/obs_vector.hpp
  src/clib/old_tests/enkf/test_enkf_obs_invalid_path.cpp
  src/clib/tests/enkf/enkf_obs_paths_detailed.cpp
  src/ert/_c_wrappers/enkf/enkf_obs.py
Labels: release-notes:skip

#5304 Add localization for summary without ECLBase
  src/ert/_c_wrappers/enkf/ert_config.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip

#5285 Backport Enable new parser DEFINE key to allow multiple arguments
  src/ert/_c_wrappers/enkf/config_keywords.py
  tests/test_config_parsing/test_res_config.py
Labels: release-notes:skip

#5279 Warn when early liveness detector triggers
  src/ert/parsing/lark_parser.py
  tests/test_config_parsing/test_ert_config_parsing.py
Labels: release-notes:skip

#5265 Refactor gen_kw_config & trans_func
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/enkf_config_node.cpp
  src/clib/lib/enkf/ensemble_config.cpp
  src/clib/lib/enkf/gen_kw_config.cpp
  src/clib/lib/enkf/trans_func.cpp
  src/clib/lib/include/ert/enkf/enkf_config_node.hpp
  src/clib/lib/include/ert/enkf/ensemble_config.hpp
  src/clib/lib/include/ert/enkf/gen_kw_config.hpp
  src/clib/lib/include/ert/enkf/trans_func.hpp
  src/clib/old_tests/enkf/CMakeLists.txt
  src/clib/old_tests/enkf/test_enkf_ensemble.cpp
  src/clib/old_tests/enkf/test_trans_func.cpp
  src/ert/_c_wrappers/enkf/config/enkf_config_node.py
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  src/ert/_c_wrappers/enkf/enkf_main.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/analysis/_es_update.py
  src/ert/libres_facade.py
  src/ert/simulator/batch_simulator.py
  src/ert/storage/local_ensemble.py
  tests/unit_tests/c_wrappers/res/enkf/config/test_gen_kw_config.py
  tests/unit_tests/c_wrappers/res/enkf/test_ert_config.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/test_libres_facade.py
Labels: release-notes:maintenance

#5306 Dont show gui in tests by default
  tests/conftest.py
Labels: release-notes:maintenance

#5311 Add localization to queue_option_max_running
  src/ert/_c_wrappers/enkf/ert_config.py
  tests/test_config_parsing/test_parser_error_collection.py
Labels: release-notes:skip
