Repository equinor/ert, pull requests merged in 2023-11, with the labels that each got.

#6454 Extract wait and findChild in gui tests
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
  tests/unit_tests/gui/test_gui_load.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/gui/test_rft_export_plugin.py
Labels: release-notes:skip

#6179 Add option to delete run_path
  src/ert/gui/simulation/simulation_panel.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/gui/simulation/test_run_path_dialog.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
  tests/unit_tests/gui/test_gui_load.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:new-feature

#6459 Refactor gui load
  tests/unit_tests/gui/test_gui_load.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:skip

#6460 Clean up test_queue_config
  tests/unit_tests/config/test_queue_config.py
Labels: release-notes:skip

#6430 Remove step states from snapshots
  src/_ert_job_runner/runner.py
  src/ert/ensemble_evaluator/_builder/_ensemble.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/ensemble_evaluator/identifiers.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/job_queue/queue.py
  tests/performance_tests/test_snapshot.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/ensemble_evaluator/test_dispatch.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/ensemble_evaluator/test_evaluator_tracker.py
  tests/unit_tests/ensemble_evaluator/test_snapshot.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/model/test_real_list.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:maintenance

#6464 Remove dependence on ansicolor
  pyproject.toml
  src/ert/cli/monitor.py
  tests/unit_tests/cli/test_cli_monitor.py
Labels: release-notes:skip

#6463 Adjust the size of ERT main window after config warnings
  src/ert/gui/main.py
  src/ert/gui/main_window.py
Labels: release-notes:maintenance

#6469 Avoid div-by-zero when no realizations to calculate
  src/ert/gui/simulation/view/progress.py
Labels: release-notes:skip

#6475 Disable add-cases-button when no case data
  src/ert/gui/tools/plot/plot_case_selection_widget.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:maintenance

#6471 Fix unable to use anything except iteration 0 for ensemble experiment
  src/ert/run_models/ensemble_experiment.py
Labels: release-notes:bug-fix

#6452 Remove JobQueueManager
  src/ert/job_queue/__init__.py
  src/ert/job_queue/job_queue_manager.py
  src/ert/job_queue/queue.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/job_queue/test_job_queue.py
  tests/unit_tests/job_queue/test_job_queue_manager.py
  tests/unit_tests/job_queue/test_job_queue_node_torque.py
Labels: release-notes:maintenance

#6492 Only add -k oe when keep_qsub_output is set
  .github/workflows/test_ert_with_slurm.yml
  src/clib/lib/job_queue/torque_driver.cpp
Labels: release-notes:maintenance

#6490 Let qstat_options be empty by default
  .github/workflows/test_ert_with_slurm.yml
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
Labels: release-notes:maintenance

#6480 Rename LegacyJob to ForwardModel
  src/ert/ensemble_evaluator/__init__.py
  src/ert/ensemble_evaluator/_builder/__init__.py
  src/ert/ensemble_evaluator/_builder/_ensemble.py
  src/ert/ensemble_evaluator/_builder/_realization.py
  src/ert/run_models/base_run_model.py
  tests/performance_tests/test_snapshot.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
Labels: release-notes:maintenance

#6501 Fix the realization number for the stdout and stderr files
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:maintenance

#6509 Use BaseModel for AnalysisIterConfig
  src/ert/config/analysis_config.py
  src/ert/config/analysis_iter_config.py
  tests/unit_tests/config/test_analysis_iter_config.py
Labels: release-notes:skip

#6508 Do not rely on builtin warn to handle ConfigWarnings
  src/ert/cli/model_factory.py
  src/ert/config/analysis_config.py
  src/ert/config/ert_config.py
  src/ert/config/field.py
  src/ert/config/gen_kw_config.py
  src/ert/config/observations.py
  src/ert/config/parsing/config_errors.py
  src/ert/config/parsing/lark_parser.py
  src/ert/config/parsing/schema_dict.py
Labels: release-notes:maintenance

#6513 Fix bug where field size with mask was wrong
  src/ert/config/field.py
  tests/unit_tests/storage/test_field_parameter.py
Labels: release-notes:bug-fix

#6519 Fix failing mac cpp tests
  .github/workflows/build_and_test.yml
Labels: release-notes:skip

#6526 Update zlib, catch2 and cjson packages
  src/clib/CMakeLists.txt
Labels: release-notes:maintenance

#6527 Update semeio test workflow
  .github/workflows/test_semeio.yml
Labels: release-notes:skip

#6530 Fix gui snapshot not showing memory usage
  pyproject.toml
  src/ert/__main__.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/gui/model/snapshot.py
Labels: bug

#6539 Fix failing mac cpp tests
  .github/workflows/build_and_test.yml
Labels: release-notes:bug-fix

#6524 Fix iteration number in GUI when using ensemble experiment
  src/ert/gui/model/job_list.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:maintenance

#6542 Remove cli option current-case for es-mda
  src/ert/__main__.py
Labels: release-notes:maintenance

#6554 Remove type ignores not necesary with new mypy
  src/ert/config/ext_param_config.py
  src/ert/config/parsing/observations_parser.py
Labels: release-notes:skip

#6555 Unpin sphinx
  pyproject.toml
Labels: release-notes:maintenance

#6548 Have restart_from combobox in es_mda be default disabled
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
Labels: release-notes:maintenance

#6560 Remove ENKF_FORCE_NCOMP and add deprecation for ENKF_NCOMP & ENKF_SUBSPACE_DIMENSION
  docs/reference/configuration/keywords.rst
  src/ert/config/parsing/config_schema_deprecations.py
  tests/unit_tests/analysis/test_analysis_module.py
  tests/unit_tests/config/test_parser_error_collection.py
Labels: release-notes:maintenance

#6552 Let JobQueue create its driver
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/job_queue/queue.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/job_queue/test_job_queue.py
Labels: release-notes:maintenance

#6566 Remove unused cpp packages
  src/clib/CMakeLists.txt
  src/clib/lib/CMakeLists.txt
  src/clib/lib/block_fs_native/CMakeLists.txt
  src/clib/lib/block_fs_native/module.cpp
  src/clib/lib/enkf/enkf_obs.cpp
Labels: release-notes:skip

#6569 Remove unused keyword ENKF_BOOTSTRAP
  docs/reference/configuration/keywords.rst
  src/ert/config/parsing/config_schema_deprecations.py
Labels: release-notes:maintenance

#6568 Remove unused keyword ENKF_MODE
  docs/reference/configuration/keywords.rst
  src/ert/config/parsing/config_schema_deprecations.py
Labels: release-notes:maintenance

#6573 Import from future to stop webviz ert from crashing
  src/ert/shared/storage/connection.py
Labels: release-notes:bug-fix

#6558 Unify execute API of JobQueue, refactor websocket connection
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/job_queue/queue.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/job_queue/test_job_queue.py
Labels: release-notes:maintenance

#6576 Remove `USE_EE` & `USE_GE` analysis keywords
  src/ert/config/analysis_module.py
  tests/unit_tests/config/test_ert_config.py
Labels: release-notes:maintenance

#6594 Set default case_name for ES_MDA when none provided
  src/ert/cli/model_factory.py
Labels: release-notes:maintenance

#6587 Fix deprecation info for Analysis Module
  src/ert/config/analysis_module.py
  src/ert/config/parsing/config_schema_deprecations.py
  tests/unit_tests/config/test_parser_error_collection.py
Labels: release-notes:maintenance

#6591 Update documentation with missing analysis keywords
  docs/reference/configuration/keywords.rst
Labels: release-notes:maintenance

#6595 Have removed analysis modules keywords raise errors
  src/ert/config/analysis_module.py
  src/ert/config/parsing/config_schema_deprecations.py
  tests/unit_tests/analysis/test_analysis_module.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_analysis_config.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_parser_error_collection.py
Labels: release-notes:maintenance

#6496 Improve documentation of the plugin system
  docs/getting_started/howto/plugin_system.rst
  docs/index.rst
  src/ert/shared/hook_implementations/workflows/__init__.py
Labels: documentation, release-notes:skip

#6598 Update LOCALIZATION keyword to only apply for ES
  docs/reference/configuration/keywords.rst
Labels: release-notes:maintenance

#6607 Fix Analysis Model UI Issues
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
Labels: release-notes:maintenance

#6625 Return update snapshot from facade
  src/ert/libres_facade.py
Labels: release-notes:maintenance

#6596 The startup feedback screen now uses equinor design system colors and icons
  src/ert/config/parsing/error_info.py
  src/ert/gui/ertwidgets/copyablelabel.py
  src/ert/gui/ertwidgets/suggestor_message.py
  src/ert/gui/main.py
  src/ert/gui/resources/gui/img/error_bgcircle.svg
  src/ert/gui/resources/gui/img/thumbdown_bgcircle.svg
  src/ert/gui/resources/gui/img/warning_bgcircle.svg
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:improvement

#6638 Fix bug where localization settings were not saved
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
  tests/unit_tests/gui/run_analysis/test_analysispanel.py
Labels: release-notes:bug-fix

#6642 Remove void monkeypatching
  tests/unit_tests/ensemble_evaluator/conftest.py
Labels: release-notes:skip

#6446 Force fortran order for row scaling
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6641 Refactor queue config docs
  docs/index.rst
  docs/reference/configuration/index.rst
  docs/reference/configuration/keywords.rst
  docs/reference/configuration/queue.rst
  docs/reference/queue.rst
  docs/reference/queue/QUEUE_TEST
  docs/reference/queue/local_queue.ert
  docs/reference/queue/lsf_queue.ert
Labels: documentation, release-notes:skip

#6635 Have continous updating of the target case field
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
Labels: release-notes:improvement

#6651 Continuous updates of target case field
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
Labels: release-notes:improvement

#6656 Fix bug where localization settings were not saved
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
  tests/unit_tests/gui/run_analysis/test_analysispanel.py
Labels: release-notes:bug-fix

#6652 Modify error message for mismatched ensemble size
  src/ert/run_models/base_run_model.py
Labels: release-notes:maintenance

#6655 Fix factual error in LOCAL info
  docs/reference/configuration/queue.rst
Labels: documentation

#6645 Make test code more robust
  tests/conftest.py
  tests/unit_tests/cli/test_integration_cli.py
Labels: release-notes:skip

#6615 Make it possible to edit the plot title
  src/ert/gui/tools/plot/plot_window.py
Labels: release-notes:maintenance

#6684 Fix flaky test gui plotter button state
  src/ert/gui/tools/plot/plot_case_selection_widget.py
Labels: release-notes:skip

#6559 Remove ert-storage as dependency
  pyproject.toml
  src/ert/__main__.py
  src/ert/dark_storage/__init__.py
  src/ert/dark_storage/app.py
  src/ert/dark_storage/client/__init__.py
  src/ert/dark_storage/client/_session.py
  src/ert/dark_storage/client/async_client.py
  src/ert/dark_storage/client/client.py
  src/ert/dark_storage/compute/__init__.py
  src/ert/dark_storage/compute/misfits.py
  src/ert/dark_storage/endpoints/compute/misfits.py
  src/ert/dark_storage/endpoints/ensembles.py
  src/ert/dark_storage/endpoints/experiments.py
  src/ert/dark_storage/endpoints/observations.py
  src/ert/dark_storage/endpoints/records.py
  src/ert/dark_storage/endpoints/updates.py
  src/ert/dark_storage/enkf.py
  src/ert/dark_storage/exceptions.py
  src/ert/dark_storage/json_schema/__init__.py
  src/ert/dark_storage/json_schema/ensemble.py
  src/ert/dark_storage/json_schema/experiment.py
  src/ert/dark_storage/json_schema/observation.py
  src/ert/dark_storage/json_schema/prior.py
  src/ert/dark_storage/json_schema/record.py
  src/ert/dark_storage/json_schema/update.py
  src/ert/dark_storage/security.py
  src/ert/namespace.py
  src/ert/services/_storage_main.py
  src/ert/services/storage_service.py
  src/ert/shared/storage/command.py
  tests/performance_tests/performance_utils.py
  tests/unit_tests/dark_storage/conftest.py
  tests/unit_tests/dark_storage/test_api_compatibility.py
  tests/unit_tests/services/test_storage_service.py
  tests/unit_tests/shared/test_main_entry.py
  tests/unit_tests/storage/conftest.py
Labels: release-notes:skip

#6711 Add headers to version 8.0 release notes
  docs/about/release_notes.rst
Labels: release-notes:skip

#5911 Remove composite coefficient names from parameters.json
  docs/reference/configuration/keywords.rst
  src/ert/enkf_main.py
Labels: release-notes:breaking-change

#6728 Avoid cutting suggestions with angular chars
  src/ert/gui/ertwidgets/suggestor_message.py
Labels: release-notes:skip
