Repository equinor/ert, pull requests merged in 2023-08, with the labels that each got.

#5755 Make update configuration type checked
  .mypy-strict.ini
  src/ert/_c_wrappers/analysis/configuration.py
Labels: release-notes:skip

#5756 Make ensemble config type checked
  .mypy-strict.ini
  src/ert/_c_wrappers/enkf/ensemble_config.py
  tests/test_config_parsing/test_ensemble_config.py
Labels: release-notes:skip

#5758 Remove prefect from mypy and docs
  .mypy-strict.ini
  .mypy.ini
  docs/developer_documentation/milestones.rst
  src/ert/shared/port_handler.py
Labels: release-notes:skip

#5759 Remove unused ExtParamConfig lookup by int
  .mypy-strict.ini
  src/ert/config/ext_param_config.py
  src/ert/simulator/batch_simulator.py
  tests/unit_tests/config/test_ext_param_config.py
Labels: release-notes:skip

#5760 Fix typing in FieldConfig
  .mypy-strict.ini
  src/ert/config/field_config.py
Labels: release-notes:skip

#5763 Remove empty docs page for config file
  docs/reference/configuration_file.rst
  docs/reference/index.rst
Labels: documentation, release-notes:skip

#5761 Remove some badges from the README
  README.md
Labels: release-notes:maintenance

#5762 Add type checking to c_wrappers
  .mypy-strict.ini
  .mypy.ini
  src/ert/_c_wrappers/__init__.py
  src/ert/_c_wrappers/analysis/analysis_module.py
  src/ert/_c_wrappers/enkf/__init__.py
  src/ert/_c_wrappers/enkf/enkf_obs.py
  src/ert/_c_wrappers/enkf/ensemble_config.py
  src/ert/_c_wrappers/enkf/ert_config.py
  src/ert/_c_wrappers/enkf/ert_run_context.py
  src/ert/_c_wrappers/enkf/model_config.py
  src/ert/_c_wrappers/enkf/observations/obs_vector.py
  src/ert/_c_wrappers/enkf/row_scaling.py
  src/ert/_c_wrappers/util/substitution_list.py
  src/ert/config/ext_param_config.py
  src/ert/config/field_config.py
  src/ert/config/gen_data_config.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parameter_config.py
  src/ert/config/queue_config.py
  src/ert/parsing/__init__.py
  src/ert/parsing/config_errors.py
  src/ert/parsing/config_linting.py
  src/ert/parsing/config_schema.py
  src/ert/parsing/config_schema_deprecations.py
  src/ert/parsing/context_values.py
  src/ert/parsing/error_info.py
  src/ert/parsing/ext_job_schema.py
  src/ert/parsing/file_context_token.py
  src/ert/parsing/lark_parser.py
  src/ert/parsing/new_observations_parser.py
  src/ert/parsing/schema_dict.py
  src/ert/parsing/types.py
  src/ert/parsing/workflow_job_schema.py
  src/ert/parsing/workflow_schema.py
  tests/test_config_parsing/test_enkf_obs_parsing.py
Labels: release-notes:skip

#5766 Increase verbosity of too many realz failed error
  src/ert/run_models/base_run_model.py
Labels: release-notes:skip

#5765 Update description of a forward model
  docs/reference/forward_models.rst
Labels: documentation, release-notes:skip

#5769 Fix pylint issue in _legacy.py with annotations
  src/ert/ensemble_evaluator/_builder/_legacy.py
Labels: release-notes:skip

#5772 Fix Next-button in docs
  docs/about/index.rst
  docs/advanced/index.rst
  docs/api_reference/index.rst
  docs/developer_documentation/index.rst
  docs/experimental/index.rst
  docs/getting_started/index.rst
  docs/index.rst
  docs/reference/index.rst
  docs/theory/index.rst
Labels: documentation

#5776 Move update.py to where it is used
  src/ert/analysis/_es_update.py
  src/ert/analysis/configuration.py
  src/ert/analysis/update.py
Labels: release-notes:skip

#5775 Move ResPrototype to where it is used
  script/ecl-check
  src/ert/__init__.py
  src/ert/_c_wrappers/__init__.py
  src/ert/job_queue/__init__.py
  src/ert/job_queue/driver.py
  src/ert/job_queue/job_queue_node.py
  src/ert/job_queue/queue.py
Labels: release-notes:skip

#5781 Remove unused job_queue_add_job
  src/clib/lib/include/ert/job_queue/job_queue.hpp
  src/clib/lib/job_queue/job_queue.cpp
Labels: release-notes:skip

#5783 Remove UPDATE_SETTINGS keyword
  docs/reference/configuration/keywords.rst
  src/ert/config/parsing/config_keywords.py
  src/ert/config/parsing/config_schema.py
  src/ert/config/parsing/config_schema_deprecations.py
  tests/unit_tests/config/parsing/test_config_schema_deprecations.py
  tests/unit_tests/config/test_parser_error_collection.py
Labels: release-notes:maintenance

#5746 Rephrase start simulation button
  src/ert/__main__.py
  src/ert/cli/monitor.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/simulation_panel.py
  tests/unit_tests/cli/test_cli_monitor.py
Labels: release-notes:improvement

#5778 Combine docs on forward models to single doc
  docs/_ext/ert_jobs.py
  docs/index.rst
  docs/reference/configuration/forward_model.rst
  docs/reference/forward_models.rst
  src/ert/shared/_doc_utils/ert_jobs.py
Labels: documentation, release-notes:skip

#5782 REmove unused queue size and completed status
  src/clib/lib/include/ert/job_queue/job_queue.hpp
  src/clib/lib/job_queue/job_queue.cpp
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/job_queue/queue.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/job_queue/test_job_queue_manager.py
Labels: release-notes:skip

#5780 Remove unused queue.is_running
  src/clib/lib/include/ert/job_queue/job_queue.hpp
  src/clib/lib/job_queue/job_queue.cpp
  src/ert/job_queue/queue.py
  tests/unit_tests/job_queue/test_job_queue_manager.py
Labels: release-notes:skip

#5788 Remove unused functionality cpp
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/include/ert/job_queue/job_queue.hpp
  src/clib/lib/include/ert/job_queue/lsf_driver.hpp
  src/clib/lib/include/ert/job_queue/queue_driver.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/clib/lib/job_queue/job_queue.cpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/queue_driver.cpp
  src/clib/old_tests/job_queue/test_job_queue_driver.cpp
  src/ert/job_queue/queue.py
Labels: release-notes:maintenance

#5787 Refactor JobQueueNode._monitor
  src/ert/job_queue/job_queue_node.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:skip

#5796 Fix flaky test
  tests/unit_tests/config/test_forward_model_data_to_json.py
Labels: release-notes:skip

#5802 Fix some silenced pylint issues
  src/ert/analysis/configuration.py
  src/ert/cli/main.py
  src/ert/config/field.py
  src/ert/job_queue/queue.py
  src/ert/libres_facade.py
  src/ert/runpaths.py
  src/ert/simulator/batch_simulator.py
  tests/unit_tests/all/plugins/test_plugin_context.py
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/res/util/test_substitution_list.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_forward_model.py
  tests/unit_tests/config/test_parser_error_collection.py
  tests/unit_tests/job_queue/test_torque_driver.py
  tests/unit_tests/shared/share/test_rms.py
  tests/unit_tests/test_libres_facade.py
Labels: release-notes:skip

#5805 Only make time map required if DATE is used in GEN_OBS
  docs/getting_started/configuration/poly_new/guide.rst
  docs/getting_started/configuration/poly_new/with_observations/poly.ert
  docs/reference/configuration/keywords.rst
  src/ert/config/observations.py
  test-data/poly_example/poly-ies.ert
  test-data/poly_example/poly.ert
  test-data/poly_example/time_map
  tests/unit_tests/c_wrappers/integration/test_field_parameter.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
  tests/unit_tests/config/test_observations.py
  tests/unit_tests/job_queue/test_lsf_driver.py
  tests/unit_tests/test_libres_facade.py
Labels: release-notes:new-feature

#5803 Refactor JobQueue & JobQueueStatus
  src/clib/lib/include/ert/job_queue/job_queue_status.hpp
  src/clib/lib/job_queue/job_queue.cpp
  src/clib/lib/job_queue/job_queue_status.cpp
  src/clib/old_tests/job_queue/test_job_status.cpp
Labels: release-notes:maintenance

#5813 Add tests that cover all driver options
  src/clib/lib/include/ert/job_queue/lsf_driver.hpp
  src/clib/lib/include/ert/job_queue/slurm_driver.hpp
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/slurm_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/old_tests/job_queue/test_job_queue_driver.cpp
Labels: release-notes:maintenance

#5817 Remove unused job_kw_definitions
  src/clib/lib/include/ert/job_queue/job_kw_definitions.hpp
Labels: release-notes:maintenance

#5810 Update intro to analysis module
  docs/reference/configuration/keywords.rst
Labels: documentation, release-notes:skip

#5822 Fix bug with gen_kw templating
  src/ert/config/gen_kw_config.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:bug-fix

#5820 Resolve RUNPATH deprecated warnings in generated tests
  tests/unit_tests/config/config_dict_generator.py
Labels: release-notes:maintenance

#5818 Fix incorrect unexpected character location
  src/ert/config/parsing/observations_parser.py
  tests/unit_tests/config/test_observations.py
Labels: release-notes:skip

#5799 Do no create experiment and case on start-up
  src/ert/gui/ertwidgets/caseselector.py
  src/ert/gui/main.py
  src/ert/gui/tools/manage_cases/case_init_configuration.py
Labels: release-notes:bug-fix

#5544 Remove some unused functions
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/include/ert/job_queue/job_queue.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/clib/lib/job_queue/job_queue.cpp
  src/ert/job_queue/queue.py
Labels: release-notes:skip

#5824 Fix an issue with double comments
  src/ert/config/parsing/lark_parser.py
  src/ert/config/parsing/observations_parser.py
  tests/unit_tests/config/parsing/test_observations_parser.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_forward_model.py
Labels: release-notes:bug-fix

#5831 Backport: Fix bug with gen_kw templating
  src/ert/_c_wrappers/enkf/config/gen_kw_config.py
  tests/unit_tests/c_wrappers/integration/test_parameter_sample_types.py
Labels: release-notes:bug-fix

#5826 Remove ANALYSIS_COPY
  docs/reference/configuration/keywords.rst
  src/ert/config/analysis_config.py
  src/ert/config/parsing/config_schema.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_analysis_config.py
Labels: release-notes:maintenance

#5825 Remove api references from docs
  docs/api_reference/data.rst
  docs/api_reference/exceptions.rst
  docs/api_reference/experiment_server.rst
  docs/index.rst
Labels: documentation, release-notes:skip

#5837 Remove last mention of ANALYSIS_COPY
  src/ert/config/parsing/config_keywords.py
Labels: release-notes:skip

#5841 Display meaningful message upon job queue failure
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/ert/gui/ertwidgets/message_box.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/file/file_dialog.py
  src/ert/job_queue/job_queue_node.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:improvement

#5840 Add line number and file to warnings
  src/ert/cli/main.py
  src/ert/config/ensemble_config.py
  src/ert/config/ert_config.py
  src/ert/config/observations.py
  src/ert/config/parsing/config_dict.py
  src/ert/config/parsing/config_errors.py
  src/ert/config/parsing/lark_parser.py
  src/ert/config/parsing/schema_dict.py
  src/ert/gui/main.py
  tests/unit_tests/config/parsing/test_config_schema_deprecations.py
  tests/unit_tests/config/test_observations.py
  tests/unit_tests/config/test_parser_error_collection.py
Labels: release-notes:skip

#5848 Rename Forward models to Jobs in config summary
  src/ert/gui/ertwidgets/summarypanel.py
Labels: release-notes:maintenance

#5856 Fix incorrect suggestion for RUNPATH deprecation
  src/ert/config/parsing/config_schema_deprecations.py
  tests/unit_tests/config/parsing/test_config_schema_deprecations.py
Labels: release-notes:bug-fix

#5863 Fix issues with new mypy
  src/ert/__main__.py
  src/ert/config/parsing/observations_parser.py
Labels: release-notes:skip

#5830 Make refcase only required if using HISTORY_OBSERVATION
  docs/reference/configuration/keywords.rst
  src/ert/config/observation_vector.py
  src/ert/config/observations.py
  src/ert/data/_measured_data.py
  src/ert/libres_facade.py
  tests/unit_tests/config/test_observations.py
  tests/unit_tests/data/test_integration_data.py
Labels: release-notes:breaking-change, release-notes:new-feature

#5845 Refactor JobQueue & JobQueueStatus
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/include/ert/job_queue/job_queue.hpp
  src/clib/lib/include/ert/job_queue/job_queue_status.hpp
  src/clib/lib/job_queue/job_queue.cpp
  src/clib/lib/job_queue/job_queue_status.cpp
  src/clib/old_tests/job_queue/test_job_status.cpp
  src/ert/job_queue/queue.py
  tests/unit_tests/job_queue/test_job_queue.py
Labels: release-notes:maintenance

#5873 Add handling of error cases for field io
  src/ert/field_utils/field_utils.py
  src/ert/field_utils/grdecl_io.py
  src/ert/field_utils/roff_io.py
  tests/unit_tests/field_utils/test_grdecl_io.py
  tests/unit_tests/field_utils/test_roff_io.py
Labels: release-notes:skip

#5870 Simplify analysis config
  src/ert/analysis/_es_update.py
  src/ert/cli/model_factory.py
  src/ert/config/analysis_config.py
  src/ert/config/observations.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/libres_facade.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/config/test_analysis_config.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/ensemble_evaluator/conftest.py
Labels: release-notes:skip

#5671 Add parameter counts in the GUI
  src/ert/gui/ertwidgets/models/ertsummary.py
  src/ert/gui/ertwidgets/summarypanel.py
  tests/unit_tests/gui/ertwidgets/models/test_ertsummary.py
  tests/unit_tests/gui/ertwidgets/test_summarypanel.py
Labels: improvement, release-notes:improvement

#5786 Add logging to reading of parameters and responses
  src/ert/callbacks.py
  src/ert/config/surface_config.py
Labels: release-notes:maintenance

#5670 Add information about submodules and git lfs in readme
  README.md
Labels: release-notes:skip

#5880 Fix bug with variable referenced before assignment
  src/ert/config/observations.py
  tests/unit_tests/scenarios/test_summary_response.py
Labels: release-notes:skip

#5865 Exit un-runnable job and fail job
  src/_ert_job_runner/job.py
  tests/unit_tests/c_wrappers/job_runner/test_job.py
Labels: release-notes:bug-fix, release-notes:improvement

#5879 Validate that observation error is above 0 at startup
  src/ert/config/general_observation.py
  src/ert/config/summary_observation.py
  tests/unit_tests/config/test_observations.py
Labels: release-notes:improvement

#5882 Show a helpful error message when reading time map fails
  src/ert/config/ert_config.py
  src/ert/config/model_config.py
  src/ert/config/observations.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_model_config.py
Labels: release-notes:bug-fix

#5888 Simplify validation of ensemble_config
  src/ert/config/ensemble_config.py
  src/ert/config/ert_config.py
Labels: release-notes:skip

#5892 Pin sphinx <7.2
  dev-requirements.txt
Labels: release-notes:skip

#5890 Move remaining c_wrappers test to match src
  tests/unit_tests/analysis/test_analysis_module.py
  tests/unit_tests/analysis/test_row_scaling.py
  tests/unit_tests/analysis/test_row_scaling_increased_belief_case.py
  tests/unit_tests/analysis/test_update_configuration.py
  tests/unit_tests/c_wrappers/conftest.py
  tests/unit_tests/c_wrappers/integration/__init__.py
  tests/unit_tests/c_wrappers/job_runner/__init__.py
  tests/unit_tests/c_wrappers/res/__init__.py
  tests/unit_tests/c_wrappers/res/analysis/__init__.py
  tests/unit_tests/c_wrappers/res/enkf/__init__.py
  tests/unit_tests/c_wrappers/res/enkf/conftest.py
  tests/unit_tests/c_wrappers/res/enkf/data/__init__.py
  tests/unit_tests/c_wrappers/res/util/__init__.py
  tests/unit_tests/c_wrappers/test_integration_config.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/conftest.py
  tests/unit_tests/job_runner/__init__.py
  tests/unit_tests/job_runner/test_event_reporter.py
  tests/unit_tests/job_runner/test_file_reporter.py
  tests/unit_tests/job_runner/test_job.py
  tests/unit_tests/job_runner/test_job_dispatch.py
  tests/unit_tests/job_runner/test_job_manager_runtime_kw.py
  tests/unit_tests/job_runner/test_jobmanager.py
  tests/unit_tests/job_runner/test_protobuf_reporter.py
  tests/unit_tests/snapshots/test_summary_response/test_load_summary_response_restart_not_zero/summary_restart
  tests/unit_tests/storage/test_field_parameter.py
  tests/unit_tests/storage/test_parameter_sample_types.py
  tests/unit_tests/summary_response/PRED_RUN.SMSPEC
  tests/unit_tests/summary_response/PRED_RUN.UNSMRY
  tests/unit_tests/test_enkf_main.py
  tests/unit_tests/test_enkf_runpath.py
  tests/unit_tests/test_ert_run_context.py
  tests/unit_tests/test_field_export.py
  tests/unit_tests/test_load_forward_model.py
  tests/unit_tests/test_local_config.py
  tests/unit_tests/test_logging.py
  tests/unit_tests/test_run_path_creation.py
  tests/unit_tests/test_substitution_list.py
  tests/unit_tests/test_summary_response.py
Labels: release-notes:skip

#5899 Restrict numpy to less than 2.0
  setup.py
Labels: release-notes:dependency

#5900 Update the welcome page
  docs/index.rst
Labels: documentation, release-notes:skip

#5895 Free allocated memory in torque driver
  src/clib/lib/job_queue/torque_driver.cpp
Labels: bug, release-notes:misc

#5881 Make template optional for GEN_KW
  docs/reference/configuration/keywords.rst
  src/ert/config/ensemble_config.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parsing/config_schema.py
  tests/unit_tests/storage/test_parameter_sample_types.py
Labels: release-notes:improvement

#5855 Make REPORT_STEP optional in GEN_DATA and GENERAL_OBSERVATION
  docs/getting_started/configuration/poly_new/guide.rst
  docs/getting_started/configuration/poly_new/with_observations/observations
  docs/getting_started/configuration/poly_new/with_observations/poly.ert
  docs/getting_started/configuration/poly_new/with_observations/poly_eval.py
  docs/getting_started/configuration/poly_new/with_observations/poly_final.ert
  docs/getting_started/configuration/poly_new/with_results/poly.ert
  docs/getting_started/configuration/poly_new/with_results/poly_eval.py
  docs/getting_started/configuration/poly_new/with_simple_script/poly_eval.py
  src/ert/config/ensemble_config.py
  src/ert/config/gen_data_config.py
  src/ert/config/observations.py
  src/ert/libres_facade.py
  src/ert/simulator/batch_simulator.py
  test-data/poly_example/README.md
  test-data/poly_example/observations
  test-data/poly_example/poly-ies.ert
  test-data/poly_example/poly.ert
  test-data/poly_example/poly_eval.py
  tests/unit_tests/config/test_gen_data_config.py
  tests/unit_tests/config/test_parser_error_collection.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/job_queue/test_lsf_driver.py
  tests/unit_tests/test_load_forward_model.py
Labels: release-notes:improvement

#5913 Fix hypothesis setup such that queue option values are tested
  tests/unit_tests/config/config_dict_generator.py
Labels: bug, release-notes:maintenance

#5914 Refactor JobStatus & JobNode
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/job_queue/job_list.hpp
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/include/ert/job_queue/job_status.hpp
  src/clib/lib/job_queue/job_list.cpp
  src/clib/lib/job_queue/job_node.cpp
  src/clib/lib/job_queue/job_queue.cpp
  src/clib/lib/job_queue/job_status.cpp
  src/clib/old_tests/job_queue/test_job_list.cpp
Labels: release-notes:maintenance

#5920 Remove unused lsf submit internal
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/job_queue/lsb.hpp
  src/clib/lib/include/ert/job_queue/lsf_driver.hpp
  src/clib/lib/include/ert/job_queue/lsf_job_stat.hpp
  src/clib/lib/job_queue/lsb.cpp
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/old_tests/job_queue/test_job_lsb.cpp
  src/clib/old_tests/job_queue/test_job_lsb2.cpp
  src/clib/old_tests/job_queue/test_job_lsf.cpp
  src/clib/old_tests/job_queue/test_job_lsf_library_submit.cpp
  src/clib/old_tests/job_queue/test_job_lsf_submit_library.cpp
Labels: release-notes:skip

#5925 Remove status_map from lsf_driver
  src/clib/lib/job_queue/lsf_driver.cpp
Labels: release-notes:maintenance

#5577 Add memory per job as Torque option
  docs/reference/configuration/keywords.rst
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/ert/config/queue_config.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_queue_config.py
  tests/unit_tests/job_queue/test_torque_driver.py
Labels: improvement, release-notes:improvement

#5933 Fix INDEX_FILE not being read properly from GENERAL_OBSERVATION
  src/ert/config/observations.py
  src/ert/config/parsing/observations_parser.py
  tests/unit_tests/config/parsing/test_observations_parser.py
  tests/unit_tests/config/test_observations.py
Labels: release-notes:bug-fix

#5935 Backport Fix INDEX_FILE reading
  src/ert/config/observations.py
  src/ert/config/parsing/observations_parser.py
  tests/unit_tests/config/parsing/test_observations_parser.py
  tests/unit_tests/config/test_observations.py
Labels: release-notes:bug-fix

#5939 Convert some jobnode methods to pybind
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/clib/lib/job_queue/queue_driver.cpp
  src/ert/job_queue/job_queue_node.py
Labels: release-notes:skip

#5951 Fix test after change in exceptions raised
  tests/unit_tests/shared/share/test_ecl_run.py
Labels: release-notes:skip

#5928 Ensure job_dispatch exits cleanly on OSError
  src/_ert_job_runner/cli.py
Labels: release-notes:bug-fix

#5921 Mark flaky test with xfail
  tests/unit_tests/gui/test_full_manual_update_workflow.py
Labels: release-notes:skip

#5957 Avoid raising Exception
  src/ert/config/external_ert_script.py
  src/ert/shared/port_handler.py
Labels: release-notes:maintenance

#5961 Make sure job_queue will not timeout when sending event
  src/ert/job_queue/queue.py
  src/ert/job_queue/queue_differ.py
Labels: release-notes:bug-fix

#5897 Remove Launching ERT from docs
  docs/getting_started/launch.rst
  docs/index.rst
Labels: documentation, release-notes:skip

#5981 Fix upper case formats
  src/ert/config/field.py
  src/ert/field_utils/__init__.py
  src/ert/field_utils/field_file_format.py
  src/ert/field_utils/field_utils.py
  tests/unit_tests/config/test_field.py
  tests/unit_tests/storage/test_field_parameter.py
Labels: release-notes:bug-fix

#5958 Solve flake8-bugbear B008
  setup.cfg
  tests/unit_tests/config/config_dict_generator.py
Labels: release-notes:skip

#5971 Remove commented out code
  src/_ert_job_runner/cli.py
  src/ert/__main__.py
  src/ert/gui/ertwidgets/pathchooser.py
  src/ert/gui/ertwidgets/searchbox.py
  src/ert/gui/ertwidgets/validationsupport.py
  src/ert/gui/plottery/plots/plot_tools.py
  src/ert/gui/tools/plot/data_type_keys_widget.py
Labels: release-notes:skip

#5977 Add DEBUG_OUTPUT to list of options supported
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
Labels: bug

#5975 Add explicit stacklevel for warnings.warn
  .github/workflows/annotate_python.yml
  setup.cfg
  src/ert/cli/model_factory.py
  src/ert/config/ert_config.py
  src/ert/config/field.py
  src/ert/config/gen_kw_config.py
  src/ert/config/observations.py
  src/ert/config/parsing/lark_parser.py
  src/ert/config/parsing/schema_dict.py
  src/ert/gui/main.py
Labels: release-notes:skip

#5884 Remove ies update from libres facade
  src/ert/libres_facade.py
  src/ert/run_models/iterated_ensemble_smoother.py
  tests/unit_tests/cli/test_model_hook_order.py
Labels: release-notes:skip

#5997 Make coverage run storage migration tests
  .github/workflows/coverage.yml
Labels: release-notes:skip

#5991 Use single if-statement instead of nested
  src/_ert_job_runner/job.py
  src/ert/__main__.py
  src/ert/callbacks.py
  src/ert/config/observations.py
  src/ert/ensemble_evaluator/_builder/_io_.py
  src/ert/gui/ertwidgets/listeditbox.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/shared/share/ert/shell_scripts/careful_copy_file.py
  src/ert/shared/share/ert/shell_scripts/copy_directory.py
  src/ert/shared/share/ert/shell_scripts/copy_file.py
  src/ert/validation/active_range.py
  tests/unit_tests/status/test_tracking_integration.py
Labels: release-notes:skip

#5998 Skip flaky gui test
  tests/unit_tests/gui/test_gui_load.py
Labels: release-notes:skip

#6000 Remove unused option to not substitute at all
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/parsing/lark_parser.py
Labels: release-notes:skip

#5999 Simplify Slurm driver
  src/clib/lib/job_queue/slurm_driver.cpp
Labels: release-notes:maintenance

#6001 Fix config aliases
  src/ert/config/parsing/lark_parser.py
  tests/unit_tests/config/parsing/test_lark_parser.py
Labels: release-notes:bug-fix

#6004 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-notes:skip

#6005 Describe squashing more precisely
  CONTRIBUTING.md
Labels: release-notes:skip

#6002 Simplify lsf driver
  src/clib/lib/job_queue/lsf_driver.cpp
Labels: release-notes:maintenance

#5996 Raise cyclical include error for self include
  src/ert/config/parsing/lark_parser.py
  tests/unit_tests/config/parsing/test_lark_parser.py
Labels: release-notes:bug-fix

#6021 Revert Convert some job_node functions to pybind
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/ert/job_queue/job_queue_node.py
Labels: release-notes:maintenance

#5993 Add warning when overwriting QUEUE_OPTION
  src/ert/config/queue_config.py
  tests/unit_tests/config/test_queue_config.py
Labels: release-notes:improvement

#5960 Let ERT handle a flaky qdel as for qsub and qstat
  docs/reference/configuration/keywords.rst
  src/clib/lib/job_queue/torque_driver.cpp
Labels: release-notes:improvement
