Repository equinor/ert, pull requests merged in 2023-09, with the labels that each got.

#5990 Solve and enforce 3 pylint issues
  script/pylint
  src/ert/gui/plottery/plot_config.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/experiment_server/test_server.py
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
Labels: release-notes:skip

#6032 Revert "Add warning when overwriting QUEUE_OPTION (#5993)"
  src/ert/config/queue_config.py
  tests/unit_tests/config/test_queue_config.py
Labels: release-notes:skip

#6034 Pin hypothesis at 6.83.0 for python 3.8
  dev-requirements.txt
Labels: release-notes:maintenance

#6013 Remove double occurrence in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-notes:skip

#6041 Upgrade to checkout v4
  .github/workflows/actionlint.yml
  .github/workflows/annotate_cpp.yml
  .github/workflows/annotate_python.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-macos.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/doctest.yml
  .github/workflows/run_ert_test_data_setups.yml
  .github/workflows/style.yml
  .github/workflows/test_ert.yml
  .github/workflows/test_semeio.yml
  .github/workflows/typing.yml
Labels: release-notes:skip

#6044 Fix qt c++ object lifetime flakiness in plot test
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
Labels: flaky-test, release-notes:skip

#5963 Solve flake8-bugbear B014
  setup.cfg
  src/_ert_job_runner/client.py
Labels: release-notes:maintenance

#6048 Remove redundant checkpoint
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-notes:skip

#6049 Fix instance where current case was None
  src/ert/gui/ertnotifier.py
Labels: release-notes:bug-fix

#5798 Add documentation on installing ERT on ARM
  README.md
Labels: documentation

#6047 Fix false-positive warning message
  src/ert/config/ert_config.py
  src/ert/substitution_list.py
  tests/unit_tests/config/test_forward_model.py
Labels: release-notes:skip

#6050 Clarify test point in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-notes:skip

#6027 Lift max_running into generic python driver
  src/clib/lib/include/ert/job_queue/queue_driver.hpp
  src/clib/lib/job_queue/queue_driver.cpp
  src/clib/old_tests/job_queue/test_job_queue_driver.cpp
  src/ert/job_queue/driver.py
  tests/unit_tests/config/test_queue_config.py
  tests/unit_tests/job_queue/test_driver.py
  tests/unit_tests/job_queue/test_job_queue.py
  tests/unit_tests/job_queue/test_job_queue_manager.py
Labels: release-notes:maintenance

#6057 Update docs of theory behind ensemble methods
  docs/theory/ensemble_based_methods.rst
Labels: documentation, release-notes:skip

#6064 Fix bug where truncated normal was not truncated
  src/ert/config/gen_kw_config.py
Labels: release-notes:bug-fix

#6065 Remove flakiness in test_ert_qstat_proxy
  tests/unit_tests/job_queue/test_ert_qstat_proxy.py
Labels: flaky-test, release-notes:skip

#6073 Fix a race condition in rft_csv_export test
  tests/unit_tests/gui/test_rft_export_plugin.py
Labels: release-notes:skip

#6076 Add test for TransformationDirectorion.__str__
  tests/unit_tests/data/test_transformation_direction.py
Labels: release-notes:skip

#6080 Remove salib as dependency as its not used
  setup.py
Labels: release-notes:skip

#6071 Fix memory test
  dev-requirements.txt
  tests/performance_tests/test_memory_usage.py
Labels: release-notes:skip

#6082 Remove xtgeo from dev-reqs as its in setup.py
  dev-requirements.txt
Labels: release-notes:skip

#6081 Move style requirements to separate file
  .github/workflows/style.yml
  dev-requirements.txt
  style-requirements.txt
Labels: release-notes:skip

#6078 Test truncated normal transfer function
  src/ert/config/__init__.py
  tests/unit_tests/config/test_gen_kw_config.py
  tests/unit_tests/config/test_transfer_functions.py
Labels: release-notes:maintenance

#6087 Fix flaky test of truncated normal
  tests/unit_tests/config/test_transfer_functions.py
Labels: release-notes:skip

#6088 Set atol in isclose in flaky test
  tests/unit_tests/config/test_transfer_functions.py
Labels: release-notes:skip

#6090 Add mailmap for a684814
  .mailmap
Labels: release-notes:skip

#6091 Add mailmap for joakim
  .mailmap
Labels: release-notes:skip

#5688 Add same message to cli as gui if existing runpath
  src/ert/cli/main.py
Labels: release-notes:maintenance

#6061 Refactor local_driver and handling of generic options
  src/clib/lib/include/ert/job_queue/local_driver.hpp
  src/clib/lib/include/ert/job_queue/queue_driver.hpp
  src/clib/lib/job_queue/local_driver.cpp
  src/clib/lib/job_queue/queue_driver.cpp
  src/clib/old_tests/job_queue/test_job_queue_driver.cpp
  src/ert/job_queue/driver.py
  tests/unit_tests/job_queue/test_driver.py
Labels: release-notes:maintenance

#6037 Print overwritten Queue Options values to log files
  src/ert/config/parsing/lark_parser.py
  src/ert/config/queue_config.py
  tests/unit_tests/config/test_queue_config.py
Labels: release-notes:skip

#6102 Skip test_rft_csv_export_plugin_exports_rft_data
  tests/unit_tests/gui/test_rft_export_plugin.py
Labels: release-notes:maintenance

#6077 Replace jobs array with job_queue_node_type vector
  src/clib/lib/include/ert/job_queue/job_list.hpp
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/job_queue/job_list.cpp
  src/clib/lib/job_queue/job_node.cpp
  src/clib/old_tests/job_queue/test_job_list.cpp
  src/clib/old_tests/job_queue/test_job_node.cpp
Labels: release-notes:maintenance

#6095 Turn on gui tests for mac
  .github/workflows/build.yml
  tests/conftest.py
Labels: release-notes:skip

#6094 Filter non ConfigWarnings
  tests/unit_tests/config/test_ert_config.py
Labels: flaky-test

#6106 Use 32bit floats for surfaces
  setup.py
  src/ert/config/surface_config.py
  src/ert/storage/local_experiment.py
  src/ert/storage/migration/block_fs.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/config/test_surface_config.py
  tests/unit_tests/storage/test_parameter_sample_types.py
Labels: release-notes:improvement

#6115 Move sortedcontainers to install_requires
  dev-requirements.txt
  setup.py
Labels: release-notes:dependency

#6117 Remove duplicates from summary files
  src/ert/config/summary_config.py
  tests/unit_tests/scenarios/test_summary_response.py
Labels: release-notes:bug-fix

#6111 Log no websocket connection as error, not debug
  src/_ert_job_runner/client.py
  src/_ert_job_runner/reporting/event.py
Labels: release-notes:skip

#6119 Remove unused jenkins files
  ci/jenkins/Jenkinsfile-libres
  ci/jenkins/Jenkinsfile-performance
  ci/jenkins/testkomodo-ERT.sh
  ci/jenkins/testkomodo-libres-ctest.sh
  ci/jenkins/testkomodo-repeat-flaky.sh
Labels: release-notes:skip

#6118 Remove callbacks from job_queue_node
  src/ert/callbacks.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/ensemble_evaluator/_builder/_step.py
  src/ert/job_queue/job_queue_node.py
  src/ert/job_queue/queue.py
  src/ert/run_models/base_run_model.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/job_queue/test_job_queue.py
  tests/unit_tests/job_queue/test_job_queue_manager.py
  tests/unit_tests/job_queue/test_job_queue_manager_torque.py
Labels: release-notes:skip

#6123 Add Flake8-pyproject to fix python annotation workflow
  .github/workflows/annotate_python.yml
Labels: release-notes:skip

#5754 Replace basemodel with dataclass in event.py
  src/ert/ensemble_evaluator/event.py
Labels: good first issue, improvement, release-notes:maintenance

#6132 Warn when min_realizations > num_realizations
  src/ert/config/analysis_config.py
  tests/unit_tests/config/test_analysis_config.py
Labels: release-notes:new-feature

#6114 Remove JobListReadLock and simplify JobQueue
  src/clib/lib/include/ert/job_queue/job_queue.hpp
  src/clib/lib/job_queue/job_list.cpp
  src/clib/lib/job_queue/job_queue.cpp
  src/clib/lib/job_queue/job_queue_status.cpp
  src/clib/old_tests/job_queue/test_job_queue_driver.cpp
  src/ert/job_queue/queue.py
  tests/unit_tests/job_queue/test_job_queue.py
Labels: release-notes:maintenance

#6128 Replace flake8 and isort with ruff
  .github/workflows/style.yml
  pyproject.toml
  src/_ert_job_runner/cli.py
  src/ert/__main__.py
  src/ert/analysis/_es_update.py
  src/ert/config/analysis_module.py
  src/ert/config/ert_config.py
  src/ert/config/ert_script.py
  src/ert/config/ext_job.py
  src/ert/config/gen_kw_config.py
  src/ert/config/model_config.py
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/parsing/lark_parser.py
  src/ert/config/parsing/observations_parser.py
  src/ert/dark_storage/common.py
  src/ert/data/_measured_data.py
  src/ert/data/record/_record.py
  src/ert/ensemble_evaluator/_wait_for_evaluator.py
  src/ert/gui/ertwidgets/listeditbox.py
  src/ert/gui/ertwidgets/pathchooser.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/plottery/plots/distribution.py
  src/ert/gui/plottery/plots/histogram.py
  src/ert/gui/simulation/view/realization.py
  src/ert/gui/tools/load_results/__init__.py
  src/ert/gui/tools/manage_cases/case_init_configuration.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/libres_facade.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/shared/feature_toggling.py
  src/ert/shared/plugins/plugin_manager.py
  src/ert/shared/port_handler.py
  src/ert/shared/share/ert/forward-models/res/script/ecl_config.py
  src/ert/shared/share/ert/forward-models/res/script/ecl_run.py
  src/ert/shared/share/ert/forward-models/res/script/rms.py
  src/ert/shared/share/ert/shell_scripts/make_directory.py
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_storage.py
  style-requirements.txt
  tests/unit_tests/analysis/test_row_scaling.py
  tests/unit_tests/config/test_forward_model_data_to_json.py
  tests/unit_tests/conftest.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/gui/model/test_job_list.py
  tests/unit_tests/gui/model/test_progress_proxy.py
  tests/unit_tests/gui/model/test_real_list.py
  tests/unit_tests/gui/model/test_snapshot.py
  tests/unit_tests/services/test_base_service.py
  tests/unit_tests/storage/test_local_storage.py
Labels: maintenance, release-notes:skip

#6137 Unskip memray test
  tests/unit_tests/storage/test_parameter_sample_types.py
Labels: release-notes:skip

#6146 Fix flaky tests related to data_to_json
  tests/unit_tests/config/test_forward_model_data_to_json.py
Labels: release-notes:skip

#6151 Move matcher to ruff
  .github/workflows/annotate_python.yml
  .github/workflows/style.yml
Labels: release-notes:skip

#6126 Use python 3.10 on run-ert-test-data for macOS
  .github/workflows/run_ert_test_data_setups.yml
Labels: release-notes:maintenance

#6152 Increase timeout of esmda has run
  tests/unit_tests/gui/conftest.py
Labels: release-notes:skip

#6153 Fix flaky test test_kill_simulations
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:skip

#6158 Mark remaining flaky tests for rerun with @flaky
  tests/unit_tests/job_queue/test_ert_qstat_proxy.py
  tests/unit_tests/job_runner/test_event_reporter.py
Labels: release-notes:skip

#6116 Replace requirement files with pyproject
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/doctest.yml
  .github/workflows/style.yml
  .github/workflows/test_ert.yml
  .github/workflows/typing.yml
  .readthedocs.yaml
  CONTRIBUTING.md
  README.md
  ci/run_ert_ctests.sh
  ci/testkomodo.sh
  dev-requirements.txt
  pyproject.toml
  setup.py
  src/ert/dark_storage/endpoints/responses.py
  style-requirements.txt
  types-requirements.txt
Labels: maintenance, release-notes:skip

#6160 Use numpy array to hold realizations
  src/ert/analysis/_es_update.py
  src/ert/enkf_main.py
  src/ert/libres_facade.py
  src/ert/run_context.py
  src/ert/simulator/batch_simulator.py
  src/ert/simulator/batch_simulator_context.py
  src/ert/simulator/simulation_context.py
  src/ert/storage/local_ensemble.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
Labels: maintenance, release-notes:skip

#6162 Add size property to param configs
  src/ert/config/field.py
  src/ert/config/gen_kw_config.py
  src/ert/config/surface_config.py
  src/ert/gui/ertwidgets/models/ertsummary.py
  tests/unit_tests/config/test_gen_kw_config.py
  tests/unit_tests/gui/ertwidgets/models/test_ertsummary.py
Labels: maintenance, release-notes:skip

#6156 Add debug information to coverage gui tests
  .github/workflows/coverage.yml
Labels: release-notes:skip

#6168 Do not use index_list in _get_A_matrix
  src/ert/analysis/_es_update.py
Labels: maintenance, release-notes:bug-fix

#6174 Remove xfail from manual update test
  tests/unit_tests/gui/test_full_manual_update_workflow.py
Labels: release-notes:skip

#6165 Get measured data using active realizations
  src/ert/data/_measured_data.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
Labels: release-notes:bug-fix

#6051 Prevent setting LSF_SERVER to an undefined environment variable
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/queue_config.py
  tests/unit_tests/config/test_queue_config.py
Labels: release-notes:maintenance

#6175 Add timings to log for internalization of data from iterations
  src/ert/callbacks.py
  src/ert/logging/logger.conf
Labels: release-notes:misc

#6176 Use tmpdir in tests that are currently polluting source dir
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
  tests/unit_tests/config/test_analysis_config.py
  tests/unit_tests/config/test_ensemble_config.py
  tests/unit_tests/job_queue/test_ert_qstat_proxy.py
  tests/unit_tests/shared/test_main_entry.py
Labels: release-notes:skip

#6122 Count memory usage for grandchildren in job_dispatch
  src/_ert_job_runner/job.py
  tests/unit_tests/job_runner/test_job.py
Labels: bug, release-notes:bug-fix

#6181 Resolve ERT slowdown seen in Azure
  src/clib/lib/include/ert/job_queue/job_node.hpp
  src/clib/lib/job_queue/job_node.cpp
  src/ert/job_queue/job_queue_node.py
Labels: release-notes:bug-fix

#6155 Refactor queue_options in QueueConfig to be Tuple[str, str]
  src/ert/config/queue_config.py
  src/ert/job_queue/driver.py
  tests/unit_tests/config/test_queue_config.py
  tests/unit_tests/job_queue/test_driver.py
Labels: release-notes:maintenance

#6172 Remove protobuf
  .github/workflows/typing.yml
  .mypy.ini
  .pylintrc
  docs/conf.py
  pyproject.toml
  setup.py
  src/_ert_com_protocol/__init__.py
  src/_ert_com_protocol/_schema.proto
  src/_ert_com_protocol/_state_machine.py
  src/_ert_com_protocol/status_type_enum.py
  src/_ert_job_runner/cli.py
  src/_ert_job_runner/reporting/__init__.py
  src/_ert_job_runner/reporting/protobuf.py
  src/ert/__main__.py
  src/ert/cli/main.py
  src/ert/ensemble_evaluator/_builder/_ensemble.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/experiment_server/__init__.py
  src/ert/experiment_server/_experiment_protocol.py
  src/ert/experiment_server/_registry.py
  src/ert/experiment_server/_server.py
  src/ert/job_queue/queue.py
  src/ert/logging/logger.conf
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/shared/feature_toggling.py
  tests/unit_tests/cli/test_integration_cli.py
  tests/unit_tests/experiment_server/__init__.py
  tests/unit_tests/experiment_server/conftest.py
  tests/unit_tests/experiment_server/test_server.py
  tests/unit_tests/experiment_server/test_statemachine.py
  tests/unit_tests/job_runner/test_protobuf_reporter.py
Labels: maintenance, release-notes:skip

#6177 Create backup for jobs.json when running in existing runpath
  src/ert/enkf_main.py
  tests/unit_tests/test_enkf_runpath.py
Labels: release-notes:new-feature, release-notes:improvement

#6193 Make lsf driver submit signal invalid instead of abort
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/old_tests/job_queue/test_job_lsf_parse_bsub_stdout.cpp
  tests/unit_tests/job_queue/test_job_queue_node.py
Labels: release-notes:skip

#6200 Get params from storage not from config
  src/ert/analysis/_es_update.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/scenarios/test_summary_response.py
Labels: maintenance, release-notes:skip

#6201 Refactor proper name formatting to reduce indents
  src/ert/validation/proper_name_argument.py
  src/ert/validation/proper_name_format_argument.py
Labels: maintenance, release-notes:skip
