Repository equinor/ert, pull requests merged in 2024-10, with the labels that each got.

#8822 Fix the everest doc generator
  src/everest/docs/__main__.py
Labels: bug, release-notes:skip, everest

#8837 Fix real mem doc
  docs/ert/reference/configuration/keywords.rst
Labels: documentation, release-notes:skip

#8826 Log LSF execution host to Azure
  src/ert/scheduler/lsf_driver.py
  tests/ert/unit_tests/scheduler/bin/bjobs.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:improvement

#8845 Fix ConfigWarning not calling class method of child classes
  src/ert/config/parsing/config_errors.py
Labels: release-notes:misc

#8843 Avoid possible UnboundLocalError for end_event
  src/ert/cli/main.py
Labels: release-notes:skip

#8850 Update the everest egg snapshot
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/egg.csv
  tests/everest/test_egg_simulation.py
Labels: release-notes:skip

#8853 Return with SIGTERM in mocked kill
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: flaky-test, release-notes:skip

#8756 Run everest tests before publishing to pypi
  .github/workflows/build_and_test.yml
  .github/workflows/test_everest.yml
  .github/workflows/test_everest_macos.yml
Labels: release-notes:skip

#8857 Fix capturing of ForwardModelStepWarning
  src/ert/config/__init__.py
  src/ert/config/capture_validation.py
  src/ert/gui/main.py
  tests/ert/unit_tests/config/test_capture_validation.py
Labels: release-notes:bug-fix

#8856 Avoid logging void host information
  src/ert/scheduler/lsf_driver.py
Labels: release-notes:skip

#8861 Fix documentation for DeleteFile
  src/ert/plugins/hook_implementations/forward_model_steps.py
Labels: release-notes:skip

#8873 Resolve flakyness in test_kill_before_submit
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#8874 Only use logger.exception for unexpected exceptions
  src/ert/__main__.py
  src/ert/cli/main.py
  src/ert/gui/tools/plot/plot_window.py
Labels: release-notes:skip

#8875 Only use logger.exception for unexpected exceptions
  src/ert/__main__.py
  src/ert/cli/main.py
  src/ert/gui/tools/plot/plot_window.py
Labels: release-notes:skip

#8876 Only use logger.exception for unexpected exceptions
  src/ert/__main__.py
  src/ert/cli/main.py
  src/ert/gui/tools/plot/plot_window.py
Labels: release-notes:skip

#8836 Remove unused directory
  src/everest/data/__init__.py
  src/everest/data/misc/welopen_format
  src/everest/data/wizard.yml
Labels: release-notes:skip

#8879 Make kill_before_submit more robust
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#8895 Add more release-notes categories
  .github/release.yml
Labels: release-notes:build-system

#8893 Fix circular import
  src/ert/gui/plottery/plot_config_factory.py
  src/ert/gui/plottery/plot_context.py
  src/ert/gui/plottery/plots/ensemble.py
Labels: release-notes:skip

#8892 Fix timeout issue with macos-14-large
  .github/workflows/build_and_test.yml
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:skip

#8684 Save & load responses as parquet
  pyproject.toml
  src/ert/analysis/_es_update.py
  src/ert/config/ert_config.py
  src/ert/config/gen_data_config.py
  src/ert/config/observation_vector.py
  src/ert/config/observations.py
  src/ert/config/response_config.py
  src/ert/config/summary_config.py
  src/ert/dark_storage/common.py
  src/ert/dark_storage/endpoints/records.py
  src/ert/data/_measured_data.py
  src/ert/gui/ertwidgets/models/ertsummary.py
  src/ert/gui/tools/manage_experiments/storage_info_widget.py
  src/ert/gui/tools/manage_experiments/storage_widget.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/simulator/batch_simulator_context.py
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  src/ert/storage/migration/to4.py
  src/ert/storage/migration/to7.py
  tests/ert/performance_tests/test_analysis.py
  tests/ert/performance_tests/test_dark_storage_performance.py
  tests/ert/performance_tests/test_memory_usage.py
  tests/ert/ui_tests/cli/analysis/test_adaptive_localization.py
  tests/ert/ui_tests/cli/analysis/test_es_update.py
  tests/ert/ui_tests/cli/snapshots/test_cli/test_es_mda/es_mda_integration_snapshot
  tests/ert/ui_tests/gui/test_csv_export.py
  tests/ert/unit_tests/all/plugins/snapshots/test_export_misfit/test_export_misfit/0/csv_data.csv
  tests/ert/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-misfit_preprocess0/update_log
  tests/ert/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-misfit_preprocess1/update_log
  tests/ert/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-misfit_preprocess2/update_log
  tests/ert/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-misfit_preprocess3/update_log
  tests/ert/unit_tests/analysis/snapshots/test_es_update/test_update_report_with_exception_in_analysis_ES/0/error_event
  tests/ert/unit_tests/analysis/test_es_update.py
  tests/ert/unit_tests/config/observations_generator.py
  tests/ert/unit_tests/config/test_observations.py
  tests/ert/unit_tests/data/snapshots/test_integration_data/test_all_measured_snapshot/0/snake_oil_measured_output.csv
  tests/ert/unit_tests/data/test_integration_data.py
  tests/ert/unit_tests/scenarios/test_summary_response.py
  tests/ert/unit_tests/snapshots/test_libres_facade/test_misfit_collector/0/misfit_collector.csv
  tests/ert/unit_tests/storage/migration/test_version_3.py
  tests/ert/unit_tests/storage/snapshots/test_storage_migration/test_that_storage_matches/observations/FWPR
  tests/ert/unit_tests/storage/snapshots/test_storage_migration/test_that_storage_matches/observations/GEN
  tests/ert/unit_tests/storage/snapshots/test_storage_migration/test_that_storage_matches/observations/gen_data
  tests/ert/unit_tests/storage/snapshots/test_storage_migration/test_that_storage_matches/observations/summary
  tests/ert/unit_tests/storage/snapshots/test_storage_migration/test_that_storage_matches/summary_data
  tests/ert/unit_tests/storage/test_local_storage.py
  tests/ert/unit_tests/storage/test_storage_migration.py
  tests/ert/unit_tests/test_load_forward_model.py
  tests/ert/unit_tests/test_summary_response.py
Labels: release-notes:breaking-change, release-notes:bug-fix, release-notes:unreleased-feature-changes

#8901 Make histogram test not integration test & add mpl
  .github/workflows/test_ert.yml
  tests/ert/unit_tests/gui/plottery/baseline/test_histogram_log_scale-empty.png
  tests/ert/unit_tests/gui/plottery/baseline/test_histogram_log_scale-float.png
  tests/ert/unit_tests/gui/plottery/baseline/test_histogram_no_ensembles-empty.png
  tests/ert/unit_tests/gui/plottery/baseline/test_histogram_no_log_scale-categorical.png
  tests/ert/unit_tests/gui/plottery/baseline/test_histogram_no_log_scale-empty.png
  tests/ert/unit_tests/gui/plottery/baseline/test_histogram_no_log_scale-float.png
  tests/ert/unit_tests/gui/plottery/test_histogram.py
Labels: release-notes:skip

#8900 Move plottery to tools plot
  src/ert/gui/plottery/__init__.py
  src/ert/gui/plottery/plots/__init__.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/plot/__init__.py
  src/ert/gui/tools/plot/customize/color_chooser.py
  src/ert/gui/tools/plot/customize/customization_view.py
  src/ert/gui/tools/plot/customize/customize_plot_dialog.py
  src/ert/gui/tools/plot/customize/default_customization_view.py
  src/ert/gui/tools/plot/customize/limits_customization_view.py
  src/ert/gui/tools/plot/customize/statistics_customization_view.py
  src/ert/gui/tools/plot/customize/style_chooser.py
  src/ert/gui/tools/plot/customize/style_customization_view.py
  src/ert/gui/tools/plot/data_type_keys_list_model.py
  src/ert/gui/tools/plot/data_type_keys_widget.py
  src/ert/gui/tools/plot/plot_ensemble_selection_widget.py
  src/ert/gui/tools/plot/plot_widget.py
  src/ert/gui/tools/plot/plot_window.py
  src/ert/gui/tools/plot/plottery/__init__.py
  src/ert/gui/tools/plot/plottery/plot_config.py
  src/ert/gui/tools/plot/plottery/plot_config_factory.py
  src/ert/gui/tools/plot/plottery/plot_config_history.py
  src/ert/gui/tools/plot/plottery/plot_context.py
  src/ert/gui/tools/plot/plottery/plot_limits.py
  src/ert/gui/tools/plot/plottery/plot_style.py
  src/ert/gui/tools/plot/plottery/plots/__init__.py
  src/ert/gui/tools/plot/plottery/plots/cesp.py
  src/ert/gui/tools/plot/plottery/plots/distribution.py
  src/ert/gui/tools/plot/plottery/plots/ensemble.py
  src/ert/gui/tools/plot/plottery/plots/gaussian_kde.py
  src/ert/gui/tools/plot/plottery/plots/histogram.py
  src/ert/gui/tools/plot/plottery/plots/history.py
  src/ert/gui/tools/plot/plottery/plots/observations.py
  src/ert/gui/tools/plot/plottery/plots/plot_tools.py
  src/ert/gui/tools/plot/plottery/plots/statistics.py
  src/ert/gui/tools/plot/plottery/plots/std_dev.py
  src/ert/gui/tools/plot/widgets/__init__.py
  src/ert/gui/tools/plot/widgets/copy_style_to_dialog.py
  src/ert/gui/tools/plot/widgets/custom_date_edit.py
  src/ert/gui/tools/plot/widgets/filter_popup.py
  src/ert/gui/tools/plot/widgets/filterable_kw_list_model.py
  tests/ert/unit_tests/gui/plottery/test_ensemble_plot.py
  tests/ert/unit_tests/gui/plottery/test_histogram.py
  tests/ert/unit_tests/gui/plottery/test_plot_config_history.py
  tests/ert/unit_tests/gui/plottery/test_plot_limits.py
  tests/ert/unit_tests/gui/plottery/test_plot_style.py
  tests/ert/unit_tests/gui/plottery/test_stddev_plot.py
Labels: release-notes:refactor

#8903 Refactor test ecl_run
  tests/ert/unit_tests/resources/test_ecl_run_new_config.py
Labels: release-notes:refactor

#8909 Remove unused plugin code
  src/ert/plugins/hook_implementations/jobs.py
Labels: release-notes:maintenance

#8911 Remove unused help_text fm_step property
  src/ert/config/ert_config.py
  src/ert/config/forward_model_step.py
  src/ert/config/parsing/forward_model_keywords.py
  tests/ert/unit_tests/config/test_forward_model.py
Labels: release-notes:maintenance

#8919 Increase timeout of long running cli tests
  tests/ert/ui_tests/cli/analysis/test_adaptive_localization.py
Labels: release-notes:flaky-test-fix

#8922 Remove broadcasting of Eclipse stdout to multiple files
  src/ert/resources/forward-models/res/script/ecl_run.py
  tests/ert/unit_tests/resources/test_ecl_run_new_config.py
  tests/ert/unit_tests/resources/test_subprocess.py
Labels: release-notes:breaking-change

#8916 Rename jobs to forward_models in snake_oil
  test-data/ert/snake_oil/forward_models/SNAKE_OIL_DIFF
  test-data/ert/snake_oil/forward_models/SNAKE_OIL_NPV
  test-data/ert/snake_oil/forward_models/SNAKE_OIL_SIMULATOR
  test-data/ert/snake_oil/forward_models/snake_oil_diff.py
  test-data/ert/snake_oil/forward_models/snake_oil_npv.py
  test-data/ert/snake_oil/forward_models/snake_oil_simulator.py
  test-data/ert/snake_oil/snake_oil.ert
  test-data/ert/snake_oil_field/forward_models/SNAKE_OIL_DIFF
  test-data/ert/snake_oil_field/forward_models/SNAKE_OIL_NPV
  test-data/ert/snake_oil_field/forward_models/SNAKE_OIL_SIMULATOR
  test-data/ert/snake_oil_field/forward_models/snake_oil_diff.py
  test-data/ert/snake_oil_field/forward_models/snake_oil_npv.py
  test-data/ert/snake_oil_field/forward_models/snake_oil_simulator.py
  test-data/ert/snake_oil_field/snake_oil.ert
  test-data/ert/snake_oil_field/snake_oil_field.ert
  test-data/ert/snake_oil_field/snake_oil_surface.ert
Labels: release-notes:maintenance

#8918 Renamed jobmanager test files to forward_model_manager
  tests/ert/unit_tests/forward_model_runner/test_forward_model_runner.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_runner_runtime_kw.py
Labels: release-notes:misc

#8908 Rename forward-models to forward_models
  docs/ert/reference/configuration/site_wide.rst
  src/ert/plugins/hook_implementations/forward_model_steps.py
  src/ert/resources/forward_models/res/script/ecl100.py
  src/ert/resources/forward_models/res/script/ecl100_config.yml
  src/ert/resources/forward_models/res/script/ecl300.py
  src/ert/resources/forward_models/res/script/ecl300_config.yml
  src/ert/resources/forward_models/res/script/ecl_config.py
  src/ert/resources/forward_models/res/script/ecl_run.py
  src/ert/resources/forward_models/res/script/flow.py
  src/ert/resources/forward_models/templating/script/template_render.py
  tests/ert/unit_tests/resources/test_ecl_run_new_config.py
  tests/ert/unit_tests/resources/test_ecl_versioning_config.py
  tests/ert/unit_tests/resources/test_forward_models.py
  tests/ert/unit_tests/resources/test_opm_flow.py
  tests/ert/unit_tests/resources/test_templating.py
Labels: release-notes:misc

#8933 Ensure missing runpath test is ran with plugins
  tests/ert/ui_tests/cli/run_cli.py
  tests/ert/ui_tests/cli/test_missing_runpath.py
  tests/ert/ui_tests/cli/test_parameter_example.py
  tests/ert/ui_tests/cli/test_shell.py
Labels: release-notes:flaky-test-fix

#8899 Refactor BatchSimulator
  src/ert/config/ext_param_config.py
  src/ert/simulator/batch_simulator.py
  src/everest/simulator/everest_to_ert.py
  src/everest/simulator/simulator.py
  tests/ert/unit_tests/simulator/test_batch_sim.py
  tests/everest/test_egg_simulation.py
  tests/everest/test_res_initialization.py
Labels: payback, everest, release-notes:refactor

#8935 Fix run_dialog second progress bar hanging
  src/ert/gui/simulation/view/progress_widget.py
Labels: release-notes:bug-fix

#8942 Only send analysis time updates every second
  src/ert/analysis/_es_update.py
Labels: release-notes:bug-fix

#8927 Refactor and rename summary_block()
  src/ert/resources/forward_models/res/script/ecl_run.py
  tests/ert/unit_tests/resources/test_ecl_run_new_config.py
Labels: release-notes:maintenance

#8938 Give warning when memory usage is set in `LSF_RESOURCE`
  src/ert/config/parsing/config_schema_deprecations.py
Labels: release-notes:improvement

#8910 Add design matrix panel for parameters preview
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/tools/design_matrix/design_matrix_panel.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: sensitivity, release-notes:new-feature

#8953 Remove irrelavant scheduler environment checkbox in issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: release-notes:skip

#8950 Give in full file path for polars write_parquet
  src/ert/storage/local_storage.py
Labels: release-notes:unreleased-feature-changes

#8969 Remove remnant ext param in ert config dicts
  tests/everest/test_egg_simulation.py
Labels: release-notes:skip

#8045 Close Evaluator server for new connections when closing down
  src/ert/ensemble_evaluator/evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:skip

#8974 Shift doc and plugins test up one level
  tests/ert/unit_tests/all/plugins/__init__.py
  tests/ert/unit_tests/docs/__init__.py
  tests/ert/unit_tests/docs/test_ert_documentation.py
  tests/ert/unit_tests/plugins/__init__.py
  tests/ert/unit_tests/plugins/dummy_plugins.py
  tests/ert/unit_tests/plugins/snapshots/test_export_misfit/test_export_misfit/0/csv_data.csv
  tests/ert/unit_tests/plugins/test_export_misfit.py
  tests/ert/unit_tests/plugins/test_export_runpath.py
  tests/ert/unit_tests/plugins/test_misfit_preprocessor.py
  tests/ert/unit_tests/plugins/test_parameter_disable.py
  tests/ert/unit_tests/plugins/test_plugin_context.py
  tests/ert/unit_tests/plugins/test_plugin_manager.py
  tests/ert/unit_tests/plugins/test_workflow_config.py
  tests/ert/unit_tests/test_main.py
Labels: release-notes:maintenance

#8977 Give hint on REALIZATION_MEMORY on oom kills
  src/_ert/forward_model_runner/job.py
Labels: release-notes:improvement

#8954 Remove redundant/superseded Everest tests
  ci/testkomodo.sh
  pyproject.toml
  test-data/everest/math_func/config_in_constr.yml
  test-data/everest/math_func/config_out_constr.yml
  test-data/everest/math_func/readme.md
  tests/everest/test_math_func.py
Labels: release-notes:skip, everest

#8971 Add runpath validation in gui load_results_manually
  src/ert/gui/ertwidgets/__init__.py
  src/ert/gui/ertwidgets/multilinestringbox.py
  src/ert/gui/tools/load_results/load_results_panel.py
  src/ert/gui/tools/load_results/load_results_tool.py
  src/ert/validation/__init__.py
  src/ert/validation/runpath_argument.py
Labels: release-notes:improvement

#8978 Merge marker used for simulation fw models in Everest and Ert
  ci/testkomodo.sh
  pyproject.toml
  tests/everest/test_egg_simulation.py
  tests/everest/test_res_initialization.py
Labels: release-notes:skip, everest

#8979 Update type of usecols in _read_excel
  src/ert/config/design_matrix.py
Labels: release-notes:skip

#8982 Remove unused constants in tests
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:skip

#8986 Fix flaky ensemble_evaluator unit test
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:flaky-test-fix

#8988 Move template_render.py up two levels
  src/ert/plugins/hook_implementations/forward_model_steps.py
  src/ert/resources/forward_models/template_render.py
  tests/ert/unit_tests/resources/test_templating.py
Labels: release-notes:maintenance

#8991 Attempt to mitigate flaky cpu polling test
  tests/ert/unit_tests/forward_model_runner/test_job.py
Labels: release-notes:flaky-test-fix

#8980 Improve validation for unintialized ensembles in manual update and evaluate ensemble
  src/ert/gui/simulation/evaluate_ensemble_panel.py
  src/ert/gui/simulation/manual_update_panel.py
  src/ert/validation/__init__.py
  src/ert/validation/ensemble_realizations_argument.py
Labels: release-notes:improvement

#8992 Fix flaky warning test
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:flaky-test-fix

#8989 Fix progress bar legend getting cut when loading bar shows
  src/ert/gui/simulation/view/progress_widget.py
Labels: release-notes:bug-fix

#8999 Remove testing of execute bit of plugin-scripts
  tests/ert/unit_tests/resources/test_forward_models.py
Labels: release-notes:flaky-test-fix

#9005 Fix bug with time format for Slurms max_runtime
  src/ert/scheduler/slurm_driver.py
  tests/ert/unit_tests/scheduler/test_slurm_driver.py
Labels: release-notes:bug-fix

#9008 Improve error messages on test komodo failures
  ci/testkomodo.sh
Labels: release-notes:skip

#9023 Make InvalidResponseFile and FileNotFoundError part of read_from_file
  src/ert/callbacks.py
  src/ert/config/__init__.py
  src/ert/config/_read_summary.py
  src/ert/config/gen_data_config.py
  src/ert/config/response_config.py
  src/ert/config/summary_config.py
  tests/ert/unit_tests/config/test_gen_data_config.py
  tests/ert/unit_tests/config/test_read_summary.py
  tests/ert/unit_tests/config/test_summary_config.py
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:bug-fix

#9026 Rename substitution_list to substitutions
  src/ert/config/ert_config.py
  src/ert/config/forward_model_step.py
  src/ert/config/workflow.py
  src/ert/enkf_main.py
  src/ert/gui/tools/export/export_panel.py
  src/ert/libres_facade.py
  src/ert/plugins/hook_implementations/workflows/export_runpath.py
  src/ert/run_models/base_run_model.py
  src/ert/runpaths.py
  src/ert/simulator/batch_simulator_context.py
  src/ert/substitutions.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_forward_model.py
  tests/ert/unit_tests/config/test_forward_model_data_to_json.py
  tests/ert/unit_tests/conftest.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_runner.py
  tests/ert/unit_tests/run_models/test_base_run_model.py
  tests/ert/unit_tests/storage/create_runpath.py
  tests/ert/unit_tests/test_enkf_main.py
  tests/ert/unit_tests/test_run_path_creation.py
  tests/ert/unit_tests/test_runpaths.py
  tests/ert/unit_tests/test_substitution_list.py
  tests/ert/unit_tests/workflow_runner/test_workflow.py
  tests/ert/unit_tests/workflow_runner/test_workflow_runner.py
Labels: release-notes:refactor

#9029 Backport logging fix
  src/ert/callbacks.py
  src/ert/config/__init__.py
  src/ert/config/_read_summary.py
  src/ert/config/gen_data_config.py
  src/ert/config/response_config.py
  src/ert/config/summary_config.py
  tests/unit_tests/config/test_gen_data_config.py
  tests/unit_tests/config/test_read_summary.py
  tests/unit_tests/config/test_summary_config.py
Labels: release-notes:bug-fix

#9022 Rename job.py to fm_step.py and Job to ForwardModelStep
  src/_ert/forward_model_runner/__init__.py
  src/_ert/forward_model_runner/forward_model_step.py
  src/_ert/forward_model_runner/reporting/message.py
  src/_ert/forward_model_runner/runner.py
  tests/ert/unit_tests/forward_model_runner/test_event_reporter.py
  tests/ert/unit_tests/forward_model_runner/test_file_reporter.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
  tests/ert/unit_tests/forward_model_runner/test_job_dispatch.py
Labels: release-notes:maintenance

#9034 Only send analysis time updates every second
  src/ert/analysis/_es_update.py
Labels: release-notes:bug-fix

#8985 Explain why we read from excel twice
  src/ert/config/design_matrix.py
Labels: release-notes:skip

#9038 Less aggressive LSF
  src/ert/scheduler/lsf_driver.py
Labels: release-notes:maintenance

#9039 Remove incorrect everest tests
  ci/testkomodo.sh
Labels: release-notes:maintenance

#9046 Add _verify_checksum lock in job.py
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/ert/unit_tests/scheduler/test_job.py
Labels: release-notes:improvement

#9048 Fix <= .to3 migrations causing .to7 gendata migration failure
  src/ert/storage/migration/to7.py
  tests/ert/unit_tests/storage/snapshots/test_storage_migration/test_that_storage_matches/gen_data
  tests/ert/unit_tests/storage/test_storage_migration.py
Labels: release-notes:bug-fix

#9020 Change job to forward model step in strings
  src/_ert/forward_model_runner/reporting/file.py
Labels: release-notes:maintenance

#8703 Move tool buttons to side pane
  src/ert/gui/main.py
  src/ert/gui/main_window.py
  src/ert/gui/resources/gui/img/in_progress.svg
  src/ert/gui/resources/gui/img/library_add.svg
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/summarypanel.py
  src/ert/gui/tools/manage_experiments/__init__.py
  src/ert/gui/tools/manage_experiments/manage_experiments_tool.py
  src/ert/gui/tools/plot/__init__.py
  src/ert/gui/tools/plot/plot_tool.py
  src/ert/gui/tools/plugins/plugins_tool.py
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure0-0.png
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure1-0.png
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure2-0.png
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3-0.png
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure4-0.png
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure5-0.png
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure6-0.png
  tests/ert/ui_tests/gui/conftest.py
  tests/ert/ui_tests/gui/test_csv_export.py
  tests/ert/ui_tests/gui/test_full_manual_update_workflow.py
  tests/ert/ui_tests/gui/test_load_results_manually.py
  tests/ert/ui_tests/gui/test_main_window.py
  tests/ert/ui_tests/gui/test_missing_runpath.py
  tests/ert/ui_tests/gui/test_plotting_of_snake_oil.py
  tests/ert/ui_tests/gui/test_restart_ensemble_experiment.py
  tests/ert/ui_tests/gui/test_restart_esmda.py
  tests/ert/ui_tests/gui/test_rft_export_plugin.py
  tests/ert/ui_tests/gui/test_single_test_run.py
  tests/ert/ui_tests/gui/test_workflow_tool.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
  tests/ert/unit_tests/gui/simulation/test_run_path_dialog.py
Labels: release-notes:user-impact

#9052 Add REALIZATION_MEMORY to init_site_config_schema
  src/ert/config/parsing/config_schema.py
Labels: release-notes:unreleased-bug-fix

#9054 Fix missing realization type in Simulation label
  src/ert/gui/main_window.py
  tests/ert/ui_tests/gui/test_main_window.py
Labels: release-notes:skip

#9056 Document and rename parameter example test
  tests/ert/ui_tests/cli/test_parameter_passing.py
Labels: release-notes:skip

#9066 Fix second progressbar
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/progress_widget.py
  tests/ert/ui_tests/gui/test_missing_runpath.py
Labels: release-notes:unreleased-bug-fix

#9068 Fix ert crashes if invalid range string in REPORT_STEPS config
  src/ert/config/gen_data_config.py
  tests/ert/unit_tests/config/test_gen_data_config.py
Labels: release-notes:bug-fix

#9069 Rename job to step in runner
  src/_ert/forward_model_runner/runner.py
  tests/ert/unit_tests/forward_model_runner/test_file_reporter.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_runner.py
  tests/ert/unit_tests/forward_model_runner/test_job_dispatch.py
Labels: release-notes:maintenance

#9055 Fix typo in variable name in testkomodo.sh
  ci/testkomodo.sh
Labels: release-notes:skip

#9067 Have run simulation button disabled when running
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:skip

#9076 Make minimum_case minimal
  tests/ert/conftest.py
Labels: release-notes:skip

#9084 Allow dark mode color scheme in side panel
  src/ert/gui/main_window.py
Labels: release-notes:skip

#9107 Test field update using heat equation instead of poly
  tests/ert/ui_tests/cli/test_field_parameter.py
Labels: release-notes:skip

#9074 Add readthedocs for everest
  docs/everest/.readthedocs.yaml
Labels: release-notes:documentation

#9097 Remove iEverest
  .github/workflows/test_ert.yml
  .github/workflows/test_everest.yml
  .mypy.ini
  ci/testkomodo.sh
  docs/everest/cli.rst
  pyproject.toml
  src/everest/bin/main.py
  src/ieverest/__init__.py
  src/ieverest/bin/__init__.py
  src/ieverest/bin/ieverest_script.py
  src/ieverest/config_widget.py
  src/ieverest/ieverest.py
  src/ieverest/io/__init__.py
  src/ieverest/io/output_dispatcher.py
  src/ieverest/io/qt_dialogs_output.py
  src/ieverest/io/qt_status_bar_output.py
  src/ieverest/main_window.py
  src/ieverest/monitor_widget.py
  src/ieverest/settings.py
  src/ieverest/ui/batch_status_widget.ui
  src/ieverest/ui/config_widget.ui
  src/ieverest/ui/export_dialog.ui
  src/ieverest/ui/main_window.ui
  src/ieverest/ui/monitor_widget.ui
  src/ieverest/ui/startup_widget.ui
  src/ieverest/utils.py
  src/ieverest/widgets/__init__.py
  src/ieverest/widgets/batch_status_widget.py
  src/ieverest/widgets/export_data_dialog.py
  src/ieverest/widgets/plot_widget.py
  tests/everest/entry_points/test_everest_entry.py
  tests/everest/functional/test_ui.py
  tests/everest/test_export_data_dialog.py
  tests/everest/test_qt_dialogs_output.py
  tests/everest/test_ui_run.py
Labels: release-notes:breaking-change

#9091 Have cli tests set env variable OMP_NUM_THREADS to 1.
  tests/ert/ui_tests/cli/conftest.py
Labels: release-notes:flaky-test-fix

#9087 Make plot_api return all observations for response
  src/ert/gui/tools/plot/plot_api.py
  tests/ert/unit_tests/gui/tools/plot/conftest.py
  tests/ert/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:bug-fix
