Repository equinor/ert, pull requests merged in 2024-06, with the labels that each got.

#8002 Add report for auto scaling of observations
  src/ert/analysis/_es_update.py
  src/ert/analysis/event.py
  src/ert/analysis/misfit_preprocessor.py
  src/ert/analysis/snapshots.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/update.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/event.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/analysis/test_misfit_preprocessor.py
  tests/unit_tests/gui/run_analysis/test_update_widget.py
Labels: release-notes:improvement

#8044 Fix copyablelabel not crashing when there is no clipboard
  src/ert/gui/ertwidgets/copyablelabel.py
Labels: release-notes:skip

#8040 Delete start iteration
  src/ert/run_models/base_run_model.py
  src/ert/run_models/run_arguments.py
  tests/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:skip

#8050 Rename to get_realization_with_responses and return array
  src/ert/shared/hook_implementations/workflows/export_misfit_data.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  src/ert/storage/local_ensemble.py
  tests/integration_tests/test_storage_migration.py
Labels: release-notes:skip

#8061 New LSF driver should allocate correct number of cpus based on config
  src/ert/config/queue_config.py
  src/ert/scheduler/__init__.py
  src/ert/scheduler/lsf_driver.py
  tests/integration_tests/scheduler/bin/bsub
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:bug-fix

#8068 Get lsf jobid at the right time
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: scheduler

#8062 Use the same seed throughout the run models
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/integration_tests/test_cli.py
Labels: release-notes:bug-fix

#8084 Don't cast array to np.array
  src/ert/storage/local_ensemble.py
Labels: release-notes:skip

#8060 Fix flaky integration test `test_generic_driver.py::test_kill_actuall…
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: flaky-test, release-notes:skip

#8039 Fix resizing of experiment manager on macos
  src/ert/gui/ertwidgets/storage_info_widget.py
  src/ert/gui/ertwidgets/storage_widget.py
  src/ert/gui/tools/manage_experiments/ensemble_init_configuration.py
  src/ert/gui/tools/manage_experiments/manage_experiments_tool.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:improvement

#8082 Add positive_int validation schema for NUM_CPU and MAX_SUBMIT
  src/ert/config/parsing/config_schema.py
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/parsing/schema_item_type.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/config/test_num_cpu.py
  tests/unit_tests/config/test_queue_config.py
Labels: configuration, release-notes:skip

#8092 Retry bsub when output is empty
  src/ert/scheduler/driver.py
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: bug, release-notes:bug-fix

#8094 Let LSFDriver pick num_cpu from the realization object
  src/ert/config/queue_config.py
  src/ert/scheduler/__init__.py
  src/ert/scheduler/driver.py
  src/ert/scheduler/job.py
  src/ert/scheduler/local_driver.py
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:bug-fix

#8102 Fix num_cpu LSF integration test
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#8103 Remove current memory usage from run details view
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:improvement

#8107 Increate grace time for kill and change logger.error to logger.debug
  src/ert/scheduler/scheduler.py
Labels: release-notes:skip

#8108 Fix lsf integration test
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#8111 Fix an issue where the about_panel didn't work
  src/ert/gui/about_dialog.py
Labels: release-notes:skip

#8104 Ensure WAITING state is set on resubmissions
  src/ert/scheduler/job.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:bug-fix

#8113 Remove un-used VariableInfo type
  src/ert/config/analysis_module.py
Labels: release-notes:maintenance

#8106 Type check suggestor
  .mypy.ini
  src/ert/gui/suggestor/_suggestor_message.py
  src/ert/gui/suggestor/suggestor.py
Labels: release-notes:skip

#8051 Rafactor Snapshot Metadata to be TypedDict
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/model/snapshot.py
Labels: improvement, release-notes:skip

#8119 Update tooltip text for plot ensemble selector
  src/ert/gui/tools/plot/plot_ensemble_selection_widget.py
Labels: release-notes:skip

#8041 Move report writing to client
  pyproject.toml
  src/ert/analysis/_es_update.py
  src/ert/analysis/event.py
  src/ert/cli/main.py
  src/ert/cli/monitor.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/run_analysis/run_analysis_tool.py
  src/ert/libres_facade.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/event.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/shared/exporter.py
  tests/integration_tests/analysis/snapshots/test_es_update/test_update_report/using_job_queue/update_log
  tests/integration_tests/analysis/snapshots/test_es_update/test_update_report/using_scheduler/update_log
  tests/integration_tests/analysis/test_es_update.py
  tests/integration_tests/test_cli.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_only_using_subset_observations/0/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-misfit_preprocess0/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-misfit_preprocess1/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-misfit_preprocess2/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-misfit_preprocess3/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report_with_exception_in_analysis_ES/0/error_event
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/run_analysis/test_update_widget.py
  tests/unit_tests/scenarios/test_summary_response.py
Labels: release-notes:new-feature

#8121 Fix incorrect AlignBottom enum
  src/ert/gui/tools/plugins/process_job_dialog.py
  src/ert/gui/tools/workflows/run_workflow_widget.py
Labels: release-notes:bug-fix

#8123 Add test for workflow tool
  tests/unit_tests/gui/tools/test_workflow_tool.py
Labels: release-notes:skip

#8131 Remove duplicate section regarding templates
  docs/reference/configuration/data_types.rst
Labels: release-notes:skip

#8133 Validate number of arguments for workflows
  src/ert/config/workflow.py
  tests/unit_tests/job_queue/test_workflow.py
Labels: release-notes:improvement

#8129 Delete template model concept from docs
  docs/developer_documentation/concepts.rst
Labels: documentation

#8138 Simplify base run model validation
  src/ert/run_models/base_run_model.py
Labels: release-notes:maintenance

#8154 Combine error and warning boxes that have the same message
  src/ert/gui/suggestor/_suggestor_message.py
  src/ert/gui/suggestor/suggestor.py
  tests/unit_tests/gui/test_suggestor.py
Labels: release-notes:user-impact

#8165 Only log INFO messages from websockets
  src/ert/logging/logger.conf
Labels: release-notes:misc

#8167 Ignore SIGNAL_OFFSET in assering exit_code from LSF
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: flaky-test, release-notes:skip

#8164 Change order of data vars in test to reflect reality
  tests/integration_tests/analysis/test_es_update.py
Labels: release-notes:skip

#8152 Replacing progress view with progress widget
  src/ert/ensemble_evaluator/event.py
  src/ert/gui/model/progress_proxy.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/__init__.py
  src/ert/gui/simulation/view/legend.py
  src/ert/gui/simulation/view/progress.py
  src/ert/gui/simulation/view/progress_widget.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/cli/test_cli_monitor.py
  tests/unit_tests/gui/model/test_progress_proxy.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/gui/simulation/view/test_legend.py
Labels: release-notes:maintenance

#8181 Fix typo reviced -> received
  src/ert/scheduler/scheduler.py
Labels: release-notes:skip

#8158 Enable ruff preview checks
  pyproject.toml
Labels: release-notes:maintenance

#8100 Add migration check for newer storage
  src/ert/storage/local_storage.py
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:improvement

#7886 Add ctrl+c copy in update report
  src/ert/gui/simulation/view/update.py
Labels: release-notes:improvement

#8197 Reset simulation endtime when restarting simulation
  src/ert/run_models/base_run_model.py
Labels: release-notes:maintenance

#7915 Refactor Lsf driver to use dataclasses
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: improvement, release-notes:skip

#7953 Refactor OpenPBS driver to use dataclasses
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: improvement, release-notes:skip

#8174 Add more tests for the experiment manager GUI
  tests/unit_tests/gui/tools/test_ensemble_tool.py
  tests/unit_tests/gui/tools/test_manage_experiments_tool.py
Labels: release-notes:skip

#8190 Set max_submit to 1 in job.py
  src/ert/scheduler/job.py
Labels: release-notes:skip

#8163 Deprecate NUM_NODES and NUM_CPUS_PER_NODE in Torque/OpenPBS driver
  docs/reference/configuration/queue.rst
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/config/queue_config.py
  src/ert/scheduler/__init__.py
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:maintenance

#8182 Increase responsiveness of run dialog under heavy load
  src/ert/cli/monitor.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/identifiers.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/model/snapshot.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/ensemble_evaluator/test_snapshot.py
Labels: release-notes:improvement

#8209 Remove builder pattern for Realization objects
  src/ert/ensemble_evaluator/__init__.py
  src/ert/ensemble_evaluator/_builder/__init__.py
  src/ert/ensemble_evaluator/_builder/_ensemble_builder.py
  src/ert/ensemble_evaluator/_builder/_realization.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
Labels: release-notes:maintenance

#8210 Remove unused functionality on EnsembleBuilder
  src/ert/ensemble_evaluator/__init__.py
  src/ert/ensemble_evaluator/_builder/__init__.py
  src/ert/ensemble_evaluator/_builder/_ensemble_builder.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/ensemble_evaluator/test_scheduler.py
Labels: release-notes:maintenance

#8212 Convert dict access of ForwardModel to .get() to avoid segfaults
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/gui/model/snapshot.py
Labels: release-notes:skip

#8160 Type check ert.gui
  .mypy.ini
  src/ert/gui/ertwidgets/listeditbox.py
  src/ert/gui/plottery/plot_config.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/evaluate_ensemble_panel.py
  src/ert/gui/simulation/experiment_config_panel.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/queue_emitter.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/progress_widget.py
  src/ert/gui/simulation/view/realization.py
  src/ert/gui/simulation/view/update.py
  src/ert/gui/tools/export/export_tool.py
  src/ert/gui/tools/file/file_dialog.py
  src/ert/gui/tools/load_results/load_results_panel.py
  src/ert/gui/tools/load_results/load_results_tool.py
  src/ert/gui/tools/manage_experiments/ensemble_init_configuration.py
  src/ert/gui/tools/manage_experiments/manage_experiments_tool.py
  src/ert/gui/tools/plot/color_chooser.py
  src/ert/gui/tools/plot/customize/__init__.py
  src/ert/gui/tools/plot/customize/customization_view.py
  src/ert/gui/tools/plot/customize/customize_plot_dialog.py
  src/ert/gui/tools/plot/customize/limits_customization_view.py
  src/ert/gui/tools/plot/customize/statistics_customization_view.py
  src/ert/gui/tools/plot/customize/style_customization_view.py
  src/ert/gui/tools/plot/data_type_keys_list_model.py
  src/ert/gui/tools/plot/data_type_keys_widget.py
  src/ert/gui/tools/plot/data_type_proxy_model.py
  src/ert/gui/tools/plot/filter_popup.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/gui/tools/plot/plot_ensemble_selection_widget.py
  src/ert/gui/tools/plot/plot_widget.py
  src/ert/gui/tools/plot/plot_window.py
  src/ert/gui/tools/plot/style_chooser.py
  src/ert/gui/tools/plot/widgets/clearable_line_edit.py
  src/ert/gui/tools/plot/widgets/custom_date_edit.py
  src/ert/gui/tools/plugins/plugin.py
  src/ert/gui/tools/plugins/plugin_handler.py
  src/ert/gui/tools/plugins/plugin_runner.py
  src/ert/gui/tools/plugins/plugins_tool.py
  src/ert/gui/tools/plugins/process_job_dialog.py
  src/ert/gui/tools/run_analysis/run_analysis_panel.py
  src/ert/gui/tools/run_analysis/run_analysis_tool.py
  src/ert/gui/tools/tool.py
  src/ert/gui/tools/workflows/run_workflow_widget.py
  src/ert/gui/tools/workflows/workflow_dialog.py
  src/ert/gui/tools/workflows/workflows_tool.py
  src/ert/run_models/__init__.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/model_factory.py
  src/ert/shared/exporter.py
Labels: release-notes:skip

#8216 Join Ensemble and LegacyEnsemble
  src/ert/ensemble_evaluator/__init__.py
  src/ert/ensemble_evaluator/_builder/__init__.py
  src/ert/ensemble_evaluator/_builder/_ensemble.py
  src/ert/ensemble_evaluator/_builder/_realization.py
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/run_models/base_run_model.py
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_state_tracker.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:maintenance

#8134 Update docs of FIELD keyword
  docs/reference/configuration/data_types.rst
  docs/reference/configuration/keywords.rst
Labels: documentation

#8228 Remove dead test utility code
  tests/integration_tests/scheduler/bin/bhist.py
  tests/integration_tests/scheduler/bin/bjobs.py
Labels: release-notes:skip

#8218 Sort output of expand wildards and add tests
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#8179 Refactor realization delegate
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/view/realization.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/model/test_snapshot.py
Labels: release-notes:improvement, release-notes:user-impact

#8225 Add blue color and underscore to STDOUT and STDERR in job view
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:improvement

#8256 Fix bug in LSF driver resource manipulation
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:bug-fix

#8250 Catch XML errors when logging error file
  src/ert/scheduler/job.py
  tests/unit_tests/scheduler/test_job.py
Labels: release-notes:misc

#8258 Ensure unique parameter & response names in test
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#8248 Add validation for FIELD parameter name
  docs/reference/configuration/keywords.rst
  src/ert/config/field.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_field.py
Labels: release-notes:improvement

#8262 Mitigate flakyness in test_slurm_driver
  tests/integration_tests/scheduler/test_slurm_driver.py
Labels: release-notes:skip
