Repository equinor/ert, pull requests merged in 2024-02, with the labels that each got.

#7066 simplify testing of create_runpath
  tests/unit_tests/storage/create_runpath.py
  tests/unit_tests/storage/test_field_parameter.py
  tests/unit_tests/storage/test_parameter_sample_types.py
Labels: release-notes:skip

#7073 Fix typo in typing
  src/ert/shared/_doc_utils/ert_jobs.py
Labels: release-notes:skip

#7072 Test semeio with python 3.11
  .github/workflows/test_semeio.yml
Labels: release-notes:skip

#7050 Change some local storage tests to stateful
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#7060 Speed up local_experiment
  src/ert/storage/local_experiment.py
Labels: release-notes:skip

#7077 Fix flakiness for gui unit_tests
  tests/integration_tests/scheduler/test_integration_local_driver.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/gui/test_main_window.py
Labels: flaky-test, release-notes:skip

#7084 Add field and observations to state storage test
  tests/unit_tests/config/egrid_generator.py
  tests/unit_tests/storage/test_local_ensemble.py
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#7082 Remove unused include
  src/clib/lib/job_queue/lsf_driver.cpp
Labels: release-notes:skip

#7059 Make updating work with failed realizations
  src/ert/config/gen_kw_config.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/storage/local_ensemble.py
  tests/integration_tests/analysis/test_es_update.py
Labels: release-notes:bug-fix

#7080 Fix migration from 8.0.12 to 8.4.x
  src/ert/storage/local_storage.py
Labels: release-notes:bug-fix

#7094 Fix test data generation failing
  tests/unit_tests/config/test_transfer_functions.py
Labels: release-notes:skip

#7095 Update codecov uploader
  .github/workflows/build_and_test.yml
  .github/workflows/coverage.yml
  .github/workflows/doctest.yml
Labels: release-notes:skip

#7056 Replace some tests with an integration test
  tests/integration_tests/test_parameter_example.py
  tests/unit_tests/storage/test_field_parameter.py
  tests/unit_tests/storage/test_local_ensemble.py
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#7100 Remove setAlignment that just loops forever
  src/ert/gui/ertwidgets/stringbox.py
Labels: release-notes:skip

#7109 Fix ert dark storage performance tests
  src/ert/dark_storage/common.py
Labels: bug

#7108 Add alias NAMES for WGNAMES and fix network vars
  src/ert/config/_read_summary.py
  tests/unit_tests/config/summary_generator.py
  tests/unit_tests/config/test_read_summary.py
Labels: release-notes:skip

#7119 pin iterative_ensemble_smoother
  pyproject.toml
Labels: release-notes:skip

#7110 Fix flaky unit test test_submit_sleep_with_max_running
  tests/unit_tests/scheduler/test_scheduler.py
Labels: flaky-test, release-notes:skip

#7118 Fix a performance problem with summary reading
  src/ert/config/_read_summary.py
Labels: release-notes:skip

#7114 Get progress from adaptive localization
  pyproject.toml
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#7117 Improve plotting performance in GUI
  src/ert/dark_storage/endpoints/records.py
Labels: release-notes:skip

#7111 Remove benchmarking files not in use
  .benchmarks/Linux-CPython-3.8-64bit/0001_benchmark-dark-storage-github-actions.json
  .benchmarks/Linux-CPython-3.8-64bit/0002_benchmark-dark-storage-github-actions.json
Labels: maintenance, release-notes:skip

#7063 Fix bug where one missing index.json caused no ensembles to be loaded
  src/ert/storage/local_storage.py
Labels: release-notes:bug-fix

#7135 Fix text color for darkmode in suggestor window
  src/ert/gui/suggestor/suggestor.py
Labels: release-notes:misc

#7133 Filter out deprecation warnings from main entry point
  src/ert/__main__.py
  src/ert/services/_storage_main.py
Labels: release-notes:maintenance

#7032 Don't create remove button in Manage Cases
  src/ert/gui/ertwidgets/caselist.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_main_window.py
Labels: maintenance, release-notes:skip

#7146 Fix a regression of using REFCASE with extension
  src/ert/config/_read_summary.py
  tests/unit_tests/config/test_observations.py
Labels: release-notes:bug-fix

#7129 Store experiment name in index.json
  src/ert/cli/model_factory.py
  src/ert/namespace.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/run_models/run_arguments.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  tests/unit_tests/cli/test_model_factory.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
  tests/unit_tests/run_models/test_base_run_model.py
  tests/unit_tests/run_models/test_ensemble_experiment.py
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#7159 Ensure local queue in tests with site config
  tests/integration_tests/storage/test_field_parameter.py
  tests/integration_tests/storage/test_parameter_sample_types.py
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_observation_times.py
  tests/integration_tests/test_parameter_example.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:skip

#7153 Always say job has started if an event is received
  src/ert/scheduler/scheduler.py
Labels: release-notes:skip

#7155 Add logging to PBS driver
  src/ert/scheduler/openpbs_driver.py
Labels: release-notes:skip

#7167 Fix incorrect import of xtgeo.gridproperty_from_file
  tests/integration_tests/storage/test_field_parameter.py
Labels: release-notes:skip

#7171 Skip export misfit data job test on mac
  tests/unit_tests/all/plugins/test_export_misfit.py
Labels: release-notes:skip

#7174 Fix issue with parameter_example test
  tests/integration_tests/test_parameter_example.py
Labels: release-notes:skip

#7177 Add logger for Azure to see usage of scheduler/job_queue
  src/ert/ensemble_evaluator/_builder/_legacy.py
Labels: improvement, release-notes:misc

#7180 Test LSF returncodes
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#7182 Remove parsing of config from dark storage
  src/ert/__main__.py
  src/ert/dark_storage/app.py
  src/ert/dark_storage/enkf.py
  src/ert/gui/main.py
  src/ert/services/_storage_main.py
  src/ert/services/storage_service.py
  tests/unit_tests/dark_storage/conftest.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/gui/simulation/test_run_path_dialog.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/gui/test_rft_export_plugin.py
Labels: release-notes:skip

#7181 Remove unused format_mode
  src/ert/cli/model_factory.py
  src/ert/gui/ertwidgets/models/targetcasemodel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  tests/unit_tests/cli/test_model_factory.py
Labels: release-notes:skip

#7189 Use get function instead of if block
  src/ert/gui/plottery/plots/histogram.py
Labels: maintenance, release-notes:skip

#7190 Use copy fixtures consistently
  tests/conftest.py
  tests/integration_tests/analysis/test_adaptive_localization.py
  tests/integration_tests/analysis/test_es_update.py
  tests/integration_tests/scheduler/test_openpbs_driver.py
  tests/integration_tests/status/test_tracking_integration.py
  tests/integration_tests/test_cli.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/test_enkf_runpath.py
Labels: release-notes:skip

#7140 Use newer macOS runners and build and test using also python 3.11 & 3.12
  .github/workflows/build-wheels-macos.yml
  .github/workflows/build_and_test.yml
  .github/workflows/run_ert_test_data_setups.yml
Labels: release-notes:maintenance

#7200 Increase max_running for test_that_long_running_jobs_were_stopped
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip, scheduler

#7198 Add test for queue name in LSF driver
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip, scheduler

#7199 Avoid generating the starting date in observations
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/observations_generator.py
Labels: release-notes:skip

#7196 Revert skipping test export misfit causing tables illegal instruction on macos
  tests/unit_tests/all/plugins/test_export_misfit.py
Labels: release-notes:maintenance

#7216 Fix semeio test in CI
  .github/workflows/test_semeio.yml
Labels: bug, release-notes:skip

#7173 Update general observation error message when no timemap or reference is provided.
  src/ert/config/observations.py
  tests/unit_tests/config/test_ert_config.py
Labels: maintenance

#7220 Improve readability of stateful storage test
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#7222 Add support for MEMORY_PER_JOB in OpenPBS
  src/ert/scheduler/__init__.py
  src/ert/scheduler/openpbs_driver.py
  tests/integration_tests/scheduler/bin/qsub
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: scheduler

#7218 Set default pytest timeout of 240s
  .github/workflows/test_ert.yml
  pyproject.toml
Labels: maintenance, release-notes:skip

#7230 Add missing space in ConfigWarning msg
  src/ert/config/ert_config.py
Labels: release-notes:skip

#7234 Ensure Summary Response is not empty
  src/ert/config/ensemble_config.py
  src/ert/config/ert_config.py
  src/ert/config/observations.py
  src/ert/config/summary_config.py
  tests/unit_tests/config/test_observations.py
  tests/unit_tests/config/test_summary_config.py
Labels: release-notes:bug-fix

#7141 Clarify error for non-UTF-8 encoded data in runpath setup
  docs/reference/configuration/keywords.rst
  src/ert/enkf_main.py
  tests/unit_tests/test_run_path_creation.py
Labels: release-notes:maintenance

#7241 Reduce logging level of most noisy logs
  src/clib/lib/job_queue/lsf_driver.cpp
  src/clib/lib/job_queue/slurm_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/ert/callbacks.py
  src/ert/job_queue/job_queue_node.py
Labels: release-notes:skip

#7243 Support (in new PBS driver) and deprecate JOB_PREFIX
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/scheduler/__init__.py
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/config/parsing/test_config_schema_deprecations.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:maintenance, scheduler

#7244 Specify diffing per file extension
  .gitattributes
Labels: release-notes:skip

#7237 update methods/classes that use deprecated pydantic api
  src/ert/config/analysis_iter_config.py
  src/ert/config/analysis_module.py
  src/ert/config/parsing/config_errors.py
  src/ert/config/parsing/config_schema_item.py
  src/ert/dark_storage/endpoints/ensembles.py
  src/ert/dark_storage/endpoints/experiments.py
  src/ert/dark_storage/json_schema/ensemble.py
  src/ert/dark_storage/json_schema/experiment.py
  src/ert/dark_storage/json_schema/observation.py
  src/ert/dark_storage/json_schema/record.py
  src/ert/dark_storage/json_schema/update.py
  src/ert/ensemble_evaluator/snapshot.py
  tests/performance_tests/test_snapshot.py
  tests/unit_tests/cli/test_cli_monitor.py
Labels: release-notes:skip

#7031 Add property to check storage availability
  src/ert/gui/ertnotifier.py
  src/ert/gui/ertwidgets/caseselector.py
  src/ert/gui/tools/plugins/plugin.py
Labels: release-notes:skip

#7183 Extract determining restart info into function
  src/ert/cli/model_factory.py
Labels: release-notes:skip

#7030 Remove unused _active_realizations_model
  src/ert/gui/simulation/single_test_run_panel.py
Labels: release-notes:skip

#7258 Extract batch-size calculation to function
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#7253 Replace gstools with scipy
  pyproject.toml
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:skip

#7267 Fix default in _iterative_case_format
  src/ert/cli/model_factory.py
Labels: release-notes:skip

#7271 Use Trusted publishing for PyPi
  .github/workflows/build_and_test.yml
Labels: release-notes:maintenance

#7272 Use Trusted publishing for PyPi
  .github/workflows/build_and_test.yml
Labels: release-notes:maintenance

#7274 Increase gui test timeout period
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: flaky-test, release-notes:skip

#7148 Gather all observation configuration errors before reporting to user
  src/ert/config/ert_config.py
  src/ert/config/observations.py
  src/ert/config/parsing/observations_parser.py
  tests/unit_tests/config/parsing/test_observations_parser.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_observations.py
Labels: release-notes:misc

#7280 Revert "Forward exceptions from threads to main thread"
  pyproject.toml
  src/_ert_job_runner/reporting/event.py
  src/ert/cli/main.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/ensemble_evaluator/dispatch.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/evaluator_tracker.py
  src/ert/ensemble_evaluator/sync_ws_duplexer.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/plugins/plugin_runner.py
  src/ert/gui/tools/workflows/run_workflow_widget.py
  src/ert/job_queue/job_queue_node.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/scheduler.py
  src/ert/shared/threading.py
  src/ert/simulator/simulation_context.py
  tests/conftest.py
  tests/integration_tests/status/test_tracking_integration.py
  tests/integration_tests/test_cli.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_client.py
  tests/unit_tests/ensemble_evaluator/test_sync_ws_duplexer.py
  tests/unit_tests/shared/test_threading.py
  tests/utils.py
Labels: release-notes:skip

#7238 Support NUM_NODES and NUM_CPUS_PER_NODE in OpenPBS driver
  src/ert/scheduler/__init__.py
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip, scheduler

#7264 Add test function combining max_submit and max_runtime
  src/ert/scheduler/job.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#7283 Replace use of TypedDict with dataclasses in observation parser
  src/ert/config/ert_config.py
  src/ert/config/observations.py
  src/ert/config/parsing/observations_parser.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/parsing/test_observations_parser.py
Labels: release-notes:skip

#7136 Storage Server no longer exists so delete it from docs
  .github/workflows/build_and_test.yml
  docs/conf.py
  docs/developer_documentation/storage_server.rst
  docs/developer_documentation/storage_server_er_diagram.plantuml
  docs/index.rst
  pyproject.toml
Labels: documentation

#7287 Fix the codecov retry
  .github/workflows/build_and_test.yml
  .github/workflows/coverage.yml
  .github/workflows/doctest.yml
Labels: release-notes:skip

#7288 Use lowercase for observation dataclasses
  src/ert/config/ert_config.py
  src/ert/config/observations.py
  src/ert/config/parsing/observations_parser.py
  tests/unit_tests/config/parsing/test_observations_parser.py
Labels: release-notes:skip

#7191 Add _execute_with_retry to pbs driver
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip, scheduler

#7285 Remove unused state TIME_MAP_FAILURE
  src/ert/job_queue/job_queue_node.py
  src/ert/load_status.py
  src/ert/scheduler/job.py
Labels: release-notes:skip

#7290 Add config test for num_cpu vs torque queue options
  src/ert/config/queue_config.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_ert_config.py
Labels: release-notes:skip

#7282 Fix wrong storage state for resubmitted runs in Local driver
  src/ert/scheduler/job.py
  tests/unit_tests/scheduler/test_job.py
Labels: release-notes:bug-fix

#7202 Add tests for LSF driver kills
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip, scheduler

#7296 Treat binary output from bkill consistently
  src/ert/scheduler/lsf_driver.py
Labels: release-notes:skip, scheduler

#7297 Update ruff config in pyproject.toml
  pyproject.toml
Labels: maintenance

#7193 Add tests for various scenarios for a faulty bjobs
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip, scheduler

#7311 Use .get(key, defaultvalue) in storage_model.py
  src/ert/gui/ertwidgets/models/storage_model.py
Labels: release-notes:skip

#7307 Test all possible PBS job states
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip, scheduler

#7302 Add support for KEEP_QSUB_OUTPUT for OpenPBSDriver
  src/ert/scheduler/__init__.py
  src/ert/scheduler/openpbs_driver.py
  tests/integration_tests/scheduler/bin/qsub
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip, scheduler

#7314 Add more warning filters to tests
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/parsing/test_lark_parser.py
  tests/unit_tests/config/test_analysis_config.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_transfer_functions.py
  tests/unit_tests/test_enkf_main.py
  tests/unit_tests/test_load_forward_model.py
  tests/unit_tests/test_run_path_creation.py
Labels: release-notes:skip
