Repository equinor/ert, pull requests merged in 2024-12, with the labels that each got.

#9396 Reduce examples ran in storage test
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:flaky-test-fix

#9403 Move some performance tests out of unit_tests
  tests/ert/performance_tests/test_dark_storage_performance.py
  tests/ert/unit_tests/gui/tools/plot/test_plot_api.py
  tests/ert/unit_tests/test_libres_facade.py
Labels: maintenance

#9110 Fix _storage_main `terminate_on_parent_death` not working on mac
  src/ert/services/_storage_main.py
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:bug-fix

#9406 Make it possible to have multiline statements in config
  docs/ert/reference/configuration/index.rst
  docs/ert/reference/configuration/syntax.rst
  src/ert/config/parsing/lark_parser.py
  test-data/ert/flow_example/flow.ert
  test-data/ert/snake_oil/snake_oil.ert
  tests/ert/unit_tests/config/parsing/test_lark_parser.py
Labels: release-notes:new-feature

#9405 Update ropt to 0.10.0
  pyproject.toml
  src/ert/run_models/everest_run_model.py
  src/everest/optimizer/everest2ropt.py
  tests/everest/test_multiobjective.py
  tests/everest/test_ropt_initialization.py
Labels: release-notes:dependency, everest

#9410 backport: Fix progress bar showing finished status for unselected reals
  src/ert/run_models/base_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  tests/ert/ui_tests/cli/test_missing_runpath.py
  tests/ert/unit_tests/cli/test_model_hook_order.py
  tests/ert/unit_tests/run_models/test_base_run_model.py
  tests/ert/unit_tests/run_models/test_ensemble_experiment.py
  tests/ert/unit_tests/run_models/test_model_factory.py
Labels: release-notes:bug-fix

#9414 Fix typing in test
  tests/ert/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:bug-fix

#9416 Add coverage gathering of everest
  .github/workflows/test_ert.yml
  .github/workflows/test_everest.yml
  codecov.yml
Labels: release-notes:maintenance

#9390 Ignore erroneous auto-scale configuration, but warn
  src/ert/analysis/_es_update.py
  tests/ert/unit_tests/analysis/test_es_update.py
Labels: release-notes:bug-fix

#9412 Make local_driver use start_new_session when spawning children
  src/ert/scheduler/local_driver.py
Labels: release-notes:bug-fix

#9425 Fix some warnings
  src/ert/ensemble_evaluator/config.py
  tests/ert/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/ert/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:maintenance

#9428 Fix import that does not work in python 3.10
  src/ert/ensemble_evaluator/config.py
Labels: release-notes:skip

#9411 Use forkserver instead of fork for multiprocessing
  src/ert/__main__.py
  tests/ert/conftest.py
Labels: release-notes:bug-fix

#9402 Fix the azure logging handler in Everest
  src/everest/detached/jobs/everserver.py
Labels: bug, everest

#9439 Add more DATA parsing tests for num_cpu
  tests/ert/unit_tests/config/test_num_cpu.py
Labels: release-notes:skip

#9441 Fix everest doc test failing due to missing coverage
  .github/workflows/test_everest.yml
Labels: release-notes:skip

#9443 Fix failing everest test due to doc not generating cov
  .github/workflows/test_everest.yml
Labels: release-notes:skip

#9444 Fix the azure logging handler in Everest
  src/everest/detached/jobs/everserver.py
Labels: release-notes:bug-fix

#9458 Fix progress bar not updating realization count for new iterations
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/everest_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/ert/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:bug-fix

#9460 Fix a bug with skipping two lines after TITLE
  src/ert/config/_get_num_cpu.py
  tests/ert/unit_tests/config/test_num_cpu.py
Labels: release-notes:bug-fix

#9462 Backport num cpu fixes
  src/ert/config/_get_num_cpu.py
  tests/ert/unit_tests/config/test_num_cpu.py
Labels: release-notes:bug-fix

#9464 Backport: Fix progress bar not updating realization count for new iterations
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/everest_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/ert/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:bug-fix

#9440 Improve exit code detection in the slurm driver
  docs/ert/reference/configuration/keywords.rst
  docs/ert/reference/configuration/queue.rst
  docs/everest/config_generated.rst
  src/ert/config/queue_config.py
  src/ert/scheduler/slurm_driver.py
  src/everest/config/simulator_config.py
  src/everest/config_keys.py
  src/everest/queue_driver/queue_driver.py
  tests/ert/unit_tests/scheduler/bin/sacct
  tests/ert/unit_tests/scheduler/bin/sacct.py
  tests/ert/unit_tests/scheduler/test_slurm_driver.py
  tests/everest/test_res_initialization.py
Labels: release-notes:misc

#9472 Delete unused `evaluate` method in ensemble_evaluator_utils
  tests/ert/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
Labels: release-notes:maintenance

#9408 Have ModelConfig output better warning when malformatted runpath
  src/ert/config/model_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:bug-fix

#9423 Improve UX for permission errors in storage
  src/ert/dark_storage/endpoints/records.py
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/gui/tools/plot/plottery/plots/histogram.py
Labels: release-notes:improvement

#9482 Mute marginal cpu overspending
  src/ert/ensemble_evaluator/evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:skip

#9483 Require positive std_cutoff
  src/ert/config/analysis_config.py
  src/ert/config/parsing/config_schema.py
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/parsing/schema_item_type.py
  tests/ert/unit_tests/config/test_analysis_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:improvement

#9485 Update everest snapshot egg-py311.csv
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/egg-py311.csv
Labels: release-notes:maintenance, release-notes:skip

#9262 Use pattern matching for make_summary_key
  src/ert/config/_read_summary.py
Labels: release-notes:refactor

#9446 Fix ForwardModelStep `handle_process_timeout...` timeout
  src/_ert/forward_model_runner/forward_model_step.py
Labels: release-notes:bug-fix

#9238 Use pattern matching for config schema
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/parsing/schema_dict.py
Labels: release-notes:refactor

#9445 Remove code paths for python <3.11
  src/_ert/events.py
  src/ert/config/parsing/analysis_mode.py
  src/ert/config/parsing/config_keywords.py
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/parsing/forward_model_keywords.py
  src/ert/config/parsing/history_source.py
  src/ert/config/parsing/hook_runtime.py
  src/ert/config/parsing/queue_system.py
  src/ert/config/parsing/schema_item_type.py
  src/ert/config/parsing/workflow_job_keywords.py
  src/ert/config/parsing/workflow_keywords.py
  src/ert/dark_storage/json_schema/prior.py
  src/ert/enum_shim.py
  src/ert/field_utils/field_file_format.py
  src/ert/gui/main.py
  src/everest/docs/generate_docs_from_config_spec.py
  src/everest/export.py
  tests/ert/conftest.py
  tests/everest/entry_points/test_visualization_entry.py
Labels: release-notes:maintenance

#9490 Fix bug in careful_copy handling None
  src/ert/resources/shell_scripts/careful_copy_file.py
  tests/ert/unit_tests/resources/test_shell.py
Labels: release-notes:bug-fix

#9407 Have ErtStorageExceptions not be unexpected in cli
  src/ert/__main__.py
  tests/ert/unit_tests/shared/test_main_entry.py
Labels: release-notes:bug-fix

#9506 Run pyupgrade on src tree
  src/ert/run_models/base_run_model.py
  src/ert/run_models/everest_run_model.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  src/everest/bin/config_branch_script.py
  src/everest/bin/everest_script.py
  src/everest/bin/main.py
  src/everest/bin/utils.py
  src/everest/config/everest_config.py
  src/everest/config_file_loader.py
  src/everest/detached/jobs/everserver.py
  src/everest/export.py
  src/everest/jobs/__init__.py
  src/everest/jobs/recovery_factor.py
  src/everest/jobs/templating/render.py
  src/everest/simulator/everest_to_ert.py
  src/everest/util/__init__.py
Labels: release-notes:maintenance

#9496 Remove deprecated slurm options `MEMORY` and `MEMORY_PER_CPU`
  docs/ert/reference/configuration/keywords.rst
  docs/ert/reference/configuration/queue.rst
  docs/everest/config_generated.rst
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/config/queue_config.py
  src/ert/scheduler/slurm_driver.py
  src/everest/config/simulator_config.py
  src/everest/config_keys.py
  src/everest/queue_driver/queue_driver.py
  tests/ert/unit_tests/config/config_dict_generator.py
  tests/ert/unit_tests/config/test_queue_config.py
  tests/ert/unit_tests/scheduler/test_slurm_driver.py
  tests/everest/test_res_initialization.py
Labels: release-notes:maintenance

#9521 Set persistent cells in update table cells
  src/ert/gui/simulation/view/update.py
Labels: release-notes:skip

#8941 Run ensemble experiment with design matrix
  src/ert/config/design_matrix.py
  src/ert/enkf_main.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/model_factory.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
  tests/ert/unit_tests/config/test_analysis_config.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
  tests/ert/unit_tests/sensitivity_analysis/test_design_matrix.py
  tests/ert/unit_tests/test_libres_facade.py
Labels: release-notes:new-feature

#9487 Log when evaluator is leaving events
  src/ert/ensemble_evaluator/evaluator.py
Labels: enhancement

#9502 Type code in src/ert/resources
  .mypy.ini
  src/ert/resources/forward_models/template_render.py
  src/ert/resources/shell_scripts/careful_copy_file.py
  src/ert/resources/shell_scripts/copy_directory.py
  src/ert/resources/shell_scripts/copy_file.py
  src/ert/resources/shell_scripts/delete_directory.py
  src/ert/resources/shell_scripts/delete_file.py
  src/ert/resources/shell_scripts/make_directory.py
  src/ert/resources/shell_scripts/move_directory.py
  src/ert/resources/shell_scripts/move_file.py
  src/ert/resources/shell_scripts/symlink.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
Labels: release-notes:maintenance

#9541 Fix ruff issues
  src/ert/resources/forward_models/template_render.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
Labels: release-notes:skip

#9530 Add benchmarking with codspeed
  .github/workflows/codspeed.yml
Labels: release-notes:maintenance

#9548 Have Ert sidebar have correct focus on startup and when simulating
  src/ert/gui/main_window.py
Labels: release-notes:skip

#9551 Remove unnecessary wrapper forward_model_data_to_json
  src/ert/config/ert_config.py
  src/ert/enkf_main.py
  tests/ert/unit_tests/config/test_create_forward_model_json.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_forward_model.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_runner.py
Labels: release-notes:maintenance

#9554 Handle empty ensemble in observations view
  src/ert/gui/tools/manage_experiments/storage_info_widget.py
  tests/ert/ui_tests/gui/test_manage_experiments_tool.py
Labels: release-notes:unreleased-bug-fix

#9529 Stop using cached seba data
  tests/everest/entry_points/test_config_branch_entry.py
Labels: release-notes:maintenance, christmas-review

#9526 Stop using cached seba data
  tests/everest/test_config_branch.py
Labels: release-notes:maintenance, christmas-review

#9438 Name job after its executable when not specified
  src/ert/scheduler/driver.py
  src/ert/scheduler/local_driver.py
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/slurm_driver.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
  tests/ert/unit_tests/scheduler/test_openpbs_driver.py
  tests/ert/unit_tests/scheduler/test_slurm_driver.py
Labels: release-notes:maintenance, christmas-review

#9572 Solve ruff literal-membership
  pyproject.toml
  src/ert/cli/main.py
  src/ert/config/_read_summary.py
  src/ert/config/analysis_config.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/config/parsing/observations_parser.py
  src/ert/config/queue_config.py
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/gui/model/fm_step_list.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/plot/plot_window.py
  src/ert/plugins/__init__.py
  src/ert/resources/forward_models/res/script/ecl_config.py
  src/ert/resources/forward_models/res/script/ecl_run.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/everest_run_model.py
  src/ert/shared/net_utils.py
  src/everest/bin/utils.py
  src/everest/config/install_data_config.py
  src/everest/config/validation_utils.py
  src/everest/optimizer/everest2ropt.py
  tests/ert/ui_tests/gui/conftest.py
  tests/ert/unit_tests/config/config_dict_generator.py
  tests/ert/unit_tests/config/observations_generator.py
  tests/ert/unit_tests/config/test_create_forward_model_json.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/dark_storage/test_http_endpoints.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/ert/unit_tests/ensemble_evaluator/test_scheduler.py
  tests/ert/unit_tests/gui/tools/plot/test_plot_api.py
  tests/ert/unit_tests/scheduler/bin/squeue.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
  tests/ert/unit_tests/scheduler/test_openpbs_driver.py
  tests/everest/test_controls.py
  tests/everest/test_detached.py
Labels: release-notes:maintenance

#9534 Rename job_dispatch -> fm_dispatch
  docs/ert/developer_documentation/forward_model.rst
  docs/ert/developer_documentation/roadmap.rst
  docs/ert/reference/configuration/site_wide.rst
  pyproject.toml
  src/_ert/forward_model_runner/cli.py
  src/_ert/forward_model_runner/fm_dispatch.py
  src/_ert/forward_model_runner/forward_model_step.py
  src/ert/config/queue_config.py
  src/ert/plugins/hook_implementations/site_config.py
  src/ert/resources/site-config
  tests/ert/conftest.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_queue_config.py
  tests/ert/unit_tests/conftest.py
  tests/ert/unit_tests/ensemble_evaluator/conftest.py
  tests/ert/unit_tests/forward_model_runner/test_job_dispatch.py
  tests/ert/unit_tests/plugins/dummy_plugins.py
  tests/ert/unit_tests/plugins/test_plugin_manager.py
  tests/ert/unit_tests/scheduler/test_job.py
  tests/ert/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:maintenance

#9570 Use f-strings for formatting
  pyproject.toml
  src/everest/bin/config_branch_script.py
  src/everest/bin/main.py
  src/everest/config_file_loader.py
  src/everest/export.py
  src/everest/simulator/everest_to_ert.py
  src/everest/util/__init__.py
  test-data/everest/math_func/jobs/adv_distance3.py
  test-data/everest/math_func/jobs/adv_dump_controls.py
  test-data/everest/math_func/jobs/discrete.py
  test-data/everest/math_func/jobs/distance3.py
  test-data/everest/math_func/jobs/dump_controls.py
  test-data/everest/math_func/jobs/fail_simulation.py
  tests/everest/entry_points/test_everexport.py
  tests/everest/test_config_file_loader.py
  tests/everest/test_data/mocked_test_case/jobs/controls_sum.py
  tests/everest/test_data/mocked_test_case/jobs/fpr_diff_mock.py
  tests/everest/test_data/mocked_test_case/jobs/npv_function_mock.py
  tests/everest/test_data/mocked_test_case/jobs/oil_prod_rate_mock.py
  tests/everest/test_detached.py
  tests/everest/test_egg_simulation.py
  tests/everest/test_export.py
  tests/everest/test_math_func.py
  tests/everest/test_res_initialization.py
  tests/everest/test_templating.py
  tests/everest/test_well_tools.py
  tests/everest/utils/__init__.py
Labels: release-notes:maintenance

#9591 Pretty print manifest.json
  src/ert/enkf_main.py
Labels: release-notes:maintenance

#9434 Simplify tests and remove uncessary config files everest/mathfunc
  test-data/everest/math_func/config_advanced_scipy.yml
  test-data/everest/math_func/config_auto_scaled_controls.yml
  test-data/everest/math_func/config_cvar.yml
  test-data/everest/math_func/config_discrete.yml
  test-data/everest/math_func/config_fm_failure.yml
  test-data/everest/math_func/config_minimal_slow.yml
  test-data/everest/math_func/config_one_batch.yml
  test-data/everest/math_func/config_remove_run_path.yml
  test-data/everest/math_func/config_stddev.yml
  test-data/everest/math_func/jobs/SLEEP
  test-data/everest/math_func/jobs/sleep.py
  tests/everest/test_api_snapshots.py
  tests/everest/test_cvar.py
  tests/everest/test_detached.py
  tests/everest/test_discrete.py
  tests/everest/test_everserver.py
  tests/everest/test_fix_control.py
  tests/everest/test_logging.py
  tests/everest/test_math_func.py
  tests/everest/test_objective_type.py
  tests/everest/test_samplers.py
  tests/everest/test_simulator_cache.py
Labels: release-notes:skip, everest, christmas-review

#9580 Add line numbers when validating everest config files
  src/everest/config/__init__.py
  src/everest/config/control_variable_config.py
  src/everest/config/everest_config.py
  src/everest/config/validation_utils.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_config_file_loader.py
  tests/everest/test_config_validation.py
  tests/everest/test_res_initialization.py
  tests/everest/test_yaml_parser.py
Labels: release-notes:improvement

#9601 Merge EGG.DATA and EGG_FLOW.DATA
  test-data/everest/egg/eclipse/include/EGG.DATA
  test-data/everest/egg/eclipse/include/EGG_FLOW.DATA
  test-data/everest/egg/eclipse/include/realizations/realization-0/eclipse/model/EGG_FLOW.DATA
  test-data/everest/egg/eclipse/include/realizations/realization-1/eclipse/model/EGG_FLOW.DATA
  test-data/everest/egg/eclipse/include/realizations/realization-2/eclipse/model/EGG_FLOW.DATA
  test-data/everest/egg/everest/model/config_flow.yml
Labels: release-notes:maintenance

#9605 Move max_runtime to QueueConfig
  src/ert/config/analysis_config.py
  src/ert/config/queue_config.py
  src/ert/run_models/base_run_model.py
  tests/ert/unit_tests/config/test_analysis_config.py
  tests/ert/unit_tests/config/test_queue_config.py
Labels: release-notes:maintenance

#9609 Remove unused async_run
  src/everest/util/__init__.py
  src/everest/util/async_run.py
  tests/everest/test_async_run.py
Labels: release-notes:maintenance

#9501 Remove deprecated queue options
  docs/ert/reference/configuration/keywords.rst
  docs/ert/reference/configuration/queue.rst
  docs/everest/config_generated.rst
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/config/queue_config.py
  src/ert/scheduler/openpbs_driver.py
  src/everest/config/simulator_config.py
  src/everest/config_keys.py
  src/everest/queue_driver/queue_driver.py
  tests/ert/unit_tests/config/config_dict_generator.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_queue_config.py
  tests/ert/unit_tests/scheduler/test_openpbs_driver.py
  tests/ert/unit_tests/scheduler/test_scheduler.py
  tests/everest/test_res_initialization.py
Labels: release-notes:maintenance
