Repository equinor/ert, pull requests merged in 2024-09, with the labels that each got.

#8559 Fix restart weights
  src/ert/gui/ertwidgets/stringbox.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_restart_esmda.py
Labels: release-notes:user-impact

#8609 Fix incorrect varname in test
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#8610 Make tests runnable from git worktree
  tests/utils.py
Labels: release-notes:skip

#8481 Rename port_handler functions
  src/ert/ensemble_evaluator/config.py
  src/ert/ensemble_evaluator/evaluator_connection_info.py
  src/ert/services/_storage_main.py
  src/ert/shared/__init__.py
  src/ert/shared/net_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator_config.py
  tests/unit_tests/ensemble_evaluator/test_monitor.py
  tests/unit_tests/services/test_storage_service.py
  tests/unit_tests/shared/test_port_handler.py
Labels: maintenance, release-notes:skip

#8622 Fix issues highlighted by pyright
  src/_ert_forward_model_runner/job.py
Labels: release-notes:skip

#8587 Fix so `Export tool` does not return duplicate data when storage contains multiple experiments with same ensemble names
  src/ert/gui/ertwidgets/listeditbox.py
  src/ert/gui/tools/export/export_panel.py
  src/ert/gui/tools/export/export_tool.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  tests/unit_tests/gui/test_csv_export.py
Labels: release-notes:bug-fix

#8615 Fix bug checksum failures
  src/ert/scheduler/job.py
Labels: release-notes:bug-fix

#8621 Use KB instead of kB
  src/ert/__main__.py
  src/ert/shared/status/utils.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:skip

#8624 Fix bug checksum failures
  src/ert/scheduler/job.py
Labels: release-notes:bug-fix

#8599 Catch FileNotFoundError in driver._execute_with_retry
  src/ert/scheduler/driver.py
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/slurm_driver.py
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: improvement, release-notes:improvement

#8629 Avoid deprecation warning from pytest-asyncio
  pyproject.toml
Labels: release-notes:skip

#8626 Standardize logging from run_experiment
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/manual_update.py
  src/ert/run_models/multiple_data_assimilation.py
Labels: release-notes:skip

#8633 Remove outdated comment on Python dev headers
  README.md
Labels: release-notes:skip

#8634 Make figure snapshot tests faster
  tests/conftest.py
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure0-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure1-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure2-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure4-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure5-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure6-0.png
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
Labels: release-notes:skip

#8636 Fix typo fligure -> figure
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
Labels: release-notes:skip

#8637 Use plot() instead of deprecated plot_date()
  src/ert/gui/plottery/plots/ensemble.py
  src/ert/gui/plottery/plots/history.py
Labels: release-notes:skip

#8608 Improve docs for error modes
  docs/reference/configuration/observations.rst
Labels: release-notes:skip

#8648 Avoid stack trace in ecl_run errors
  src/ert/resources/forward-models/res/script/ecl_run.py
Labels: release-notes:improvement

#8623 Delete get_ensemble_by_name from `LocalStorage`
  src/ert/__main__.py
  src/ert/simulator/batch_simulator.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  src/ert/storage/migration/block_fs.py
  test-data/poly_example/Plot_correlations.ipynb
  tests/conftest.py
  tests/integration_tests/analysis/test_adaptive_localization.py
  tests/integration_tests/analysis/test_es_update.py
  tests/integration_tests/storage/test_field_parameter.py
  tests/integration_tests/storage/test_parameter_sample_types.py
  tests/integration_tests/test_cli.py
  tests/performance_tests/enkf/test_load_state.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/gui/test_csv_export.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
  tests/unit_tests/gui/test_restart_no_responses_and_parameters.py
  tests/unit_tests/storage/migration/test_block_fs_simple_case.py
  tests/unit_tests/storage/migration/test_block_fs_snake_oil.py
  tests/unit_tests/test_load_forward_model.py
Labels: release-notes:breaking-change

#8654 Remove unreachable code in test
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
Labels: release-notes:skip

#8655 Make event validation stricter
  src/_ert/events.py
  tests/performance_tests/test_snapshot.py
Labels: release-notes:skip

#8651 Only disable weights when weights have been found in storage
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
Labels: release-notes:skip

#8662 Generate Ert manifest file using ensemble Experiment content
  src/ert/config/ert_config.py
  src/ert/enkf_main.py
  tests/unit_tests/test_run_path_creation.py
Labels: release-notes:bug-fix

#8586 Store & plot scaling factors
  src/ert/analysis/_es_update.py
  src/ert/gui/tools/manage_experiments/storage_info_widget.py
  src/ert/storage/local_ensemble.py
  tests/integration_tests/analysis/test_adaptive_localization.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/gui/tools/test_manage_experiments_tool.py
Labels: enhancement, release-notes:new-feature

#8664 Remove legacy websocket
  src/ert/ensemble_evaluator/evaluator.py
Labels: maintenance, release-notes:skip

#8673 Cleanup SETENV documentation
  docs/reference/configuration/keywords.rst
Labels: release-notes:skip

#8675 Fix error in job dispatch's memory reporting
  src/_ert_forward_model_runner/job.py
  tests/unit_tests/forward_model_runner/test_job.py
Labels: release-notes:skip

#8678 Avoid crashing while cleaning up tmp-directory
  src/ert/plugins/plugin_manager.py
Labels: release-notes:skip

#8669 Rename two Snapshot classes to reflect what they contain
  src/_ert/forkserver.py
  src/ert/cli/monitor.py
  src/ert/ensemble_evaluator/__init__.py
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/event.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/model/fm_step_list.py
  src/ert/gui/model/node.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/realization.py
  src/ert/run_models/base_run_model.py
  src/ert/simulator/batch_simulator_context.py
  tests/__init__.py
  tests/integration_tests/status/test_tracking_integration.py
  tests/integration_tests/test_cli.py
  tests/performance_tests/test_snapshot.py
  tests/unit_tests/cli/test_cli_monitor.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/ensemble_evaluator/test_snapshot.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/model/gui_models_utils.py
  tests/unit_tests/gui/model/test_job_list.py
  tests/unit_tests/gui/model/test_real_list.py
  tests/unit_tests/gui/model/test_snapshot.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#8672 Remove excess check_response call in std_dev_for_parameter
  src/ert/gui/tools/plot/plot_api.py
Labels: maintenance, release-notes:skip

#8682 Make copy_directories error message readable
  src/ert/resources/shell_scripts/copy_directory.py
  tests/unit_tests/shared/share/test_shell.py
Labels: release-notes:bug-fix

#8694 Use FORWARD_MODEL in poly-example
  test-data/poly_example/poly.ert
Labels: release-notes:skip

#8619 Fix general queue options not being added bug
  src/ert/config/ert_config.py
  src/ert/config/parsing/lark_parser.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_field.py
Labels: release-notes:bug-fix

#8701 Fix typo existant -> existent
  tests/unit_tests/config/test_ert_config.py
Labels: release-notes:skip

#8704 Remove unused index_lists
  src/ert/data/_measured_data.py
  tests/unit_tests/data/test_integration_data.py
Labels: release-notes:breaking-change

#8706 Improve pytest skip message for missing git-lfs
  tests/conftest.py
Labels: release-notes:skip

#8707 Move _ert_forward_model_runner to _ert.forward_model_runner
  .mypy.ini
  pyproject.toml
  src/_ert/forward_model_runner/__init__.py
  src/_ert/forward_model_runner/cli.py
  src/_ert/forward_model_runner/client.py
  src/_ert/forward_model_runner/io/__init__.py
  src/_ert/forward_model_runner/job.py
  src/_ert/forward_model_runner/job_dispatch.py
  src/_ert/forward_model_runner/reporting/__init__.py
  src/_ert/forward_model_runner/reporting/base.py
  src/_ert/forward_model_runner/reporting/event.py
  src/_ert/forward_model_runner/reporting/file.py
  src/_ert/forward_model_runner/reporting/interactive.py
  src/_ert/forward_model_runner/reporting/message.py
  src/_ert/forward_model_runner/reporting/statemachine.py
  src/_ert/forward_model_runner/runner.py
  src/_ert/forward_model_runner/util/__init__.py
  src/_ert/forward_model_runner/util/data.py
  src/_ert_forward_model_runner/__init__.py
  src/ert/ensemble_evaluator/_ensemble.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_client.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/forward_model_runner/test_event_reporter.py
  tests/unit_tests/forward_model_runner/test_file_reporter.py
  tests/unit_tests/forward_model_runner/test_job.py
  tests/unit_tests/forward_model_runner/test_job_dispatch.py
  tests/unit_tests/forward_model_runner/test_job_manager_runtime_kw.py
  tests/unit_tests/forward_model_runner/test_jobmanager.py
  tests/utils.py
Labels: release-notes:skip

#8711 Send codecov upload token as input to tests
  .github/workflows/build_and_test.yml
Labels: release-notes:skip

#8696 Log contents of custom forward model steps
  src/ert/config/ert_config.py
  tests/unit_tests/config/test_ert_config.py
Labels: release-notes:misc

#8698 Replace selected usage of SIMULATION_JOB with FORWARD_MODEL
  docs/reference/queue/local_queue.ert
  docs/reference/queue/lsf_queue.ert
  test-data/poly_template/poly.ert.j2
  tests/ui_tests/cli/analysis/test_adaptive_localization.py
  tests/ui_tests/cli/test_field_parameter.py
  tests/ui_tests/cli/test_parameter_sample_types.py
  tests/ui_tests/gui/test_manage_experiments_tool.py
  tests/ui_tests/gui/test_restart_no_responses_and_parameters.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/test_tracking.py
Labels: release-notes:skip

#8714 Add a retry for opening jobs.json
  src/_ert/forward_model_runner/cli.py
  tests/conftest.py
  tests/unit_tests/forward_model_runner/test_job_dispatch.py
Labels: release-notes:improvement

#8710 Update README to include `git lfs install` step for testing
  README.md
Labels: release-notes:skip

#8723 Strip newlines from strings read from disk
  src/ert/config/ert_config.py
Labels: release-notes:skip

#8724 Call the name() function when logging
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/manual_update.py
  src/ert/run_models/multiple_data_assimilation.py
Labels: release-notes:skip

#8732 Remove unused mypy config
  .mypy.ini
Labels: release-notes:skip

#8731 Make pyproject.toml pretty again
  pyproject.toml
Labels: release-notes:skip

#8733 Add pyright settings
  pyproject.toml
Labels: release-notes:skip

#8713 Add cpu_seconds to MemoryStatus report sent from the runner
  src/_ert/forward_model_runner/cli.py
  src/_ert/forward_model_runner/job.py
  src/_ert/forward_model_runner/reporting/file.py
  src/_ert/forward_model_runner/reporting/message.py
  tests/unit_tests/forward_model_runner/test_event_reporter.py
  tests/unit_tests/forward_model_runner/test_file_reporter.py
  tests/unit_tests/forward_model_runner/test_job.py
Labels: release-notes:improvement

#8751 Remove deprecated pgk_resources
  src/everest/detached/__init__.py
  src/everest/jobs/__init__.py
  src/everest/templates/__init__.py
Labels: release-notes:skip

#8746 Detect license failures in Eclipse slave models
  src/ert/resources/forward-models/res/script/ecl_run.py
  tests/unit_tests/resources/test_ecl_run_new_config.py
Labels: release-notes:improvement

#8766 Use default eq in ErtConfig
  src/ert/config/ert_config.py
Labels: release-notes:skip

#8765 Use codecov's flaky test detection feature
  .github/workflows/test_ert.yml
Labels: release-notes:skip

#8752 Remove blockfs support
  src/ert/storage/local_storage.py
  src/ert/storage/migration/block_fs.py
  tests/ert/unit_tests/storage/migration/test_block_fs.py
  tests/ert/unit_tests/storage/migration/test_block_fs_ext_param.py
  tests/ert/unit_tests/storage/migration/test_block_fs_simple_case.py
  tests/ert/unit_tests/storage/migration/test_block_fs_snake_oil.py
Labels: release-notes:breaking-change

#8771 Fix flaky stateful storage test
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#8777 Refactor reading from contents
  src/ert/config/ert_config.py
  src/ert/config/parsing/__init__.py
  src/ert/config/parsing/lark_parser.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:skip

#8778 Update ert tests path
  ci/testkomodo.sh
Labels: release-notes:skip

#8722 Log mismatch between NUM_CPU and actual cpu usage
  src/_ert/events.py
  src/_ert/forward_model_runner/reporting/event.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/identifiers.py
  src/ert/ensemble_evaluator/snapshot.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:improvement

#8785 Fix flaky storage test
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#8790 Avoid bsub retrying on known error messages
  src/ert/scheduler/driver.py
  src/ert/scheduler/lsf_driver.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:bug-fix

#8735 Have ForwardModelRunner validate executable_file earlier
  src/_ert/forward_model_runner/io/__init__.py
  src/_ert/forward_model_runner/job.py
  tests/ert/unit_tests/forward_model_runner/test_job.py
Labels: release-notes:bug-fix

#8795 Mark all flaky tests as integration_tests
  tests/ert/unit_tests/forward_model_runner/test_event_reporter.py
  tests/ert/unit_tests/forward_model_runner/test_job.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
  tests/ert/unit_tests/scheduler/test_scheduler.py
  tests/ert/unit_tests/scheduler/test_slurm_driver.py
  tests/ert/unit_tests/simulator/test_batch_sim.py
Labels: release-notes:skip

#8796 Fix flaky test
  tests/ert/unit_tests/forward_model_runner/test_job.py
Labels: release-notes:skip

#8802 Fix an issue where aborted processes could corrupt storage
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:bug-fix

#8812 Fix flaky memory test
  tests/ert/performance_tests/test_memory_usage.py
Labels: release-notes:skip

#8816 Add formatting to simulation mode helptext
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/single_test_run.py
Labels: release-notes:maintenance

#8602 Group items in Experiment Panel's drop-down
  src/ert/gui/simulation/combobox_with_description.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/run_models/single_test_run.py
  tests/ert/ui_tests/gui/test_main_window.py
  tests/ert/ui_tests/gui/test_single_test_run.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:improvement

#8807 Fix flaky kill_before_submit test for lsf
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip
