Repository equinor/ert, pull requests merged in 2024-07, with the labels that each got.

#8240 Document auto scaling
  src/ert/analysis/misfit_preprocessor.py
Labels: release-notes:skip

#8266 Output the number of reals running in existing runpaths
  src/ert/cli/main.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  tests/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:improvement

#8269 Avoid imports from job_queue
  src/ert/scheduler/scheduler.py
Labels: release-notes:skip

#8277 Avoid unused varibles in test_slurm_driver
  tests/integration_tests/scheduler/test_slurm_driver.py
Labels: release-notes:skip

#8213 Have ensemble evaluator methods early return instead of if-else
  src/ert/ensemble_evaluator/evaluator.py
Labels: improvement, release-notes:skip

#8230 Simplify Snapshot model
  src/ert/gui/model/job_list.py
  src/ert/gui/model/node.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/model/test_job_list.py
  tests/unit_tests/gui/model/test_snapshot.py
Labels: release-notes:maintenance

#8287 Avoid false positive ruff issue by noqa
  pyproject.toml
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
Labels: release-notes:skip

#8290 Allow adjustable size for job overview header
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:improvement

#8292 Show ert filename in eventviewer windowtitle
  src/ert/gui/main.py
  src/ert/gui/tools/event_viewer/tool.py
Labels: release-notes:improvement

#8298 Fix small GUI error in create_experiment
  src/ert/gui/ertwidgets/create_experiment_dialog.py
  src/ert/gui/ertwidgets/stringbox.py
Labels: release-notes:skip

#8283 Fix the 'initialize from scratch' tab
  src/ert/gui/tools/manage_experiments/ensemble_init_configuration.py
Labels: release-notes:improvement

#8302 Fix color selection in plotter
  src/ert/gui/plottery/plot_config.py
  src/ert/gui/tools/plot/color_chooser.py
  src/ert/gui/tools/plot/customize/style_customization_view.py
Labels: release-notes:bug-fix

#8306 Rename EnsembleInitializationConfigurationPanel
  src/ert/gui/tools/manage_experiments/__init__.py
  src/ert/gui/tools/manage_experiments/manage_experiments_panel.py
  src/ert/gui/tools/manage_experiments/manage_experiments_tool.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/gui/tools/test_manage_experiments_tool.py
Labels: release-notes:skip

#8286 Refactor job_list & real_list
  src/ert/gui/model/job_list.py
  src/ert/gui/model/real_list.py
Labels: release-notes:maintenance

#8311 Cache result of row in _Node
  src/ert/gui/model/node.py
Labels: release-notes:skip

#8294 Solve ruff collapsible-else-if
  pyproject.toml
  src/ert/gui/simulation/run_dialog.py
  src/ert/shared/share/ert/forward-models/res/script/ecl_run.py
  src/ert/shared/share/ert/shell_scripts/delete_file.py
  src/ert/simulator/batch_simulator_context.py
  tests/unit_tests/config/test_forward_model_data_to_json.py
Labels: release-notes:skip

#8289 Fix typing issues in gui model
  .mypy.ini
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/ensemble_evaluator/state.py
  src/ert/gui/model/node.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:skip

#8315 Fix typing issues in gui code
  .mypy.ini
  src/ert/config/analysis_module.py
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
  src/ert/gui/ertwidgets/validationsupport.py
  src/ert/gui/model/real_list.py
Labels: release-notes:skip

#8291 Have driver.__init__(...) exceptions propagate
  src/ert/ensemble_evaluator/_ensemble.py
  tests/integration_tests/test_cli.py
Labels: improvement, release-notes:skip

#8109 Make sure that scheduler send all events when jobs are finished
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: scheduler

#8329 Add traceback information to ErtThreadError
  src/_ert/threading.py
  tests/unit_tests/shared/test_threading.py
Labels: improvement

#8335 Remove unnecessary mypy ignores
  .mypy.ini
Labels: release-notes:skip

#6994 Implement async version EnsembleEvaluator
  src/ert/ensemble_evaluator/__init__.py
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/dispatch.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_dispatch.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/ensemble_evaluator/test_scheduler.py
Labels: release-notes:improvement

#8352 Fix invalid grid file raising uncaught exception
  src/ert/config/ensemble_config.py
  tests/unit_tests/config/test_ensemble_config.py
Labels: release-notes:bug-fix

#8356 Test that no ee config will raise when running evaluator
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:skip

#8357 Rename EnsembleEvaluator._stop and remove async keyword
  src/ert/ensemble_evaluator/evaluator.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
Labels: improvement, release-notes:skip

#8361 Add test of about dialog
  src/ert/gui/main_window.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:skip

#8136 Fix test_unexpected_close
  tests/unit_tests/ensemble_evaluator/test_monitor.py
Labels: release-notes:skip
