Repository equinor/ert, pull requests merged in 2024-08, with the labels that each got.

#8309 Mark empty stdout/stderr files in simulation
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/shared/status/utils.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:improvement

#8339 Display experiment and ensemble name next to drag icon.
  src/ert/gui/tools/plot/plot_ensemble_selection_widget.py
Labels: release-notes:improvement

#8334 Add SearchBar to the event viewer
  src/ert/gui/tools/event_viewer/panel.py
  src/ert/gui/tools/file/file_dialog.py
  src/ert/gui/tools/search_bar/__init__.py
  src/ert/gui/tools/search_bar/search_bar.py
  tests/unit_tests/gui/ertwidgets/test_search_bar.py
Labels: release-notes:improvement

#8372 Send end event from main simulation function in base run model
  src/ert/cli/main.py
  src/ert/cli/monitor.py
  src/ert/run_models/base_run_model.py
  tests/integration_tests/test_cli.py
Labels: release-notes:maintenance

#8366 Move information about iteration
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/unit_tests/ensemble_evaluator/test_scheduler.py
Labels: maintenance, release-notes:maintenance

#8373 Add testing of STD_DEV plot
  tests/conftest.py
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure0-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure1-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure1.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure2-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure2.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure4-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure4.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure5-0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure5.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure6.png
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
Labels: release-notes:skip

#8374 Add MOVE_DIRECTORY forward model job
  docs/about/release_notes.rst
  src/ert/plugins/hook_implementations/forward_model_steps.py
  src/ert/resources/shell_scripts/move_directory.py
  src/ert/resources/workflows/jobs/shell/MOVE_DIRECTORY
  tests/integration_tests/shared/share/test_shell.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/shared/share/test_shell.py
Labels: feature

#8295 Avoid import outside top-level
  pyproject.toml
  src/ert/__main__.py
  src/ert/plugins/hook_implementations/workflows/export_misfit_data.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/resources/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
Labels: release-notes:skip

#8384 Update kalman smoother innovation term
  docs/theory/ensemble_based_methods.rst
Labels: release-notes:skip

#8296 Solve ruff issue non-augmented assignment
  pyproject.toml
  src/_ert_forward_model_runner/io/__init__.py
  src/ert/analysis/_es_update.py
  src/ert/config/parsing/lark_parser.py
  src/ert/shared/status/utils.py
  tests/performance_tests/performance_utils.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
Labels: release-notes:skip

#8317 Speed up snapshot index
  src/ert/gui/model/node.py
  src/ert/gui/model/snapshot.py
  tests/unit_tests/gui/model/test_job_list.py
  tests/unit_tests/gui/model/test_real_list.py
  tests/unit_tests/gui/model/test_snapshot.py
  tests/unit_tests/gui/simulation/view/test_realization.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
Labels: release-notes:skip

#8387 Fix typos in comment
  src/ert/ensemble_evaluator/evaluator.py
Labels: release-notes:skip

#8273 Add generic driver test for num_cpu
  tests/integration_tests/scheduler/bin/bsub
  tests/integration_tests/scheduler/bin/lsfrunner
  tests/integration_tests/scheduler/bin/qsub
  tests/integration_tests/scheduler/bin/runner
  tests/integration_tests/scheduler/bin/sbatch.py
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: release-notes:maintenance

#8270 Use success instead of stopped when no failure
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/identifiers.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/event_type_constants.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#8281 Log only once per unique forward model job name
  src/ert/cli/main.py
  src/ert/gui/main.py
  tests/integration_tests/test_cli.py
Labels: release-notes:improvement

#8392 Fix typo in documentation
  docs/reference/configuration/keywords.rst
  docs/reference/workflows/complete_workflows.rst
Labels: release-notes:skip

#8390 Fix filter popup not closing
  src/ert/gui/tools/plot/filter_popup.py
Labels: release-notes:bug-fix

#8388 Disable validation of experiment name on restart
  src/ert/gui/ertwidgets/stringbox.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
Labels: release-notes:bug-fix

#8288 Avoid unneeded lambda functions
  pyproject.toml
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
Labels: release-notes:skip

#8402 Allow a lambda to satisfy mypy
  src/ert/gui/model/node.py
Labels: release-notes:skip

#8394 Fix flaky test test_memory_profile_in_running_events
  tests/unit_tests/forward_model_runner/test_job.py
Labels: flaky-test, release-notes:skip

#7884 Improve bug template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: release-notes:skip

#8401 Solve and enforce ruff-unused-variable
  pyproject.toml
  src/ert/gui/ertwidgets/pathchooser.py
  src/ert/gui/main.py
  src/ert/gui/tools/plot/plot_widget.py
  src/ert/run_models/iterated_ensemble_smoother.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/shared/test_port_handler.py
  tests/unit_tests/test_enkf_main.py
Labels: release-notes:skip

#8410 Make sure adaptive localization works with single observation
  src/ert/analysis/_es_update.py
  tests/integration_tests/analysis/test_adaptive_localization.py
Labels: release-notes:bug-fix

#8408 Fixed a bug in std dev plot where color gradiant range was always 0 to 1 & two corner cells where always white
  src/ert/gui/plottery/plots/std_dev.py
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3.png
Labels: release-notes:bug-fix

#8405 Improve documentation for NUM_CPU
  docs/reference/configuration/keywords.rst
Labels: documentation, release-notes:misc

#8215 Add a new configuration keyword for memory pr realization
  docs/reference/configuration/keywords.rst
  src/ert/config/parsing/config_keywords.py
  src/ert/config/parsing/config_schema.py
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/config/queue_config.py
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/run_models/base_run_model.py
  src/ert/scheduler/driver.py
  src/ert/scheduler/job.py
  src/ert/scheduler/local_driver.py
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/slurm_driver.py
  src/ert/simulator/batch_simulator_context.py
  test-data/poly_example/poly.ert
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/config/test_queue_config.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_builder.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
  tests/unit_tests/scheduler/test_slurm_driver.py
Labels: release-notes:new-feature

#8414 Use codecov flags feature
  .github/workflows/coverage.yml
Labels: release-notes:skip

#8415 Remove irrelevant comment on job_queue
  src/ert/simulator/batch_simulator.py
Labels: release-notes:skip

#8416 Make forward_model_ok an async function
  src/ert/callbacks.py
  src/ert/libres_facade.py
  src/ert/scheduler/job.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/scheduler/test_job.py
Labels: release-notes:misc

#8396 Deprecate slurm queue option MEMORY_PER_CPU
  src/ert/config/parsing/config_schema_deprecations.py
Labels: maintenance, release-notes:misc

#8420 Remove unused function
  src/ert/storage/local_ensemble.py
Labels: release-notes:breaking-change

#8417 Try to mitigate flakiness in driver test
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: release-notes:skip

#8393 Fix waiting cursor in load results manually panel
  src/ert/gui/tools/load_results/load_results_panel.py
  src/ert/gui/tools/load_results/load_results_tool.py
Labels: release-notes:bug-fix

#8425 Remove unused properties
  src/ert/run_models/run_arguments.py
Labels: release-notes:maintenance

#8430 Fix type error
  src/ert/ensemble_evaluator/_wait_for_evaluator.py
Labels: release-notes:skip

#8431 Fix indentation in docs
  docs/reference/configuration/forward_model.rst
  src/ert/shared/_doc_utils/ert_jobs.py
Labels: release-notes:skip

#8440 Run snake oil field storage in same xdist group
  tests/conftest.py
Labels: release-notes:skip

#8444 Remove deprecated MeasuredData functions filter_ensemble_std & filter_ensemble_mean_obs
  src/ert/data/_measured_data.py
Labels: release-notes:breaking-change

#8445 Remove check locale function
  src/ert/gui/main.py
Labels: release-notes:maintenance

#8426 Use a plain dict for queue system options
  src/ert/config/queue_config.py
  tests/unit_tests/config/test_queue_config.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:maintenance

#8421 Merge snapshot and partialsnapshot
  src/ert/cli/monitor.py
  src/ert/ensemble_evaluator/__init__.py
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/event.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/queue_emitter.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/run_models/base_run_model.py
  tests/integration_tests/status/test_tracking_integration.py
  tests/performance_tests/test_snapshot.py
  tests/unit_tests/cli/test_cli_monitor.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/ensemble_evaluator/test_snapshot.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/model/gui_models_utils.py
  tests/unit_tests/gui/model/test_job_list.py
  tests/unit_tests/gui/model/test_real_list.py
  tests/unit_tests/gui/model/test_snapshot.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: improvement, release-notes:skip

#8455 Fix bug where iteration was hard coded
  src/ert/run_models/base_run_model.py
Labels: release-notes:skip

#8461 Change look&feel of simulation mode combobox
  src/ert/gui/ertwidgets/combobox_with_description.py
Labels: release-notes:improvement

#8449 Add splitter to rundialog to facilitate UI adjustments
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:improvement

#8448 Fix bug in heat equation example
  test-data/heat_equation/config.ert
  test-data/heat_equation/generate_files.py
  test-data/heat_equation/heat_equation.py
  test-data/heat_equation/obs_10.txt
  test-data/heat_equation/obs_132.txt
  test-data/heat_equation/obs_193.txt
  test-data/heat_equation/obs_255.txt
  test-data/heat_equation/obs_316.txt
  test-data/heat_equation/obs_377.txt
  test-data/heat_equation/obs_438.txt
  test-data/heat_equation/obs_71.txt
Labels: release-notes:skip

#8462 Use load_parameters when calculating std
  src/ert/storage/local_ensemble.py
Labels: release-notes:skip

#8478 Resize columns to content and guarantee min size
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:skip

#8483 Hide suggestor location if location not specified
  src/ert/gui/suggestor/_suggestor_message.py
Labels: release-notes:skip

#8471 Remove unused and deprecated queue_options
  docs/reference/configuration/keywords.rst
  docs/reference/configuration/queue.rst
  docs/reference/configuration/site_wide.rst
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/config/queue_config.py
  tests/unit_tests/config/parsing/test_config_schema_deprecations.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_parser_error_collection.py
  tests/unit_tests/config/test_queue_config.py
Labels: maintenance, release-notes:maintenance

#8479 Remove the UI elements that show current memory usage
  src/ert/gui/model/job_list.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/view/realization.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:skip

#8480 Fix a bug in ClosableDialog
  src/ert/gui/ertwidgets/closabledialog.py
  tests/unit_tests/gui/ertwidgets/test_closabledialog.py
Labels: release-notes:bug-fix

#8469 Fix bug where std dev plots were clipped to 0-1 range
  src/ert/dark_storage/endpoints/records.py
  src/ert/dark_storage/json_schema/__init__.py
  src/ert/dark_storage/json_schema/record.py
  src/ert/gui/plottery/plots/cesp.py
  src/ert/gui/plottery/plots/distribution.py
  src/ert/gui/plottery/plots/ensemble.py
  src/ert/gui/plottery/plots/gaussian_kde.py
  src/ert/gui/plottery/plots/histogram.py
  src/ert/gui/plottery/plots/statistics.py
  src/ert/gui/plottery/plots/std_dev.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/gui/tools/plot/plot_widget.py
  src/ert/gui/tools/plot/plot_window.py
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3.png
Labels: release-notes:bug-fix

#8389 Remove translation between JobState and JobStatus
  src/ert/__init__.py
  src/ert/scheduler/__init__.py
  src/ert/scheduler/job.py
  src/ert/scheduler/job_status.py
  src/ert/scheduler/scheduler.py
  src/ert/simulator/__init__.py
  src/ert/simulator/batch_simulator_context.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_scheduler.py
  tests/unit_tests/simulator/test_batch_sim.py
  tests/unit_tests/simulator/test_simulation_context.py
Labels: maintenance, release-notes:skip

#8500 Allow user to inhibit tab changes during simulation
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:skip

#8486 Reverse ensemble order for plotting
  src/ert/gui/tools/plot/plot_ensemble_selection_widget.py
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure0.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure1.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure2.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure4.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure5.png
  tests/unit_tests/gui/plottery/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure6.png
Labels: release-notes:skip

#8496 Enforce minimum size on update report widget
  src/ert/gui/simulation/view/update.py
Labels: release-notes:skip

#8498 Remove std cutoff filtering in HISTORY_OBSERVATION
  src/ert/config/ert_config.py
  src/ert/config/observations.py
  tests/unit_tests/config/test_observations.py
Labels: release-notes:improvement

#8504 Remove hide details button in rundialog
  src/ert/gui/simulation/run_dialog.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/gui/simulation/test_run_path_dialog.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/gui/test_restart_ensemble_experiment.py
  tests/unit_tests/gui/test_single_test_run.py
Labels: release-notes:user-impact

#8508 Fix flaky config generator
  tests/unit_tests/config/observations_generator.py
Labels: flaky-test, release-notes:skip

#8512 Fix job label not updating when selecting same index
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/realization.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/gui/simulation/view/test_realization.py
Labels: release-notes:bug-fix

#8517 Fix bug where template file was interpreted as parameters file
  src/ert/config/ert_config.py
  src/ert/config/gen_kw_config.py
  tests/unit_tests/config/test_ensemble_config.py
  tests/unit_tests/config/test_ert_config.py
Labels: release-notes:bug-fix

#8521 Hide JobOverview when UpdateWidget is visible in run_dialog
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:skip

#8514 Use EDS icon and stylesheets for run_dialog splitter
  src/ert/gui/resources/gui/img/drag_handle.svg
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:user-impact

#8519 Simplify creating deprecation warnings
  src/ert/config/_get_num_cpu.py
  src/ert/config/analysis_config.py
  src/ert/config/ert_config.py
  src/ert/config/field.py
  src/ert/config/gen_kw_config.py
  src/ert/config/observations.py
  src/ert/config/parsing/config_errors.py
  src/ert/config/parsing/lark_parser.py
  src/ert/config/parsing/schema_dict.py
  src/ert/config/queue_config.py
  src/ert/run_models/model_factory.py
Labels: release-notes:skip

#8520 Add suggestion to simplify GEN_KW config on empty template file
  src/ert/config/gen_kw_config.py
  tests/unit_tests/config/test_gen_kw_config.py
Labels: release-notes:improvement

#8524 Remove skipped out-of-memory test
  tests/conftest.py
  tests/integration_tests/test_cli.py
Labels: release-notes:skip

#8424 Use queue to exchange events between scheduler and evaluator
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: improvement, scheduler

#8475 Refactor queue_options to use Pydantic dataclasses
  src/ert/config/__init__.py
  src/ert/config/queue_config.py
  src/ert/scheduler/__init__.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/slurm_driver.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_parser_error_collection.py
  tests/unit_tests/config/test_queue_config.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:maintenance

#8526 Allow empty field for target ensemble format
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
Labels: release-notes:skip

#8528 Sort exports through __all__
  src/_ert_forward_model_runner/reporting/__init__.py
  src/ert/__init__.py
  src/ert/analysis/__init__.py
  src/ert/config/__init__.py
  src/ert/config/parsing/__init__.py
  src/ert/data/__init__.py
  src/ert/ensemble_evaluator/__init__.py
  src/ert/enum_shim.py
  src/ert/field_utils/__init__.py
  src/ert/gui/ertwidgets/__init__.py
  src/ert/gui/ertwidgets/models/__init__.py
  src/ert/gui/tools/manage_experiments/__init__.py
  src/ert/gui/tools/plot/customize/__init__.py
  src/ert/plugins/__init__.py
  src/ert/plugins/hook_implementations/__init__.py
  src/ert/plugins/hook_specifications/__init__.py
  src/ert/run_models/__init__.py
  src/ert/scheduler/__init__.py
  src/ert/shared/__init__.py
  src/ert/shared/plugins/plugin_manager.py
  src/ert/simulator/__init__.py
  src/ert/simulator/forward_model_status.py
  src/ert/storage/__init__.py
  src/ert/validation/__init__.py
Labels: release-notes:skip

#8527 Disallow GENERIC queue system
  src/ert/config/parsing/__init__.py
  src/ert/config/parsing/config_schema.py
  src/ert/config/parsing/queue_system.py
  src/ert/config/queue_config.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_queue_config.py
Labels: release-notes:bug-fix

#8446 Mitigate specific LSF test flakyness
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#8537 Backport #8525 to version 10.2
  docs/reference/configuration/keywords.rst
  src/ert/enkf_main.py
  src/ert/libres_facade.py
  src/ert/plugins/hook_implementations/workflows/export_runpath.py
  src/ert/run_models/base_run_model.py
  src/ert/runpaths.py
  src/ert/simulator/batch_simulator_context.py
  tests/unit_tests/test_runpaths.py
Labels: release-notes:bug-fix

#8538 Fix bug where seed was not set for manual initialization
  src/ert/gui/tools/manage_experiments/manage_experiments_panel.py
  tests/unit_tests/gui/tools/test_manage_experiments_tool.py
Labels: release-notes:bug-fix

#8539 Fix bug where seed was not set for manual initialization
  src/ert/gui/tools/manage_experiments/manage_experiments_panel.py
  tests/unit_tests/gui/tools/test_manage_experiments_tool.py
Labels: release-notes:bug-fix

#8532 Set status explicitly in progress_bar_label
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:skip

#8534 Fix broken ert test_run
  src/ert/config/queue_config.py
  tests/integration_tests/test_cli.py
  tests/unit_tests/config/test_queue_config.py
Labels: release-notes:skip

#8549 Fix runpath check in evaluate ensemble
  src/ert/run_models/evaluate_ensemble.py
  tests/unit_tests/run_models/test_model_factory.py
Labels: release-notes:bug-fix

#8438 Add pyrightconfig.json to gitignore
  .gitignore
Labels: release-notes:skip

#8523 Remove redundant experiment_id from ensemble
  src/ert/ensemble_evaluator/_ensemble.py
Labels: maintenance, release-notes:skip

#8556 Resolve typing errors in combobox_with_description
  src/ert/gui/simulation/combobox_with_description.py
  src/ert/gui/simulation/experiment_panel.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:skip

#8558 Remove unused infer iteration from rft csv export
  src/ert/resources/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  tests/unit_tests/gui/test_rft_export_plugin.py
Labels: release-notes:maintenance

#8547 Remove mark applied to a fixture
  tests/conftest.py
Labels: release-notes:skip

#8552 Mute asserted warnings in schema deprecations
  tests/unit_tests/config/parsing/test_config_schema_deprecations.py
Labels: release-notes:skip

#8561 Do not run gui tests in parallel
  ci/testkomodo.sh
Labels: release-notes:skip

#8541 Change style for disabled simulation modes
  src/ert/gui/simulation/combobox_with_description.py
Labels: release-notes:user-impact

#8540 Expose environment variables with run information in compute nodes
  src/ert/config/ert_config.py
  src/ert/enkf_main.py
  src/ert/run_models/base_run_model.py
  src/ert/simulator/batch_simulator_context.py
  tests/integration_tests/status/test_tracking_integration.py
  tests/integration_tests/test_cli.py
Labels: release-notes:new-feature

#8577 Replace json with orjson for performance reasons
  pyproject.toml
  src/_ert_forward_model_runner/reporting/file.py
  src/ert/enkf_main.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/test_run_path_creation.py
Labels: release-notes:improvement

#8579 Combine rss and oom_score checker in fm_runner
  src/_ert_forward_model_runner/job.py
  tests/unit_tests/forward_model_runner/test_job.py
Labels: release-notes:skip

#8584 Fix test that could give false positive
  tests/unit_tests/forward_model_runner/test_job.py
Labels: release-notes:skip

#8581 Remove children_list that shadows the children
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/model/node.py
  src/ert/gui/model/snapshot.py
  tests/unit_tests/gui/model/test_snapshot.py
Labels: release-notes:bug-fix

#8589 Add get_experiment_by_name to storage
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  tests/integration_tests/test_cli.py
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:improvement

#8595 Migrate from websockets legacy functionality
  docs/conf.py
  src/ert/ensemble_evaluator/evaluator.py
Labels: maintenance, release-notes:skip

#8596 Change driver `retries` param to `total_attempts`
  src/ert/scheduler/driver.py
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/slurm_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: maintenance, release-notes:skip

#8597 Set ensemble name of single test run to "ensemble"
  src/ert/gui/simulation/single_test_run_panel.py
  tests/unit_tests/gui/test_single_test_run.py
Labels: release-notes:skip

#8598 Increase reruns for flaky test_repeated_submit_same_iens to 10
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: flaky-test, release-notes:skip
