Repository equinor/ert, pull requests merged in 2024-11, with the labels that each got.

#9119 Have CopyDebugInfoButton change text to `Copied...` on click
  src/ert/gui/simulation/run_dialog.py
  tests/ert/unit_tests/gui/ertwidgets/test_copy_debug_info_button.py
Labels: release-notes:improvement

#9118 Update docs path in readthedocs config
  docs/everest/.readthedocs.yaml
Labels: release-notes:skip

#9122 Skip logging of short fm steps
  src/ert/ensemble_evaluator/_ensemble.py
Labels: release-notes:maintenance

#9089 Use maxprocesses=2 for cli tests
  .github/workflows/test_ert.yml
  ci/testkomodo.sh
Labels: release-notes:flaky-test-fix

#9129 Revert "Increase sleep in memory profile test from 0.1 -> 0.15"
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:flaky-test-fix

#9123 Backport logging of long forward model time steps.
  src/ert/ensemble_evaluator/_ensemble.py
Labels: release-notes:maintenance

#9132 Mitigate flakiness in memory profiling
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:flaky-test-fix

#9083 Improve logging with open telemetry traces
  pyproject.toml
  src/ert/__main__.py
  src/ert/plugins/hook_specifications/__init__.py
  src/ert/plugins/hook_specifications/logging.py
  src/ert/plugins/plugin_manager.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/scheduler/job.py
  src/ert/trace.py
  tests/ert/unit_tests/plugins/dummy_plugins.py
  tests/ert/unit_tests/plugins/test_plugin_manager.py
Labels: release-notes:logging

#9128 Timeout reading information from forward model runner after 60s and proceed with status from queue system
  src/_ert/forward_model_runner/client.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/scheduler/job.py
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:bug-fix

#9070 Remove ert config from batch sim
  src/ert/cli/workflow.py
  src/ert/config/ert_config.py
  src/ert/enkf_main.py
  src/ert/gui/tools/workflows/run_workflow_widget.py
  src/ert/run_models/base_run_model.py
  src/ert/simulator/batch_simulator.py
  src/ert/simulator/batch_simulator_context.py
  src/ert/workflow_runner.py
  src/everest/detached/__init__.py
  src/everest/simulator/simulator.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_forward_model.py
  tests/ert/unit_tests/config/test_forward_model_data_to_json.py
  tests/ert/unit_tests/config/test_gen_kw_config.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_runner.py
  tests/ert/unit_tests/simulator/test_batch_sim.py
  tests/ert/unit_tests/simulator/test_simulation_context.py
  tests/ert/unit_tests/storage/create_runpath.py
  tests/ert/unit_tests/test_enkf_main.py
  tests/ert/unit_tests/test_enkf_runpath.py
  tests/ert/unit_tests/test_load_forward_model.py
  tests/ert/unit_tests/test_run_path_creation.py
  tests/ert/unit_tests/test_summary_response.py
Labels: release-notes:maintenance

#9133 Scheduler now allows other code to run when starting realizations
  src/ert/scheduler/scheduler.py
Labels: release-notes:bug-fix

#9138 Update ropt dependency to 0.9.0
  pyproject.toml
  src/ert/run_models/everest_run_model.py
  src/everest/optimizer/everest2ropt.py
  tests/everest/test_simulator_cache.py
Labels: release-notes:dependency, everest

#9127 Transpose before calculating covariance in test
  tests/ert/ui_tests/cli/test_field_parameter.py
Labels: release-notes:skip

#9007 Disable experiment types that do parameter updates if there are no params to update
  src/ert/cli/main.py
  src/ert/gui/simulation/experiment_panel.py
  tests/ert/ui_tests/cli/test_parameter.py
  tests/ert/ui_tests/gui/test_missing_parameters_to_update.py
Labels: release-notes:improvement

#9190 Assume non-LSF host error is flaky
  src/ert/scheduler/lsf_driver.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:bug-fix

#9157 Add trace ID to clipboard debug info and title bar
  src/ert/gui/main_window.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/trace.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:logging

#9184 Remove old job queue test snapshot
  tests/ert/ui_tests/cli/snapshots/test_cli/test_es_mda/using_job_queue/es_mda_integration_snapshot
Labels: release-notes:skip

#9168 Use uvloop for asyncio
  pyproject.toml
  src/_ert/async_utils.py
  src/ert/__main__.py
Labels: release-notes:improvement

#9205 Fix error with inconsistent blobsize in flaky test
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:flaky-test-fix

#9131 Add right click capability to open external plot windows
  src/ert/gui/main_window.py
  tests/ert/ui_tests/gui/test_main_window.py
Labels: release-notes:improvement

#9206 Add egg snapshots for py38 and py311
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/egg-py311.csv
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/egg-py38.csv
  tests/everest/test_egg_simulation.py
Labels: release-notes:maintenance

#9213 Use sh for all code blocks in readme
  README.md
Labels: release-notes:documentation

#9214 Fix typing for batching_interval
  src/ert/ensemble_evaluator/evaluator.py
Labels: release-notes:skip

#9221 Fix flaky rightclick plot-button test
  tests/ert/ui_tests/gui/test_main_window.py
Labels: release-notes:skip, release-notes:flaky-test-fix

#9222 Fix faulty validation for maintained forward model objectives.
  src/everest/config/everest_config.py
  tests/everest/test_config_validation.py
Labels: release-notes:bug-fix

#9125 Extend save parameters to handle multiple realizations
  src/ert/analysis/_es_update.py
  src/ert/storage/local_ensemble.py
  tests/ert/ui_tests/cli/test_field_parameter.py
Labels: release-notes:improvement

#9219 Simplify test logic
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:skip, release-notes:flaky-test-fix

#9228 Fix walltime computation bug
  src/ert/ensemble_evaluator/_ensemble.py
Labels: release-notes:bug-fix

#9235 Leave test machine usable when running rapid-tests
  justfile
Labels: release-notes:skip

#9236 Remove outdated git lfs instruction
  README.md
Labels: documentation, release-notes:misc

#9239 Add test for mean calculation in dark_storage common
  tests/ert/unit_tests/dark_storage/test_common.py
Labels: release-notes:skip

#9231 Remove ErtConfig and LibresFacade
  src/everest/bin/everload_script.py
  tests/everest/unit/everest/bin/test_everload.py
Labels: release-notes:maintenance

#9242 Remove flaky memory profiling test
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:flaky-test-fix

#9246 Log which hostname had an OOM-situation
  src/_ert/forward_model_runner/forward_model_step.py
Labels: release-notes:misc

#9249 Perform validation earlier by returning EnOptConfig instead of dict
  src/everest/optimizer/everest2ropt.py
  tests/everest/test_ropt_initialization.py
Labels: release-notes:skip, everest

#9255 Update everest install command in ReadMe
  README.md
Labels: release-notes:skip

#9248 Fix ecl not able to parce errors from MPI runs
  src/ert/resources/forward_models/res/script/ecl_run.py
  tests/ert/unit_tests/resources/test_ecl_run_new_config.py
Labels: release-notes:bug-fix

#9265 Fix issue where dark_storage did not handle empty responses
  src/ert/dark_storage/common.py
  tests/ert/unit_tests/dark_storage/test_common.py
Labels: release-notes:bug-fix

#9257 Remove loading the same workflow twice
  tests/ert/unit_tests/simulator/test_batch_sim.py
Labels: release-notes:skip

#9272 Degrade logged warning to info
  src/ert/ensemble_evaluator/_ensemble.py
Labels: release-notes:misc

#9278 Remove unused files from test-data/detached
  tests/everest/test_data/detached/error_file.0
  tests/everest/test_data/detached/valid_yaml_config.yml
Labels: release-notes:maintenance

#9202 Test field with FORWARD_INIT:False
  test-data/ert/heat_equation/cond_0.bgrdecl
  test-data/ert/heat_equation/cond_1.bgrdecl
  test-data/ert/heat_equation/cond_2.bgrdecl
  test-data/ert/heat_equation/cond_3.bgrdecl
  test-data/ert/heat_equation/cond_4.bgrdecl
  test-data/ert/heat_equation/cond_5.bgrdecl
  test-data/ert/heat_equation/cond_6.bgrdecl
  test-data/ert/heat_equation/cond_7.bgrdecl
  test-data/ert/heat_equation/cond_8.bgrdecl
  test-data/ert/heat_equation/cond_9.bgrdecl
  test-data/ert/heat_equation/config_forward_init_false.ert
  test-data/ert/heat_equation/generate_files.py
  tests/ert/conftest.py
  tests/ert/ui_tests/cli/test_field_parameter.py
Labels: release-notes:skip

#9243 Replace Flask with FastAPI
  pyproject.toml
  src/everest/detached/jobs/everserver.py
Labels: release-notes:maintenance

#9300 Fix ambiguous find_unsmry()
  src/ert/resources/forward_models/res/script/ecl_run.py
  tests/ert/unit_tests/resources/test_ecl_run_new_config.py
Labels: release-notes:bug-fix

#9298 Fix tests writing files to the source tree
  tests/everest/conftest.py
  tests/everest/entry_points/test_everest_entry.py
  tests/everest/test_fm_plugins.py
  tests/everest/test_yaml_parser.py
Labels: release-notes:maintenance

#9312 Clean up everest tests
  tests/everest/test_data/spe1case/realization-0/eclipse/model/SPE1.DATA
  tests/everest/test_everlint.py
Labels: release-notes:maintenance

#9287 Remove unused files from test-data/valid_config_file
  tests/everest/test_data/valid_config_file/forward_models/input/configs/drill_planner_config.yml
  tests/everest/test_data/valid_config_file/forward_models/input/models/WELLSELECT.SCH
Labels: release-notes:maintenance

#9333 Mark a test as flaky
  tests/ert/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#9271 Remove report_steps from Everest config
  docs/everest/config_generated.rst
  src/everest/config/model_config.py
  src/everest/config_keys.py
  src/everest/simulator/everest_to_ert.py
  test-data/everest/egg/everest/model/config.yml
  test-data/everest/egg/everest/model/config_flow.yml
  tests/everest/test_config_validation.py
  tests/everest/test_egg_simulation.py
  tests/everest/test_everlint.py
  tests/everest/test_res_initialization.py
Labels: release-notes:breaking-change

#9324 Remove unused files from test-data/templating
  tests/everest/test_data/templating/cached_results_config/seba.db
Labels: release-notes:maintenance

#9332 Install everest deps when building readthedocs
  docs/everest/.readthedocs.yaml
Labels: release-notes:skip

#9330 Remove unused files from test-data/mocked_test_case
  tests/everest/test_data/mocked_test_case/cached_results_multi_objectives/seba.db
  tests/everest/test_data/mocked_test_case/cached_results_output_constraints/seba.db
  tests/everest/test_data/mocked_test_case/cached_results_test_case/seba.db
  tests/everest/test_data/mocked_test_case/config_fail_simulation.yml
  tests/everest/test_data/mocked_test_case/test_output/seba.db
Labels: release-notes:maintenance

#9350 Make bsub tests faster
  src/ert/scheduler/driver.py
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/slurm_driver.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
  tests/ert/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip

#9358 Remove the everest load entry point
  docs/everest/cli.rst
  src/everest/bin/everload_script.py
  src/everest/bin/main.py
  tests/everest/unit/everest/bin/test_everload.py
Labels: release-notes:user-impact, everest

#9139 Have ensemble fail early when problems on initial connection to ensemble evaluator
  src/ert/ensemble_evaluator/monitor.py
  tests/ert/unit_tests/ensemble_evaluator/test_monitor.py
Labels: release-notes:bug-fix

#9361 Fix everest output folder rolling
  src/everest/bin/everest_script.py
Labels: bug

#9372 Log that NUM_CPU was parsed from DATA
  src/ert/config/ert_config.py
Labels: release-notes:skip

#9374 Fix test when other plugins could be installed
  tests/everest/test_detached.py
Labels: release-notes:skip

#9233 Fix manifest having too many files and not substituting
  src/ert/callbacks.py
  src/ert/config/ext_param_config.py
  src/ert/config/field.py
  src/ert/config/gen_data_config.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parameter_config.py
  src/ert/config/response_config.py
  src/ert/config/summary_config.py
  src/ert/config/surface_config.py
  src/ert/enkf_main.py
  src/ert/substitutions.py
  tests/ert/unit_tests/config/egrid_generator.py
  tests/ert/unit_tests/config/summary_generator.py
  tests/ert/unit_tests/config/test_gen_data_config.py
  tests/ert/unit_tests/config/test_gen_kw_config.py
  tests/ert/unit_tests/config/test_summary_config.py
  tests/ert/unit_tests/config/test_surface_config.py
  tests/ert/unit_tests/dark_storage/test_common.py
  tests/ert/unit_tests/storage/test_local_storage.py
  tests/ert/unit_tests/test_run_path_creation.py
Labels: release-notes:maintenance

#9323 Mention runpath in copy_file docs
  src/ert/plugins/hook_implementations/forward_model_steps.py
Labels: release-notes:documentation

#9346 Add time&mem test for snake oil plotting
  tests/ert/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:skip

#9322 Only read process tree once per job_dispatch report
  src/_ert/forward_model_runner/forward_model_step.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:improvement

#9379 Ensure tests run in clean directory
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:skip

#9344 Simplify ensemble evaluator shutdown timeout
  src/ert/ensemble_evaluator/evaluator.py
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:flaky-test-fix

#9385 Enforce correct dtypes in migration
  src/ert/storage/migration/to8.py
Labels: release-notes:bug-fix, release-notes:skip

#9382 Remove lambda function
  src/everest/config/everest_config.py
Labels: release-notes:maintenance

#9397 Simplify torque test
  tests/everest/test_data/snake_oil/everest/model/snake_oil_torque.yml
  tests/everest/test_res_initialization.py
Labels: release-notes:maintenance
