Repository equinor/ert, pull requests merged in 2024-01, with the labels that each got.

#6820 Support simulation_context in scheduler
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  src/ert/simulator/batch_simulator_context.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/scheduler/test_scheduler.py
  tests/unit_tests/simulator/test_batch_sim.py
  tests/unit_tests/simulator/test_simulation_context.py
Labels: release-notes:skip

#6866 Sample a single value instead of ensemble_size
  src/ert/config/gen_kw_config.py
Labels: release-notes:skip

#6872 Make sure tests using scheduler have running event loop
  tests/conftest.py
Labels: flaky-test, release-notes:skip

#6880 Fix roff outputting double for parameters
  src/ert/field_utils/roff_io.py
  tests/unit_tests/field_utils/test_roff_io.py
Labels: release-notes:bug-fix

#6882 Backport roff fix
  src/ert/field_utils/roff_io.py
  tests/unit_tests/field_utils/test_roff_io.py
Labels: release-notes:bug-fix

#6881 Upgrade publish job
  .github/workflows/build_and_test.yml
Labels: release-notes:skip

#6843 Add tests for local driver
  tests/integration_tests/scheduler/test_integration_local_driver.py
  tests/unit_tests/scheduler/test_local_driver.py
Labels: release-notes:skip, scheduler

#6865 Add stop_long_running_jobs functionality to Scheduler
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/conftest.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip, scheduler

#6884 Clarify fixture param for try_queue_and_scheduler
  tests/conftest.py
  tests/integration_tests/analysis/snapshots/test_es_update/test_update_report/using_job_queue/update_log
  tests/integration_tests/analysis/snapshots/test_es_update/test_update_report/using_scheduler/update_log
  tests/integration_tests/cli/snapshots/test_integration_cli/test_es_mda/using_job_queue/es_mda_integration_snapshot
  tests/integration_tests/cli/snapshots/test_integration_cli/test_es_mda/using_scheduler/es_mda_integration_snapshot
Labels: release-notes:skip, scheduler

#6893 Add missing __init__ file
  tests/integration_tests/__init__.py
Labels: release-notes:skip

#6894 Fix unit test scheduler local driver
  tests/unit_tests/scheduler/test_local_driver.py
Labels: release-notes:skip

#6888 Use custom loop to get additional exceptions
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/evaluator_tracker.py
  src/ert/ensemble_evaluator/sync_ws_duplexer.py
  tests/conftest.py
  tests/unit_tests/ensemble_evaluator/conftest.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
Labels: release-notes:skip

#6824 Add unit tests for scheduler job states
  tests/unit_tests/scheduler/conftest.py
  tests/unit_tests/scheduler/test_job.py
Labels: release-notes:skip

#6902 Remove duplicate logging in scheduler job
  src/ert/scheduler/job.py
Labels: release-notes:skip

#6857 Support max_running in Scheduler
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#6870 Extract copy of non-updated params to func
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#6907 Make sure to log exception only when there is one
  src/ert/async_utils.py
Labels: release-notes:skip, scheduler

#6901 Reduce accuracy of surface-order test
  tests/integration_tests/analysis/test_es_update.py
Labels: release-notes:maintenance

#6895 Update README.md
  README.md
Labels: release-notes:skip

#6909 Ignore CancelledError when killing
  src/ert/scheduler/local_driver.py
Labels: release-notes:skip

#6915 Remove unused function _split_by
  src/ert/substitution_list.py
Labels: release-notes:skip

#6918 Add scheduler logs to jobqeue_file handler
  src/ert/logging/logger.conf
Labels: release-notes:skip, scheduler

#6778 Feature toggling can now be done from environment variables
  src/ert/__main__.py
  src/ert/shared/feature_toggling.py
  tests/conftest.py
  tests/unit_tests/shared/test_feature_toggling.py
  tests/unit_tests/shared/test_main_entry.py
Labels: release-notes:improvement

#6919 Upload coverage for doctests
  .github/workflows/doctest.yml
  codecov.yml
Labels: release-notes:skip

#6922 Ensure consistent log levels in integration tests
  tests/conftest.py
  tests/unit_tests/conftest.py
Labels: bug, release-notes:skip

#6913 Set max items in benchmark chart
  .github/workflows/benchmark.yml
Labels: release-notes:skip

#6925 Set default max_submit to 1 in tests
  tests/unit_tests/ensemble_evaluator/conftest.py
Labels: maintenance

#6920 Add explicit logging when Scheduler was cancelled
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
Labels: release-notes:skip, scheduler

#6908 Correctly cancel tasks from sync context in Scheduler
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip, scheduler

#6930 Ensure parsing errors of the summary file is not propagated to the user.
  src/ert/shared/share/ert/forward-models/res/script/ecl_run.py
Labels: release-notes:bug-fix

#6929 Use rangestring_to_list instead of IntVector
  src/ert/config/observations.py
Labels: release-notes:skip

#6934 Improve license error retry
  src/ert/shared/share/ert/forward-models/res/script/ecl_run.py
  tests/unit_tests/shared/share/test_ecl_run.py
Labels: release-notes:improvement

#6943 Fix ecl_run eclipse tests
  src/ert/shared/share/ert/forward-models/res/script/ecl_run.py
  tests/unit_tests/shared/share/test_ecl_run.py
  tests/unit_tests/shared/share/test_ecl_run_new_config.py
Labels: release-notes:skip

#6932 Fix an issue where summary keys were not consistently named
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/enkf_obs.cpp
  src/ert/config/_read_summary.py
  src/ert/config/ensemble_config.py
  src/ert/config/ert_config.py
  src/ert/config/observations.py
  src/ert/config/summary_config.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/all/plugins/snapshots/test_export_misfit/test_export_misfit/0/csv_data.csv
  tests/unit_tests/config/test_ensemble_config.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_observations.py
  tests/unit_tests/config/test_read_summary.py
  tests/unit_tests/data/snapshots/test_integration_data/test_all_measured_snapshot/0/snake_oil_measured_output.csv
  tests/unit_tests/snapshots/test_libres_facade/test_misfit_collector/0/misfit_collector.csv
  tests/unit_tests/test_libres_facade.py
Labels: bug

#6959 Provide more descriptive feedback on USE_EE and USE_GE
  src/ert/config/analysis_config.py
  tests/unit_tests/config/test_ert_config.py
Labels: release-notes:maintenance

#6962 Fix summary_keys generator
  tests/unit_tests/config/config_dict_generator.py
Labels: release-notes:skip

#6957 Refactor transfer functions test
  tests/unit_tests/config/test_transfer_functions.py
Labels: release-notes:skip

#6924 Add new workflow for dark storage performance benchmark
  .github/workflows/dark_storage_benchmark.yml
Labels: documentation, release-notes:skip

#6858 Support submit sleep in scheduler
  src/ert/config/queue_config.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#6973 Set minimum suggestor width to no more than two ui-cards
  src/ert/gui/suggestor/suggestor.py
Labels: release-notes:maintenance

#6950 Remove redudant while loop
  src/ert/scheduler/job.py
Labels: release-notes:skip, scheduler

#6964 Make poly-case runnable by default on RHEL7
  test-data/poly_example/poly_eval.py
Labels: release-notes:skip

#6980 Mark two scheduler tests as flaky
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#6989 Add missing space in error message
  src/ert/config/ert_config.py
Labels: release-notes:skip

#6965 Fix csv export
  src/ert/data/_measured_data.py
  tests/unit_tests/scenarios/test_summary_response.py
Labels: release-notes:bug-fix

#6998 Give proper error message when eclrun fails with nonzero return code
  src/ert/shared/share/ert/forward-models/res/script/ecl_run.py
  tests/unit_tests/shared/share/test_ecl_run.py
  tests/unit_tests/shared/share/test_ecl_run_new_config.py
Labels: release-notes:bug-fix

#7011 Relax requirement on return_code from mocked eclrun
  tests/unit_tests/shared/share/test_ecl_run_new_config.py
Labels: release-notes:skip

#7008 Scheduler: Pick last MAX_RUNNING rather than first
  src/ert/config/queue_config.py
  tests/unit_tests/config/test_queue_config.py
Labels: scheduler

#7014 Use relative tolerance for triangular test
  tests/unit_tests/config/test_transfer_functions.py
Labels: release-notes:skip

#7005 Use full run_path in UI and cut to valid path for clipboard
  src/ert/gui/ertwidgets/copyablelabel.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/libres_facade.py
  tests/unit_tests/gui/ertwidgets/test_copyablelabel.py
  tests/unit_tests/test_libres_facade.py
Labels: release-notes:maintenance

#7013 Update documentation on arm installation
  README.md
Labels: release-notes:skip

#6993 Log when ert is used with float64 fields and surfaces
  src/ert/storage/local_ensemble.py
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:skip

#7009 Add ContextBoolEncoder to facilitate json serialization of ContextBools.
  src/ert/config/parsing/context_values.py
  src/ert/storage/local_experiment.py
  tests/unit_tests/config/test_ert_config.py
Labels: release-notes:bug-fix

#7000 Enable scheduler by default for LOCAL queue
  src/ert/cli/main.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/gui/main.py
  src/ert/shared/feature_toggling.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
Labels: release-notes:misc, scheduler

#7006 Fix plotter raising ValueError when plotting same case twice
  src/ert/gui/ertwidgets/models/selectable_list_model.py
  src/ert/gui/main.py
  src/ert/gui/plottery/plot_config_factory.py
  src/ert/gui/plottery/plots/distribution.py
  src/ert/gui/tools/plot/customize/customize_plot_dialog.py
  src/ert/gui/tools/plot/data_type_keys_list_model.py
  src/ert/gui/tools/plot/data_type_keys_widget.py
  src/ert/gui/tools/plot/filter_popup.py
  src/ert/gui/tools/plot/filterable_kw_list_model.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/gui/tools/plot/plot_case_model.py
  src/ert/gui/tools/plot/plot_case_selection_widget.py
  src/ert/gui/tools/plot/plot_widget.py
  src/ert/gui/tools/plot/plot_window.py
  src/ert/gui/tools/plot/widgets/copy_style_to_dialog.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/ertwidgets/test_plot_case_selection_widget.py
  tests/unit_tests/gui/plottery/test_plotting_of_snake_oil.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/gui/tools/plot/test_plot_api.py
Labels: bug, qt, release-notes:improvement

#7026 Catch OSError so that Ctrl-c works for ERT
  src/ert/cli/main.py
Labels: release-notes:bug-fix

#7035 Update docstring of load_all_gen_kw_data
  src/ert/storage/local_ensemble.py
Labels: release-notes:skip

#7034 Remove mention of opencensus.
  src/ert/run_models/base_run_model.py
Labels: maintenance

#7018 Move experiment creation to run models
  src/ert/cli/main.py
  src/ert/cli/model_factory.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/run_models/single_test_run.py
  tests/integration_tests/status/test_tracking_integration.py
  tests/unit_tests/cli/test_model_factory.py
  tests/unit_tests/cli/test_model_hook_order.py
  tests/unit_tests/cli/test_run_context.py
  tests/unit_tests/ensemble_evaluator/test_evaluator_tracker.py
  tests/unit_tests/run_models/test_base_run_model.py
  tests/unit_tests/run_models/test_ensemble_experiment.py
Labels: release-notes:maintenance

#6887 Add TorqueDriver
  .github/workflows/coverage.yml
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/scheduler/__init__.py
  src/ert/scheduler/driver.py
  src/ert/scheduler/event.py
  src/ert/scheduler/job.py
  src/ert/scheduler/local_driver.py
  src/ert/scheduler/scheduler.py
  src/ert/scheduler/torque_driver.py
  tests/conftest.py
  tests/integration_tests/scheduler/__init__.py
  tests/integration_tests/scheduler/bin/qdel
  tests/integration_tests/scheduler/bin/qstat
  tests/integration_tests/scheduler/bin/qstat.py
  tests/integration_tests/scheduler/bin/qsub
  tests/integration_tests/scheduler/bin/runner
  tests/integration_tests/scheduler/test_torque_driver.py
  tests/unit_tests/scheduler/conftest.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_local_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:improvement

#7044 Replace observation_config with observations
  src/ert/analysis/_es_update.py
  src/ert/analysis/configuration.py
Labels: release-notes:skip

#7036 Fix a bug in migration
  src/ert/storage/local_storage.py
Labels: release-notes:bug-fix

#7033 Remove unused ignore_current from CaseSelector
  src/ert/gui/ertwidgets/caseselector.py
Labels: release-notes:skip

#7007 Remove libres from dark storage
  src/ert/dark_storage/common.py
  src/ert/dark_storage/endpoints/compute/misfits.py
  src/ert/dark_storage/endpoints/ensembles.py
  src/ert/dark_storage/endpoints/experiments.py
  src/ert/dark_storage/endpoints/observations.py
  src/ert/dark_storage/endpoints/records.py
  src/ert/dark_storage/endpoints/updates.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/shared/storage/extraction.py
  tests/performance_tests/test_dark_storage_performance.py
  tests/unit_tests/dark_storage/test_http_endpoints.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:skip

#7058 Speed up tests
  tests/conftest.py
  tests/integration_tests/test_observation_times.py
  tests/unit_tests/config/conftest.py
  tests/unit_tests/conftest.py
Labels: release-notes:skip

#7057 Speed up local_ensemble
  src/ert/storage/local_ensemble.py
Labels: release-notes:skip
