Repository equinor/ert, pull requests merged in 2024-05, with the labels that each got.

#7300 Add logging to map surface usage
  src/ert/config/ensemble_config.py
Labels: release-notes:misc

#7815 Skip snapshot test
  tests/performance_tests/test_snapshot.py
Labels: release-notes:skip

#7816 Iterate ensembles to look for history to plot
  src/ert/gui/tools/plot/plot_api.py
  src/ert/gui/tools/plot/plot_window.py
  tests/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:bug-fix

#7818 Iterate ensembles to look for history to plot
  src/ert/gui/tools/plot/plot_api.py
  src/ert/gui/tools/plot/plot_window.py
  tests/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:bug-fix

#7806 Move snapshot headerData logic for realizations to job_list.py
  src/ert/gui/model/job_list.py
  src/ert/gui/model/snapshot.py
  tests/unit_tests/gui/model/test_job_list.py
Labels: improvement, release-notes:skip

#7823 Set max-worker-restart to zero
  ci/testkomodo.sh
Labels: release-notes:skip

#7824 Add workflow to test against everest
  .github/workflows/test_everest.yml
Labels: release-notes:skip

#7827 Update pre-commit hooks
  .pre-commit-config.yaml
Labels: release-notes:skip

#7825 Fix an issue with finding smspec files
  src/ert/config/_read_summary.py
  test-data/eclipse/parse/ERROR.PRT
Labels: release-notes:bug-fix

#7837 Revert skipping test
  tests/performance_tests/test_snapshot.py
Labels: release-notes:skip

#7822 Simplify how we call and parse bjobs
  src/ert/scheduler/lsf_driver.py
  tests/integration_tests/job_queue/test_lsf_driver.py
  tests/integration_tests/scheduler/bin/bjobs.py
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:misc

#7846 Fix flaky test_new_monitor_can_pick_up_where_we_left_off
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: flaky-test, release-notes:skip

#7838 Remove unused iteration from ensemble experiment
  src/ert/cli/model_factory.py
  src/ert/gui/ertwidgets/models/init_iter_value.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/run_arguments.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/run_models/test_base_run_model.py
  tests/unit_tests/run_models/test_ensemble_experiment.py
Labels: release-notes:maintenance

#7853 Fix parameter example test
  tests/integration_tests/test_parameter_example.py
Labels: release-notes:skip

#7826 Add realizations to Ensemble manager tree view
  src/ert/gui/ertwidgets/models/storage_model.py
  src/ert/gui/ertwidgets/storage_info_widget.py
  src/ert/gui/ertwidgets/storage_widget.py
  src/ert/gui/tools/manage_experiments/ensemble_init_configuration.py
Labels: release-notes:improvement

#7861 Fix failing lsf integration test
  src/ert/scheduler/lsf_driver.py
Labels: release-notes:skip, scheduler

#7857 Fix flaky test_restarted_jobs_do_not_have_error_msgs
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: flaky-test, release-notes:skip

#7812 Add a CSV logger for memory logging pr. realization
  src/_ert_forward_model_runner/cli.py
  src/_ert_forward_model_runner/job.py
  src/_ert_forward_model_runner/reporting/event.py
  src/_ert_forward_model_runner/reporting/file.py
  src/_ert_forward_model_runner/reporting/message.py
  tests/unit_tests/forward_model_runner/test_event_reporter.py
  tests/unit_tests/forward_model_runner/test_file_reporter.py
  tests/unit_tests/forward_model_runner/test_job.py
  tests/unit_tests/forward_model_runner/test_job_dispatch.py
Labels: release-notes:new-feature

#7855 Migrate summary data as 32 bit float
  src/ert/storage/migration/to5.py
  tests/integration_tests/test_storage_migration.py
Labels: release-notes:bug-fix

#7874 Log more from scheduler when killing jobs
  src/ert/scheduler/scheduler.py
Labels: release-notes:skip

#7432 Deprecate lsf server
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/config/parsing/config_schema_item.py
Labels: configuration, release-notes:user-impact

#7881 Enable Scheduler for LSF Queue by default
  src/ert/shared/feature_toggling.py
  tests/integration_tests/job_queue/test_lsf_driver.py
Labels: release-notes:new-feature, release-notes:improvement, scheduler

#7865 Instruct LSF to dump stderr of submitted job to runpath
  src/ert/scheduler/lsf_driver.py
  tests/integration_tests/scheduler/bin/bsub
  tests/integration_tests/scheduler/bin/lsfrunner
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:new-feature

#7762 Have RealizationDelegate be hover-able
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/realization.py
Labels: improvement, release-notes:improvement

#7889 Improve memory usage reporting in GUI
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/realization.py
Labels: release-notes:user-impact

#7868 Reduce flakiness in memory profiling
  tests/unit_tests/forward_model_runner/test_job.py
Labels: release-notes:skip

#7653 Remove unused current_case
  src/ert/cli/model_factory.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/simulation_config_panel.py
  src/ert/run_models/run_arguments.py
  tests/unit_tests/cli/test_model_factory.py
  tests/unit_tests/cli/test_model_hook_order.py
Labels: release-notes:maintenance

#7896 Fix misleading logging statement
  src/ert/scheduler/scheduler.py
Labels: release-notes:skip

#7876 Trim jobs.json content
  src/ert/config/ert_config.py
  tests/unit_tests/config/test_forward_model_data_to_json.py
Labels: release-notes:breaking-change

#7900 Open job error messages in dialog window
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:improvement

#7904 Unpin hypothesis
  pyproject.toml
  tests/unit_tests/config/summary_generator.py
Labels: release-notes:skip

#7908 Add lower bound for hypothesis on py312
  pyproject.toml
Labels: release-notes:skip

#7909 Fix crash when FIELD has no data
  src/ert/gui/plottery/plots/std_dev.py
  src/ert/gui/tools/plot/plot_api.py
Labels: release-notes:bug-fix

#7862 Refactor gui node to use dataclasses
  src/ert/gui/model/node.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/run_dialog.py
  tests/unit_tests/gui/model/test_real_list.py
  tests/unit_tests/gui/model/test_snapshot.py
  tests/unit_tests/gui/simulation/view/test_realization.py
Labels: improvement, release-notes:skip

#7905 Remove step_id from forward_model_runner Init message
  src/_ert_forward_model_runner/reporting/message.py
Labels: improvement, release-notes:skip

#7926 Remove stray print statement
  src/ert/gui/model/snapshot.py
Labels: release-notes:skip

#7925 Use correct plural form for zero
  src/ert/gui/ertwidgets/summarypanel.py
Labels: release-notes:skip

#7875 Add version 10 highlights to release notes
  docs/about/click-on-stderr.png
  docs/about/click-show-details.png
  docs/about/license-retry.png
  docs/about/release_notes.rst
  docs/about/v10_manage_experiments.png
Labels: release-notes:skip

#7922 Use private simulation arguments in base run model
  src/ert/run_models/base_run_model.py
Labels: release-notes:skip

#7918 Change order of data in update view
  src/ert/gui/simulation/view/update.py
Labels: release-notes:improvement

#7920 Update config guide with more observations
  docs/getting_started/configuration/poly_new/guide.rst
  docs/getting_started/configuration/poly_new/with_more_observations/POLY_EVAL
  docs/getting_started/configuration/poly_new/with_more_observations/coeff_b.png
  docs/getting_started/configuration/poly_new/with_more_observations/coeff_priors
  docs/getting_started/configuration/poly_new/with_more_observations/generate_synthetic_observations.py
  docs/getting_started/configuration/poly_new/with_more_observations/observations
  docs/getting_started/configuration/poly_new/with_more_observations/poly_eval.py
  docs/getting_started/configuration/poly_new/with_more_observations/poly_final.ert
  docs/getting_started/configuration/poly_new/with_more_observations/poly_obs_data.txt
  docs/getting_started/configuration/poly_new/with_observations/coeff_a.png
  docs/getting_started/configuration/poly_new/with_observations/coeff_b.png
  docs/getting_started/configuration/poly_new/with_observations/coeff_c.png
  docs/getting_started/configuration/poly_new/with_observations/generate_synthetic_observations.py
  docs/getting_started/configuration/poly_new/with_observations/plot_obs.png
  docs/getting_started/configuration/poly_new/with_observations/time_map
  docs/getting_started/configuration/poly_new/with_results/plots.png
  docs/getting_started/configuration/poly_new/with_results/poly_plot.png
Labels: documentation, release-notes:skip

#7794 Have scheduler lsf driver dump bhist summary to runpath
  src/ert/scheduler/driver.py
  src/ert/scheduler/lsf_driver.py
  tests/integration_tests/job_queue/test_lsf_driver.py
  tests/integration_tests/scheduler/bin/bhist.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: improvement, release-notes:skip

#7919 Remove C Torque driver and tests
  setup.py
  src/clib/lib/CMakeLists.txt
  src/clib/lib/include/ert/job_queue/queue_driver.hpp
  src/clib/lib/include/ert/job_queue/torque_driver.hpp
  src/clib/lib/job_queue/queue_driver.cpp
  src/clib/lib/job_queue/torque_driver.cpp
  src/clib/tests/CMakeLists.txt
  src/clib/tests/job_queue/test_job_queue_driver.cpp
  src/clib/tests/job_queue/test_job_torque.cpp
  src/clib/tests/job_queue/test_job_torque_submit.cpp
  src/ert/config/queue_config.py
  src/ert/job_queue/qstat_proxy.sh
  src/ert/shared/feature_toggling.py
  tests/unit_tests/config/config_dict_generator.py
  tests/unit_tests/config/test_queue_config.py
  tests/unit_tests/job_queue/test_driver.py
  tests/unit_tests/job_queue/test_ert_qstat_proxy.py
  tests/unit_tests/job_queue/test_job_queue_node.py
  tests/unit_tests/job_queue/test_job_queue_node_torque.py
  tests/unit_tests/job_queue/test_torque_driver.py
Labels: release-notes:maintenance, scheduler

#7935 Show parameter and response status
  src/ert/gui/ertwidgets/models/storage_model.py
  src/ert/gui/ertwidgets/storage_info_widget.py
  src/ert/gui/ertwidgets/storage_widget.py
  src/ert/storage/local_ensemble.py
Labels: release-notes:improvement

#7945 Dynamically load ert.gui in workflows
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
Labels: release-notes:skip

#7949 Fix `_get_oom_score_for_processtree(...)` not ignoring `ProcessLookup…
  src/_ert_forward_model_runner/job.py
Labels: bug, release-notes:skip

#7952 Pattern match correct casing of analysis module algorithm
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
Labels: release-notes:bug-fix

#7928 Add an index column to the update log table
  src/ert/analysis/_es_update.py
  src/ert/analysis/snapshots.py
  src/ert/gui/simulation/view/update.py
Labels: release-notes:improvement

#7942 Fix restart enabling logic
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
Labels: release-notes:bug-fix

#7954 Plot first observation as default if found
  src/ert/gui/ertwidgets/storage_info_widget.py
Labels: release-notes:maintenance

#7955 Allow larger columns for treeview in manage experiments
  src/ert/gui/ertwidgets/storage_widget.py
Labels: release-notes:maintenance

#7956 Backport Fix `_get_oom_score_for_processtree(...)` not ignoring `ProcessLookupError` in `_ert_forward_model_runner/job.py`
  src/_ert_forward_model_runner/job.py
Labels: release-notes:bug-fix

#7957 Backport: Pattern match correct casing of analysis module algorithm
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
Labels: release-notes:bug-fix

#7958 Backport: Fix crash when FIELD has no data
  src/ert/gui/plottery/plots/std_dev.py
  src/ert/gui/tools/plot/plot_api.py
Labels: release-notes:bug-fix

#7380 Update documentation for GEN_KW
  docs/reference/configuration/keywords.rst
Labels: release-notes:skip

#7963 Fix ensemble selector counting list items wrongly
  src/ert/gui/tools/plot/plot_ensemble_selection_widget.py
Labels: release-notes:bug-fix

#7964 Backport: Fix ensemble selector counting list items wrongly
  src/ert/gui/tools/plot/plot_ensemble_selection_widget.py
Labels: release-notes:bug-fix

#7972 Fix typo parmeter -> parameter
  tests/unit_tests/forward_model_runner/test_job_dispatch.py
Labels: release-notes:skip

#7836 Add driver related failure info when job fails
  src/ert/scheduler/driver.py
  src/ert/scheduler/job.py
  src/ert/scheduler/local_driver.py
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: improvement, scheduler

#7902 Change default MAX_SUBMIT to 1
  docs/reference/configuration/keywords.rst
  src/ert/config/queue_config.py
  src/ert/job_queue/job_queue_node.py
  tests/integration_tests/test_cli.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:misc

#7976 Propagate debug logs from callbacks
  src/ert/logging/logger.conf
Labels: release-notes:maintenance

#7977 Backport: Propagate debug logs from callbacks
  src/ert/logging/logger.conf
Labels: release-notes:maintenance

#7979 Add migration feedback
  src/ert/storage/local_storage.py
Labels: release-notes:improvement

#7981 Add created at for experiment in GUI
  src/ert/gui/ertwidgets/models/storage_model.py
Labels: release-notes:bug-fix

#7978 Change which lines are ignored in coverage
  .coveragerc
Labels: release-notes:skip

#7989 Avoid using abspath for commands
  src/ert/config/parsing/config_schema_item.py
Labels: release-notes:bug-fix

#7992 Avoid using abspath for commands
  src/ert/config/parsing/config_schema_item.py
Labels: release-notes:bug-fix

#7924 Let ERT be able to stop experiment when all realizations are pending
  src/ert/ensemble_evaluator/monitor.py
  src/ert/run_models/base_run_model.py
  tests/unit_tests/ensemble_evaluator/test_monitor.py
Labels: release-notes:bug-fix

#7965 Move get_machine_name to public API
  src/ert/ensemble_evaluator/config.py
  src/ert/shared/__init__.py
  src/ert/shared/port_handler.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator_config.py
  tests/unit_tests/shared/test_port_handler.py
Labels: release-notes:maintenance

#7988 Log queue system used when logging orchestrator
  src/ert/ensemble_evaluator/_builder/_legacy.py
Labels: scheduler

#7982 Simplify calculation of weights to run in ES-MDA
  src/ert/run_models/multiple_data_assimilation.py
Labels: release-notes:skip

#7994 Add test for new cmd behavior
  tests/unit_tests/config/test_forward_model_data_to_json.py
Labels: release-notes:skip

#7961 Add icon to ert
  README.md
  docs/about/index.rst
  docs/index.rst
  src/ert/gui/main.py
  src/ert/gui/resources/gui/img/ert_icon.svg
Labels: release-notes:improvement

#7997 Fix test_parameter_example generation of min > max
  tests/integration_tests/test_parameter_example.py
Labels: release-notes:skip

#8000 Add heartbeat to test_run_and_cancel_legacy_ensemble
  tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
Labels: flaky-test

#7974 Add out-of-memory detection
  pyproject.toml
  src/_ert_forward_model_runner/job.py
  tests/conftest.py
  tests/integration_tests/test_cli.py
  tests/unit_tests/forward_model_runner/test_job_dispatch.py
Labels: release-notes:improvement

#7986 Rename simulation mode to experiment type
  README.md
  src/ert/gui/main.py
  src/ert/gui/simulation/__init__.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/evaluate_ensemble_panel.py
  src/ert/gui/simulation/experiment_config_panel.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/single_test_run_panel.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/simulation/test_evaluate_ensemble_panel.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
  tests/unit_tests/gui/simulation/test_run_path_dialog.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/gui/test_restart_ensemble_experiment.py
  tests/unit_tests/gui/test_restart_no_responses_and_parameters.py
  tests/unit_tests/gui/test_single_test_run.py
Labels: release-notes:maintenance

#7980 Fix RealNodeData subscriptable
  src/ert/gui/model/node.py
  src/ert/gui/model/snapshot.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/model/test_progress_proxy.py
  tests/unit_tests/gui/model/test_real_list.py
  tests/unit_tests/gui/model/test_snapshot.py
Labels: release-notes:maintenance
