Repository equinor/ert, pull requests merged in 2024-03, with the labels that each got.

#7322 Remove timeouts for LSF integration tests
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: bug, release-notes:skip, scheduler

#7321 Mute warnings from PBS driver
  src/ert/scheduler/openpbs_driver.py
Labels: release-notes:skip, scheduler

#7121 Remove experimental feature row scaling
  README.md
  src/clib/CMakeLists.txt
  src/clib/lib/CMakeLists.txt
  src/clib/lib/enkf/row_scaling.cpp
  src/clib/lib/include/ert/enkf/row_scaling.hpp
  src/clib/lib/include/ert/python.hpp
  src/clib/tests/CMakeLists.txt
  src/clib/tests/enkf/test_row_scaling.cpp
  src/ert/analysis/_es_update.py
  src/ert/analysis/configuration.py
  src/ert/analysis/row_scaling.py
  src/ert/analysis/update.py
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/analysis/test_row_scaling.py
  tests/unit_tests/analysis/test_row_scaling_increased_belief_case.py
  tests/unit_tests/analysis/test_update_configuration.py
Labels: release-notes:breaking-change

#7319 Remove update configuration and introduce update option to gen_kw
  src/ert/analysis/__init__.py
  src/ert/analysis/_es_update.py
  src/ert/analysis/configuration.py
  src/ert/analysis/update.py
  src/ert/config/ert_config.py
  src/ert/config/ert_script.py
  src/ert/config/ext_param_config.py
  src/ert/config/field.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parameter_config.py
  src/ert/config/surface_config.py
  src/ert/enkf_main.py
  src/ert/gui/simulation/view/update.py
  src/ert/gui/tools/run_analysis/run_analysis_tool.py
  src/ert/libres_facade.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/shared/hook_implementations/workflows/disable_parameters.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  src/ert/storage/migration/update_params.py
  tests/integration_tests/analysis/test_es_update.py
  tests/integration_tests/test_cli.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/all/plugins/test_parameter_disable.py
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_only_using_subset_observations/0/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-False/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-True/update_log
  tests/unit_tests/analysis/test_es_update.py
  tests/unit_tests/analysis/test_update_configuration.py
  tests/unit_tests/config/test_gen_kw_config.py
  tests/unit_tests/config/test_surface_config.py
  tests/unit_tests/gui/ertwidgets/models/test_ertsummary.py
  tests/unit_tests/scenarios/test_summary_response.py
  tests/unit_tests/storage/migration/test_block_fs_snake_oil.py
  tests/unit_tests/storage/test_local_storage.py
  tests/unit_tests/storage/test_parameter_config.py
  tests/unit_tests/storage/test_parameter_sample_types.py
  tests/unit_tests/test_local_config.py
Labels: release-notes:breaking-change, release-notes:user-impact

#7224 Remove jobname from poly example
  test-data/poly_example/poly.ert
  tests/integration_tests/test_cli.py
Labels: release-notes:maintenance

#7334 Mute transitions from PBS
  src/ert/scheduler/openpbs_driver.py
Labels: release-notes:skip, scheduler

#7348 Fix bug creating tmp in the wrong place
  ci/testkomodo.sh
Labels: release-notes:skip

#7346 Change from using flaky to pytest_rerunfailures
  pyproject.toml
  tests/integration_tests/storage/test_parameter_sample_types.py
  tests/performance_tests/test_memory_usage.py
  tests/unit_tests/job_queue/test_ert_qstat_proxy.py
  tests/unit_tests/job_runner/test_event_reporter.py
  tests/unit_tests/job_runner/test_job.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: bug, release-notes:skip

#7362 Remove leftover debug comment
  src/ert/ensemble_evaluator/snapshot.py
Labels: release-notes:skip

#7291 Fixed <ERTCASE> in runpath not working
  src/ert/enkf_main.py
  src/ert/run_context.py
  src/ert/run_models/base_run_model.py
  src/ert/runpaths.py
  src/ert/shared/hook_implementations/workflows/export_runpath.py
  src/ert/simulator/simulation_context.py
  tests/unit_tests/config/test_defines.py
  tests/unit_tests/config/test_gen_kw_config.py
  tests/unit_tests/run_models/test_base_run_model.py
  tests/unit_tests/storage/create_runpath.py
  tests/unit_tests/test_enkf_main.py
  tests/unit_tests/test_enkf_runpath.py
  tests/unit_tests/test_load_forward_model.py
  tests/unit_tests/test_run_path_creation.py
  tests/unit_tests/test_runpaths.py
  tests/unit_tests/test_summary_response.py
Labels: release-notes:bug-fix

#7359 Make parameter example test shrink better
  tests/integration_tests/test_parameter_example.py
Labels: release-notes:skip

#7375 Use concurrency to cancel existing workflow jobs
  .github/workflows/actionlint.yml
  .github/workflows/annotate_cpp.yml
  .github/workflows/benchmark.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-macos.yml
  .github/workflows/build_and_test.yml
  .github/workflows/coverage.yml
  .github/workflows/dark_storage_benchmark.yml
  .github/workflows/doctest.yml
  .github/workflows/run_ert_test_data_setups.yml
  .github/workflows/style.yml
  .github/workflows/test_ert.yml
  .github/workflows/test_ert_with_slurm.yml
  .github/workflows/test_semeio.yml
  .github/workflows/typing.yml
Labels: release-notes:maintenance

#7304 Fix bug where nan values were exported to grdecl
  src/ert/field_utils/grdecl_io.py
  tests/integration_tests/storage/test_field_parameter.py
  tests/unit_tests/field_utils/test_grdecl_io.py
Labels: release-notes:bug-fix

#7379 Limit MacOS testing to python 3.12, skipping 3.10 and 3.11
  .github/workflows/benchmark.yml
  .github/workflows/build_and_test.yml
  .github/workflows/doctest.yml
  .github/workflows/run_ert_test_data_setups.yml
Labels: release-notes:maintenance

#7373 Do not retry when we get 'Job has finished' from qdel
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip, scheduler

#7390 Add test of storage migration
  tests/integration_tests/snapshots/test_storage_migration/test_that_storage_matches/parameters
  tests/integration_tests/snapshots/test_storage_migration/test_that_storage_matches/responses
  tests/integration_tests/test_storage_migration.py
Labels: release-notes:skip

#7354 Dodge bug when simulation_context tears down
  tests/unit_tests/simulator/test_batch_sim.py
Labels: release-notes:skip

#7376 Avoid "qstat -f" for non-finished jobs in PBS
  src/ert/scheduler/openpbs_driver.py
  tests/integration_tests/scheduler/bin/qstat.py
  tests/integration_tests/scheduler/test_openpbs_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:improvement, scheduler

#7397 Ensure no duplicate keys in SummaryConfig
  src/ert/config/summary_config.py
  tests/integration_tests/test_storage_migration.py
  tests/unit_tests/config/test_summary_config.py
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#7385 Treat exceptions of long lived tasks (scheduling_tasks) in scheduler
  src/ert/async_utils.py
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/integration_tests/scheduler/test_openpbs_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
  tests/unit_tests/test_async_utils.py
Labels: release-notes:bug-fix, scheduler

#7213 Fix external_ert_script does not fail on error
  docs/reference/workflows/configuring_jobs.rst
  src/ert/job_queue/workflow_runner.py
  tests/integration_tests/test_cli.py
Labels: release-notes:breaking-change, release-notes:bug-fix

#7389 Use newer style v resource allocation for Torque (C) and PBS (Python)
  src/clib/lib/job_queue/torque_driver.cpp
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/job_queue/test_torque_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:bug-fix

#7410 Fix summary reading being too slow in case of many summary keys to match against
  src/ert/config/_read_summary.py
  tests/unit_tests/config/test_read_summary.py
Labels: release-notes:bug-fix

#7411 Use block storage path fixture in storage test
  tests/conftest.py
  tests/integration_tests/test_storage_migration.py
  tests/unit_tests/storage/migration/conftest.py
Labels: release-notes:bug-fix

#7424 Improve scheduler unit tests for scheduling_tasks exceptions
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#7423 Add remaining states to the working STATES for LSF driver
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip, scheduler

#7430 Show total time in update tab
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/view/update.py
Labels: release-notes:improvement

#7417 Rename simulation arguments
  src/ert/gui/ertwidgets/models/storage_model.py
  src/ert/storage/local_experiment.py
Labels: release-notes:skip

#7398 Add more info about observations
  src/ert/analysis/_es_update.py
  src/ert/gui/simulation/view/update.py
  tests/integration_tests/analysis/test_es_update.py
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_only_using_subset_observations/0/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-False/update_log
  tests/unit_tests/analysis/snapshots/test_es_update/test_update_report/0-True/update_log
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:improvement

#7428 Deprecate unused lsf options
  docs/reference/configuration/keywords.rst
  docs/reference/configuration/queue.rst
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/parsing/schema_dict.py
  tests/unit_tests/config/parsing/test_config_schema_deprecations.py
Labels: blocked, release-notes:user-impact

#7442 Only build & test using macos runners for tags
  .github/workflows/build_and_test.yml
  .github/workflows/run_ert_test_data_setups.yml
Labels: release-notes:skip

#7419 Account for cases when the summary data is empty.
  src/ert/dark_storage/common.py
  src/ert/storage/local_ensemble.py
Labels: release-notes:bug-fix

#7426 Store update log in experiment
  src/ert/analysis/_es_update.py
  src/ert/gui/simulation/view/update.py
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:improvement

#7445 Remove fixture marks that has no effect
  tests/unit_tests/gui/conftest.py
Labels: release-notes:skip

#7454 Make PBS tests more tolerant for SIGTERM variants
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: release-notes:skip

#7420 Have OpenPBS driver use qstat -w option
  src/ert/scheduler/openpbs_driver.py
  tests/integration_tests/scheduler/bin/qstat.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip

#7461 Update contributing.md
  CONTRIBUTING.md
Labels: release-notes:misc

#7466 Fix LSF drivers ability to send to non-default queue
  ci/testkomodo.sh
  src/ert/scheduler/lsf_driver.py
  tests/integration_tests/scheduler/bin/bsub
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: bug, release-notes:skip

#7450 Make gui tests independent
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_full_manual_update_workflow.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:skip

#7467 Stop failing on upload error
  .github/workflows/build_and_test.yml
  .github/workflows/coverage.yml
  .github/workflows/doctest.yml
Labels: release-notes:skip

#7463 Fix integration tests with real LSF cluster
  tests/integration_tests/scheduler/test_generic_driver.py
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: bug, release-notes:skip

#7469 Allow one macOS build
  .github/workflows/build_and_test.yml
  .github/workflows/run_ert_test_data_setups.yml
Labels: release-notes:maintenance

#7464 Remove unused file exists exception
  src/ert/exceptions/__init__.py
  src/ert/exceptions/_exceptions.py
Labels: release-notes:skip

#7470 Allow cleanup rm commands to fail
  ci/testkomodo.sh
Labels: release-notes:skip

#7471 Ensure no overflow in parameter_example test
  tests/integration_tests/test_parameter_example.py
Labels: release-notes:skip

#7293 Log scheduler/job_queue orchestrator when created
  src/ert/ensemble_evaluator/_builder/_legacy.py
Labels: release-notes:skip

#7485 Mark failing test test_openpbs_driver_with_poly_example_failing_poll_…
  tests/integration_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip

#7421 Have scheduler handle exceptions in Job.__call__()
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/integration_tests/scheduler/test_openpbs_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip, scheduler

#7491 Skip flaky test_parameter_example
  tests/integration_tests/test_parameter_example.py
Labels: release-notes:skip

#7489 Use correct dependencies when tagged builds
  .github/workflows/build_and_test.yml
Labels: bug

#7433 Have lsf_driver specify SIGKILL when bkilling
  src/clib/lib/job_queue/lsf_driver.cpp
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:bug-fix

#7476 Ensure correct array type with ES
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#7488 Add tests for bjobs output with exec_host split over two lines and missing
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: testing, release-notes:skip

#7391 Save storage version after migration
  src/ert/storage/local_storage.py
  src/ert/storage/migration/gen_kw.py
  src/ert/storage/migration/observations.py
  src/ert/storage/migration/response_info.py
Labels: maintenance

#7459 Use headers in keyword documentation instead of topics
  docs/reference/configuration/keywords.rst
  src/ert/config/parsing/config_schema_deprecations.py
Labels: release-notes:maintenance

#7484 Add a test for opening empty storage
  src/ert/storage/local_storage.py
  tests/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#7506 Fix If -> if in docs
  docs/reference/configuration/keywords.rst
Labels: documentation, release-notes:skip

#7521 Increase sleep time flaky integration test
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: flaky-test, release-notes:skip

#7523 Skip integration test analysis/test_es_update.py::test_update_multipl…
  tests/integration_tests/analysis/test_es_update.py
Labels: skipped_test, flaky-test, release-notes:skip
