Repository equinor/ert, pull requests merged in 2024-04, with the labels that each got.

#7517 Fix ruff preview option PLC1901
  src/ert/config/_option_dict.py
  src/ert/config/_read_summary.py
  src/ert/config/field.py
  src/ert/config/queue_config.py
  src/ert/gui/ertwidgets/checklist.py
  src/ert/gui/ertwidgets/ensemblelist.py
  src/ert/gui/ertwidgets/models/activerealizationsmodel.py
  src/ert/gui/ertwidgets/models/targetensemblemodel.py
  src/ert/gui/ertwidgets/models/text_model.py
  src/ert/gui/ertwidgets/pathchooser.py
  src/ert/gui/ertwidgets/searchbox.py
  src/ert/gui/ertwidgets/stringbox.py
  src/ert/gui/ertwidgets/validateddialog.py
  src/ert/gui/ertwidgets/validationsupport.py
  src/ert/gui/plottery/plot_style.py
  src/ert/gui/plottery/plots/ensemble.py
  src/ert/gui/plottery/plots/observations.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/single_test_run_panel.py
  src/ert/gui/tools/plot/customize/customization_view.py
  src/ert/gui/tools/plot/style_chooser.py
  src/ert/gui/tools/plot/widgets/clearable_line_edit.py
  src/ert/job_queue/job_queue_node.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/scheduler/job.py
  src/ert/services/_base_service.py
  src/ert/shared/share/ert/forward-models/res/script/rms.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/validation/active_range.py
  src/ert/validation/argument_definition.py
  src/ert/validation/rangestring.py
  tests/integration_tests/scheduler/bin/qstat.py
  tests/unit_tests/config/test_ert_config.py
  tests/unit_tests/config/test_queue_config.py
  tests/unit_tests/gui/ide/test_integer_argument.py
  tests/unit_tests/gui/plottery/test_plot_style.py
  tests/unit_tests/job_queue/test_driver.py
  tests/unit_tests/job_runner/test_file_reporter.py
Labels: improvement, release-notes:skip

#7526 Remove poly integration test on PBS
  tests/integration_tests/scheduler/test_openpbs_driver.py
Labels: bug

#7529 Fix ruff preview option PLR6301
  src/_ert_job_runner/reporting/file.py
  src/_ert_job_runner/reporting/interactive.py
  src/ert/config/ert_plugin.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parsing/lark_parser.py
  src/ert/config/parsing/observations_parser.py
  src/ert/config/surface_config.py
  src/ert/dark_storage/app.py
  src/ert/data/_measured_data.py
  src/ert/ensemble_evaluator/_builder/_ensemble.py
  src/ert/gui/about_dialog.py
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
  src/ert/gui/ertwidgets/customdialog.py
  src/ert/gui/ertwidgets/models/storage_model.py
  src/ert/gui/ertwidgets/summarypanel.py
  src/ert/gui/ertwidgets/validateddialog.py
  src/ert/gui/model/job_list.py
  src/ert/gui/model/progress_proxy.py
  src/ert/gui/model/real_list.py
  src/ert/gui/model/snapshot.py
  src/ert/gui/plottery/plots/cesp.py
  src/ert/gui/plottery/plots/distribution.py
  src/ert/gui/plottery/plots/ensemble.py
  src/ert/gui/plottery/plots/gaussian_kde.py
  src/ert/gui/plottery/plots/histogram.py
  src/ert/gui/plottery/plots/statistics.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/simulation/simulation_config_panel.py
  src/ert/gui/simulation/simulation_panel.py
  src/ert/gui/simulation/view/legend.py
  src/ert/gui/simulation/view/progress.py
  src/ert/gui/simulation/view/realization.py
  src/ert/gui/tools/plot/customize/limits_customization_view.py
  src/ert/gui/tools/plot/customize/style_customization_view.py
  src/ert/gui/tools/plot/data_type_keys_list_model.py
  src/ert/gui/tools/plot/style_chooser.py
  src/ert/libres_facade.py
  src/ert/logging/__init__.py
  src/ert/scheduler/driver.py
  src/ert/scheduler/local_driver.py
  src/ert/shared/hook_implementations/workflows/export_runpath.py
  src/ert/shared/share/ert/forward-models/res/script/ecl_config.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/csv_export.py
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py
  tests/unit_tests/config/observations_generator.py
  tests/unit_tests/job_queue/test_ert_plugin.py
  tests/unit_tests/job_queue/test_ert_script.py
  tests/unit_tests/scheduler/conftest.py
  tests/unit_tests/storage/test_local_storage.py
  tests/unit_tests/storage/test_mode.py
Labels: release-notes:skip

#7482 Have BKILL signal SIGKILL after SIGTERM
  src/clib/lib/job_queue/lsf_driver.cpp
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:misc

#7299 Let LSF driver fall back to bhist for not-found jobs in bjobs
  src/ert/scheduler/__init__.py
  src/ert/scheduler/lsf_driver.py
  tests/integration_tests/scheduler/bin/bhist
  tests/integration_tests/scheduler/bin/bhist.py
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
  tests/utils.py
Labels: release-notes:skip, scheduler

#7536 Fix flaky parameter test
  tests/integration_tests/test_parameter_example.py
Labels: release-notes:skip

#7540 Fix ErtPlugin interface staticmethods
  src/ert/config/ert_plugin.py
Labels: release-notes:skip

#7547 Revert "Implement EXCLUDE_HOST for scheduler lsf driver"
  src/ert/scheduler/__init__.py
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#7548 Fix docs about auto scale
  docs/reference/configuration/keywords.rst
Labels: release-notes:maintenance

#7538 Fix bug where all ensembles would show instead of just initialized
  src/ert/gui/ertwidgets/ensembleselector.py
  tests/unit_tests/gui/ertwidgets/test_ensembleselector.py
Labels: release-notes:bug-fix

#7556 Avoid calling kill() on each submit in LocalDriver
  src/ert/scheduler/local_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip

#7553 Fix incorrect lsf_driver integration test
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: bug, release-notes:skip

#7561 Return none if the parser does not provide scheduler_feature
  src/ert/shared/feature_toggling.py
Labels: scheduler

#7568 Add new implementation of get_num_cpu
  src/ert/config/_get_num_cpu.py
  src/ert/config/ert_config.py
  src/ert/substitution_list.py
  tests/unit_tests/config/test_forward_model_data_to_json.py
  tests/unit_tests/job_runner/test_jobmanager.py
  tests/unit_tests/test_run_path_creation.py
Labels: release-notes:skip

#7567 Remove deprecated function libres_facade.grid
  src/ert/libres_facade.py
Labels: release-notes:breaking-change

#7580 Ensure no underflow in parameter_example_test
  tests/integration_tests/test_parameter_example.py
Labels: release-notes:skip

#7575 Display possible error when removing existing runpath
  src/ert/gui/simulation/simulation_panel.py
  tests/unit_tests/gui/simulation/test_run_path_dialog.py
Labels: release-notes:bug-fix

#7586 Add SIGKILL to possible returncodes from kill
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: bug, release-notes:skip

#7581 Solve race condition in lsf_driver for job_ids
  src/ert/scheduler/lsf_driver.py
Labels: bug, release-notes:skip

#7414 Test that pbs driver ignores qstat flakiness
  tests/conftest.py
  tests/integration_tests/scheduler/bin/qstat.py
  tests/integration_tests/scheduler/test_openpbs_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: testing, release-notes:skip, scheduler

#7542 Split release notes in highlighted changes and change log
  docs/about/release_notes.rst
Labels: release-notes:maintenance

#7566 Remove unused endpoint in dark storage
  src/ert/dark_storage/endpoints/__init__.py
  src/ert/dark_storage/endpoints/responses.py
  tests/performance_tests/test_dark_storage_performance.py
  tests/unit_tests/dark_storage/test_http_endpoints.py
Labels: release-notes:breaking-change

#7577 Fix OpenPBS driver logging error when killing failed jobs
  src/ert/scheduler/openpbs_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: bug, release-notes:skip

#7480 Refactor _get_obs_and_measure_data
  src/ert/analysis/_es_update.py
Labels: release-notes:skip

#7579 Fix storage instance used outside of storage context
  tests/integration_tests/storage/test_field_parameter.py
  tests/integration_tests/storage/test_parameter_sample_types.py
Labels: release-notes:skip

#7543 Fix exclude host lsf queue option
  src/ert/scheduler/__init__.py
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: bug, release-notes:skip

#7584 Solve deprecation warning from datetime on UTC
  tests/integration_tests/scheduler/bin/bjobs.py
Labels: release-notes:skip

#7597 Solve py312 warning on pkgutil.get_loader
  src/ert/config/ert_config.py
  src/ert/shared/hook_implementations/jobs.py
  tests/conftest.py
  tests/unit_tests/shared/share/test_forward_models.py
  tests/unit_tests/shared/share/test_rms.py
  tests/unit_tests/shared/share/test_templating.py
Labels: maintenance, release-notes:skip

#7599 Let mocked bkill support specific kill signal
  tests/integration_tests/scheduler/bin/bkill.py
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: release-notes:skip

#7601 Fix hanging cli integration test
  tests/integration_tests/test_cli.py
Labels: bug, release-notes:skip

#7444 Document how delete_directory works on symlinks
  src/ert/shared/share/ert/forward-models/docs/description/DELETE_DIRECTORY.rst
  tests/unit_tests/shared/share/test_shell.py
Labels: documentation, release-notes:skip

#7585 Avoid erroneous developer commits to main branch
  .pre-commit-config.yaml
Labels: release-notes:skip

#7613 Fix test_small_time_mismatches_are_ignored
  tests/integration_tests/test_observation_times.py
Labels: bug, release-notes:skip

#7607 Remove pass statement
  src/ert/config/ert_config.py
Labels: release-notes:skip

#7614 Fix storage instance used outside of storage context
  tests/integration_tests/storage/test_field_parameter.py
Labels: improvement, release-notes:skip

#7615 Rename Job.__call__ to job.run in scheduler
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/test_job.py
Labels: maintenance, release-notes:skip, scheduler

#7594 Fix Python3.12 deprecation warning in async_utils.py
  src/ert/async_utils.py
Labels: bug, release-notes:skip

#7254 Document storage
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  src/ert/storage/mode.py
Labels: documentation, release-notes:improvement

#7623 Remove duplicate data
  src/ert/gui/simulation/view/update.py
Labels: release-notes:skip

#7620 Increase timeout for cluster integration tests
  ci/testkomodo.sh
  tests/integration_tests/scheduler/test_generic_driver.py
Labels: testing, release-notes:skip

#7618 Rename async_utils get_event_loop() to get_running_loop()
  src/ert/async_utils.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/ensemble_evaluator/evaluator_tracker.py
  tests/conftest.py
  tests/performance_tests/test_dark_storage_performance.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
Labels: improvement, release-notes:skip

#7616 Remove start sync event from scheduler job.__call__
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/test_job.py
Labels: improvement, release-notes:skip, scheduler

#7573 Increase qstat performance by adding -E option
  src/ert/scheduler/openpbs_driver.py
  tests/integration_tests/scheduler/bin/qstat.py
Labels: release-notes:misc

#7583 Change cwd to tmpdir in some tests currently polluting working dir
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#7622 Plot items support reorder and have visual indicators
  src/ert/gui/resources/gui/img/swap_vertical.svg
  src/ert/gui/tools/plot/plot_ensemble_selection_widget.py
  tests/unit_tests/gui/ertwidgets/test_plot_case_selection_widget.py
  tests/unit_tests/gui/test_main_window.py
Labels: release-notes:improvement

#7650 Fix bug where single_test_run could not run after anything else #7649
  src/ert/gui/simulation/single_test_run_panel.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_single_test_run.py
Labels: release-notes:bug-fix

#7652 Rename Jobs to Forward Model in GUI
  src/ert/gui/ertwidgets/summarypanel.py
Labels: release-notes:misc

#7656 Fix memory being reported without units in GUI
  src/ert/gui/model/snapshot.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:misc

#7617 Fix GUI RunDialog not expanding details header
  src/ert/gui/model/job_list.py
  src/ert/gui/simulation/run_dialog.py
Labels: bug, release-notes:bug-fix

#7673 Ignore stderr for parsing bsub output
  src/clib/lib/job_queue/lsf_driver.cpp
  tests/unit_tests/job_queue/test_job_queue_node.py
Labels: release-notes:bug-fix

#7671 Fix runtime-error string in lsf_driver
  src/clib/lib/job_queue/lsf_driver.cpp
Labels: release-notes:skip

#7674 Ignore stderr for parsing bsub output
  src/clib/lib/job_queue/lsf_driver.cpp
  tests/unit_tests/job_queue/test_job_queue_node.py
Labels: release-notes:bug-fix

#7672 Fix LSF driver logging wrong message when killing
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: bug, release-notes:skip, scheduler

#7649 Fix bug where single_test_run could not run after anything else
  src/ert/gui/simulation/single_test_run_panel.py
  tests/unit_tests/gui/conftest.py
  tests/unit_tests/gui/test_single_test_run.py
Labels: release-notes:bug-fix

#7624 Have async function use event loop from async_utils
  src/_ert/async_utils.py
  src/_ert_job_runner/client.py
  src/ert/ensemble_evaluator/_builder/_legacy.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/evaluator_tracker.py
  src/ert/ensemble_evaluator/sync_ws_duplexer.py
  src/ert/scheduler/scheduler.py
  tests/conftest.py
  tests/performance_tests/test_dark_storage_performance.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_async_queue_execution.py
Labels: improvement, release-notes:skip

#7654 Fix documentation for LSF memory booking
  docs/reference/configuration/queue.rst
Labels: bug, release-notes:misc

#7640 Make sure to not cancel the job when job is done
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: release-notes:skip, scheduler

#7684 Let jobs failing in LSF be resubmitted
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: bug, release-notes:bug-fix, scheduler

#7687 Allow reruns on flaky test_update_report
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:skip

#7683 Move duplicate ev_types to ert/event_type_constants.py
  src/ert/ensemble_evaluator/identifiers.py
  src/ert/event_type_constants.py
  src/ert/job_queue/queue.py
Labels: improvement, release-notes:skip

#7628 Rename JobRunner to ForwardModelRunner
  pyproject.toml
  src/_ert_forward_model_runner/__init__.py
  src/_ert_forward_model_runner/cli.py
  src/_ert_forward_model_runner/client.py
  src/_ert_forward_model_runner/io/__init__.py
  src/_ert_forward_model_runner/job.py
  src/_ert_forward_model_runner/job_dispatch.py
  src/_ert_forward_model_runner/reporting/__init__.py
  src/_ert_forward_model_runner/reporting/base.py
  src/_ert_forward_model_runner/reporting/event.py
  src/_ert_forward_model_runner/reporting/file.py
  src/_ert_forward_model_runner/reporting/interactive.py
  src/_ert_forward_model_runner/reporting/message.py
  src/_ert_forward_model_runner/reporting/statemachine.py
  src/_ert_forward_model_runner/runner.py
  src/_ert_forward_model_runner/util/__init__.py
  src/_ert_forward_model_runner/util/data.py
  src/clib/tests/CMakeLists.txt
  src/ert/ensemble_evaluator/_builder/_ensemble.py
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_client.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/unit_tests/forward_model_runner/__init__.py
  tests/unit_tests/forward_model_runner/test_event_reporter.py
  tests/unit_tests/forward_model_runner/test_file_reporter.py
  tests/unit_tests/forward_model_runner/test_job.py
  tests/unit_tests/forward_model_runner/test_job_dispatch.py
  tests/unit_tests/forward_model_runner/test_job_manager_runtime_kw.py
  tests/unit_tests/forward_model_runner/test_jobmanager.py
  tests/utils.py
Labels: release-notes:skip

#7692 Write reponse as yaml
  src/ert/gui/ertwidgets/storage_info_widget.py
Labels: release-notes:improvement

#7688 Make flakiness test for qstat faster
  src/ert/scheduler/openpbs_driver.py
  tests/integration_tests/scheduler/test_openpbs_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: release-notes:skip

#7682 Remove unused code ensemble_evaluator_utils
  tests/unit_tests/ensemble_evaluator/ensemble_evaluator_utils.py
Labels: improvement, release-notes:skip

#7690 Do not cancel the returncode in scheduler
  src/ert/scheduler/job.py
  src/ert/scheduler/scheduler.py
  tests/unit_tests/scheduler/conftest.py
  tests/unit_tests/scheduler/test_job.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_scheduler.py
Labels: maintenance, release-notes:maintenance, scheduler

#7699 Let bkill retry on ssh failures
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:maintenance

#7696 Make sure that rerun jobs do not how an error message in the GUI.
  src/ert/ensemble_evaluator/snapshot.py
  tests/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:bug-fix

#7706 Increase scheduler cancel_job_tasks timeout
  src/ert/scheduler/scheduler.py
Labels: bug, release-notes:skip

#7726 Increase tolerance in truncated_normal test
  tests/unit_tests/config/test_transfer_functions.py
Labels: release-notes:skip

#7648 Have scheduler LSF driver not bhist jobs newer than POLL_PERIOD
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: improvement, release-notes:skip

#7733 Add correct return types to MagicMock
  tests/performance_tests/test_snapshot.py
  tests/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:skip

#7724 Add -o option to bsub for stdout from LSF
  src/ert/scheduler/lsf_driver.py
  tests/integration_tests/scheduler/bin/bsub
  tests/integration_tests/scheduler/bin/lsfrunner
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:improvement, scheduler

#7714 Have bkill not retry on error Job already finished
  src/ert/scheduler/driver.py
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: bug, release-notes:skip

#7710 Make local_driver kill() robust wrt timing
  src/ert/scheduler/local_driver.py
  tests/unit_tests/scheduler/test_local_driver.py
Labels: bug, scheduler

#7737 Fix dark storage performance benchmark test not compatible with async…
  tests/performance_tests/test_dark_storage_performance.py
Labels: bug, release-notes:skip

#7725 Improve scheduler driver logging to always include exit code, stdout, stderr
  src/ert/scheduler/driver.py
  src/ert/scheduler/lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_openpbs_driver.py
Labels: improvement, release-notes:skip

#7739 Have integration tests running towards cluster set job names
  tests/integration_tests/scheduler/bin/bjobs.py
  tests/integration_tests/scheduler/conftest.py
  tests/integration_tests/scheduler/test_generic_driver.py
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: improvement, release-notes:skip

#7744 Improve codecov coverage lsf_driver polling and using bhist
  tests/integration_tests/scheduler/test_lsf_driver.py
Labels: testing, release-notes:skip

#7604 Add plot for observations
  src/ert/gui/ertwidgets/storage_info_widget.py
  src/ert/gui/ertwidgets/storage_widget.py
  src/ert/gui/tools/manage_experiments/ensemble_init_configuration.py
  tests/unit_tests/gui/tools/test_ensemble_tool.py
Labels: release-notes:new-feature

#7741 Rely on komodo to setup integration tests for queues
  ci/testkomodo.sh
Labels: release-notes:skip

#7757 Implement OpenPBS queue option`QSTAT_OPTIONS`
  src/ert/config/parsing/config_schema_deprecations.py
Labels: improvement, release-notes:skip

#7767 Hardcode `-x` qstat option in `torque_driver.cpp`
  src/clib/lib/job_queue/torque_driver.cpp
  tests/unit_tests/job_queue/test_job_queue_node_torque.py
Labels: bug, release-notes:skip

#7748 Remove parts of LSF example
  docs/reference/queue/lsf_queue.ert
Labels: release-notes:skip

#7769 Fix colours of Pending forward models on resubmitted realizations
  src/ert/gui/model/snapshot.py
Labels: release-notes:bug-fix

#7756 Replace temp_storage dict with array
  src/ert/analysis/_es_update.py
  tests/integration_tests/analysis/test_es_update.py
  tests/unit_tests/analysis/test_es_update.py
Labels: release-notes:skip

#7790 Add use_tmpdir to tests that pollute cwd when running pytest
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/config/test_observations.py
Labels: release-notes:skip

#7778 Rename get_all_ensembles_not_running
  src/ert/gui/tools/plot/plot_api.py
  src/ert/gui/tools/plot/plot_window.py
  tests/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:skip

#7786 Fix metadata bug
  src/ert/storage/migration/to5.py
  tests/unit_tests/storage/migration/test_version_4.py
Labels: release-notes:bug-fix

#7796 Increase number and duration of license retry
  src/ert/shared/share/ert/forward-models/res/script/ecl_run.py
Labels: release-notes:skip

#7782 Implemented exit codes in lsf driver
  src/ert/scheduler/lsf_driver.py
  tests/integration_tests/scheduler/bin/bhist.py
  tests/integration_tests/scheduler/bin/bjobs.py
  tests/integration_tests/scheduler/bin/lsfrunner
  tests/integration_tests/scheduler/test_generic_driver.py
  tests/integration_tests/scheduler/test_lsf_driver.py
  tests/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#7799 Fix CSV export
  src/ert/shared/share/ert/workflows/jobs/internal-gui/scripts/csv_export.py
  tests/unit_tests/gui/test_csv_export.py
Labels: release-notes:bug-fix

#7502 Show images for FIELD std_dev in the plotter
  src/ert/dark_storage/common.py
  src/ert/dark_storage/endpoints/records.py
  src/ert/dark_storage/json_schema/__init__.py
  src/ert/dark_storage/json_schema/record.py
  src/ert/gui/plottery/plot_context.py
  src/ert/gui/plottery/plots/cesp.py
  src/ert/gui/plottery/plots/distribution.py
  src/ert/gui/plottery/plots/ensemble.py
  src/ert/gui/plottery/plots/gaussian_kde.py
  src/ert/gui/plottery/plots/histogram.py
  src/ert/gui/plottery/plots/statistics.py
  src/ert/gui/plottery/plots/std_dev.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/gui/tools/plot/plot_widget.py
  src/ert/gui/tools/plot/plot_window.py
  tests/unit_tests/dark_storage/test_http_endpoints.py
  tests/unit_tests/gui/test_main_window.py
  tests/unit_tests/gui/tools/plot/conftest.py
Labels: release-notes:new-feature

#7779 Remove unused fields from EnsembleOut
  src/ert/dark_storage/endpoints/ensembles.py
  src/ert/dark_storage/endpoints/experiments.py
  src/ert/dark_storage/json_schema/ensemble.py
Labels: release-notes:skip

#7811 Fix flaky csv-export test
  tests/unit_tests/gui/test_csv_export.py
Labels: release-notes:skip
