Repository equinor/ert, pull requests merged in 2025-02, with the labels that each got.

#9940 Add everest-models as a package installation when building readthedocs for everest
  docs/everest/.readthedocs.yaml
  docs/everest/requirements.txt
Labels: release-notes:skip, release-notes:documentation

#9946 Remove un-needed code after 30f2fb9
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:skip

#9943 Correctly calculate cpu_seconds for processtree
  src/_ert/forward_model_runner/forward_model_step.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:bug-fix

#9952 Fix version in everest readthedocs page
  docs/everest/.readthedocs.yaml
Labels: release-notes:skip, release-notes:documentation

#9948 Log pending time for a job
  src/ert/scheduler/job.py
Labels: release-notes:maintenance

#9955 Backport proper counting of cpu-seconds for subprocesses
  src/_ert/forward_model_runner/forward_model_step.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:bug-fix

#9953 Refactor counting cpu-seconds for processtree
  src/_ert/forward_model_runner/forward_model_step.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:skip

#9958 Linewrap comments in _storage_main.py
  src/ert/services/_storage_main.py
Labels: release-notes:skip

#9971 Remove Title Casing from doc
  docs/ert/getting_started/configuration/poly_new/guide.rst
  docs/ert/getting_started/howto/plugin_system.rst
  docs/ert/index.rst
  docs/ert/reference/running_ert.rst
  docs/everest/forward_model_jobs.rst
  docs/everest/index.rst
Labels: release-notes:skip

#9992 Skip reporter if dispatch_url is None
  src/_ert/forward_model_runner/fm_dispatch.py
Labels: release-notes:maintenance

#9972 Change filename for log in realization directories from job-runner to forward-model-runner
  docs/ert/getting_started/configuration/poly_new/guide.rst
  src/_ert/forward_model_runner/fm_dispatch.py
Labels: release-notes:user-impact

#9915 Add more validation to design matrix
  src/ert/config/design_matrix.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/validation/__init__.py
  src/ert/validation/active_range.py
  src/ert/validation/range_string_argument.py
  tests/ert/unit_tests/gui/ide/test_range_string_argument.py
  tests/ert/unit_tests/sensitivity_analysis/test_design_matrix.py
Labels: release-notes:improvement

#9991 Let zmq select port in EnsembleEvaluator
  src/ert/cli/main.py
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/config.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/evaluator_connection_info.py
  src/ert/ensemble_evaluator/monitor.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/run_models/base_run_model.py
  src/ert/services/_storage_main.py
  src/ert/shared/net_utils.py
  src/everest/detached/jobs/everserver.py
  tests/ert/unit_tests/ensemble_evaluator/conftest.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator_config.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/ert/unit_tests/ensemble_evaluator/test_monitor.py
  tests/ert/unit_tests/ensemble_evaluator/test_scheduler.py
  tests/ert/unit_tests/shared/test_port_handler.py
  tests/ert/unit_tests/test_tracking.py
  tests/everest/test_simulator_cache.py
Labels: release-notes:bug-fix

#9998 Rename objective function config key scaling to scale
  src/everest/config/objective_function_config.py
  src/everest/everest_storage.py
  src/everest/optimizer/everest2ropt.py
  test-data/everest/math_func/config_multiobj.yml
  tests/everest/test_config_validation.py
  tests/everest/test_data/mocked_test_case/mocked_multi_batch.yml
  tests/everest/test_data/open_shut_state_modifier/everest/model/array.yml
  tests/everest/test_data/open_shut_state_modifier/everest/model/index.yml
  tests/everest/test_multiobjective.py
Labels: release-notes:skip

#9869 Remove ErtConfig from EverestRunModel
  src/ert/config/ert_config.py
  src/ert/run_models/everest_run_model.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_res_initialization.py
Labels: release-notes:refactor

#10003 Reimplement output constraint scaling
  src/ert/run_models/everest_run_model.py
  src/everest/optimizer/everest2ropt.py
  src/everest/optimizer/opt_model_transforms.py
  tests/everest/snapshots/test_ropt_initialization/test_everest2ropt_snapshot/config_advanced.yml/ropt_config.json
  tests/everest/test_math_func.py
  tests/everest/test_ropt_initialization.py
Labels: release-notes:skip, everest

#10010 Make everserver port selection random
  src/everest/detached/jobs/everserver.py
Labels: release-notes:maintenance

#9962 Replace _wait_until with wait_until
  tests/ert/unit_tests/forward_model_runner/test_event_reporter.py
  tests/ert/unit_tests/forward_model_runner/test_fm_dispatch.py
Labels: release-notes:skip

#10013 Rename job to step in _ert/forward_model_runner
  src/_ert/forward_model_runner/forward_model_step.py
  src/_ert/forward_model_runner/reporting/__init__.py
  src/_ert/forward_model_runner/reporting/event.py
  src/_ert/forward_model_runner/reporting/file.py
  src/_ert/forward_model_runner/reporting/interactive.py
  src/_ert/forward_model_runner/reporting/message.py
  src/_ert/forward_model_runner/reporting/statemachine.py
  src/_ert/forward_model_runner/util/__init__.py
  src/_ert/forward_model_runner/util/data.py
  tests/ert/unit_tests/forward_model_runner/test_file_reporter.py
Labels: release-notes:refactor

#10022 Propegate correct queue information
  src/ert/run_models/everest_run_model.py
Labels: release-notes:unreleased-bug-fix

#10004 Filter out azure.monitor logs from terminal output
  src/ert/logging/__init__.py
  src/ert/logging/storage_log.conf
Labels: release-notes:skip

#10027 Fix typo
  src/ert/logging/__init__.py
  src/ert/logging/storage_log.conf
Labels: release-notes:skip

#10029 Fix potentially flaky test for fm_runner
  tests/ert/unit_tests/forward_model_runner/test_fm_dispatch.py
Labels: release-notes:flaky-test-fix

#10023 Fix test filename
  tests/ert/unit_tests/gui/model/test_step_list.py
Labels: release-notes:skip

#10042 Remove integration_test mark from ee tests
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:skip

#10041 Fix everest caching of test results has race conditions
  tests/everest/entry_points/test_config_branch_entry.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_api_snapshots.py
  tests/everest/test_config_branch.py
  tests/everest/test_detached.py
  tests/everest/test_everest_output.py
  tests/everest/test_math_func.py
Labels: release-notes:flaky-test-fix

#10054 Mute FutureWarnings from plugin initialization
  src/ert/plugins/plugin_manager.py
Labels: release-notes:misc

#10052 Update to ropt 0.14
  pyproject.toml
  src/everest/config/everest_config.py
  src/everest/optimizer/everest2ropt.py
  src/everest/optimizer/opt_model_transforms.py
  tests/everest/snapshots/test_ropt_initialization/test_everest2ropt_snapshot/config_advanced.yml/ropt_config.json
  tests/everest/snapshots/test_ropt_initialization/test_everest2ropt_snapshot/config_minimal.yml/ropt_config.json
  tests/everest/snapshots/test_ropt_initialization/test_everest2ropt_snapshot/config_multiobj.yml/ropt_config.json
  tests/everest/test_multiobjective.py
  tests/everest/test_output_constraints.py
  tests/everest/test_ropt_initialization.py
  uv.lock
Labels: release-notes:skip, everest

#10064 Stop polars warning in asof sort test
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:skip

#10066 Skip using importlib in test_fm_dispatch
  tests/ert/unit_tests/forward_model_runner/test_fm_dispatch.py
Labels: release-notes:skip

#10032 Remove usage of everest_to_ert_config
  src/ert/run_models/everest_run_model.py
  src/everest/bin/everest_script.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_config_validation.py
  tests/everest/test_res_initialization.py
  tests/everest/test_yaml_parser.py
Labels: release-notes:maintenance

#10073 Adjust logging when client retries to send event
  src/_ert/forward_model_runner/client.py
Labels: release-notes:skip

#10104 Use the correct term step in log message
  src/ert/scheduler/job.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/ui_tests/gui/test_main_window.py
Labels: release-notes:maintenance

#10083 Type everest/simulator
  .mypy.ini
  src/everest/config/everest_config.py
  src/everest/simulator/everest_to_ert.py
Labels: release-notes:maintenance

#10076 Update ropt 0.15
  pyproject.toml
  src/ert/run_models/everest_run_model.py
  src/everest/optimizer/everest2ropt.py
  src/everest/optimizer/opt_model_transforms.py
  tests/everest/test_ropt_initialization.py
  uv.lock
Labels: release-notes:skip, everest

#10107 Pin sphinx below 8.2.0
  pyproject.toml
Labels: release-notes:skip

#10108 Remove empty files
  src/_ert/forkserver.py
  src/everest/export.py
Labels: release-notes:maintenance

#10082 Fix bug where iteration was not set
  src/ert/run_models/everest_run_model.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_egg_simulation.py
  tests/everest/test_environment.py
  tests/everest/test_math_func.py
Labels: release-notes:bug-fix

#10121 Mute logger.warning from plugin initialization
  src/ert/plugins/plugin_manager.py
Labels: release-notes:logging

#10122 Fix GUI showing `ERT experiment failed!` twice on terminate experiment
  src/ert/gui/simulation/run_dialog.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:bug-fix

#10117 Deprecate un-used everest export keywords
  src/everest/api/everest_data_api.py
  src/everest/config/export_config.py
  tests/everest/test_config_validation.py
Labels: release-notes:maintenance

#10085 Type everest/jobs
  .mypy.ini
  src/everest/jobs/__init__.py
  src/everest/jobs/io/__init__.py
  src/everest/jobs/recovery_factor.py
  src/everest/jobs/templating/render.py
  src/everest/jobs/well_tools/__init__.py
  src/everest/simulator/everest_to_ert.py
Labels: release-notes:maintenance

#10127 Fix test that did not write to tmp
  tests/everest/test_environment.py
Labels: release-notes:maintenance

#10142 Try to mitigate flakyness in cpu_seconds_can_detect_multiprocess
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:flaky-test-fix

#10135 Log how long `rm_run_path()` takes
  src/ert/config/field.py
  src/ert/enkf_main.py
  src/ert/gui/tools/plot/plot_window.py
  src/ert/run_models/base_run_model.py
  src/ert/utils/__init__.py
Labels: release-notes:logging

#10144 Backport: Log how long `rm_run_path()` takes
  src/ert/config/field.py
  src/ert/enkf_main.py
  src/ert/gui/tools/plot/plot_window.py
  src/ert/run_models/base_run_model.py
  src/ert/utils/__init__.py
Labels: release-notes:logging

#10119 Format logged config dict to enhance readability
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:logging

#10139 Type everest/storage
  .mypy.ini
  src/everest/everest_storage.py
Labels: release-notes:maintenance

#10152 Log PBS submit script
  src/ert/scheduler/openpbs_driver.py
Labels: release-notes:maintenance

#10102 Fix muted exceptions in fm_dispatch due to self SIGKILL
  src/_ert/forward_model_runner/fm_dispatch.py
  tests/ert/unit_tests/forward_model_runner/test_fm_dispatch.py
Labels: release-notes:bug-fix

#10174 Refactor test_scheduler_receives_checksum_and_waits_for_disk_sync
  tests/ert/unit_tests/ensemble_evaluator/test_scheduler.py
Labels: release-notes:skip
