Repository equinor/ert, pull requests merged in 2025-10, with the labels that each got.

#11980 Revert "Remove eightcells"
  .github/workflows/test_ert_with_flow.yml
  test-data/everest/eightcells/eclipse/include/EIGHTCELLS.DATA
  test-data/everest/eightcells/eclipse/include/grid/perm.inc
  test-data/everest/eightcells/eclipse/include/realizations/realization-0/eclipse/include/grid/perm.inc
  test-data/everest/eightcells/eclipse/include/realizations/realization-0/eclipse/include/schedule
  test-data/everest/eightcells/eclipse/include/realizations/realization-0/eclipse/model/EIGHTCELLS.DATA
  test-data/everest/eightcells/eclipse/include/realizations/realization-1/eclipse/include/grid/perm.inc
  test-data/everest/eightcells/eclipse/include/realizations/realization-1/eclipse/include/schedule
  test-data/everest/eightcells/eclipse/include/realizations/realization-1/eclipse/model/EIGHTCELLS.DATA
  test-data/everest/eightcells/eclipse/include/realizations/realization-2/eclipse/include/grid/perm.inc
  test-data/everest/eightcells/eclipse/include/realizations/realization-2/eclipse/include/schedule
  test-data/everest/eightcells/eclipse/include/realizations/realization-2/eclipse/model/EIGHTCELLS.DATA
  test-data/everest/eightcells/eclipse/include/schedule/events.sch
  test-data/everest/eightcells/eclipse/include/schedule/schedule.sch
  test-data/everest/eightcells/eclipse/include/schedule/schedule.tmpl
  test-data/everest/eightcells/everest/input/files/at_config.yml
  test-data/everest/eightcells/everest/input/files/templates/wconinje.j2.tmpl
  test-data/everest/eightcells/everest/input/files/templates/wconprod.j2.tmpl
  test-data/everest/eightcells/everest/input/files/wc_config.yml
  test-data/everest/eightcells/everest/input/files/well_readydate.json
  test-data/everest/eightcells/everest/model/config.yml
Labels: release-notes:skip

#11991 Move ExperimentState and ExperimentStatus to run_model
  src/ert/run_models/run_model.py
  src/everest/detached/client.py
  src/everest/detached/everserver.py
Labels: release-notes:maintenance

#11994 Fix test writing to source tree
  tests/everest/test_res_initialization.py
Labels: release-notes:skip

#11993 Fix failing field test
  tests/ert/unit_tests/config/test_field.py
Labels: release-notes:skip

#11995 Change evaluator log message for fm_steps with missing status updates
  src/ert/ensemble_evaluator/evaluator.py
Labels: release-notes:logging, backport version-15.0

#11933 Allow inline data in install_data
  src/everest/config/everest_config.py
  src/everest/config/install_data_config.py
  src/everest/config/validation_utils.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_config_validation.py
  tests/everest/test_everlint.py
Labels: release-notes:new-feature

#11998 Use pathlib for reading files
  docs/everest/conf.py
  pyproject.toml
  src/_ert/forward_model_runner/reporting/file.py
  src/ert/config/ert_config.py
  src/ert/config/parsing/_read_file.py
  src/ert/scheduler/scheduler.py
  src/ert/shared/_doc_utils/forward_model_documentation.py
  src/everest/detached/client.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/ui_tests/cli/test_shell.py
  tests/ert/ui_tests/gui/test_docs_screenshots.py
  tests/ert/unit_tests/plugins/test_plugin_manager.py
  tests/ert/unit_tests/resources/test_shell.py
  tests/ert/unit_tests/resources/test_templating.py
  tests/ert/unit_tests/services/test_base_service.py
  tests/ert/unit_tests/test_run_path_creation.py
  tests/ert/unit_tests/workflow_runner/test_workflow_runner.py
  tests/everest/test_templating.py
Labels: release-notes:maintenance

#11967 Improve surface mismatch error message
  src/ert/config/surface_config.py
  tests/ert/unit_tests/config/test_surface_config.py
Labels: release-notes:improvement

#11985 Move log messages in prior sampling according to actual behaviour
  src/ert/sample_prior.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
Labels: release-notes:skip

#12000 Remove the default for perturbation_magnitude
  src/everest/config/control_config.py
  src/everest/config/control_variable_config.py
  src/everest/config/everest_config.py
  src/everest/optimizer/everest2ropt.py
  test-data/everest/eightcells/everest/model/config.yml
  tests/everest/conftest.py
  tests/everest/test_config_validation.py
  tests/everest/test_controls.py
  tests/everest/test_discrete.py
  tests/everest/test_domain_transforms.py
  tests/everest/test_everest_config.py
  tests/everest/test_input_constraints_config.py
  tests/everest/test_res_initialization.py
  tests/everest/test_ropt_initialization.py
  tests/everest/test_templating.py
  tests/everest/test_yaml_parser.py
Labels: release-notes:breaking-change
