Repository equinor/ert, pull requests merged in 2025-03, with the labels that each got.

#10195 Remove exclusion of removed files
  .mypy.ini
Labels: release-notes:skip

#10173 Type everest/bin
  .mypy.ini
  src/everest/bin/config_branch_script.py
  src/everest/bin/everconfigdump_script.py
  src/everest/bin/everest_script.py
  src/everest/bin/everexport_script.py
  src/everest/bin/everlint_script.py
  src/everest/bin/kill_script.py
  src/everest/bin/main.py
  src/everest/bin/monitor_script.py
  src/everest/bin/utils.py
  src/everest/bin/visualization_script.py
Labels: release-notes:maintenance

#10170 Make the egg test run on azure
  ci/testkomodo.sh
  src/everest/bin/everest_script.py
Labels: release-notes:build-system

#10201 Skip test_cpu_seconds_can_detect_multiprocess on macOS
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:flaky-test-fix

#10208 Allow non-utf-8 characters in PRT files
  src/ert/resources/forward_models/run_reservoirsimulator.py
  tests/ert/unit_tests/resources/test_run_reservoirsimulator.py
Labels: release-notes:bug-fix, backport to 14.0

#10217 Fix qwarning from QApplication after migration to pyqt6
  src/ert/gui/main.py
Labels: release-notes:bug-fix

#10214 Issue ConfigWarning when DATA_FILE should replace RUN_TEMPLATE
  docs/ert/reference/configuration/keywords.rst
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:misc, backport to 14.0

#10220 Remove unused property from ErtNotifier
  src/ert/gui/ertnotifier.py
  src/ert/gui/main_window.py
  tests/ert/ui_tests/gui/test_manage_experiments_tool.py
  tests/ert/unit_tests/gui/ertwidgets/test_ensembleselector.py
Labels: release-notes:maintenance

#10222 Issue warning when DATA_FILE should replace RUN_TEMPLATE
  docs/ert/reference/configuration/keywords.rst
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:misc

#10219 Call steps steps in documentation for magic strings
  docs/ert/reference/configuration/magic_strings.rst
Labels: release-notes:documentation

#10231 Tag some tests using cached_example with loadgroup
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_everest_runmodel_events.py
  tests/everest/test_math_func.py
Labels: release-notes:maintenance

#10233 Remove incorrect test_cpu_seconds_can_detect_multiprocess
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:flaky-test-fix

#10237 Mark slow tests as integration_test
  tests/ert/unit_tests/forward_model_runner/test_event_reporter.py
  tests/everest/test_everserver.py
Labels: release-notes:maintenance

#10257 Use check-all for ci tests
  ci/testkomodo.sh
Labels: release-notes:maintenance

#10261 Disable monitoring of ert in testkomodo
  ci/testkomodo.sh
Labels: release-notes:skip

#10236 Update developing section of README with instructions for uv
  .pre-commit-config.yaml
  README.md
Labels: release-notes:maintenance

#10267 Fix incorrect import
  src/ert/gui/simulation/ensemble_smoother_panel.py
Labels: release-notes:skip

#10283 Adjust logger level for azure.monitor
  src/ert/logging/logger.conf
Labels: release-notes:maintenance

#10262 Add more debugging when submitting everserver
  src/everest/bin/everest_script.py
Labels: release-notes:logging

#10249 Remove comments before substituting
  src/everest/config_file_loader.py
  tests/everest/test_everlint.py
Labels: release-notes:bug-fix

#10307 Change jobs to steps in error message shown to user from monitor
  src/ert/cli/monitor.py
Labels: release-notes:maintenance

#10309 Clean up documentation, naming and order of _read_summary.py
  src/ert/config/_read_summary.py
Labels: release-notes:refactor

#10321 Make EverestClient tests wait for server to come up
  tests/everest/test_everest_client.py
Labels: release-notes:flaky-test-fix

#10333 Remove redundant test_ert_context
  tests/ert/unit_tests/test_enkf_main.py
Labels: release-notes:maintenance

#10264 Log when duration of forward model step is negative
  src/ert/gui/model/snapshot.py
Labels: release-notes:logging

#10348 Reduce timeouts for github workflows
  .github/workflows/actionlint.yml
  .github/workflows/build-wheels.yml
  .github/workflows/codspeed.yml
  .github/workflows/test_ert.yml
  .github/workflows/test_everest.yml
  .github/workflows/test_semeio.yml
Labels: release-notes:build-system

#10350 Fix FLOW forward model documentation
  src/ert/plugins/hook_implementations/forward_model_steps.py
Labels: release-notes:skip

#10342 Revert `Fix qwarning from QApplication after migration to pyqt6`
  src/ert/gui/main.py
Labels: maintenance

#10357 Ensure sensitivity_analysis tests are run
  tests/ert/unit_tests/sensitivity_analysis/__init__.py
Labels: release-notes:maintenance

#10367 Remove unused JSON_STRING
  tests/ert/unit_tests/forward_model_runner/test_forward_model_runner.py
Labels: release-notes:maintenance

#10365 Make cached everest example persist deletion of tmpdirs
  tests/everest/conftest.py
Labels: release-notes:maintenance

#10371 Dummy commit
  dummy_commit_file.md
Labels: backport backport_test_main

#10316 Validate `DESIGN_MATRIX` when running `DESIGN2PARAMS`
  src/ert/config/design_matrix.py
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:maintenance

#10308 Clean up the logging a bit
  ci/testkomodo.sh
  src/ert/run_models/everest_run_model.py
  src/everest/bin/everest_script.py
  src/everest/bin/main.py
  src/everest/config_file_loader.py
  src/everest/detached/__init__.py
  src/everest/detached/jobs/everserver.py
  src/everest/simulator/everest_to_ert.py
  src/everest/strings.py
  test-data/everest/math_func/config_advanced.yml
  test-data/everest/math_func/config_minimal.yml
  tests/everest/test_detached.py
  tests/everest/test_logging.py
Labels: release-notes:maintenance

#10368 Restructure forward model required keyword validation for readability
  src/ert/config/ert_config.py
  src/ert/config/forward_model_step.py
  tests/ert/unit_tests/config/test_forward_model.py
Labels: release-notes:improvement

#10378 Fix flaky ert test_tracking unittest
  tests/ert/unit_tests/test_tracking.py
Labels: release-notes:flaky-test-fix

#10379 Mark batch_objective_gradient as optional for GradientBatchStorageData
  src/everest/api/everest_data_api.py
  src/everest/everest_storage.py
Labels: release-notes:skip

#10370 Remove an extra tmp dir from runpath for egg test
  ci/testkomodo.sh
Labels: release-notes:skip

#10389 Fix validation of design matrix not validating beyond 2nd DESIGN2PARAMS
  src/ert/config/_design_matrix_validator.py
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:unreleased-bug-fix

#10394 Remove objective name aliasing
  src/ert/run_models/everest_run_model.py
  src/everest/config/everest_config.py
  src/everest/config/objective_function_config.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_config_validation.py
  tests/everest/test_objective_type.py
Labels: everest

#10405 Merge log statements for seed
  src/ert/enkf_main.py
  tests/ert/unit_tests/storage/test_parameter_sample_types.py
Labels: release-notes:skip

#10400 Remove mention of IES in README
  README.md
Labels: documentation, release-notes:skip

#10272 Have DESIGN_MATRIX not require design_sheet and default_sheet
  src/ert/config/design_matrix.py
  src/ert/config/parsing/config_schema.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
  tests/ert/unit_tests/config/test_analysis_config.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
  tests/ert/unit_tests/sensitivity_analysis/test_design_matrix.py
  tests/ert/unit_tests/test_libres_facade.py
Labels: release-notes:improvement

#10414 Add deprecation warning for init_files with GEN_KW
  src/ert/config/parsing/config_schema_deprecations.py
  tests/ert/unit_tests/config/parsing/test_config_schema_deprecations.py
Labels: release-notes:maintenance

#10415 Update PR template with backport label checkbox
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-notes:skip

#10423 Remove default value of eclbase and replace with validation
  src/everest/config/everest_config.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_config_validation.py
Labels: release-notes:improvement

#10428 Fix a bug where join_after=2 was erronously removed
  src/ert/config/parsing/config_schema.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:unreleased-bug-fix

#10429 Fix test writing to source tree
  tests/everest/test_config_validation.py
Labels: release-notes:skip

#10432 Fix bug where no summary data leads to everviz not opening
  src/everest/api/everest_data_api.py
  tests/everest/test_api_snapshots.py
Labels: release-notes:bug-fix, backport version-14.1

#10427 Add --disable-monitoring to everest
  .github/workflows/test_ert_with_flow.yml
  ci/testkomodo.sh
  src/everest/bin/everest_script.py
  src/everest/bin/utils.py
Labels: release-notes:new-feature

#10442 Have testkomodo test subsystems instead
  ci/testkomodo.sh
  justfile
Labels: release-notes:build-system

#10369 Pin numpy < 2.2 in Ert
  pyproject.toml
  src/ert/analysis/_es_update.py
  tests/ert/ui_tests/cli/snapshots/test_cli/test_es_mda/es_mda_integration_snapshot
  uv.lock
Labels: needs-discussion, release-notes:dependency

#10449 Have testkomodo error properly
  ci/testkomodo.sh
Labels: release-notes:build-system

#10436 Add more config validation for design matrix
  src/ert/config/ert_config.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
Labels: release-notes:skip

#10450 Adjust best_objective_gradients_csv snapshot to match bleeding testing.
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/best_objective_gradients_csv
Labels: release-notes:bug-fix, release-notes:skip

#10473 Add info on cached evaluations to the evaluator result
  src/ert/run_models/everest_run_model.py
Labels: release-notes:skip, everest

#10469 Use --dist loadgroup in pre-commit push and rapid-tests
  .github/workflows/test_everest.yml
  .pre-commit-config.yaml
  justfile
Labels: release-notes:build-system

#10489 Add back default recurse dirs
  pyproject.toml
Labels: release-notes:maintenance

#10493 Fix deprecation warning regarding np.bool in pydantic
  src/ert/analysis/_es_update.py
Labels: release-notes:dependency

#10496 Add specific snapshot for es_mda numpy 1.*
  tests/ert/ui_tests/cli/snapshots/test_cli/test_es_mda/es_mda_integration_snapshot_numpy1
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:skip

#10490 Update labels in bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: release-notes:skip

#10463 Fix removing of old egg tests
  ci/testkomodo.sh
Labels: release-notes:skip

#10396 Add some logging for the queues
  src/everest/bin/everest_script.py
  src/everest/detached/__init__.py
  src/everest/detached/jobs/everserver.py
  tests/everest/test_fm_plugins.py
Labels: release-notes:skip

#10440 Add DESIGN_MATRIX to keywords docs
  docs/ert/reference/configuration/keywords.rst
Labels: release-notes:new-feature

#10479 Make sure not to run update without update-able parameters
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
Labels: release-notes:skip

#10498 Describe test naming convention in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release-notes:documentation

#10509 Clean up ert_script tests
  tests/ert/unit_tests/workflow_runner/test_ert_script.py
Labels: release-notes:maintenance
