Repository equinor/ert, pull requests merged in 2025-08, with the labels that each got.

#11406 Do copy unupdated parameters only once in enif
  src/ert/analysis/_enif_update.py
Labels: release-notes:skip

#11408 Remove unused functions from genkw config
  src/ert/config/gen_kw_config.py
Labels: release-notes:skip

#11409 Add qtbot fixture parameter to test
  tests/ert/ui_tests/gui/test_restart_no_responses_and_parameters.py
Labels: release-notes:skip

#11397 Improve typing for src/_ert
  src/_ert/forward_model_runner/fm_dispatch.py
  src/_ert/forward_model_runner/forward_model_step.py
  src/_ert/forward_model_runner/io/__init__.py
  src/_ert/forward_model_runner/reporting/base.py
  src/_ert/forward_model_runner/reporting/event.py
  src/_ert/forward_model_runner/reporting/file.py
  src/_ert/forward_model_runner/reporting/interactive.py
  src/_ert/forward_model_runner/reporting/message.py
  src/_ert/forward_model_runner/reporting/statemachine.py
  src/_ert/forward_model_runner/runner.py
  src/_ert/forward_model_runner/util/data.py
  src/ert/config/ert_config.py
  src/ert/config/forward_model_step.py
  src/ert/enkf_main.py
Labels: release-notes:improvement

#11401 Fix error messages for drivers.kill
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/slurm_driver.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
  tests/ert/unit_tests/scheduler/test_slurm_driver.py
Labels: release-notes:bug-fix

#11410 Move evaluate from ensemble to EnsembleEvaluator
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/scheduler/job.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
Labels: release-notes:misc

#11455 [Backport version-14.4] Add num_params to log statement (#11427)
  src/ert/run_models/base_run_model.py
  tests/ert/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:logging

#11464 Fix coverage data for unit tests being overwritten
  .github/workflows/test_ert.yml
Labels: release-notes:build-system

#11452 Remove obsoleted keywords DATA_ROOT & CONFIG_DIRECTORY
  src/ert/config/ert_config.py
  src/ert/config/parsing/config_keywords.py
  src/ert/config/parsing/config_schema.py
  src/ert/config/parsing/config_schema_deprecations.py
Labels: release-notes:skip

#11440 Move responsibility to save parameters into Ensemble
  src/ert/config/ext_param_config.py
  src/ert/config/field.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parameter_config.py
  src/ert/config/surface_config.py
  src/ert/run_models/everest_run_model.py
  src/ert/storage/local_ensemble.py
  tests/ert/unit_tests/test_run_path_creation.py
Labels: release-notes:skip

#11463 Rename inaccurate test title
  tests/ert/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:skip

#11473 Improve documentation and testing of _history_key
  docs/ert/reference/configuration/keywords.rst
  src/ert/config/_read_summary.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/summary_key_type.py
  tests/ert/unit_tests/config/test_read_summary.py
Labels: release-notes:maintenance

#11481 Remove test_async_queue_execution
  tests/ert/unit_tests/ensemble_evaluator/test_async_queue_execution.py
Labels: release-notes:maintenance

#11484 Use property to simplify remember logic in remaining verification time
  src/ert/scheduler/job.py
Labels: release-notes:refactor

#11248 Grid per field
  docs/ert/reference/configuration/keywords.rst
  src/ert/config/ensemble_config.py
  test-data/ert/snake_oil_field/snake_oil_field.ert
  tests/ert/unit_tests/config/test_ensemble_config.py
Labels: release-notes:new-feature

#11487 Filter non-finalized responses in the plotter
  src/ert/config/everest_constraints_config.py
  src/ert/config/everest_objective_config.py
  src/ert/config/gen_data_config.py
  src/ert/config/response_config.py
  src/ert/config/summary_config.py
  src/ert/gui/tools/plot/data_type_proxy_model.py
  tests/ert/unit_tests/dark_storage/test_http_endpoints.py
  tests/ert/unit_tests/gui/tools/plot/conftest.py
  tests/ert/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:bug-fix

#11509 Disable pytest benchmarks on parallel runs
  justfile
Labels: release-notes:skip

#11508 Make general observation tests conform to CONTRIBUTING.md
  tests/ert/unit_tests/config/parsing/test_observations_parser.py
Labels: release-notes:refactor

#11531 Limit local queue to 2 simultaneous realizations when running Everest tests
  tests/everest/conftest.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_everest_client.py
  tests/everest/test_everserver.py
  tests/everest/test_math_func.py
  tests/everest/test_objective_type.py
Labels: release-notes:maintenance

#11532 Make sure to wait to process the manifest queue
  src/ert/ensemble_evaluator/evaluator.py
Labels: release-notes:bug-fix, backport version-14.5

#11548 Skip test_that_killed_ert_does_not_leave_storage_server_process on mac
  tests/ert/ui_tests/cli/test_cli.py
Labels: skipped_test, release-notes:build-system, backport version-14.4, backport version-14.5

#11553 Rename es_update test to conform to CONTRIBUTING.md
  tests/ert/ui_tests/cli/analysis/test_es_update.py
Labels: release-notes:refactor

#11570 Consolidate history key
  src/ert/config/observations.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/summary_key_type.py
Labels: release-notes:maintenance

#11576 Clean up parser tests
  tests/ert/unit_tests/config/parsing/test_lark_parser.py
Labels: release-notes:maintenance

#11568 Skip failing ci tests on mac
  tests/ert/ui_tests/gui/test_main_window.py
  tests/ert/ui_tests/gui/test_plotting_of_snake_oil.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_everest_client.py
  tests/everest/test_everserver.py
  tests/everest/test_logging.py
Labels: flaky-test, release-notes:skip, backport version-14.4, backport version-14.5

#11585 Make sure x509 OID COMMON NAME is at most 64 characters
  src/everest/detached/everserver.py
  tests/everest/test_everserver.py
Labels: release-notes:bug-fix, backport version-14.5

#11567 Setup Qt resources directory for all test runs
  tests/conftest.py
Labels: release-notes:maintenance

#11607 Reduce LSF logging with removal of low value log statements
  src/ert/scheduler/lsf_driver.py
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip, backport version-14.5, backport version-14.6

#11608 Mute warnings from test_job when running tests
  tests/ert/unit_tests/scheduler/test_job.py
Labels: release-notes:skip

#11637 Fix progressbar failing on post simulation warnings
  src/ert/gui/simulation/run_dialog.py
  tests/ert/ui_tests/gui/test_main_window.py
Labels: release-notes:bug-fix, backport version-14.4, backport version-14.5, backport version-14.6

#11647 Add upper version bound to ropt and upgrade uv.lock
  pyproject.toml
  uv.lock
Labels: release-notes:skip

#11644 Keep observations flag in multi-experiments
  src/ert/gui/tools/plot/plot_api.py
  tests/ert/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:bug-fix, backport version-14.4, backport version-14.5, backport version-14.6

#11638 Add documentation and rename tests related to redefines
  docs/ert/reference/configuration/keywords.rst
  tests/ert/unit_tests/config/parsing/test_lark_parser.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_workflow.py
Labels: release-notes:documentation

#11635 Fix a bug where max_memory was not propagated realization_memory
  src/everest/config/simulator_config.py
  tests/everest/test_res_initialization.py
Labels: release-notes:bug-fix

#11633 Restructure some tests in test_runpath_creation.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/test_run_path_creation.py
Labels: release-notes:maintenance

#11663 Remove unused _get_abs_path
  src/ert/config/ensemble_config.py
Labels: release-notes:maintenance
