Repository equinor/ert, pull requests merged in 2025-05, with the labels that each got.

#10717 Solve and enforce flake8-builtins via ruff
  docs/everest/conf.py
  pyproject.toml
  src/ert/callbacks.py
  src/ert/config/_read_summary.py
  src/ert/config/ert_config.py
  src/ert/config/gen_data_config.py
  src/ert/config/response_config.py
  src/ert/config/summary_config.py
  src/ert/enkf_main.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/gui/simulation/view/realization.py
  src/ert/gui/tools/plot/plot_api.py
  src/ert/logging/__init__.py
  src/ert/plugins/hook_implementations/workflows/export_runpath.py
  src/ert/resources/forward_models/template_render.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/scheduler/job.py
  src/ert/scheduler/slurm_driver.py
  src/ert/storage/local_storage.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/ui_tests/cli/test_parameter_passing.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_gen_kw_config.py
  tests/ert/unit_tests/config/test_read_summary.py
  tests/everest/test_config_validation.py
  tests/everest/test_data/mocked_test_case/jobs/npv_function_mock.py
  tests/everest/test_data/mocked_test_case/jobs/oil_prod_rate_mock.py
  tests/everest/test_yaml_parser.py
Labels: release-notes:maintenance

#10690 Pass token to ConfigValidationError
  src/ert/config/parsing/_read_file.py
  src/ert/config/parsing/config_schema_item.py
Labels: bug, release-notes:bug-fix

#10740 Reintroduce possibility to log from Everest with pluggins
  src/everest/bin/main.py
Labels: release-notes:logging

#10737 Fix ui progress bar color order
  src/ert/cli/monitor.py
  src/ert/ensemble_evaluator/state.py
  tests/ert/unit_tests/gui/simulation/view/test_legend.py
Labels: release-notes:skip, backport version-14.2

#10731 Move load_from_run_path out of LibresFacade class
  src/ert/callbacks.py
  src/ert/gui/tools/load_results/load_results_panel.py
  src/ert/libres_facade.py
  src/ert/scheduler/job.py
  src/ert/storage/__init__.py
  src/ert/storage/load_status.py
  src/ert/storage/local_ensemble.py
  tests/ert/performance_tests/enkf/test_load_state.py
  tests/ert/unit_tests/ensemble_evaluator/conftest.py
  tests/ert/unit_tests/scenarios/test_summary_response.py
  tests/ert/unit_tests/scheduler/test_job.py
  tests/ert/unit_tests/scheduler/test_scheduler.py
  tests/ert/unit_tests/storage/test_parameter_sample_types.py
  tests/ert/unit_tests/test_load_forward_model.py
  tests/ert/unit_tests/test_run_path_creation.py
  tests/ert/unit_tests/test_summary_response.py
Labels: release-notes:maintenance

#10696 Catch and log Python exceptions in QT code
  src/ert/gui/main.py
Labels: release-notes:bug-fix, backport version-14.1, backport version-14.2

#10718 Remove forward_init_file option from GenKW config
  docs/ert/reference/configuration/keywords.rst
  src/ert/config/ensemble_config.py
  src/ert/config/gen_kw_config.py
  src/ert/config/parsing/config_schema_deprecations.py
  src/ert/enkf_main.py
  src/ert/storage/migration/to10.py
  tests/ert/unit_tests/config/parsing/test_config_schema_deprecations.py
  tests/ert/unit_tests/config/test_gen_kw_config.py
  tests/ert/unit_tests/storage/snapshots/test_storage_migration/test_that_storage_matches/parameters
  tests/ert/unit_tests/storage/test_parameter_sample_types.py
  tests/ert/unit_tests/test_run_path_creation.py
Labels: release-notes:misc, release-notes:user-impact

#10751 Pin everest-models in Ert 14.1
  .github/workflows/test_everest.yml
Labels: maintenance

#10745 Avoid claiming misconfigured NUM_CPU for short jobs
  src/ert/ensemble_evaluator/evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:bug-fix, backport version-14.1, backport version-14.2

#10765 Tune error messages
  src/ert/storage/local_ensemble.py
Labels: release-notes:maintenance, backport version-14.2

#10637 Add max_memory keyword to the Everest config
  src/ert/config/queue_config.py
  src/everest/config/simulator_config.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_res_initialization.py
Labels: release-notes:bug-fix

#10769 Extend error message for NoPortsInRangeException
  src/ert/shared/net_utils.py
Labels: release-notes:maintenance, backport version-14.2

#10738 Stop allowing install data target location outside the runpath.
  src/everest/config/validation_utils.py
  tests/everest/test_everlint.py
Labels: release-notes:bug-fix, release-notes:user-impact

#10788 Be explicit about unit in SUBMIT_SLEEP docs
  docs/ert/reference/configuration/keywords.rst
  docs/ert/reference/configuration/queue.rst
Labels: release-notes:documentation

#10770 Align simulation panel contents to the left
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/manual_update_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/run_models/manual_update.py
Labels: release-notes:skip

#10756 Unify ert and everest trace instrumentation
  src/ert/__main__.py
  src/ert/trace.py
  src/everest/bin/main.py
  src/everest/detached/__init__.py
  src/everest/detached/jobs/everserver.py
  src/everest/trace.py
Labels: release-notes:logging, backport version-14.1, backport version-14.2

#10813 Linewrap OOM trace
  src/_ert/forward_model_runner/forward_model_step.py
Labels: release-notes:maintenance, backport version-14.2

#10807 Ignore OSError when handling failure
  src/ert/scheduler/job.py
Labels: release-notes:maintenance, backport version-14.2

#10829 Avoid using exc_info in logger.warning
  src/ert/callbacks.py
Labels: release-notes:maintenance

#10831 Don't claim a warning is an exception to user
  src/ert/config/ert_config.py
Labels: release-notes:maintenance, backport version-14.2

#10828 Fix flaky tests in test_run_dialog
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:flaky-test-fix

#10834 Do not ignore .github in .gitignore
  .gitignore
Labels: release-notes:maintenance

#10859 Use runpath for disk usage widget
  src/ert/config/model_config.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/shared/status/utils.py
  tests/ert/unit_tests/gui/simulation/view/test_disk_space_widget.py
Labels: release-notes:bug-fix, backport version-14.1, backport version-14.2

#10860 Assert that LSF job names can include spaces
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:skip

#10863 [Backport version-14.2] Use runpath for disk usage widget
  src/ert/config/model_config.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/shared/status/utils.py
  tests/ert/unit_tests/gui/simulation/view/test_disk_space_widget.py
Labels: release-notes:bug-fix

#10864 [Backport version-14.1] Use runpath for disk usage widget
  src/ert/config/model_config.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/shared/status/utils.py
  tests/ert/unit_tests/gui/simulation/view/test_disk_space_widget.py
Labels: release-notes:bug-fix

#10872 Fix duplicate span entries created during everest tests
  src/ert/__main__.py
  src/ert/plugins/plugin_manager.py
  src/ert/services/_storage_main.py
  src/ert/trace.py
  src/everest/bin/main.py
  src/everest/detached/jobs/everserver.py
  src/everest/plugins/everest_plugin_manager.py
  tests/ert/unit_tests/plugins/dummy_plugins.py
  tests/ert/unit_tests/plugins/test_plugin_manager.py
Labels: release-notes:logging, backport version-14.1, backport version-14.2

#10875 Fix copy text to clipboard functionality
  src/ert/gui/tools/file/file_dialog.py
Labels: release-notes:bug-fix, backport version-14.1, backport version-14.2

#10877 Remove ErtRunError traceback
  src/ert/run_models/base_run_model.py
Labels: bug

#10891 Render Open Ert button conditionally
  src/ert/gui/suggestor/suggestor.py
Labels: bug, release-notes:bug-fix

#10888 Fix test writing to sourcetree
  tests/everest/test_res_initialization.py
Labels: release-notes:skip

#10887 Stop window resizing
  src/ert/gui/tools/file/file_dialog.py
Labels: release-notes:skip

#10900 Update ruff, 0.11.9 -> 0.11.10
  .pre-commit-config.yaml
Labels: release-notes:dependency

#10905 Add metadata prop to everest response types
  src/ert/config/everest_constraints_config.py
  src/ert/config/everest_objective_config.py
Labels: release-notes:skip

#10904 Re-enable Mac memory test for field parameters
  tests/ert/performance_tests/test_memory_usage.py
Labels: release-notes:maintenance

#10871 Update ERT getting started with new screenshots and updated text
  docs/ert/getting_started/configuration/poly_new/guide.rst
  docs/ert/getting_started/configuration/poly_new/minimal/ert.png
  docs/ert/getting_started/configuration/poly_new/minimal/simulations.png
  docs/ert/getting_started/configuration/poly_new/with_more_observations/coeff_b.png
  docs/ert/getting_started/configuration/poly_new/with_observations/coeff_a.png
  docs/ert/getting_started/configuration/poly_new/with_observations/coeff_b.png
  docs/ert/getting_started/configuration/poly_new/with_observations/coeff_c.png
  docs/ert/getting_started/configuration/poly_new/with_observations/plot_obs.png
  docs/ert/getting_started/configuration/poly_new/with_results/plots.png
  docs/ert/getting_started/configuration/poly_new/with_results/poly_plot.png
  docs/ert/getting_started/configuration/poly_new/with_simple_script/ert.png
Labels: release-notes:documentation

#10918 Don't parse old stdout/stderr files
  src/ert/scheduler/job.py
  tests/ert/unit_tests/scheduler/test_job.py
Labels: release-notes:bug-fix, backport version-14.2

#10836 Amend LOCAL_STORAGE_VERSION=10
  src/ert/storage/local_storage.py
Labels: blocked

#10939 Make QueueConfig into BaseModel
  src/ert/config/queue_config.py
Labels: release-notes:skip

#10930 Catch all warnings raised when doing ensemble update
  src/ert/analysis/_es_update.py
Labels: release-notes:logging, backport version-14.2

#10934 Fix test for job_script
  tests/ert/unit_tests/config/config_dict_generator.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_queue_config.py
Labels: release-notes:unreleased-bug-fix

#10763 Remove enspath from LibresFacade
  src/ert/libres_facade.py
  tests/ert/performance_tests/test_dark_storage_performance.py
  tests/ert/ui_tests/cli/analysis/test_es_update.py
  tests/ert/unit_tests/test_libres_facade.py
  tests/ert/unit_tests/test_load_forward_model.py
Labels: release-notes:maintenance

#11009 Remove analysis module settings from enif panel
  src/ert/gui/simulation/ensemble_information_filter_panel.py
Labels: release-notes:bug-fix
