Repository equinor/ert, pull requests merged in 2025-01, with the labels that each got.

#9633 Avoid warning from pytest
  tests/ert/performance_tests/test_dark_storage_performance.py
Labels: release-notes:skip

#9632 Avoid using deprecated --target-case in tests
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:skip

#9630 Avoid deprecated utcnow()
  src/everest/detached/jobs/everserver.py
  src/everest/util/__init__.py
Labels: release-notes:skip

#9626 Avoid repeated logging for each cluster in misfit analysis
  src/ert/analysis/misfit_preprocessor.py
Labels: release-notes:maintenance

#9634 Change needed for updated everest-models
  tests/everest/test_data/open_shut_state_modifier/everest/model/array.yml
  tests/everest/test_data/open_shut_state_modifier/everest/model/index.yml
Labels: release-notes:maintenance

#9647 Set up dependabot for github actions
  .github/dependabot.yml
Labels: release-notes:maintenance

#9656 Ignore unimportant ConfigWarnings
  tests/everest/conftest.py
Labels: release-notes:improvement

#9635 Fixed plotter remembering correct tab when switching plot types
  src/ert/gui/tools/plot/plot_window.py
  tests/ert/ui_tests/gui/test_main_window.py
Labels: release-notes:bug-fix

#9653 Add nicer error message when init fails
  src/everest/__init__.py
Labels: release-notes:improvement

#8993 Add post/pre experiment simulation hooks
  docs/ert/reference/workflows/complete_workflows.rst
  src/ert/config/parsing/hook_runtime.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/unit_tests/cli/test_model_hook_order.py
Labels: release-notes:new-feature

#9638 Delete duplicate enum
  src/ert/config/__init__.py
  src/ert/config/enkf_observation_implementation_type.py
  src/ert/config/observation_vector.py
  src/ert/config/observations.py
  src/ert/config/parsing/__init__.py
  src/ert/libres_facade.py
  tests/ert/unit_tests/config/test_observations.py
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:maintenance

#9659 Avoid UserWarning when vmin==vmax in std_dev plot
  src/ert/gui/tools/plot/plottery/plots/std_dev.py
Labels: release-notes:maintenance

#9648 Add GEN_KW to heat equation and turn localization on
  test-data/ert/heat_equation/config.ert
  test-data/ert/heat_equation/config_forward_init_false.ert
  test-data/ert/heat_equation/corr_length_prior.txt
  test-data/ert/heat_equation/heat_equation.py
  test-data/ert/heat_equation/init_temp_prior.txt
  tests/ert/ui_tests/cli/test_field_parameter.py
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3-0 copy.png
  tests/ert/ui_tests/gui/baseline/test_that_all_snake_oil_visualisations_matches_snapshot_plot_figure3-0.png
Labels: release-notes:maintenance

#9577 Non optional everest model and nonzero realizations
  src/everest/config/everest_config.py
  src/everest/config/model_config.py
  tests/everest/entry_points/test_everest_entry.py
  tests/everest/test_config_validation.py
Labels: everest

#9669 Remove dependency on ropt config in forward model evaluations
  src/ert/run_models/everest_run_model.py
  src/everest/config/everest_config.py
Labels: release-notes:skip, everest

#9685 Make timestamps in dmesg output human readable
  src/_ert/forward_model_runner/forward_model_step.py
Labels: release-notes:maintenance

#9683 Make realization number span attribute
  src/ert/scheduler/job.py
Labels: release-notes:logging

#9535 Include spans for dark storage
  pyproject.toml
  src/ert/dark_storage/app.py
  src/ert/logging/storage_log.conf
  src/ert/services/_storage_main.py
  src/ert/services/storage_service.py
  src/ert/shared/storage/command.py
  src/ert/trace.py
Labels: release-notes:logging

#9695 Fix typo in dependencies
  pyproject.toml
Labels: release-notes:skip

#9108 Replace interface towards eclrun and flow using fmstep_config
  .github/workflows/build_and_test.yml
  .github/workflows/test_ert_with_flow.yml
  src/ert/config/ert_config.py
  src/ert/plugins/hook_implementations/forward_model_steps.py
  src/ert/resources/forward_models/res/script/ecl100.py
  src/ert/resources/forward_models/res/script/ecl100_config.yml
  src/ert/resources/forward_models/res/script/ecl300.py
  src/ert/resources/forward_models/res/script/ecl300_config.yml
  src/ert/resources/forward_models/res/script/ecl_config.py
  src/ert/resources/forward_models/res/script/ecl_run.py
  src/ert/resources/forward_models/res/script/flow.py
  src/ert/resources/forward_models/run_reservoirsimulator.py
  test-data/ert/eclipse/EIGHTCELLS.DATA
  test-data/ert/flow_example/flow.ert
  test-data/everest/egg/everest/model/config_flow.yml
  test-data/everest/egg/everest/model/jobs/flow
  test-data/everest/egg/everest/model/jobs/flow.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_forward_model.py
  tests/ert/unit_tests/resources/test_ecl_versioning_config.py
  tests/ert/unit_tests/resources/test_opm_flow.py
  tests/ert/unit_tests/resources/test_run_eclipse_simulator.py
  tests/ert/unit_tests/resources/test_run_flow_simulator.py
  tests/ert/unit_tests/resources/test_run_reservoirsimulator.py
Labels: release-notes:refactor

#9678 Show inversion errors in GUI
  src/ert/analysis/_es_update.py
  src/ert/run_models/base_run_model.py
  tests/ert/unit_tests/analysis/test_es_update.py
Labels: release-notes:bug-fix

#9680 Refactor preferred_num_cpu
  src/ert/config/ert_config.py
  src/ert/config/queue_config.py
  src/ert/run_models/base_run_model.py
  tests/ert/unit_tests/config/test_num_cpu.py
Labels: release-notes:maintenance

#9710 Adapt everest to run_reservoirsimulator
  .github/workflows/test_ert_with_flow.yml
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_egg_simulation.py
Labels: release-notes:unreleased-bug-fix

#9664 Remove asyncio.run_in_executor() calls and make scheduler cancel() async
  src/ert/ensemble_evaluator/_ensemble.py
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/ensemble_evaluator/monitor.py
  src/ert/run_models/base_run_model.py
  src/ert/scheduler/scheduler.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
Labels: release-notes:bug-fix

#9692 Set span status if realization fails
  src/ert/scheduler/job.py
Labels: release-notes:logging

#9684 Ignore non ConfigWarnings when running everest lint command
  src/everest/bin/everlint_script.py
Labels: release-notes:misc, release-notes:skip

#9723 Fix test when other plugins could be installed
  tests/everest/test_detached.py
Labels: release-notes:skip

#9676 Refactor BaseRunModel
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/everest_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/manual_update.py
  src/ert/run_models/multiple_data_assimilation.py
  src/everest/detached/jobs/everserver.py
  tests/ert/unit_tests/run_models/test_base_run_model.py
  tests/ert/unit_tests/run_models/test_model_factory.py
  tests/everest/conftest.py
  tests/everest/test_simulator_cache.py
Labels: release-notes:maintenance

#9744 Set the default flow simulator version to default
  tests/ert/unit_tests/resources/test_run_flow_simulator.py
Labels: release-notes:skip

#9743 Support forwarding multiple arguments to reservoir simulators
  src/ert/resources/forward_models/run_reservoirsimulator.py
  tests/ert/unit_tests/resources/test_run_reservoirsimulator.py
Labels: release-notes:unreleased-bug-fix

#9740 Speed up tests by reusing plugin manager
  src/ert/config/ert_config.py
  src/everest/config/simulator_config.py
  tests/ert/ui_tests/cli/run_cli.py
  tests/ert/unit_tests/test_run_path_creation.py
Labels: release-notes:maintenance

#9735 Use lalr parser for main ert config
  src/ert/config/parsing/lark_parser.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/config/test_forward_model.py
Labels: release-notes:user-impact

#9741 Update forward model doc for FLOW
  src/ert/plugins/hook_implementations/forward_model_steps.py
Labels: release-notes:documentation

#9753 Remove redundant tests
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:maintenance

#9748 Remove misleading comment
  src/everest/config/everest_config.py
Labels: release-notes:skip

#9764 Update test_model_factory.py
  tests/ert/unit_tests/run_models/test_model_factory.py
Labels: release-notes:maintenance

#9766 "disable-monitor" -> "disable-monitoring"
  tests/ert/conftest.py
  tests/ert/performance_tests/conftest.py
  tests/ert/performance_tests/test_memory_usage.py
  tests/ert/ui_tests/cli/analysis/test_adaptive_localization.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
  tests/ert/ui_tests/cli/analysis/test_es_update.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/ui_tests/cli/test_field_parameter.py
  tests/ert/ui_tests/cli/test_observation_times.py
  tests/ert/ui_tests/cli/test_parameter.py
  tests/ert/ui_tests/cli/test_parameter_passing.py
  tests/ert/ui_tests/cli/test_parameter_sample_types.py
  tests/ert/ui_tests/cli/test_shell.py
  tests/ert/ui_tests/cli/test_update.py
  tests/ert/unit_tests/dark_storage/conftest.py
Labels: release-notes:skip

#9768 Clean up ert config tests
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:maintenance

#9765 Mark rarely flaky test as flaky with reruns
  tests/ert/unit_tests/scenarios/test_summary_response.py
Labels: release-notes:flaky-test-fix

#9786 Fix recommended pytest command
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  justfile
Labels: release-notes:documentation

#9781 Remove everest.ConfigKeys
  src/everest/__init__.py
  src/everest/bin/config_branch_script.py
  src/everest/config_file_loader.py
  src/everest/config_keys.py
  src/everest/detached/__init__.py
  src/everest/jobs/scripts/wdcompl
  src/everest/jobs/well_tools/__init__.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/entry_points/test_config_branch_entry.py
  tests/everest/entry_points/test_everexport.py
  tests/everest/test_config_branch.py
  tests/everest/test_config_file_loader.py
  tests/everest/test_controls.py
  tests/everest/test_detached.py
  tests/everest/test_egg_simulation.py
  tests/everest/test_everlint.py
  tests/everest/test_input_constraints_config.py
  tests/everest/test_math_func.py
  tests/everest/test_output_constraints.py
  tests/everest/test_res_initialization.py
  tests/everest/test_util.py
  tests/everest/test_well_tools.py
  tests/everest/test_yaml_parser.py
Labels: release-notes:skip, everest

#9779 Add integration tests for parallel flow simulator
  tests/ert/ui_tests/cli/test_run_flow_simulator.py
  tests/ert/unit_tests/resources/test_run_flow_simulator.py
Labels: release-notes:maintenance

#9791 Add objective values to everest api snapshot
  tests/everest/snapshots/test_api_snapshots/test_api_snapshots/config_advanced.yml/snapshot.json
  tests/everest/snapshots/test_api_snapshots/test_api_snapshots/config_minimal.yml/snapshot.json
  tests/everest/snapshots/test_api_snapshots/test_api_snapshots/config_multiobj.yml/snapshot.json
  tests/everest/test_api_snapshots.py
Labels: release-notes:skip

#9793 Avoid non-informative ValueError in parameter/response configuration
  src/ert/storage/local_experiment.py
Labels: release-notes:improvement

#9792 Pretty print index.json files in storage
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  src/ert/storage/migration/to5.py
Labels: release-notes:improvement

#9800 Use the configuration file as the everest server job name
  src/everest/detached/__init__.py
Labels: release-notes:bug-fix

#9698 Add optimization algorithms section in the documentation for the theory chapter
  docs/everest/index.rst
  docs/everest/optimization_algorithms.rst
  docs/everest/optimization_backends.rst
Labels: release-notes:documentation

#9775 Fix wrong wording in test name
  tests/ert/unit_tests/resources/test_run_flow_simulator.py
Labels: release-notes:skip

#9802 Update outdated documentation mentioning archived EVEREST repository
  docs/everest/conf.py
  docs/everest/index.rst
  docs/everest/installation.rst
Labels: release-notes:documentation

#9804 Set permissions for transaction files to 0o666
  src/ert/storage/local_storage.py
  src/ert/storage/migration/to9.py
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:bug-fix

#9796 Fix right_click external plotter flaky test
  src/ert/gui/main_window.py
  tests/ert/ui_tests/gui/test_main_window.py
Labels: release-notes:skip

#9808 Simplify hook test
  tests/ert/unit_tests/cli/test_model_hook_order.py
Labels: release-notes:skip

#9801 Move egg test from komodo-releases
  ci/testkomodo.sh
Labels: release-notes:build-system

#9809 Trim Ert workflows
  .github/workflows/build_and_test.yml
Labels: release-notes:skip

#9807 Correct permissions is 660
  src/ert/storage/local_storage.py
  src/ert/storage/migration/to9.py
  tests/ert/unit_tests/storage/test_local_storage.py
Labels: release-notes:unreleased-bug-fix

#9785 Remove flaky prepost exp hook test
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:skip

#9814 Remove redundant apt download in run-ert-test-data
  .github/workflows/run_ert_test_data_setups.yml
Labels: release-notes:skip

#9818 Add integration test label to potentially conflicting tests
  tests/ert/unit_tests/config/test_forward_model.py
Labels: release-notes:maintenance

#9812 Trust the queue system when a job is finished in tests
  tests/ert/unit_tests/scheduler/test_generic_driver.py
Labels: release-notes:maintenance

#9771 Mark ES_MDA as recommended algorithm
  src/ert/gui/simulation/experiment_panel.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/ert/ui_tests/gui/conftest.py
  tests/ert/ui_tests/gui/test_csv_export.py
  tests/ert/ui_tests/gui/test_main_window.py
  tests/ert/ui_tests/gui/test_missing_parameters_to_update.py
  tests/ert/ui_tests/gui/test_restart_esmda.py
Labels: release-notes:user-impact

#9806 Remove logging_level setter from Everest config
  src/everest/config/everest_config.py
  src/everest/detached/jobs/everserver.py
  tests/everest/test_everest_config.py
Labels: release-notes:maintenance, release-notes:logging

#9819 Fix rerun button not disabled for ES-MDA
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
Labels: release-notes:bug-fix

#9749 Replace server_started Event with Future to handle exceptions
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/run_models/base_run_model.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
  tests/ert/unit_tests/ensemble_evaluator/test_scheduler.py
Labels: zmq

#9828 Mark ES_MDA as recommended algorithm in GUI
  src/ert/gui/simulation/experiment_panel.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
  tests/ert/ui_tests/gui/conftest.py
  tests/ert/ui_tests/gui/test_csv_export.py
  tests/ert/ui_tests/gui/test_main_window.py
  tests/ert/ui_tests/gui/test_missing_parameters_to_update.py
  tests/ert/ui_tests/gui/test_restart_esmda.py
Labels: release-notes:improvement

#9823 Adapt Slurm test setup to Ubuntu 24.04
  .github/workflows/test_ert_with_slurm.yml
Labels: release-notes:maintenance

#9833 Skip slow tests in mac ci
  .github/workflows/build_and_test.yml
  .github/workflows/test_ert.yml
  .github/workflows/test_everest.yml
  pyproject.toml
  tests/ert/ui_tests/cli/test_parameter_passing.py
  tests/ert/ui_tests/gui/test_plotting_of_snake_oil.py
  tests/ert/unit_tests/dark_storage/test_dark_storage_state.py
  tests/ert/unit_tests/gui/model/test_snapshot.py
  tests/everest/entry_points/test_everexport.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_detached.py
  tests/everest/test_everlint.py
  tests/everest/test_res_initialization.py
  tests/everest/test_yaml_parser.py
Labels: release-notes:build-system

#9839 Fix mac select string
  .github/workflows/build_and_test.yml
Labels: release-notes:build-system

#9805 Refactor control handling in everest config
  src/ert/run_models/everest_run_model.py
  src/everest/config/everest_config.py
  src/everest/config/utils.py
  src/everest/optimizer/everest2ropt.py
Labels: everest, release-notes:refactor

#9834 Add tests for flow vs OMP_NUM_THREADS
  tests/ert/ui_tests/cli/test_run_flow_simulator.py
Labels: release-notes:skip

#9825 Fix unable to have path object in argslist for localdriver
  src/ert/scheduler/local_driver.py
  tests/ert/unit_tests/scheduler/test_local_driver.py
Labels: release-notes:bug-fix

#9845 Reduce test matrix for flow and slurm tests
  .github/workflows/build_and_test.yml
Labels: release-notes:maintenance

#9843 Remove IES
  docs/ert/reference/configuration/keywords.rst
  docs/ert/reference/running_ert.rst
  docs/ert/theory/ensemble_based_methods.rst
  src/ert/__main__.py
  src/ert/analysis/__init__.py
  src/ert/analysis/_es_update.py
  src/ert/cli/main.py
  src/ert/config/__init__.py
  src/ert/config/analysis_config.py
  src/ert/config/analysis_module.py
  src/ert/config/parsing/__init__.py
  src/ert/config/parsing/analysis_mode.py
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/iterated_ensemble_smoother_panel.py
  src/ert/mode_definitions.py
  src/ert/run_models/__init__.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/iterated_ensemble_smoother.py
  src/ert/run_models/model_factory.py
  test-data/ert/snake_oil/snake_oil.ert
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/ui_tests/gui/test_main_window.py
  tests/ert/ui_tests/gui/test_missing_parameters_to_update.py
  tests/ert/unit_tests/analysis/test_es_update.py
  tests/ert/unit_tests/cli/test_model_hook_order.py
  tests/ert/unit_tests/config/test_analysis_config.py
  tests/ert/unit_tests/run_models/test_model_factory.py
  tests/ert/unit_tests/test_main.py
Labels: release-notes:breaking-change

#9846 Increase timeout of test_that_killed_ert_does_not_leave_storage_server_process
  src/ert/services/_storage_main.py
  tests/ert/ui_tests/cli/test_cli.py
Labels: flaky-test

#9848 Skip testing lsf/openpbs in slurm specific test
  .github/workflows/test_ert_with_slurm.yml
Labels: release-notes:skip

#9841 Have parameter config keep parameters types when using design matrix with categorical data
  src/ert/enkf_main.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
Labels: release-notes:improvement

#9826 Fix bug where only literal error had position info
  src/everest/config/everest_config.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_config_validation.py
Labels: release-notes:unreleased-bug-fix

#9798 Do heartbeat on clients
  src/_ert/forward_model_runner/client.py
  src/ert/ensemble_evaluator/evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_client.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_monitor.py
  tests/ert/unit_tests/forward_model_runner/test_event_reporter.py
  tests/ert/utils.py
Labels: zmq

#9824 Make the run dialogue snappier by tuning batching interval
  src/ert/ensemble_evaluator/evaluator.py
Labels: release-notes:improvement

#9853 Fix mac failing on main
  .github/workflows/build_and_test.yml
Labels: release-notes:build-system

#9851 Install correct dependency and adjust slurm config
  .github/workflows/test_ert_with_slurm.yml
  tests/ert/unit_tests/scheduler/test_slurm_driver.py
Labels: release-notes:maintenance

#9855 Move type parsing for genkw from `enkf_main` to `gen_kw_config`
  src/ert/config/gen_kw_config.py
  src/ert/enkf_main.py
Labels: release-notes:maintenance

#9859 Ensure SETENV is also substituted when writing json
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:bug-fix

#9861 Make sure parameter.txt files with too few values per line is validated
  src/ert/config/gen_kw_config.py
  tests/ert/unit_tests/config/test_gen_kw_config.py
Labels: release-notes:bug-fix

#9840 Remove DESIGN_MATRIX_GROUP for parameter_configuration in design matrix
  src/ert/config/design_matrix.py
  tests/ert/unit_tests/sensitivity_analysis/test_design_matrix.py
  tests/ert/unit_tests/test_libres_facade.py
Labels: release-notes:skip

#9872 Ensure cpu_seconds is always reported increasingly
  src/_ert/forward_model_runner/forward_model_step.py
  tests/ert/unit_tests/forward_model_runner/test_forward_model_step.py
Labels: release-notes:bug-fix

#9871 zmq: make sure no clients are connected when closing mockzmqsever
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_client.py
  tests/ert/utils.py
Labels: zmq

#9876 Make tests write to tmp
  tests/everest/test_res_initialization.py
Labels: release-notes:bug-fix

#9877 Fix analysispanel test failing on mac
  tests/ert/unit_tests/gui/run_analysis/test_analysispanel.py
Labels: release-notes:flaky-test-fix

#9883 Remove unused Everest GUI test code
  tests/everest/dialogs_mocker.py
Labels: release-notes:skip

#9886 Remove copy debug info button
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  tests/ert/unit_tests/gui/ertwidgets/test_copy_debug_info_button.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:user-impact

#9889 Port range of dark storage changed
  src/ert/services/_storage_main.py
Labels: release-notes:improvement

#9892 Fix ee unittest ...monitor_can_shut_down_evaluator
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:flaky-test-fix

#9885 zmq: add test for zmq start up failure when port already in use
  src/ert/ensemble_evaluator/evaluator.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:skip, zmq

#9896 Set max_batch_num to 2 to make test faster
  tests/everest/test_fix_control.py
Labels: release-notes:maintenance

#9777 Refactor everserver 2
  src/ert/run_models/everest_run_model.py
  src/everest/bin/everest_script.py
  src/everest/detached/__init__.py
  src/everest/detached/jobs/everserver.py
  src/everest/strings.py
  tests/everest/entry_points/test_everest_entry.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_detached.py
  tests/everest/test_everest_output.py
  tests/everest/test_everserver.py
  tests/everest/test_logging.py
Labels: release-notes:maintenance

#9893 Fix logging of custom forward model steps
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:maintenance

#9904 Remove tests that are covered by ropt testing
  tests/everest/test_samplers.py
Labels: release-notes:maintenance

#9898 Enforce objectives and controls have at least one element in everest config
  src/everest/config/everest_config.py
  tests/everest/test_config_validation.py
Labels: release-notes:user-impact

#9927 Omit old everest storage check for --new-run
  src/everest/bin/everest_script.py
Labels: release-notes:unreleased-bug-fix
