Repository equinor/ert, pull requests merged in 2025-06, with the labels that each got.

#10989 Move closing of filedialogs to when simulation panel is closed
  src/ert/gui/simulation/run_dialog.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:improvement

#11010 Fix fm_runner not yielding Finish message when early exit
  src/_ert/forward_model_runner/runner.py
Labels: release-notes:bug-fix, backport version-14.3

#10988 Change FileDialog to use Close button (with reject role)
  src/ert/gui/tools/file/file_dialog.py
  src/ert/gui/tools/search_bar/search_bar.py
  tests/ert/unit_tests/gui/ertwidgets/test_file_dialog.py
Labels: release-notes:improvement

#11012 Resolve Pydantic 2.11 deprecation warning
  src/ert/gui/ertwidgets/analysismodulevariablespanel.py
Labels: release-notes:skip

#11047 Remove empty and non-used suite.py
  src/everest/suite.py
Labels: release-notes:maintenance

#11054 Fix everest results not working
  src/everest/api/everest_data_api.py
Labels: release-notes:unreleased-bug-fix

#11082 Disable QDockWidget features
  src/ert/gui/tools/plot/plot_window.py
Labels: release-notes:bug-fix

#11081 Validate gen_kw parameter name cannot be IENS,ITER, or realization
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:bug-fix, backport version-14.3

#11092 Allow realization ranges in everest model config
  src/everest/config/model_config.py
  test-data/everest/math_func/config_advanced.yml
  tests/everest/test_config_validation.py
Labels: release-notes:improvement

#11087 Remove objective/constraint forward model types
  src/everest/config/forward_model_config.py
  test-data/everest/math_func/config_advanced.yml
Labels: release-notes:bug-fix

#11091 Fix Event reporter not exiting after failed retries
  src/_ert/forward_model_runner/client.py
  src/_ert/forward_model_runner/reporting/event.py
  tests/ert/unit_tests/forward_model_runner/test_event_reporter.py
  tests/ert/utils.py
Labels: release-notes:bug-fix, backport version-14.3

#11106 Add EnIF simulation mode for environment variable
  src/ert/mode_definitions.py
Labels: release-notes:skip, backport version-14.3

#11088 Handle running workflows without selected ensemble
  src/ert/gui/tools/workflows/run_workflow_widget.py
  tests/ert/ui_tests/gui/test_workflow_tool.py
Labels: backport version-14.2, backport version-14.3

#11114 Add everest-models test to PR
  .github/workflows/test_everest_models.yml
Labels: release-notes:skip

#11160 Ensure a tmpdir is used in test
  tests/ert/unit_tests/run_models/test_base_run_model.py
Labels: release-notes:skip

#11142 Use isoformat() instead of strftime()
  src/_ert/forward_model_runner/fm_dispatch.py
  src/ert/enkf_main.py
  src/ert/gui/main_window.py
  src/ert/logging/__init__.py
  src/ert/storage/local_experiment.py
  src/everest/util/__init__.py
  test-data/ert/snake_oil/forward_models/snake_oil_npv.py
  test-data/ert/snake_oil/forward_models/snake_oil_simulator.py
  test-data/ert/snake_oil_field/forward_models/snake_oil_npv.py
  test-data/ert/snake_oil_field/forward_models/snake_oil_simulator.py
  tests/ert/ui_tests/cli/test_observation_times.py
  tests/ert/unit_tests/config/observations_generator.py
Labels: release-notes:maintenance

#11158 Refactor setup of logging for everest entry points
  src/everest/bin/config_branch_script.py
  src/everest/bin/everest_script.py
  src/everest/bin/everexport_script.py
  src/everest/bin/kill_script.py
  src/everest/bin/main.py
  src/everest/bin/monitor_script.py
  src/everest/bin/utils.py
  src/everest/bin/visualization_script.py
  tests/everest/entry_points/test_everest_entry.py
Labels: release-notes:unreleased-bug-fix

#10902 Deprecate QUEUE_OPTION SUBMIT_SLEEP
  docs/ert/reference/configuration/keywords.rst
  docs/ert/reference/configuration/queue.rst
  src/ert/config/queue_config.py
  tests/ert/unit_tests/config/test_queue_config.py
Labels: release-notes:user-impact

#11095 Validate `DESIGN_MATRIX` parameter name overlap
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:bug-fix, backport version-14.3

#11195 Remove outdated documentation reference
  src/ert/config/ert_config.py
Labels: release-notes:skip

#11206 Fix cli test taking 120s -> 1.5s
  src/ert/scheduler/job.py
  tests/ert/ui_tests/cli/test_cli.py
Labels: release-notes:flaky-test-fix, backport version-14.3, backport version-14.4

#11201 Rewrite test to not depend on checked in data
  tests/everest/test_config_validation.py
Labels: release-notes:maintenance

#11226 Ensure the status test is run on a local queue
  tests/everest/test_everserver.py
Labels: release-notes:unreleased-bug-fix, backport version-14.4

#11225 Fix everest job-name
  src/everest/detached/client.py
  src/everest/simulator/everest_to_ert.py
  tests/everest/test_egg_simulation.py
Labels: release-notes:bug-fix

#11211 Improve exception handling in plot window
  src/ert/gui/tools/plot/plot_window.py
Labels: release-notes:unreleased-bug-fix

#11221 Add deprecation warnings for non-iso data formats
  src/everest/config/well_config.py
  src/everest/strings.py
  src/everest/util/__init__.py
  tests/everest/test_everlint.py
  tests/everest/test_wells.py
Labels: release-notes:maintenance

#11242 Reduce logging of data access from storage
  pyproject.toml
  src/ert/dark_storage/app.py
  src/ert/services/storage_service.py
Labels: release-notes:maintenance, backport version-14.3, backport version-14.4

#11250 Reduce mac os flakyness for Everest tests
  .github/workflows/test_everest.yml
  justfile
Labels: release-notes:maintenance

#11254 Split out memory tests
  .github/workflows/test_ert.yml
  justfile
  pyproject.toml
  tests/ert/performance_tests/test_memory_usage.py
  tests/ert/performance_tests/test_obs_and_responses_performance.py
Labels: release-notes:skip

#11259 Fix restart in ensemble experiment
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/initial_ensemble_run_model.py
Labels: release-notes:unreleased-bug-fix
