Repository equinor/ert, pull requests merged in 2025-09, with the labels that each got.

#11666 Resolve type errors regarding ConfigDict by using dict[Any, Any]
  src/ert/config/analysis_config.py
  src/ert/config/ensemble_config.py
  src/ert/config/model_config.py
  src/ert/config/parsing/__init__.py
  src/ert/config/parsing/config_dict.py
  src/ert/config/parsing/config_errors.py
  src/ert/config/parsing/config_schema_item.py
  src/ert/config/parsing/error_info.py
  src/ert/config/parsing/lark_parser.py
  src/ert/config/parsing/types.py
  src/ert/config/queue_config.py
  src/ert/config/workflow.py
  src/ert/config/workflow_job.py
  src/ert/run_models/everest_run_model.py
Labels: release-notes:maintenance

#11672 Remove repeated option benchmark-disable
  justfile
Labels: release-notes:skip

#11671 backport Log missing communication from fm_dispatch event reporter
  src/ert/ensemble_evaluator/evaluator.py
  src/ert/shared/net_utils.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_evaluator.py
Labels: release-notes:improvement

#11686 Improve test names
  tests/everest/test_environment.py
Labels: release-notes:skip

#11690 Use pep8 private/public convention for imports in workflow_job.py
  src/ert/config/workflow_job.py
Labels: release-notes:refactor

#11691 Remove remaining blanket type ignores in ert.config
  src/ert/config/parsing/schema_dict.py
  src/ert/config/parsing/workflow_job_schema.py
  src/ert/config/summary_config.py
Labels: release-notes:maintenance

#11703 Make sure all segments are collected in observations
  src/ert/config/parsing/observations_parser.py
  tests/ert/unit_tests/config/parsing/test_observations_parser.py
Labels: release-notes:bug-fix, backport version-14.5, backport version-14.6

#11702 Replace egg-case in tests by eightcells and remove egg case
  ci/testkomodo.sh
  test-data/everest/egg/eclipse/include/EGG.DATA
  test-data/everest/egg/eclipse/include/grid/PERM.INC
  test-data/everest/egg/eclipse/include/grid/active.inc
  test-data/everest/egg/eclipse/include/realizations/realization-0/eclipse/include/grid/PERM.INC
  test-data/everest/egg/eclipse/include/realizations/realization-0/eclipse/include/grid/active.inc
  test-data/everest/egg/eclipse/include/realizations/realization-0/eclipse/include/schedule
  test-data/everest/egg/eclipse/include/realizations/realization-0/eclipse/include/summary
  test-data/everest/egg/eclipse/include/realizations/realization-0/eclipse/model/EGG.DATA
  test-data/everest/egg/eclipse/include/realizations/realization-1/eclipse/include/grid/PERM.INC
  test-data/everest/egg/eclipse/include/realizations/realization-1/eclipse/include/grid/active.inc
  test-data/everest/egg/eclipse/include/realizations/realization-1/eclipse/include/schedule
  test-data/everest/egg/eclipse/include/realizations/realization-1/eclipse/include/summary
  test-data/everest/egg/eclipse/include/realizations/realization-1/eclipse/model/EGG.DATA
  test-data/everest/egg/eclipse/include/realizations/realization-2/eclipse/include/grid/PERM.INC
  test-data/everest/egg/eclipse/include/realizations/realization-2/eclipse/include/grid/active.inc
  test-data/everest/egg/eclipse/include/realizations/realization-2/eclipse/include/schedule
  test-data/everest/egg/eclipse/include/realizations/realization-2/eclipse/include/summary
  test-data/everest/egg/eclipse/include/realizations/realization-2/eclipse/model/EGG.DATA
  test-data/everest/egg/eclipse/include/schedule/events.sch
  test-data/everest/egg/eclipse/include/schedule/schedule.tmpl
  test-data/everest/egg/eclipse/include/summary/example_summary.txt
  test-data/everest/egg/eclipse/include/summary/grid
  test-data/everest/egg/eclipse/include/summary/schedule
  test-data/everest/egg/everest/input/files/at_config.yml
  test-data/everest/egg/everest/input/files/templates/wconinje.j2.html
  test-data/everest/egg/everest/input/files/templates/wconprod.j2.html
  test-data/everest/egg/everest/input/files/wc_config.yml
  test-data/everest/egg/everest/input/files/well_readydate.json
  test-data/everest/egg/everest/model/config.yml
  test-data/everest/egg/everest/model/config_flow.yml
  test-data/everest/eightcells/everest/model/config.yml
  tests/everest/conftest.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/best_controls
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/best_objective_gradients_csv
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/best_objectives_csv
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/egg-py311.csv
  tests/everest/snapshots/test_egg_simulation/test_egg_snapshot/egg-py38.csv
  tests/everest/snapshots/test_eightcells_simulation/test_eightcells_snapshot/best_controls
  tests/everest/snapshots/test_eightcells_simulation/test_eightcells_snapshot/best_objective_gradients_csv
  tests/everest/snapshots/test_eightcells_simulation/test_eightcells_snapshot/best_objectives_csv
  tests/everest/test_eightcells_simulation.py
  tests/everest/test_everest_initialization.py
  tests/everest/test_everlint.py
  tests/everest/test_repo_configs.py
  tests/everest/test_util.py
Labels: release-notes:maintenance

#11725 Remove perturbation_magnitude from eightcells example
  test-data/everest/eightcells/everest/model/config.yml
Labels: release-notes:skip

#11718 Add a check for duplicate keys in observations
  src/ert/config/parsing/observations_parser.py
  tests/ert/unit_tests/config/observations_generator.py
  tests/ert/unit_tests/config/parsing/test_observations_parser.py
Labels: release-notes:improvement

#11726 Improve the parsing of realization_memory to catch more edge-cases
  src/ert/config/queue_config.py
  src/everest/config/simulator_config.py
  tests/ert/unit_tests/config/test_queue_config.py
  tests/everest/test_res_initialization.py
Labels: release-notes:bug-fix

#11740 Fix typo "ment" to "meant" in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release-notes:documentation

#11760 Resolve job py warnings
  tests/ert/unit_tests/scheduler/test_job.py
Labels: release-notes:skip

#11678 Implement auto-scaling for input constraints
  src/ert/run_models/everest_run_model.py
  src/everest/config/everest_config.py
  src/everest/config/input_constraint_config.py
  src/everest/config/objective_function_config.py
  src/everest/config/output_constraint_config.py
  src/everest/optimizer/opt_model_transforms.py
  tests/everest/test_domain_transforms.py
  tests/everest/test_input_constraints_config.py
  tests/everest/test_multiobjective.py
Labels: release-notes:improvement

#11762 Fix docstring of get_realization_mask_with_responses
  src/ert/storage/local_ensemble.py
Labels: release-notes:skip

#11761 Have GEN_DATA INPUT_FORMAT yield config deprecation warning
  docs/ert/reference/configuration/observations.rst
  src/ert/config/gen_data_config.py
  src/ert/config/parsing/_option_dict.py
  test-data/ert/heat_equation/config.ert
  test-data/ert/heat_equation/config_forward_init_false.ert
  test-data/ert/poly_template/poly.ert.j2
  test-data/ert/snake_oil/snake_oil.ert
  test-data/ert/snake_oil_field/snake_oil.ert
  test-data/ert/snake_oil_field/snake_oil_field.ert
  test-data/ert/snake_oil_field/snake_oil_surface.ert
  tests/ert/performance_tests/test_memory_usage.py
  tests/ert/ui_tests/cli/test_field_parameter.py
  tests/ert/ui_tests/cli/test_parameter_sample_types.py
  tests/ert/ui_tests/gui/test_rft_export_plugin.py
  tests/ert/unit_tests/config/config_dict_generator.py
  tests/ert/unit_tests/config/test_ensemble_config.py
  tests/ert/unit_tests/config/test_gen_data_config.py
  tests/ert/unit_tests/config/test_observations.py
  tests/ert/unit_tests/config/test_parser_error_collection.py
  tests/ert/unit_tests/test_load_forward_model.py
Labels: release-notes:maintenance

#11770 More observation tests
  tests/ert/unit_tests/config/test_observations.py
Labels: release-notes:maintenance

#11811 Split std validation into field validator for truncated normal
  src/ert/config/distribution.py
Labels: release-notes:skip

#11817 Update uv lockfile
  uv.lock
Labels: dependency_workflow

#11827 Raise Error for restart without time_map or refcase
  src/ert/config/_create_observations.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:bug-fix, backport version-14.6

#11835 Change driver.kill loglevel from debug to info
  src/ert/scheduler/lsf_driver.py
  src/ert/scheduler/openpbs_driver.py
  src/ert/scheduler/slurm_driver.py
Labels: release-notes:logging, backport version-14.6

#11754 Add everviz testing to PRs
  .github/workflows/build_and_test.yml
  .github/workflows/test_everest.yml
  tests/everest/entry_points/test_visualization_entry.py
  tests/everest/utils/__init__.py
  tests/everest/utils/utils.py
Labels: release-notes:build-system

#11853 Move _get_optimization_status to experiment server
  src/ert/dark_storage/endpoints/experiment_server.py
  src/everest/detached/everserver.py
Labels: release-notes:skip

#11860 Move test snapshot for cli test with numpy1 to correct location
  tests/ert/ui_tests/cli/snapshots/test_cli/test_es_mda/using_scheduler/es_mda_integration_snapshot
  tests/ert/ui_tests/cli/snapshots/test_cli/test_that_es_mda_on_poly_case_matches_snapshot/es_mda_integration_snapshot_numpy1
Labels: release-notes:misc

#11861 Fix csv export
  src/ert/plugins/hook_implementations/workflows/csv_export.py
Labels: release-notes:bug-fix, backport version-14.6

#11868 Fix flaky test test_that_kill_before_submit_is_finished_works
  tests/ert/unit_tests/scheduler/test_lsf_driver.py
Labels: release-notes:flaky-test-fix, backport version-14.6, backport version-15.0

#11878 Remove unused folder in ensemble storage
  src/ert/storage/local_ensemble.py
Labels: release-notes:skip

#11903 Adjust tests for site configurations
  tests/conftest.py
  tests/ert/conftest.py
  tests/ert/performance_tests/test_memory_usage.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/ui_tests/cli/test_field_parameter.py
  tests/ert/ui_tests/cli/test_observation_times.py
  tests/ert/ui_tests/cli/test_parameter_sample_types.py
  tests/ert/ui_tests/gui/test_main_window.py
  tests/ert/unit_tests/config/test_ert_config.py
  tests/ert/unit_tests/storage/test_parameter_sample_types.py
  tests/everest/conftest.py
  tests/everest/functional/test_main_everest_entry.py
  tests/everest/test_cvar.py
  tests/everest/test_detached.py
  tests/everest/test_discrete.py
  tests/everest/test_everserver.py
  tests/everest/test_fix_control.py
  tests/everest/test_logging.py
  tests/everest/test_math_func.py
  tests/everest/test_objective_type.py
  tests/everest/test_res_initialization.py
  tests/everest/test_templating.py
  tests/everest/test_workflows.py
Labels: release-notes:skip

#11912 Deprecate the --new-run argument for everest
  src/everest/bin/everest_script.py
  src/everest/bin/utils.py
  tests/everest/entry_points/test_everest_entry.py
Labels: release-notes:user-impact

#11913 Allow more fine-grained subsystem tests
  ci/testkomodo.sh
Labels: release-notes:build-system, backport version-14.6, backport version-15.0

#11942 Rename observation types
  src/ert/config/_create_observation_dataframes.py
  src/ert/config/_observations.py
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_observation_declaration.py
Labels: release-notes:refactor

#11959 Fix typing error
  src/ert/run_models/everest_run_model.py
  src/everest/bin/everest_script.py
  src/everest/config/everest_config.py
  src/everest/simulator/everest_to_ert.py
Labels: release-notes:skip

#11961 Fix dict encoded observations
  src/ert/run_models/initial_ensemble_run_model.py
  src/ert/run_models/model_factory.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
Labels: release-notes:maintenance

#11966 Add RFT related terms to the glossary
  docs/ert/reference/glossary.rst
  src/ert/plugins/hook_implementations/workflows/gen_data_rft_export.py
Labels: release-notes:documentation
