Repository equinor/ert, pull requests merged in 2025-04, with the labels that each got.

#10515 Disable monitoring in test_ert_with_flow
  .github/workflows/test_ert_with_flow.yml
Labels: release-notes:maintenance

#10514 Ensure OpenMP parallelization will not take place in tests
  .github/workflows/codspeed.yml
  .github/workflows/run_ert_test_data_setups.yml
  .github/workflows/test_ert.yml
  .github/workflows/test_everest.yml
  .github/workflows/test_semeio.yml
Labels: release-notes:maintenance

#10522 Fix typing in everest simulator_config
  src/everest/config/simulator_config.py
Labels: release-notes:improvement

#10521 Do not log debug messages from urllib3
  src/ert/logging/logger.conf
Labels: release-notes:maintenance

#10526 Amend docs for DESIGN_MATRIX keyword
  docs/ert/reference/configuration/keywords.rst
Labels: backport version-14.1

#10417 Fix gui not working with high contrast mode
  src/ert/gui/main_window.py
  src/ert/gui/simulation/combobox_with_description.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/manage_experiments/storage_model.py
  src/ert/gui/tools/manage_experiments/storage_widget.py
  src/ert/gui/tools/plugins/plugins_tool.py
Labels: release-notes:bug-fix, backport version-14.1

#10535 Pass shared data explicitly
  src/everest/detached/jobs/everserver.py
  tests/everest/test_everserver.py
Labels: release-notes:skip

#10540 Stop loading plugins to avoid conflict with site config
  tests/everest/conftest.py
  tests/everest/test_detached.py
  tests/everest/test_res_initialization.py
Labels: release-notes:flaky-test-fix

#10541 Revert "Fix high contrast mode not working"
  src/ert/gui/main_window.py
  src/ert/gui/simulation/combobox_with_description.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/tools/manage_experiments/storage_model.py
  src/ert/gui/tools/manage_experiments/storage_widget.py
  src/ert/gui/tools/plugins/plugins_tool.py
Labels: release-notes:bug-fix, backport version-14.1

#10524 Add an everest kill on egg failure
  ci/testkomodo.sh
Labels: release-notes:skip

#10544 Fix gui realization selector using magic string as default
  src/ert/gui/ertwidgets/stringbox.py
  src/ert/gui/simulation/evaluate_ensemble_panel.py
  src/ert/gui/simulation/manual_update_panel.py
Labels: release-notes:bug-fix, backport version-14.1

#10551 Fix gui manual update validation
  src/ert/gui/simulation/evaluate_ensemble_panel.py
  src/ert/gui/simulation/manual_update_panel.py
  src/ert/validation/ensemble_realizations_argument.py
Labels: release-notes:bug-fix, backport version-14.1

#10556 Replace print statements with ConfigWarnings
  src/everest/config/everest_config.py
  tests/everest/test_input_constraints_config.py
Labels: release-notes:logging

#10553 Have gui notify user if high contrast mode is enabled
  src/ert/gui/main_window.py
Labels: release-notes:bug-fix, backport version-14.1

#10326 Add import safety to CLI execution in restricted environments
  .github/workflows/run_ert_test_data_setups.yml
  .github/workflows/test_ert_with_flow.yml
  .github/workflows/test_ert_with_slurm.yml
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/plugins/hook_implementations/workflows/gen_data_rft_export.py
  src/ert/plugins/workflow_fixtures.py
  tests/ert/conftest.py
Labels: release-notes:bug-fix

#10559 Replace QColor with state string in model
  src/ert/cli/monitor.py
  src/ert/ensemble_evaluator/snapshot.py
  src/ert/ensemble_evaluator/state.py
  src/ert/gui/model/node.py
  src/ert/gui/model/snapshot.py
  tests/ert/unit_tests/run_models/test_status_events_serialization.py
  tests/everest/test_monitor.py
Labels: release-notes:maintenance

#10560 Remove experiment-type column from Manage experiments
  src/ert/gui/tools/manage_experiments/storage_model.py
Labels: release-notes:skip

#10570 Catch exceptions from unmatched quotes in config
  src/ert/config/parsing/lark_parser.py
  tests/ert/unit_tests/config/test_forward_model.py
Labels: release-notes:bug-fix, backport version-14.1

#10581 Fix issue where tooltip was not possible on realization visuals
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/view/realization.py
Labels: release-notes:bug-fix, backport version-14.1

#10542 Update test_everest.yml
  .github/workflows/test_everest.yml
Labels: release-notes:skip

#10591 Backport: Fix issue where tooltip was not possible on realization visuals
  src/ert/gui/model/snapshot.py
  src/ert/gui/simulation/view/realization.py
Labels: release-notes:bug-fix

#10579 Move imports to the top, and enforce it
  docs/everest/conf.py
  pyproject.toml
  src/ert/config/design_matrix.py
  src/ert/config/summary_config.py
  src/ert/gui/ertwidgets/__init__.py
  src/ert/gui/tools/plot/plot_window.py
  src/ert/gui/tools/plot/plottery/__init__.py
  src/ert/services/storage_service.py
  src/ert/shared/__init__.py
  src/ert/storage/local_ensemble.py
  src/ert/storage/local_experiment.py
  src/ert/substitutions.py
  tests/ert/ui_tests/cli/analysis/test_adaptive_localization.py
  tests/ert/ui_tests/cli/test_cli.py
  tests/ert/ui_tests/cli/test_parameter_passing.py
  tests/ert/ui_tests/gui/test_csv_export.py
  tests/ert/unit_tests/config/test_read_summary.py
  tests/everest/test_monitor.py
Labels: release-notes:maintenance

#10561 Remove unused everest jobs
  src/everest/jobs/__init__.py
  src/everest/jobs/recovery_factor.py
  src/everest/jobs/scripts/recovery_factor
  src/everest/jobs/scripts/wdcompl
  src/everest/jobs/scripts/wddatefilter
  src/everest/jobs/scripts/wdfilter
  src/everest/jobs/scripts/wdreorder
  src/everest/jobs/scripts/wdset
  src/everest/jobs/scripts/wdupdate
  src/everest/jobs/well_tools/__init__.py
  tests/everest/test_res_initialization.py
  tests/everest/test_well_tools.py
Labels: release-notes:maintenance

#10600 Remove outdated log message
  src/ert/ensemble_evaluator/_ensemble.py
Labels: release-notes:maintenance

#10602 Remove superfluous log statement
  src/ert/ensemble_evaluator/_ensemble.py
Labels: release-notes:maintenance

#10598 Fix error racecondition bug
  src/_ert/forward_model_runner/reporting/file.py
Labels: bug

#10606 Merge observation warnings into one
  src/ert/analysis/_es_update.py
Labels: release-notes:maintenance, backport version-14.1

#10611 Reword warning on too high MIN_REALIZATIONS
  src/ert/config/analysis_config.py
  tests/ert/unit_tests/config/test_analysis_config.py
Labels: release-notes:misc, backport version-14.1

#10605 Dont run everest egg test on azure
  ci/testkomodo.sh
Labels: release-notes:skip

#10626 Do not merge design matrix with parameters when restarting experiment
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/multiple_data_assimilation.py
Labels: release-notes:bug-fix, backport version-14.1

#10595 Remove `ce_unary_send` concept from LegacyEnsemble
  src/ert/ensemble_evaluator/_ensemble.py
  tests/ert/unit_tests/ensemble_evaluator/test_ensemble_legacy.py
Labels: release-notes:skip

#10464 Use app token when creating backport PRs
  .github/workflows/backport.yml
Labels: release-notes:build-system

#10630 Add forward model step description for E100 and E300
  src/ert/plugins/hook_implementations/forward_model_steps.py
Labels: release-notes:documentation

#10647 Change job to step in docstrings
  src/ert/config/forward_model_step.py
Labels: release-notes:skip

#10648 Deprecate usage of ECL_BASE
  docs/ert/reference/configuration/magic_strings.rst
  docs/everest/config.rst
  src/ert/config/ert_config.py
  tests/ert/unit_tests/config/test_ert_config.py
Labels: release-notes:maintenance

#10649 Log current working directory when starting Ert
  src/ert/__main__.py
Labels: release-notes:skip

#10660 Fix some everest log messages missing operation id
  src/everest/trace.py
Labels: release-notes:logging, backport version-14.1

#10667 Update test snapshot for test_es_mda numpy1
  tests/ert/ui_tests/cli/snapshots/test_cli/test_es_mda/es_mda_integration_snapshot_numpy1
Labels: release-notes:skip

#10617 Internalize ert_templates into storage
  src/ert/enkf_main.py
  src/ert/gui/tools/manage_experiments/storage_widget.py
  src/ert/run_models/base_run_model.py
  src/ert/run_models/ensemble_experiment.py
  src/ert/run_models/ensemble_smoother.py
  src/ert/run_models/evaluate_ensemble.py
  src/ert/run_models/everest_run_model.py
  src/ert/run_models/manual_update.py
  src/ert/run_models/multiple_data_assimilation.py
  src/ert/storage/local_experiment.py
  src/ert/storage/local_storage.py
  src/ert/storage/migration/to10.py
  tests/ert/unit_tests/config/test_gen_kw_config.py
  tests/ert/unit_tests/conftest.py
  tests/ert/unit_tests/run_models/test_base_run_model.py
  tests/ert/unit_tests/storage/create_runpath.py
  tests/ert/unit_tests/test_enkf_main.py
  tests/ert/unit_tests/test_load_forward_model.py
  tests/ert/unit_tests/test_run_path_creation.py
  tests/ert/unit_tests/test_summary_response.py
Labels: improvement, release-notes:misc

#10655 Fix experiment_panel validation error on simulation done
  src/ert/gui/simulation/experiment_panel.py
Labels: release-notes:bug-fix, backport version-14.1

#10680 Fixup reference to ObservationStatus.ACTIVE as "active"
  src/ert/analysis/_es_update.py
  tests/ert/unit_tests/analysis/test_es_update.py
Labels: release-notes:bug-fix

#10686 Fixup whitespace in error displayed to user
  src/ert/config/observations.py
Labels: maintenance, backport version-14.1

#10679 Add queue system name to run_dialog
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/run_dialog.py
Labels: release-notes:improvement

#10715 Mark back as flaky test_that_multiple_everest_clients_can_connect_to_server
  tests/everest/test_everest_client.py
Labels: release-notes:flaky-test-fix

#10698 Remove enkf.py from dark_storage
  src/ert/dark_storage/common.py
  src/ert/dark_storage/endpoints/compute/misfits.py
  src/ert/dark_storage/endpoints/ensembles.py
  src/ert/dark_storage/endpoints/experiments.py
  src/ert/dark_storage/endpoints/observations.py
  src/ert/dark_storage/endpoints/records.py
  src/ert/dark_storage/enkf.py
  tests/ert/performance_tests/performance_utils.py
  tests/ert/performance_tests/test_dark_storage_performance.py
  tests/ert/unit_tests/dark_storage/conftest.py
  tests/ert/unit_tests/dark_storage/test_dark_storage_state.py
  tests/ert/unit_tests/gui/tools/plot/test_plot_api.py
Labels: release-notes:maintenance

#10720 Update select_wells job arguments in valid_config_maintained_forward_models.yml
  tests/everest/test_data/valid_config_file/forward_models/valid_config_maintained_forward_models.yml
Labels: release-notes:bug-fix
