Repository equinor/ert, pull requests merged in 2025-07, with the labels that each got.

#11264 Vectorize heat equation
  test-data/ert/heat_equation/heat_equation.py
Labels: release-notes:skip

#11266 Emit a specific error if all realizations fail during optimization
  src/ert/run_models/everest_run_model.py
  src/everest/detached/everserver.py
  src/everest/strings.py
  tests/everest/test_everserver.py
Labels: release-notes:improvement

#11271 Close model storage on run_model cancellation
  src/ert/gui/simulation/experiment_panel.py
  tests/ert/ui_tests/gui/test_main_window.py
Labels: bug, release-notes:bug-fix, backport version-14.4

#11277 Add parent to Suggestor windows
  src/ert/gui/ertwidgets/ensembleselector.py
  src/ert/gui/simulation/evaluate_ensemble_panel.py
  src/ert/gui/simulation/manual_update_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/gui/simulation/run_dialog.py
  src/ert/gui/suggestor/suggestor.py
  src/ert/gui/tools/load_results/load_results_panel.py
  src/ert/gui/tools/manage_experiments/storage_widget.py
Labels: release-notes:maintenance

#11193 Remove unused attributes in model factory
  src/ert/run_models/everest_run_model.py
  src/ert/run_models/model_factory.py
Labels: release-notes:maintenance

#11284 Add test that would catch bug fixed in ff375ad
  tests/ert/ui_tests/gui/test_restart_ensemble_experiment.py
Labels: release-notes:unreleased-bug-fix

#11238 Turn distributions into pydantic class
  src/ert/config/distribution.py
  src/ert/config/gen_kw_config.py
  src/ert/shared/storage/extraction.py
  tests/ert/ui_tests/cli/test_update.py
  tests/ert/unit_tests/config/test_gen_kw_config.py
  tests/ert/unit_tests/config/test_transfer_functions.py
Labels: improvement, release-notes:skip

#11295 Fix duplicate log entries in storage log
  src/ert/logging/storage_log.conf
  tests/ert/unit_tests/services/test_storage_service.py
Labels: release-notes:bug-fix

#11132 Fix model_factory realization_list validation returning np array and GUI not showing correct NUM_REALIZATIONS when using designmatrix
  src/ert/cli/main.py
  src/ert/config/ert_config.py
  src/ert/gui/simulation/_design_matrix_panel.py
  src/ert/gui/simulation/ensemble_experiment_panel.py
  src/ert/gui/simulation/ensemble_information_filter_panel.py
  src/ert/gui/simulation/ensemble_smoother_panel.py
  src/ert/gui/simulation/experiment_panel.py
  src/ert/gui/simulation/multiple_data_assimilation_panel.py
  src/ert/run_models/model_factory.py
  tests/ert/ui_tests/cli/analysis/test_design_matrix.py
  tests/ert/unit_tests/gui/simulation/test_run_dialog.py
Labels: release-notes:bug-fix

#11307 Print system load on pytest failures
  tests/conftest.py
Labels: release-notes:maintenance

#11311 Avoid copying existing poly storage to tmpdir
  tests/ert/unit_tests/dark_storage/conftest.py
Labels: release-notes:flaky-test-fix

#10958 Update eclipse example everest docs for new ForwardModelStep description
  docs/everest/forward_model_jobs.rst
Labels: documentation, release-notes:skip, everest

#11327 More cleaning up everest test_data
  tests/everest/test_data/README.md
Labels: release-notes:skip

#11316 Leave note in everest test-data
  test-data/everest/math_func/config_minimal.yml
Labels: release-notes:skip

#11333 Start storage server on KeyError from storage_server.json
  src/ert/services/storage_service.py
  tests/ert/unit_tests/services/test_storage_service.py
Labels: release-notes:bug-fix, backport version-14.4

#11339 Revert to previous behavior of FlattenedControls
  src/everest/config/utils.py
Labels: release-notes:skip

#11362 Ignore a flaky test in release branch
  tests/everest/functional/test_main_everest_entry.py
Labels: release-notes:skip

#11379 Remove setting of env var ECL_SKIP_SIGNAL
  .github/workflows/test_ert.yml
  ci/testkomodo.sh
Labels: release-notes:maintenance
